### ISSUE TITLE
怎么加速APPLE STORE？

### ISSUE THREAD

**Issue by yulhun** [koolshare/koolshare.github.io#1]
怎么加速APPLE STORE？R6300v2呢 刷了你们的固件。还有加这个广告屏蔽怎么样
Adblock Warning Removal List
EasyList China+EasyList
加这个省事呢。谢谢 希望加APPLE STORE和Adblock EasyList。

**Comment by sadoneli** [comment]
如果我没有记错的话apple store国内有人提供dns，可以加速的，你可以用自定义国内dns的方法，去实现加速

list的话正在整理
