### ISSUE TITLE
RAM占用越来越多，只能靠重启来解决。

### ISSUE THREAD

**Issue by cjameslynn** [koolshare/koolshare.github.io#10]
开机2~3天后，RAM占用61%，需要重启路由器才能下降

**Comment by sadoneli** [comment]
1 如果插入了格式不对或者磁盘有错误的usb设备，可能会出现这种情况
2 merlin固件自378.55后就改变了内存策略，现在很多东西都会常驻内存，在内存不足的情况下才会释放
https://github.com/RMerl/asuswrt-merlin/blob/master/Changelog.txt#L65-L68
