### ISSUE TITLE
DNS不够稳定

### ISSUE THREAD

**Issue by ahxxm** [koolshare/koolshare.github.io#101]
最近udp出国经常长时间（>1小时）丢包，从china dns/ss-tunnel切回了其他选项，发现dns2socks/dnscrypt/pcap都经常挂，重启就好了。

但是重启不太方便，一是手动，二是重启整个服务比较慢，希望作者能加入DNS监控和重启功能

**Comment by malash** [comment]
+1最近这个版本的SS是有些问题

**Comment by jannson** [comment]
好的,目前我们在开发新的 dns 工具.未来也可以加上进程实时坚控.目前里面的 ADM 是加了实时控制的.

**Comment by houzi-** [comment]
是这些进程挂掉还是DNS出现time out的情况？
判断方法：
打开需要代理的网页，使用chrmoe的F12的console来查看！

**Comment by malash** [comment]
是Time Out

**Comment by houzi-** [comment]
不可能三个全部都有问题吧！dnscrypt这个可能有些时候会抽风

**Comment by malash** [comment]
确实三个都有问题，但这个问题不能稳定复现，最近几天比较正常

**Comment by gonejack** [comment]
其实是dnsmasq渣渣
