### ISSUE TITLE
科学上网软件下不了

### ISSUE THREAD

**Issue by zjlifegoeson** [koolshare/koolshare.github.io#1013]
提示文件校对错误无法安装

**Comment by 36304099** [comment]
想知道什么原因,以前安装能用的,现在也不能用了.  R7000安装的梅林版本7.2

**Comment by pdfun** [comment]
我也有这个问题。

**Comment by pdfun** [comment]
手动安装上了。

**Comment by primewang** [comment]
怎样手动安装哈?

**Comment by pdfun** [comment]
@primewang  https://github.com/heweiye/Merlin_Shadowsocks 有安装步骤。

**Comment by Litangren** [comment]
开启软件离线安装！
【xxx】: /tmp目录下检测到上传的离线安装包shadowsocks.tar.gz
【xxx】: 尝试解压离线安装包离线安装包
【xxx】: 解压完成！
【xxx】: 没有找到安装脚本！
【xxx】: 删除相关文件并退出...
