### ISSUE TITLE
shadowsocks什么时候增加通配符或正则匹配域名？

### ISSUE THREAD

**Issue by shellus** [koolshare/koolshare.github.io#102]
www.gravatar.com
en.gravatar.com
例如这样的。
_.gravatar.com
或
/._?.gravatar.com/i

**Comment by shellus** [comment]
下面的正则被转义了，懂就好。

**Comment by jannson** [comment]
有这个考虑了。目前有一些开源的项目已经支持正则功能。

**Comment by gonejack** [comment]
gfw黑名单里写gravatar.com不就行了么

**Comment by shellus** [comment]
@gonejack 不行的哦，没试过不要乱说哦

**Comment by gonejack** [comment]
我的黑名单是这么写的
```
apple.com
icloud-content.com
twitch.com
```
工作正常，不知道为什么你的不行。
