### ISSUE TITLE
请问SS-SERVER如何使用ipv6连接

### ISSUE THREAD

**Issue by comeonchris** [koolshare/koolshare.github.io#1043]
你使用的路由器型号、固件版本?
路由型号：R7K
固件版本：380.66_4-X7.5

你遇到问题的是什么插件?
插件名称：科学上网-SERVER
插件版本：3.1.0

使用这个插件你遇到了什么问题（尽量详细描述）?
问题描述：小白求教，请问如何使用ipv6连接server？
已在/jffs/.koolshare/ssserver/ssserver.sh中修改为ss-server -s 0:0:0:0:0:0:0:0，但是仍然连接不上，提示超时。 
1.已确定客户端和服务端ipv6能用
2.使用花生壳可以连接ss-server，所以ss-server中原来ipv4的配置和参数应该也没问题
3.看SS-SERVER的日志顺利启动
4.梅林ipv6防火墙已关闭
5.内网可以使用ipv6连接ss-server，到了外网则不行
请问大神们，这个应该如何操作才能用ipv6连接呢？

附日志：
Oct 12 02:51:38 ss-server[25748]: UDP relay enabled
Oct 12 02:51:38 ss-server[25748]: initializing ciphers... aes-256-cfb
Oct 12 02:51:38 ss-server[25748]: tcp server listening at 0:0:0:0:0:0:0:0:2222
Oct 12 02:51:38 ss-server[25748]: udp server listening at 0:0:0:0:0:0:0:0:2222
Oct 12 02:51:38 ss-server[25748]: running from root user

**Comment by comeonchris** [comment]
已解决 ip6tables未写入规则

**Comment by net2cn** [comment]
我也遇到了这个问题，可以麻烦写一个详细一点的教程吗？
