### ISSUE TITLE
建议软件中心开发goflyway插件。

### ISSUE THREAD

**Issue by falltree** [koolshare/koolshare.github.io#1045]
目前用的AC86u，刷的koolshare官改固件，之前一直用的koolshare的改版梅林固件。
软件中心安装了酸酸乳，但是很少用，酸酸乳名气太大，经常被墙盯上，封ip。之前自己搭建的VPS就曾经被封过半年。后来找到了一个小众的goflyway，这个非常稳定好用，还可以自设80端口来伪装成正常网页访问流量。两年多了，从来没有被墙盯上过。

VPS搭了服务端后，可以手动在路由器运行命令行启动，但这个方式无法自动实现国内外分流。希望koolshare各位大神能否拨冗研究一下，争取在现有软件中心内加入这个goflyway，在此感谢了。其项目地址为https://github.com/coyove/goflyway/releases      

目前在电脑上搭配客户端软件goflyway tools，还是比较方便的，更希望路由器实现，这样局域网其他设备也可以不需任何设置使用了。该软件为另一高手制作  https://doubibackup.com/7btobhno.html

**Comment by sadoneli** [comment]
无此计划，请尝试手动在路由器上运行并使用iptables分流
