### ISSUE TITLE
希望越来越好 捐赠100

### ISSUE THREAD

**Issue by sashimizhao** [koolshare/koolshare.github.io#105]
微信流水号:4000192001201605286411178956

虽然每次更新68U的固件都是各种问题,甚至这次的_beta2-X6.6.0都是各种路由器崩溃,我不得不返回上一个版本.还是希望你们能继续维持这个项目. 毕竟有这样态度的公益开发组已经是凤毛麟角. 再次感谢.

**Comment by jannson** [comment]
感谢！
你的名字会出现在 http://c.koolshare.io

路由器崩溃？直接论坛私信我，或在 QQ 群里找我反馈下具体的崩溃问题。
