### ISSUE TITLE
插件开发者文档实现

### ISSUE THREAD

**Issue by jannson** [koolshare/koolshare.github.io#107]
目前没有很好的文档，导致想开发插件的同学们不知道如何入手。文档应该及时有。

**Comment by yulhun** [comment]
开源了  https://github.com/icodesign/Potatso-iOS

**Comment by jannson** [comment]
感谢提供这么好的资讯！

**Comment by sadoneli** [comment]
其实目前的软件中心算是试水，各种还存在各种问题，而且因为有打算上软件中心二代，所以插件文档会针对二代软件中心
