### ISSUE TITLE
关于游戏模式出现NAT3的疑问

### ISSUE THREAD

**Issue by kun945** [koolshare/koolshare.github.io#108]
首先说声抱歉，我这里讨论的问题和路由器固件无关，实在是其它地方找不答案才来求教。

ss服务器不是自建的，据介绍是支持udp，实际也可以做dns转发。
ss-redir等工具，都是github上clone下来原生代码编译的，没改过。

树莓派设为一级路由的dmz主机，二级路由的网关和dns服务器设为树莓派。
| PS4 |  ----》|二级路由| ----》 | 树莓派 | ----》 | 一级路由|

树莓派运行chinadns配合ss-tunnel做域名解析。
chinadns -m -c /etc/shadowsocks/chnroute.txt -s 202.101.226.69,127.0.0.1:5353
ss-tunnel -c /etc/shadowsocks/default.json -l 5353 -L 8.8.4.4:53 -u

ss-redir 做透明DL。
ss-redir -c /etc/shadowsocks/default.json -u -l 1081

iptable配置， IGN_TAB 是以/etc/shadowsocks/chnroute.txt 文件中国内ip为基础，这些ip全部return不走DL，其它ip无论tcp还是udp都走ss。

    IGLIST=$(cat $IGN_FILE）
    ipset create igntab hash:net

    iptables -t nat -N SS
    iptables -t nat -A SS -d $SERVERIP -j RETURN
    iptables -t nat -A SS -d 0.0.0.0/8 -j RETURN
    iptables -t nat -A SS -d 10.0.0.0/8 -j RETURN
    iptables -t nat -A SS -d 127.0.0.0/8 -j RETURN
    iptables -t nat -A SS -d 169.254.0.0/16 -j RETURN
    iptables -t nat -A SS -d 172.16.0.0/12 -j RETURN
    iptables -t nat -A SS -d 192.168.0.0/16 -j RETURN
    iptables -t nat -A SS -d 224.0.0.0/4 -j RETURN
    iptables -t nat -A SS -d 240.0.0.0/4 -j RETURN

    ip rule add fwmark 0x01/0x01 table 300
    ip route add local 0.0.0.0/0 dev lo table 300

    iptables -t mangle -N SS2
    iptables -t mangle -A SS2 -d $SERVERIP -j RETURN
    iptables -t mangle -A SS2 -d 0.0.0.0/8 -j RETURN
    iptables -t mangle -A SS2 -d 10.0.0.0/8 -j RETURN
    iptables -t mangle -A SS2 -d 127.0.0.0/8 -j RETURN
    iptables -t mangle -A SS2 -d 169.254.0.0/16 -j RETURN
    iptables -t mangle -A SS2 -d 172.16.0.0/12 -j RETURN
    iptables -t mangle -A SS2 -d 192.168.0.0/16 -j RETURN
    iptables -t mangle -A SS2 -d 224.0.0.0/4 -j RETURN
    iptables -t mangle -A SS2 -d 240.0.0.0/4 -j RETURN

    for igip in $IGLIST; do
        ipset -A $IGN_TAB $igip
    done

    iptables -t nat -A SS -m set --match-set $IGN_TAB dst -j RETURN 
    iptables -t nat -A SS -p tcp -j REDIRECT --to-ports $LOCALPORT 
    iptables -t nat -A PREROUTING -p tcp -j SS

    **_#主要是这部分udp转发，不知道能不能这样设置，我完全是猜的_**
    iptables -t mangle -A SS2 -m set --match-set $IGN_TAB dst -j RETURN
    iptables -t mangle -A SS2 -p udp -j TPROXY --on-port $LOCALPORT --tproxy-mark 0x01/0x0
    iptables -t mangle -A PREROUTING -p udp -j SS2

这样的设置如果不转发udp完全正常，NTA2一些隐藏网站也能上。我想问一下我这样设置能达到转发udp的目的吗？ 还有出现NAT3的原因肯能是什么？如果有人能回答这些疑问或者一起讨论给我提供思路的话，我将万分感激。谢谢。

**Comment by jannson** [comment]
说实话，我看你的配置应试是对的。具体你可以参考： https://github.com/koolshare/koolshare.github.io/blob/master/shadowsocks/shadowsocks/ss/game/nat-start

你应该用测试 udp 的软件测试下，看你从 udp 得到的 ip 是否为你 服务器的 ip
nat3 的原因可能是，你的 ss 版本 与 服务器的 ss 版本不对应？按理如果成功，即使你不 dmz 都可以 nat2

**Comment by kun945** [comment]
@jannson 感谢回复
有什么测试的软件可以推介，论坛里那个我在win10里运行不了，linux下的也行。
ss版本和ss服务器版本应该选取那个版本？ 目前我的shadowsocks-libev的版本是 2.4.5，服务器版本不知道，但是我想自建服务器。

**Comment by kun945** [comment]
多谢，问题已解决
