### ISSUE TITLE
捐赠100

### ISSUE THREAD

**Issue by ggyy99** [koolshare/koolshare.github.io#109]
分两次各50，订单编号：
E20160606233431020199751
E20160606233029020121197
koolshare ID:：ggyy99
建议：在有一定固件基础后是否有可能往定制硬件上发展。
另：问一下QQ群如何加？

**Comment by houzi-** [comment]
感谢你的捐赠

不明白你的这句话?
`在有一定固件基础后是否有可能往定制硬件上发展`

**Comment by ggyy99** [comment]
高端路由价格高的原因不是因为硬件有多贵，更多的是品牌、软件、服务，其中软件占比是最大的，而你们目前做的正是软件部分。

大家目前都是因为兴趣因为爱好或者别的在一起做这件事情，为了不让事情变质都坚持着免费，在我看来这是很好的但也是很不好的，很好是因为初衷是美好的并且在坚持，很不好是因为没有形成利益循环。

我捐赠是因为我认可，为了能以后用到更好的所以我会去支持，但是这不是长久之计的吧。

你让中国人花几百块买个硬件，舍得花钱的人大有人在，再花几十块买个固件估计大部分人就不愿意了吧。

所以卖硬件自带软件是很有市场的（苹果），单卖软件是很难卖动。

你们还是需要考虑一下日后的发展的，形成一个好的利益循环是最好的，直接出定制硬件加固件或者是去做一部分定制app都是方向，但是就目前来看定制硬件加固件可能会相对好一点吧。没有资金，可以去考虑众筹的，腾达都知道去众筹一个ac18的对吗。

以上仅个人意见，仅供参考

**Comment by jannson** [comment]
好的，感谢你的建议。我们也在摸索，找到一个好的利益循环的。为了能坚持，相信也会找到好的经营方式，不至于让好不容易产生的团队那么快猝死的！
论坛里私信我，我加您 QQ。让你到 QQ 群。目前 群里人太多，管理员不让加了。是朋友帮管理的。

**Comment by ggyy99** [comment]
ggyy99 就是我论坛id吧，给你私信了
