### ISSUE TITLE
白名单模式功能建议

### ISSUE THREAD

**Issue by ytzong** [koolshare/koolshare.github.io#11]
大陆白名单模式的 cdn.txt，可否在其基础上提供域名黑白名单的功能（比如 cdn.txt 包含 apple.com，我想让 apple.com 强制使用 ss 代理）？

**Comment by sadoneli** [comment]
可以用gfwlist模式达到你要的效果

**Comment by ytzong** [comment]
@sadoneli 国外网站直连太慢，gfwlist 并不能覆盖所有国外域名

**Comment by ytzong** [comment]
@sadoneli 能否告知一下 cdn.txt 在路由器上的位置？我手动移除部分域名，取消自动更新是不是就可以了？

**Comment by sadoneli** [comment]
当然不能覆盖完，但是基本的够用了，因为只整理了被墙的部分常用网站

在/jffs/ss/redchn/cdn.txt

**Comment by ytzong** [comment]
@sadoneli 从 cnd.txt 去除域名已经满足我的要求了，thanks
