### ISSUE TITLE
大陆白名单模式下 局域网客户端控制 黑名单功能 无效

### ISSUE THREAD

**Issue by boboshu** [koolshare/koolshare.github.io#113]
大陆白名单模式 局域网客户端控制 黑名单功能无效

家里有个 联通盒子 我妈看国产用，我用ss 开启大陆白名单模式  他们就看不了了。。
然后我想用局域网控制黑名单，添加了 联通盒子的ip  发现 无效果。论坛里也有其他人和我一样

**Comment by sadoneli** [comment]
请更新到最新版本ss再测试并反馈
