### ISSUE TITLE
Donate 20

### ISSUE THREAD

**Issue by skksdd** [koolshare/koolshare.github.io#115]
感谢你们无私的奉献
 E20160710222836034762968
4007362001201607108730688572
22:28:36 July 10th

**Comment by jannson** [comment]
感谢！！！

**Comment by skksdd** [comment]
建议论坛加入“屏蔽主题” 及“屏蔽用户“的功能， 以应对诸如”xxx是不是被遗忘了“ 及”xxx网速怎么这么烂“这样的帖子

祝越办越好

skksdd

**Comment by jannson** [comment]
是阿，有时候回复这样的帖子很心累。
