### ISSUE TITLE
小宝,能不能写一下游戏模式在openwrt的实现.

### ISSUE THREAD

**Issue by genics** [koolshare/koolshare.github.io#116]
我梅林和openwrt路由都有,很想在openwrt复刻梅林的游戏模式,现在ss-redir已经-u了,但是不会写防火墙转发规则,
# Add any UDP rules
root@Wrt:~# ip rule add fwmark 0x01/0x01 table 100
root@Wrt:~# ip route add local 0.0.0.0/0 dev lo table 100
root@Wrt:~# iptables -t mangle -A SHADOWSOCKS -p udp --dport 53 -j TPROXY --on-port 12345 --tproxy-mark 0x01/0x01

是否以上的命令全部加在防火墙规则里?对应我的固件,哪些地方需要修改呢?给点提示也行.

**Comment by sadoneli** [comment]
参考 https://github.com/shadowsocks/shadowsocks-libev 内Advanced usage，另外openwrt固件编译的时候需要开启tproxy支持
