### ISSUE TITLE
没办法在线更新

### ISSUE THREAD

**Issue by Ahoge1993** [koolshare/koolshare.github.io#117]
ASUSWRT-Merlin RT-N66U 380.59-alpha1-X6.5.2 Fri Mar 25 12:48:18 UTC 2016                                 
ahoge@RT-N66R-7F58:/tmp/home/root# wget --no-check-certificate --timeout=15 -P /                         
tmp https://raw.githubusercontent.com/koolshare/koolshare.github.io/master/shado                         
wsocks/shadowsocks.tar.gz                                                                                
--2016-07-13 18:34:49--  https://raw.githubusercontent.com/koolshare/koolshare.github.io/master/shadowsoc
ks/shadowsocks.tar.gz                                                                                    
Resolving raw.githubusercontent.com... failed: Connection timed out.                                     
wget: unable to resolve host address 'raw.githubusercontent.com'                                         
ahoge@RT-N66R-7F58:/tmp/home/root# tar -zxvf /tmp/shadowsocks.tar.gz                                     
tar: can't open '/tmp/shadowsocks.tar.gz': No such file or directory                                     
ahoge@RT-N66R-7F58:/tmp/home/root# chmod +x /tmp/shadowsocks/install.sh                                  
chmod: /tmp/shadowsocks/install.sh: No such file or directory                                            
ahoge@RT-N66R-7F58:/tmp/home/root# sh /tmp/shadowsocks/install.sh                                        
sh: can't open '/tmp/shadowsocks/install.sh'  

在家里没办法访问raw.githubusercontent.com，到别的地方下载了shadowsocks.tar.gz没办法上传到/tmp，请问怎么解决

**Comment by sadoneli** [comment]
可以用winscp上传到路由器的
