### ISSUE TITLE
梅林6.6.1 shadowsocks各个模式的速度衰减

### ISSUE THREAD

**Issue by skksdd** [koolshare/koolshare.github.io#119]
![ssspeedcomparison2](https://cloud.githubusercontent.com/assets/19769650/16861466/8fa325d4-4a73-11e6-8b38-b4ea44fd1071.jpg)

梅林6.6.1 shadowsocks 各个模式的速度衰减

如果方便的话， 想请教一下原因呢

**Comment by skksdd** [comment]
自行测试结果， 瓶颈在  加密方式 及 路由器性能。。。。。。
各种不同加密方式测试结果如下图
![sstest2](https://cloud.githubusercontent.com/assets/19769650/16998991/7eef2ec0-4eee-11e6-9b67-8d699c889dc1.jpg)


结果表明，还是路由器不给力。。。。 然后， 加密方式也会有所影响

请教一下， 各种加密方式的取舍。  目前就网页浏览来看， mac端， 还是rc4-md5 延迟最小，最流畅的

**Comment by skksdd** [comment]
结果都是经过多次测试， 这次用了个AWS的服务器， 也换DO的测试过， 结果一致的

**Comment by sadoneli** [comment]
你好，路由器上使用的是https://github.com/shadowsocks/shadowsocks-libev项目，windows上的项目是https://github.com/shadowsocks/shadowsocks-windows
不同代码，不同架构机器，不能保证速度的一致性的

**Comment by skksdd** [comment]
@sadoneli 我一会再去测试一下哈

**Comment by bazingaterry** [comment]
我用的是 R6300，实测跑 60 Mbps 的时候，双核 CPU 已经 100 %。这个是路由器的问题，只能换 CPU 性能更加好的系列，或者软路由？

**Comment by lingaoyi** [comment]
我的 88U 速度也是衰减，游戏模式下跟大陆白名单速度不一致，游戏模式最多跑到40M。

**Comment by sadoneli** [comment]
游戏模式是ss-rdir，大陆白是ss-local+redsocks2
而且游戏模式还多了udp规则
速度当然没有可比性

2016-08-22 11:41 GMT+08:00 L.G.Y <notifications@github.com>:
