### ISSUE TITLE
dbconf 没有对值进行编码导致配置页面不可用

### ISSUE THREAD

**Issue by page31** [koolshare/koolshare.github.io#129]
复现步骤：
shadowsocks 配置中密码填入带有半角单引号 ' 的内容
提交
刷新

**Comment by page31** [comment]
dbconf 这个接口真的做得很粗暴而且貌似不开源，折腾了半天没方法，改了相关脚本把密码给硬编码了。

**Comment by sadoneli** [comment]
你好，接口目前没有开源，不过dbus和skipd有开源的
