### ISSUE TITLE
无法打开GITHUB啊 用大陆模式呢。

### ISSUE THREAD

**Issue by yulhun** [koolshare/koolshare.github.io#13]
Sun Sep 6 12:53:37 GMT 2015:
/usr/bin/ssconfig: /jffs/ss/redchn/start.sh: line 199: echoecho: not found
Sun Sep 6 12:53:37 GMT 2015: done
Sun Sep 6 12:53:37 GMT 2015:
Sun Sep 6 12:53:37 GMT 2015: restarting dnsmasq…
Sun Sep 6 12:53:37 GMT 2015: done
Sun Sep 6 12:53:37 GMT 2015:
Sun Sep 6 12:53:37 GMT 2015: append nat rules
Sun Sep 6 12:53:37 GMT 2015: done
Sun Sep 6 12:53:37 GMT 2015:
Sun Sep 6 12:53:37 GMT 2015: Restarting firewall…
Sun Sep 6 12:53:37 GMT 2015: done
Sun Sep 6 12:53:37 GMT 2015:
Sun Sep 6 12:53:37 GMT 2015: Restarting nat…
Sun Sep 6 12:53:38 GMT 2015: done
Sun Sep 6 12:53:38 GMT 2015:
Sun Sep 6 12:53:38 GMT 2015: starting REDSOCKS2…
file parsing error at line 11: Name or service not known
file parsing error at line 11: value can’t be parsed
file parsing error at line 11: unclosed section

**Comment by sadoneli** [comment]
请使用ip地址，密码内保证无特殊字符
