### ISSUE TITLE
何时更新一下AC66U的固件？

### ISSUE THREAD

**Issue by Ranger007** [koolshare/koolshare.github.io#131]
何时更新一下AC66U的固件？  软件中心不会有了吗？....

**Comment by jannson** [comment]
最近出差太多，几个开发者都忙个人。不过这周开始回归了。应该不久就会有各种更新。

**Comment by lingaoyi** [comment]
游戏模式V2昵？ @jannson

**Comment by sadoneli** [comment]
@Ranger007 mips机型目前没有上软件中心计划
@lingaoyi 游戏模式V2不会出现在mips机型上
