### ISSUE TITLE
请求gfwlist模式添加对IP段的自定义办法

### ISSUE THREAD

**Issue by pre-sight** [koolshare/koolshare.github.io#135]
主要目的就是提供telegram的代理
望提供办法

**Comment by tianshi1987** [comment]
你用的KCP还是最新版本的都已经支持了IP的黑名单，参考http://koolshare.cn/thread-62315-1-1.html

2016-08-10 21:23 GMT+08:00 pre-sight <notifications@github.com>:

**Comment by sadoneli** [comment]
@tianshi1987 谢谢解答
