### ISSUE TITLE
出了奇怪的问题，无法判断到底是客户端，路由器还是服务器的问题

### ISSUE THREAD

**Issue by prolene** [koolshare/koolshare.github.io#136]
环境：
客户端为MacBook和iphone
路由器为ac68u刷梅林改版固件，并设置了ss
服务器是用了我朋友在香港开的ss服务器和我自己在google cloud开的ss服务器

症状说来话比较长⋯⋯
一个月前：
路由器刷完改版固件，找香港的朋友要来ss账号并且设置好路由器，当时还是1.5.4版本。gfwlist模式，控制面板里国内国外都显示working，但是用mac和iphone测试了google，Facebook等均发现上不去。各种改设置清缓存等等均不行。最后绝望的找来mac版的ss客户端打算当单机用了，一模一样设置好，访问墙外网站，秒开。再后来关掉ss客户端，突然发现路由器上的ss好使了，顺利的用了一个月毫无问题。这一个月之中自己通过google cloud搭了一个ss服务器，使用也毫无问题。
昨天：
昨天出差回家，到家以后发现翻不出墙了，登录路由器的web管理发现打不开，果断重启路由器。
重启路由器登录web管理以后发现ss处于默认关闭状态（好奇怪），开启并升级为1.5.5以后发现又翻不了墙了，换iphone也上不去，换了朋友用的ss服务器也上不去。
后来呢发现gmail上的去，google上不去，Facebook等等都上不去。再换mac上的ss端上了一会儿google，过会儿发现用回路由器上的ss发现也能上了，其他的Facebook，Twitter都如法炮制一遍，也都可以上去了。
最终发现都要用mac上的ss端上过一遍的网站，用路由器的ss端才能上去，这算哪门子事儿呀-_-||
希望作者能帮我分析分析

**Comment by tianshi1987** [comment]
从你的现象来看，貌似感觉还是DNS得解析问题比较有可能，你用MAC上过一次以后，应该浏览器里存储了你当时的翻墙后的IP地址，第二次去掉后，路由器可能直接转发的是IP，我也是个人猜测，建议你修改下路由器里SS的DNS方式，比如大陆白呀等，看看是否能有效

在 2016年8月13日 上午11:55，prolene <notifications@github.com>写道：

**Comment by prolene** [comment]
好像很有道理
我用的是dnscrypt-proxy加密解析gfwlist中的条域名，服务器是Cisco（opendns）
可能当时服务有点问题

**Comment by tianshi1987** [comment]
试试DNS2SOCKS这个我用用比较稳定

2016-08-14 21:44 GMT+08:00 prolene <notifications@github.com>:

**Comment by prolene** [comment]
已改成dns2socks5模式，目前使用正常
