### ISSUE TITLE
- remove	为了让网页更小更好加载，去掉了各个模式的说明，各个DNS软件的说明，反正没人看，去掉就去掉了吧;

### ISSUE THREAD

**Issue by gonejack** [koolshare/koolshare.github.io#138]
还我说明不仅要还我，还要解释得很清楚，起码能让程序员看得懂，或者你在那里放一个链接，让大家能来github看看各模式的原理。

**Comment by tianshi1987** [comment]
这个支持一下，建议S大在github的redme里放一下吧

2016-08-17 21:29 GMT+08:00 John Youi <notifications@github.com>:

**Comment by sevenfxx** [comment]
各个模式，包括DNS模式的说明不要去掉啊，强烈要求加回来，这些文本的东西也多不了好多内容吧。没有说明，有问题也不好找。

**Comment by sadoneli** [comment]
fixed https://github.com/koolshare/koolshare.github.io/blob/acelan_softcenter_ui/shadowsocks/Changelog.txt#L23
