### ISSUE TITLE
SS 2.2 GFWlist 模式下 DNS设定和黑白名单功能相互冲突的Bug报告

### ISSUE THREAD

**Issue by FlyingGitHub** [koolshare/koolshare.github.io#139]
SS 2.2 GFWlist 模式下
1.在DNS设定中自定义dnsmasq设定，点击页面“应用DNS设定“后会直接覆盖掉/jffs/configs/dnsmasq.d/custom.conf里面的内容
2.在黑白名单中设置域名白名单和黑名单后，点击“应用黑白名单”后也会直接覆盖掉/jffs/configs/dnsmasq.d/custom.conf里面的内容

由于存在此问题，导致自定义dnsmasq设定和域名黑白名单无法共存，之前1.5.7没有这个Bug # #

**Comment by sadoneli** [comment]
fixed https://github.com/koolshare/koolshare.github.io/blob/acelan_softcenter_ui/shadowsocks/Changelog.txt#L14
