### ISSUE TITLE
GFWlist模式不能正常工作

### ISSUE THREAD

**Issue by sevenfxx** [koolshare/koolshare.github.io#14]
使用GFWlist模式时，状态为：国外连接 - [ 2015-09-13 10:06:09 ] Problem detected!
Twitter，youtube等网站正常，但Google相关域名的网站打不开。

使用大陆白名单模式，则一切正常。

两种模式的国外DNS都选择的一样的设置。

**Comment by jannson** [comment]
因为S大不小心提交了这个更新,在最新固件上可以用,但是老固件不行,一会我改回来.

**Comment by sevenfxx** [comment]
原来如此，我没有升级最新的固件。
