### ISSUE TITLE
在B类网段shadowsocks存在问题

### ISSUE THREAD

**Issue by lawrence-zhang** [koolshare/koolshare.github.io#140]
Hi 我发现了一个问题，现在局域网设置为B类网段，如172.18.0.1(这是网关), 如果机器在172.18.0这个子网段可以翻墙使用shadowsocks，但是这个子网段之外如172.18.1, 172.18.2都不能使用翻墙

**Comment by sadoneli** [comment]
设置网络请参照标准的保留地址设置
[https://github.com/shadowsocks/shadowsocks-libev#advanced-usage](https://github.com/shadowsocks/shadowsocks-libev#advanced-usage)
