### ISSUE TITLE
Bug in SS 2.4

### ISSUE THREAD

**Issue by LRD2015** [koolshare/koolshare.github.io#141]
cannot activate the apply button

**Comment by sadoneli** [comment]
under what circumstance？

**Comment by Gzxhwq** [comment]
添加节点的浮动窗口在分辨率不够的情况下无法完整显示

**Comment by SevenNL** [comment]
I  reseted R7000 in web page. Then same as LRD2015. "cannot activate the apply button". SS can not work now. Please help to fix it .

**Comment by sadoneli** [comment]
@SevenNL best and fast solution, format your jffs and install again.
your problem seem to be the skipd database error, when that occur, threr is no way but format your jffs.

**Comment by SevenNL** [comment]
@sadoneli  Thanks，Let me try.

**Comment by SevenNL** [comment]
@sadoneli  Fixed。Thanks again。
