### ISSUE TITLE
梅林固件里面的SS到底走的ss-local还是走的ss-redir

### ISSUE THREAD

**Issue by lawrence-zhang** [koolshare/koolshare.github.io#142]
我在进程中看到了ss-local, 没看到ss-redir，到底走的哪个？两个是否可以并存

**Comment by sadoneli** [comment]
gfwlist下，数据走的ss-redir，开dns2socks的话，会启动ss-local走dns用
大陆白下，数据走的ss-local
全局模式下，数据走的ss-redir
游戏模式下，数据走ss-redir，开dns2socks的话，会启动ss-local走dns用

**Comment by sadoneli** [comment]
可以并存

**Comment by lawrence-zhang** [comment]
现在我在gfwlist和大陆白下，均不能翻墙，我设置网段是172.18， 路由的地址是172.18.0.1，但是非172.18.0网段均不能翻墙，只有在172.18.0网段下才能翻

**Comment by lawrence-zhang** [comment]
还试了全局模式，在非172.18.0网段也不能翻墙
