### ISSUE TITLE
全局模式下，不能翻墙

### ISSUE THREAD

**Issue by lawrence-zhang** [koolshare/koolshare.github.io#143]
麻烦高手看看
现在我在gfwlist和大陆白下，均不能翻墙，我设置网段是172.18， 路由的地址是172.18.0.1，但是非172.18.0网段均不能翻墙，只有在172.18.0网段下才能翻.还试了全局模式，在非172.18.0网段也不能翻墙,下面是全局模式下的路由表

Chain SHADOWSOCKS (1 references)
    pkts      bytes target     prot opt in     out     source               destination
       0        0 RETURN     all  --  \*      \*       0.0.0.0/0            159.203.235.57
       0        0 RETURN     all  --  \*      \*       0.0.0.0/0            208.67.220.220
       0        0 RETURN     all  --  \*      \*       0.0.0.0/0            8.8.8.8
       0        0 RETURN     all  --  \*      \*       0.0.0.0/0            0.0.0.0/8
       0        0 RETURN     all  --  \*      \*       0.0.0.0/0            10.0.0.0/8
       0        0 RETURN     all  --  \*      \*       0.0.0.0/0            127.0.0.0/8
       0        0 RETURN     all  --  \*      \*       0.0.0.0/0            169.254.0.0/16
      61     3904 RETURN     all  --  \*      \*       0.0.0.0/0            172.16.0.0/12
       0        0 RETURN     all  --  \*      \*       0.0.0.0/0            192.168.0.0/16
       0        0 RETURN     all  --  \*      \*       0.0.0.0/0            224.0.0.0/4
       0        0 RETURN     all  --  \*      \*       0.0.0.0/0            240.0.0.0/4
       4      184 RETURN     all  --  \*      \*       0.0.0.0/0            111.175.0.0/16
       4      240 REDIRECT   tcp  --  \*      \*       0.0.0.0/0            0.0.0.0/0            tcp dpt:80 redir ports 3333
       2      128 REDIRECT   tcp  --  \*      \*       0.0.0.0/0            0.0.0.0/0            tcp dpt:443 redir ports 3333

Chain VSERVER (2 references)
    pkts      bytes target     prot opt in     out     source               destination
       0        0 DNAT       udp  --  \*      \*       0.0.0.0/0            0.0.0.0/0            udp dpt:4672 to:172.18.0.1
       0        0 DNAT       udp  --  \*      \*       0.0.0.0/0            0.0.0.0/0            udp dpt:4665 to:172.18.0.1
       1       60 DNAT       tcp  --  \*      \*       0.0.0.0/0            0.0.0.0/0            tcp dpt:4662 to:172.18.0.1
    1603   138958 DNAT       udp  --  \*      \*       0.0.0.0/0            0.0.0.0/0            udp dpt:51413 to:172.18.0.1
    4315   239195 DNAT       tcp  --  \*      \*       0.0.0.0/0            0.0.0.0/0            tcp dpt:51413 to:172.18.0.1
       9      436 DNAT       tcp  --  \*      \*       0.0.0.0/0            0.0.0.0/0            tcp dpt:8081 to:172.18.0.1:8081
       0        0 DNAT       tcp  --  \*      \*       0.0.0.0/0            0.0.0.0/0            tcp dpt:8083 to:172.18.0.1:80
      21      956 DNAT       tcp  --  \*      \*       0.0.0.0/0            0.0.0.0/0            tcp dpt:3389 to:172.18.2.2:3389
       0        0 DNAT       tcp  --  \*      \*       0.0.0.0/0            0.0.0.0/0            tcp dpt:9900 to:172.18.2.2:9900
       0        0 DNAT       tcp  --  \*      \*       0.0.0.0/0            0.0.0.0/0            tcp dpt:4530 to:172.18.2.2:4530
       0        0 DNAT       tcp  --  \*      \*       0.0.0.0/0            0.0.0.0/0            tcp dpt:9 to:172.18.2.2:9
       0        0 DNAT       udp  --  \*      \*       0.0.0.0/0            0.0.0.0/0            udp dpt:9 to:172.18.2.2:9
    5785   317735 VUPNP      all  --  \*      \*       0.0.0.0/0            0.0.0.0/0
       0        0 DNAT       tcp  --  \*      \*       0.0.0.0/0            0.0.0.0/0            tcp dpt:16661 to:172.18.0.1:16661

**Comment by lawrence-zhang** [comment]
有人能帮忙看看么

**Comment by sadoneli** [comment]
不是很清楚你这块，等高人吧

**Comment by houzi-** [comment]
@lawrence-zhang 我建议你打印iptables nat链上的规则出来，这个看不出来所以然的！

**Comment by houzi-** [comment]
@lawrence-zhang 
命令:
```
iptables-save -t nat
```

**Comment by lawrence-zhang** [comment]
@houzi- 
规则如下
# Generated by iptables-save v1.4.14 on Sun Aug 28 00:45:45 2016
*nat
:PREROUTING ACCEPT [2174:169990]
:INPUT ACCEPT [913:62258]
:OUTPUT ACCEPT [4008:314371]
:POSTROUTING ACCEPT [4010:314459]
:DNSFILTER - [0:0]
:LOCALSRV - [0:0]
:PCREDIRECT - [0:0]
:SHADOWSOCKS - [0:0]
:VSERVER - [0:0]
:VUPNP - [0:0]
-A PREROUTING -d 119.98.213.152/32 -j VSERVER
-A PREROUTING -d 192.168.1.2/32 -j VSERVER
-A PREROUTING -p tcp -j SHADOWSOCKS
-A PREROUTING -s 172.18.0.0/24 -p udp -m udp --dport 53 -j DNAT --to-destination 172.18.0.1
-A OUTPUT -p tcp -m set --match-set router dst -j REDIRECT --to-ports 3333
-A POSTROUTING ! -s 119.98.213.152/32 -o ppp0 -j MASQUERADE
-A POSTROUTING ! -s 192.168.1.2/32 -o eth0 -j MASQUERADE
-A POSTROUTING -m mark --mark 0xb400 -j MASQUERADE
-A SHADOWSOCKS -d 103.57.167.16/32 -j RETURN
-A SHADOWSOCKS -d 0.0.0.0/8 -j RETURN
-A SHADOWSOCKS -d 10.0.0.0/8 -j RETURN
-A SHADOWSOCKS -d 127.0.0.0/8 -j RETURN
-A SHADOWSOCKS -d 169.254.0.0/16 -j RETURN
-A SHADOWSOCKS -d 172.16.0.0/12 -j RETURN
-A SHADOWSOCKS -d 192.168.0.0/16 -j RETURN
-A SHADOWSOCKS -d 224.0.0.0/4 -j RETURN
-A SHADOWSOCKS -d 240.0.0.0/4 -j RETURN
-A SHADOWSOCKS -d 119.98.0.0/16 -j RETURN
-A SHADOWSOCKS -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-ports 3333
-A VSERVER -p udp -m udp --dport 4672 -j DNAT --to-destination 172.18.0.1
-A VSERVER -p udp -m udp --dport 4665 -j DNAT --to-destination 172.18.0.1
-A VSERVER -p tcp -m tcp --dport 4662 -j DNAT --to-destination 172.18.0.1
-A VSERVER -p udp -m udp --dport 51413 -j DNAT --to-destination 172.18.0.1
-A VSERVER -p tcp -m tcp --dport 51413 -j DNAT --to-destination 172.18.0.1
-A VSERVER -p tcp -m tcp --dport 8081 -j DNAT --to-destination 172.18.0.1:8081
-A VSERVER -p tcp -m tcp --dport 8083 -j DNAT --to-destination 172.18.0.1:80
-A VSERVER -p tcp -m tcp --dport 3389 -j DNAT --to-destination 172.18.2.2:3389
-A VSERVER -p tcp -m tcp --dport 9900 -j DNAT --to-destination 172.18.2.2:9900
-A VSERVER -p tcp -m tcp --dport 4530 -j DNAT --to-destination 172.18.2.2:4530
-A VSERVER -p tcp -m tcp --dport 9 -j DNAT --to-destination 172.18.2.2:9
-A VSERVER -p udp -m udp --dport 9 -j DNAT --to-destination 172.18.2.2:9
-A VSERVER -j VUPNP
-A VSERVER -p tcp -m tcp --dport 16661 -j DNAT --to-destination 172.18.0.1:16661
COMMIT
# Completed on Sun Aug 28 00:45:45 2016

**Comment by sadoneli** [comment]
-A PREROUTING -s 172.18.0.0/24 -p udp -m udp --dport 53 -j DNAT --to-destination 172.18.0.1

从这里看，你的ss是2.0以前的版本？
可能的问题，你其它上不了网的机器是否定义了自定义DNS？

**Comment by lawrence-zhang** [comment]
@sadoneli 没有自定义dns，都是一样从dhcp获得的
