### ISSUE TITLE
需要精简版的gfwlist，需要节点能自动fallback

### ISSUE THREAD

**Issue by gonejack** [koolshare/koolshare.github.io#144]
现在的gfwlist四千多条，里面多少是乱七八糟的政治网站，大部分人根本不会去上的，那么多规则除了浪费性能也没啥用。

节点自动fallback也是很有用的，SS节点服务器偶尔是会挂的大家应该很有体会。

**Comment by sadoneli** [comment]
简版请自己维护

**Comment by gonejack** [comment]
自己维护也可以（但请在模式下拉框里给我那样一个自定义的选项啊喂）

**Comment by sadoneli** [comment]
请自行替换/koolshare/ss/ipset/gfwlist.conf文件

在 2016年8月23日 下午10:59，John Youi <notifications@github.com>写道：
