### ISSUE TITLE
start shadowsocks , Domestic and foreign can working. But 5 sec, foreign in Problem.

### ISSUE THREAD

**Issue by SevenNL** [koolshare/koolshare.github.io#145]
start shadowsocks , Domestic and foreign both can working.

 But after 5 sec, Foreign in Problem.Domestic still work.

The same ss id via  shadosocks.exe , will be fine.

Please help me .

Tell me that's the  problem and fix it.

**Comment by sadoneli** [comment]
Your description not doing any help.
first check your line accessiblity;
second check any unusual log in ss log and system log;
third check if you use ip in server colum.

**Comment by SevenNL** [comment]
1 Lan is fine.I can access www.baidu.com as nomal

2 ss log as below , shows no error 

Tue Aug 23 22:46:34 GMT 2016: ---------------------- Restart chnmode addon ---------------------------
Tue Aug 23 22:46:34 GMT 2016: boot delay time not changing, still 0 seconds
Tue Aug 23 22:46:34 GMT 2016: done
Tue Aug 23 22:46:34 GMT 2016:
Tue Aug 23 22:46:34 GMT 2016: disable lan dns take over..
Tue Aug 23 22:46:34 GMT 2016: done
Tue Aug 23 22:46:34 GMT 2016:
Tue Aug 23 22:46:35 GMT 2016: lan control not enabled
Tue Aug 23 22:46:35 GMT 2016: done
Tue Aug 23 22:46:35 GMT 2016:
Tue Aug 23 22:46:35 GMT 2016: kill crontab job
Tue Aug 23 22:46:35 GMT 2016: done
Tue Aug 23 22:46:35 GMT 2016: -------------------- Shadowsock service Stopped--------------------------
Tue Aug 23 22:46:35 GMT 2016:
Tue Aug 23 22:46:35 GMT 2016: ss rule schedual update enabled
Tue Aug 23 22:46:35 GMT 2016: done
Tue Aug 23 22:46:35 GMT 2016:
Tue Aug 23 22:46:35 GMT 2016: ---------------------- chnmode addon applied ---------------------------
Tue Aug 23 22:46:35 GMT 2016:
Tue Aug 23 22:46:35 GMT 2016: Enjoy surfing internet without Great Fire Wall!
Tue Aug 23 22:46:35 GMT 2016:
Tue Aug 23 22:46:35 GMT 2016: ================= Shell by sadoneli, Web by Xiaobao =====================

3 
In server colum.
Ping show fine. but web test shows failed(youtube.com) 
Then I ssh the SS server.Try to ping www.youtube.com

[root@host-163-44-149-85 ~]# ping www.youtube.com
PING youtube-ui.l.google.com (74.125.68.93) 56(84) bytes of data.
64 bytes from sc-in-f93.1e100.net (74.125.68.93): icmp_seq=1 ttl=46 time=3.56 ms
64 bytes from sc-in-f93.1e100.net (74.125.68.93): icmp_seq=2 ttl=46 time=3.57 ms

That's the result  for my check.

**Comment by sadoneli** [comment]
webtest failed means your setting in router is incorrect, maybe you turned OTA on?

**Comment by SevenNL** [comment]
update 2.8.3 still PD
Now back to 1.57 everything is ok.

**Comment by sadoneli** [comment]
talk to me on telegram, maybe I can help you with the issue in 2.* version.
https://telegram.me/joinchat/DCq55kC7pgWKX9J4cJ4dJw
