### ISSUE TITLE
2.7好不稳定啊

### ISSUE THREAD

**Issue by zynbasil** [koolshare/koolshare.github.io#146]
开关点不了， 设置了没反应

**Comment by sadoneli** [comment]
请给出ss日志，系统日志，ss主界面控制台信息

**Comment by sadoneli** [comment]
主界面控制台信息进入chrome浏览器，按F12就能看到
如果实在不能反馈这新信息，请假telegram讨论组，我会帮你解决

**Comment by zynbasil** [comment]
<input id="switch" class="switch" type="checkbox" style="display: none; background-color: rgb(71, 90, 95);" disabled="">

**Comment by zynbasil** [comment]
input id="switch" class="switch" type="checkbox" style="display: none; background-color: rgb(71, 90, 95);" disabled=""

**Comment by zynbasil** [comment]
开关按钮的html

**Comment by zynbasil** [comment]
2.2都是好的~

**Comment by zynbasil** [comment]
我手动改为 enabled 然后打开设置完， 刷新又变成不能点了~

**Comment by zynbasil** [comment]
升级2.8一样~可以回滚不~

**Comment by sadoneli** [comment]
怎么不能，方法一直写在github的

**Comment by zynbasil** [comment]
哦~~~感谢

**Comment by zynbasil** [comment]
R7000  380.57_X6.5   这是我的系统配置，供参考

**Comment by sadoneli** [comment]
这个没什么参考的，要解决不能应用的问题，肯定得详细的信息
ss日志，系统日志，ss主界面chrome控制台信息，这些我得有才能解决

**Comment by zynbasil** [comment]
日志没什么特殊~明晚给你详细的~睡了~
