### ISSUE TITLE
报bug，ss的国内dns设置为获取运营商DNS无效

### ISSUE THREAD

**Issue by gonejack** [koolshare/koolshare.github.io#147]
设置为获取运营商DNS无效时，dnsmasq.conf里面写的是114.114.114.114，前面还有no-resolv。

我在wan口设置里自己指定的DNS无效。

实际上不仅想要自己指定DNS，还想给dnsmasq指定all-server，但似乎写了也会被刷掉。

**Comment by sadoneli** [comment]
请自行该dnsmasq配置文件，目前merlin ss因为做集成方案，这些地方的自由度会比较小

**Comment by gonejack** [comment]
找到bug原因是

`ISP_DNS=$(nvram get wan0_dns|sed 's/ /\n/g'|grep -v 0.0.0.0|grep -v 127.0.0.1|sed -n 1p)`

这里为空值，nvram get wan0_dns应该改为nvram get wan0_xdns
