### ISSUE TITLE
Bug: shadowsocks,大陆白名单, VPN连接不能fQ

### ISSUE THREAD

**Issue by lawrence-zhang** [koolshare/koolshare.github.io#149]
设备:R7000
Shadowsocks版本2.7
vpn, pptp连接路由器，不能打开google，设备连接状态是好的

**Comment by sadoneli** [comment]
你可以试试把你的pptp客户端的ip地址，在路由器上做个return

**Comment by lawrence-zhang** [comment]
原来2.0是可以翻墙的，vpn连接

**Comment by sadoneli** [comment]
https://github.com/koolshare/koolshare.github.io/blob/master/shadowsocks/shadowsocks/ss/redchn/nat-start#L71-L82

**Comment by sadoneli** [comment]
内部并没更改什么，理论上你2.0能翻，2.8也能翻

**Comment by lawrence-zhang** [comment]
给的pptp客户端地址是和路由器内网同一个网段

**Comment by sadoneli** [comment]
那你就应该检查下pptp客户端的dns了

**Comment by lawrence-zhang** [comment]
我现在看看

**Comment by lawrence-zhang** [comment]
vpn的信息如下ipv4是192.168.1.246 router：192.168.1.246， dns是192.168.1.1就是R7000

**Comment by jannson** [comment]
issue 会发很多邮件给各路邮箱，最好还是换个词。

同时，为何要把 vpn 与路由器弄成一个网段呢？分开两个网段呗。

**Comment by lawrence-zhang** [comment]
因为内部有一些服务器，是在网段192.168.1上。我是准备切换到B类网段，但是B类网段也存在一样的问题，如果路由在172.16.0.1, 那么172.16.1.1就不能翻墙，只有在172.16.0的网段才能fq，实在是很迷惑

**Comment by lawrence-zhang** [comment]
刚刚测试，我家里6300v2, shadowsocks版本不明，vpn可以fq， 公司是r7000, shadowsocks2.7, vpn不能fq

**Comment by lawrence-zhang** [comment]
不过家里用的是gfwlist

**Comment by mjw000** [comment]
我也是这个问题.不知道怎么解决.~ 局域网里是通过路由的SS是可以翻墙的.但是用vpn连接过来死活上不去..
