### ISSUE TITLE
编辑 gfwlist 模式下的黑名单，会让 httpd 崩溃

### ISSUE THREAD

**Issue by geekdada** [koolshare/koolshare.github.io#15]
我自己的配置如下：

https://gist.github.com/geekdada/2ebf126e85e39a147d37

提交后 httpd 就会崩溃，等待一段时间后才能重新登录，但是无法再浏览 gfwlist 模式这个 tab。唯一的解决办法就是把 `/jffs/config/ipset.sh` 里的黑名单设定恢复到无值状态才能再次打开页面。

**Comment by sadoneli** [comment]
@geekdada 如果你是在网页上添加这些list的，list过长就会导致这个问题，这个是因为post字节过多，导致httpd崩溃的，如果你要添加自己的list，可以尝试关掉gfwlist自动更新，然后修改/jffs/ss/ipset/gfwlist.conf文件

**Comment by geekdada** [comment]
实际上当添加后，每次打开那个 tab 也是会崩溃的。其实可以添加的条数非常少，大概20行不到。

**Comment by sadoneli** [comment]
确实是，这个问题一直都在，算是web上的一个bug吧

在 2015年9月17日 上午9:42，Roy Li <notifications@github.com>写道：

**Comment by geekdada** [comment]
是否有修复的计划？

**Comment by sadoneli** [comment]
精力有限，目前尚没有修复计划，顺便招募web人才
