### ISSUE TITLE
Proposal: <#add option> redo DNS lookup when problem detected. / 提议：<增选项>重做 DNS 查看什么时候问题检测到

### ISSUE THREAD

**Issue by amosnet** [koolshare/koolshare.github.io#150]
Hi,
Sorry for my bad Chinese.

1. I have a raspberry pi runs shadowsocks server & KCPTUN server in Europe.
2. I setup KCPTUN client at my apartment in Beijing, my devices connect to its listening port via DDNS pointing to my public IP there. It works like a charm. BUT
3. It's weird that my public IP address changes EVERYTIME my router restarts, although I fill DDNS into shadowsocks' server address, it still stuck at the IP address when service starts.

I think maybe you could make it better to make a option like check and lookup DDNS' IP again when problem detected shows up.

Thank you.

嗨
对不起我的中文不好。

1.我有一个树莓Pi运行shadowsocks服务器&KCPTUN 服务器在欧洲。
2.我设定KCPTUN客户在我的公寓在北京，我的设备连接到它正在听端口，从DDNS指针到那里我的公共IP。它的工作原理就像一個魅力
3.它是奇怪的那我的公共IP改变EVERYTIME我的路由器重新开始，尽管我填DDNS进shadowsock服务器地址，它仍然卡IP地址启动服务时的。

我想可能你们可以让它更好来做一个选项喜欢检查和抬头DDNS的IP再次当问题检测展示。

谢谢你们

**Comment by sadoneli** [comment]
Hi, 
Thanks for your proposal! and also sorry for my poor english.

For now ,the ip address is only checked once when the shadowsocks/kcptun service startup, and the ip address will be stored in skipd database running on merlin firmware, you can find it out by typing command `dbus get shadowsocks_server_ip`. However, when the DNS lookup failed, it will use the ip address pre-stored in the skipd database. In your case, when your kcp server ip changes, and the dns lookup failed, problem detected showed up. 
related code here https://github.com/koolshare/koolshare.github.io/blob/acelan_softcenter_ui/shadowsocks/shadowsocks/ss/ipset/start.sh#L10-L27

recently, I changed the dns server for DDNS resolve to 114.114.114.114, for its the most popular DNS server in China. Maybe I can add an option to define which DNS server to lookup when  shadowsocks/kcptun service startup. You can easyily set the dns server to some DNS provider which resolve your ddns more efficient.

you can change the `start.sh` files in `/koolshare/ss/ipset|redchn|game|koolgame|overall`   and `/koolshare/kcptun/gfwlist|chnmode` to test if it works.

**Comment by sadoneli** [comment]
I assume your ddns provider is  in Europe, you can simple change 114.114.114.114 to some DNS resolve provider in Europe. maybe it can help~

**Comment by amosnet** [comment]
Hi, Thanks for the quick reply.

The IP needs to be associated with DDNS is at my apartment located in Beijing, China.

It's obtained from the operator(China Unioncomm or something, sorry) via PPPoE.

as we know, we have to set a listening port on KCPTUN client, I just mapped this port to public, so that all of my devices can have KCP accelerated traffic over this port anywhere. I also have an ASUS router which is running Koolshare modified firmware at my office, I have to restart shadowsocks service everytime when my apartment's IP address changes.

I'm sorry that I may confuse you before and I have to say English is not my native language either ;)

Thank you.

**Comment by sadoneli** [comment]
Now I get it, you mean when the ip changed, problem detected showed up.  if there is a problem detected, can ss do dns lookup and reboot once.
However, there is a bad news,  to use the minimal resources in router , we do status check only when the Main_Ss_Contene.asp page is open, if you are not on the page, we do not know the status of the shadowsocks.
one way to do that is make a monitor scripts  running in background, if you can write it, jsut run /koolshare/scripts/ss_config.sh, when problem detected is showed up.

**Comment by amosnet** [comment]
Thanks, I'll try to do the logical test script and keep an eye on resource consumption on the router.

I'll back to report if I get positive results.

Thanks for the ideas, and wish me luck.

**Comment by sadoneli** [comment]
some tips:
1 run /koolshare/ss/cru/foreign.sh, when problem detected show in your monitor scripts, reboot ss by running `/koolshare/scripts/ss_config.sh`
2 run nslookup you ddns monitor scripts, when ip change detected,reboot ss by running `/koolshare/scripts/ss_config.sh`

good luck!

**Comment by amosnet** [comment]
Hi, All.

After two days testing with this script, my problem has been solved.

Just run in background.

Regards.


```
LOOP=true
DNSA=$(nslookup ###YOUR_DDNS_DOMAIN_HERE### | tail -n1)
while [ "$LOOP" = "true" ]
do
if ping -c 1 www.baidu.com &> /dev/null
then
 printf "WAN OK and Mr. Lee Ianhon is reached.\n Sleep for 60sec.\n"
 sleep 60
 DNSB=$(nslookup ###YOUR_DDNS_DOMAIN_HERE### | tail -n1)
 if [ "$DNSB" == "nslookup: can't resolve '###YOUR_DDNS_DOMAIN_HERE###'" ]
 then
  printf "WAN or DDNS service may down.\n"
  sleep 60
 else
  if [ "$DNSA" == "$DNSB" ]
  then
   printf "Result matched this round, No IP change has been made.\n"
   LOOP=true
  else
   printf "Result mis-match.\nShadowsocks service is restarting...\n"
   sh /koolshare/scripts/ss_config.sh &
   sleep 120
  fi
 fi
else
printf "WAN down or Mr. Lee Ianhon is down.\n"
sleep 60
fi
done

```

**Comment by sadoneli** [comment]
wow~ nice work!
