### ISSUE TITLE
Aakamai和Apple的CDN经常性shutdown(relay, SHUT_WR)

### ISSUE THREAD

**Issue by skksdd** [koolshare/koolshare.github.io#151]
系统日志里的报错几本都是这两家的cdn

 shutdown(client, SHUT_WR): Transport endpoint is not connected

有方法解决吗？ 或者实现域名通配符添加到黑名单中强制走shadowsocks线路可行吗？

**Comment by sadoneli** [comment]
你好，这是redsocks2的运行日志
如果有疑问，可以去作者的项目地址反馈：https://github.com/semigodking/redsocks

**Comment by skksdd** [comment]
@sadoneli thx
