### ISSUE TITLE
远程连接路由器上的SS 服务器不能翻墙

### ISSUE THREAD

**Issue by ywwzwb** [koolshare/koolshare.github.io#154]
家里路由器已经设置 SS 翻墙, 家里的局域网中可以正常翻墙
在路由器上使用 ss-server 插件开启一个 ss 服务(主要是想方便在公司等地方使用电脑/手机访问家中局域网并且可以享受翻墙)
在公司连接家中服务器之后,  局域网可以正常访问, 但是翻墙就不行了
如果在家中局域网中其他电脑上部署 ss 服务则可以正常翻墙并访问局域网

**Comment by sadoneli** [comment]
ss-server插件不是用来fq的，作用本身就是用来远程链接回路由器的
