### ISSUE TITLE
Google+访问的问题

### ISSUE THREAD

**Issue by sevenfxx** [koolshare/koolshare.github.io#16]
Google+ https://plus.google.com 的访问情况很奇怪
全局，游戏模式正常
大陆白名单模式有时正常
Gfwlist模式不正常，页面返回ERR_TIMED_OUT

奇怪的是在Gfwlist模式下，其它被墙的网站，包括google的其它网站（map，gmail，news，blog等）都可以访问，就只有这个G+不能。

路由器是R6300V2 Firmware:378.56_alpha2-X5.6

**Comment by sadoneli** [comment]
这个问题待观察，我这里和其他几个刷过的测试了是没问题的，按理说这个问题存在上个版本，这个版本应该是解决了的，你试试格式化掉jffs分区后重新尝试，并确保DNS缓存没有污染

**Comment by sevenfxx** [comment]
今天又可以了，不知道怎么回事，估计是你说的原因。
