### ISSUE TITLE
抗重放、CCA攻击升级版协议 auth_sha1_v3 SSR更新了新协议插件

### ISSUE THREAD

**Issue by Expectopen** [koolshare/koolshare.github.io#161]
抗重放、CCA攻击升级版协议 auth_sha1_v3 SSR更新了新协议插件

**Comment by sadoneli** [comment]
你好，ssr-libev项目并未见到更新auth_sha1_v3
https://github.com/breakwa11/shadowsocks-libev

**Comment by Expectopen** [comment]
破娃新客顾端已更新这协议

发自我的 iPhone

在 2016年9月8日，11:35，sadoneli <notifications@github.com> 写道：

你好，ssr-libev项目并未见到更新auth_sha1_v3
https://github.com/breakwa11/shadowsocks-libev

**Comment by sadoneli** [comment]
@Expectopen 那个没用，因为路由器下用的是libev版本的客户端

**Comment by Expectopen** [comment]
ssr-libev更新：支持auth_sha1_v4

发自我的 iPhone

在 2016年9月9日，11:23，sadoneli <notifications@github.com> 写道：

@Expectopen 那个没用，因为路由器下用的是libev版本的客户端

**Comment by lingaoyi** [comment]
求S大更新～～～

**Comment by sadoneli** [comment]
会的
