### ISSUE TITLE
游戏模式加载有问题

### ISSUE THREAD

**Issue by lastczj** [koolshare/koolshare.github.io#163]
Fri Sep 9 15:37:51 GMT 2016: ------------------- Shadowsock GAME mode Starting-------------------------
Fri Sep 9 15:37:54 GMT 2016: create shadowsocks config file...
Fri Sep 9 15:37:54 GMT 2016: done
Fri Sep 9 15:37:54 GMT 2016:
Fri Sep 9 15:37:55 GMT 2016: create dnsmasq.conf.add..
Fri Sep 9 15:37:55 GMT 2016: done
Fri Sep 9 15:37:55 GMT 2016:
Fri Sep 9 15:37:55 GMT 2016: append router output chain rules
Fri Sep 9 15:37:55 GMT 2016: done
Fri Sep 9 15:37:55 GMT 2016:
Fri Sep 9 15:37:55 GMT 2016: append CDN list into dnsmasq conf file in game mode
Fri Sep 9 15:37:56 GMT 2016: done
Fri Sep 9 15:37:56 GMT 2016:
Fri Sep 9 15:37:56 GMT 2016: create dnsmasq.postconf
Fri Sep 9 15:37:56 GMT 2016: done
Fri Sep 9 15:37:56 GMT 2016:
Fri Sep 9 15:37:56 GMT 2016: Add service to nat-start...
Fri Sep 9 15:37:56 GMT 2016: done
Fri Sep 9 15:37:56 GMT 2016:
Fri Sep 9 15:37:56 GMT 2016: Add service to wan-start...
Fri Sep 9 15:37:56 GMT 2016: done
Fri Sep 9 15:37:56 GMT 2016:
Fri Sep 9 15:37:56 GMT 2016: ss rule schedual update not enabled
Fri Sep 9 15:37:56 GMT 2016: done
Fri Sep 9 15:37:56 GMT 2016:
 2016-09-09 15:37:57 INFO: protocol auth_sha1_v2
 2016-09-09 15:37:57 INFO: method rc4-md5
 2016-09-09 15:37:57 INFO: obfs tls1.2_ticket_auth
 2016-09-09 15:37:57 INFO: obfs_param cloudflare.com
Fri Sep 9 15:37:57 GMT 2016: Starting chinadns
Fri Sep 9 15:37:57 GMT 2016: done
Fri Sep 9 15:37:57 GMT 2016:
Fri Sep 9 15:37:57 GMT 2016: Starting ss-redir...
Fri Sep 9 15:37:57 GMT 2016: done
Fri Sep 9 15:37:58 GMT 2016:
Fri Sep 9 15:37:58 GMT 2016: Apply nat rules!
Fri Sep 9 15:38:02 GMT 2016: load TPROXY modules...
Fri Sep 9 15:38:02 GMT 2016: done
Fri Sep 9 15:38:02 GMT 2016:

看日志发现卡在那里了。重现了很多次了。论坛发现其他人也有这样的情况。本人R6300V2。

**Comment by sadoneli** [comment]
请检查mangle表，nat表，还有route表，另外ap模式应该也会出现这种
