### ISSUE TITLE
R7000_380.61-X7.0  电流声

### ISSUE THREAD

**Issue by skksdd** [koolshare/koolshare.github.io#166]
R7000_380.61-X7.0.trx 更新之后有显著电流声

之前6.6.1 并无此问题， 准备降级到6.6.1 降级之后会更新测试结果。

**Comment by guqikay** [comment]
R7000本来就有的。。

**Comment by skksdd** [comment]
@guqikay 降级6.6.1之后没有了。 又试着升级7.0 还是感觉很明显
