### ISSUE TITLE
关于插件 ddnspod的问题：自动更新到dnspod的ip，与路由器自身的公网ip不一致；

### ISSUE THREAD

**Issue by ifcheung2012** [koolshare/koolshare.github.io#171]
如题，也不知道为什么，百度过通过dnspod api 得到公网ip 也试过，确实不一样，代码如下：

> import socket
> def getip():
>   sock = socket.create_connection(('ns1.dnspod.net', 6666))
>   sock.settimeout(10)
>   ip = sock.recv(16)
>   sock.close()
>   return ip
> 
> if **name** == '**main**':
>   ip = getip()
>   print(ip)

**Comment by sadoneli** [comment]
路由器的公网ip是从路由器内拿的，如果不一致，检查下自己是否在nat后
