### ISSUE TITLE
插件系统bug

### ISSUE THREAD

**Issue by GongT** [koolshare/koolshare.github.io#173]
shadowsocks页面：
![image](https://cloud.githubusercontent.com/assets/2265048/18834740/31b33b4e-842a-11e6-9846-a0bd36922a61.png)

Tools>Script 页面
![image](https://cloud.githubusercontent.com/assets/2265048/18834758/4c9c551c-842a-11e6-8aaa-3cb0903f2f67.png)

不是很确定原因，   
似乎是因为添加了一个定时脚本？（每天6点执行 /jffs/scripts/6am.sh ）

**Comment by sadoneli** [comment]
可能是因为skipd储存的值出问题了！
删除/jffs/db，重新配置试试把，不过这样会丢失所有的软件中心配置

**Comment by jannson** [comment]
定时脚本有 bug, sorry.

以前一直没解,我们内部已经不用这个定时功能了.
