### ISSUE TITLE
ss 挂了以后，DNS 也跟着挂了

### ISSUE THREAD

**Issue by cielpy** [koolshare/koolshare.github.io#175]
ss + pdnsd 组合，pdnsd 的上游是 8.8.4.4，在 ss 挂了以后，pdnsd 也挂了，不能正常解析很多国外域名，简单试验了下，应该是 8.8.4.4 也走了 ss 代理，把 8.8.4.4 添加到 IP/CIDR白名单 后可以正常解析了。

不知道以上猜测对吗，如果是的话，我想 8.8.4.4 之类的 DNS 应该默认在白名单里比较好吧。

**Comment by sadoneli** [comment]
pdnsd在merlin上还是不够稳定，不太建议使用

**Comment by cielpy** [comment]
比较稳定的是？

**Comment by sadoneli** [comment]
请看固件内关于dns的说明

2016-12-08 10:27 GMT+08:00 Kevin <notifications@github.com>:
