### ISSUE TITLE
SS更新到291后频繁出现ss-redir[2674]: Request did not begin with TLS handshake.

### ISSUE THREAD

**Issue by FlyingGitHub** [koolshare/koolshare.github.io#176]
降级到288后解决，环境标准ss，开启OTA

**Comment by sadoneli** [comment]
2.9.1使用的是ss-libev 2.5.3，请确保服务器端也是一样的版本，或者最新的版本

**Comment by FlyingGitHub** [comment]
28号重装的shadowsocks-libev-2.5.3，已经最新。

**Comment by FlyingGitHub** [comment]
S大，已确认服务器端是最新的shadowsocks-libev-2.5.3，开启OTA，不知道这个报错是SS的问题还是固件的问题。

**Comment by FlyingGitHub** [comment]
再次测试结果：
客户端环境：ss插件2.8.9及以上版本,gfwlist模式，rc4-md5加密，ota开启
服务器环境：vultr日本机房shadowsocks-libev 2.4.7，digitalocean新加坡机房shadowsocks-libev 2.5.3
目前问题：路由日志中不断出现"ss-redir[2674]: Request did not begin with TLS handshake."
暂时解决方案：ss插件降级到2.8.8，恢复正常。

**Comment by tonyshva** [comment]
我也碰到同样的问题，估计还是插件的问题

**Comment by FlyingGitHub** [comment]
据说是openssl库的问题，用mbedtls （原PolarSSL）可以解决报错的问题

**Comment by jannson** [comment]
现在已经用上 mbedtls 了。

**Comment by FlyingGitHub** [comment]
感谢

发自我的 iPhone

在 2016年12月8日，09:31，janson <notifications@github.com<mailto:notifications@github.com>> 写道：


现在已经用上 mbedtls 了。

―
