### ISSUE TITLE
国外连接 Problem detected!

### ISSUE THREAD

**Issue by gdillainepub** [koolshare/koolshare.github.io#177]
这是个老问题了，在6.5时代早期的$$不存在这个问题，后来$$几次更新后出现改问题：
- gfw模式下
# \- 明明可用的$$节点，提示 “国外连接 Problem detected!”。这一问题一直延续到最新版本的$$
1. 再这问题刚出现时：我曾在论坛发帖报错。有开发者表示：国外连接是否有Problem仅供参考、因此也未对这个问题尝试修复。
2.  我想说的是，这个功能是重要的，有必要修复。特别是当节点出问题时，我们需要知道国外连接到底有没有问题：如果不论有没有问题，$$一律显示 “国外连接 Problem detected!” 那我们就无法判断节点到国外连接到底行不行了
3. 热切希望开发者能修复这一问题（问题似乎仅限于gfw模式；白名单模式等就没有这个问题）

**Comment by sadoneli** [comment]
请更新到最新版本尝试
