### ISSUE TITLE
请问能否加入反向Shadowsocks

### ISSUE THREAD

**Issue by Gizardry** [koolshare/koolshare.github.io#179]
开发者你(们)好
因为在海外的华人，有连接内地服务的需求，不知道能否请求开发逆向功能。
就是比如gfwlist中的站在大多数人的使用场景下，应该走ss，而反向的情况下，就不走ss（本质上就是黑白名单反着用）。
可能用其他软件实现起来会比较方便，但是由于集成在路由器里，可以傻瓜化使用，我在内地买好服务器，让妹子点点路由器的设置界面还是会方便一些。

不知道这个请求会不会太过分，无论如何谢谢了。

还有顺带就是，能提供一个支付宝捐款链接么？

**Comment by sadoneli** [comment]
你好，思路是这样的没错，不过实际情况是比较复杂的
比如说一个国外网站并没有被墙，也不会收录进gfwlist，如果纯反向的话，那么你访问这个网站本来是走你本地网络快些，但是最后的情况是走了中国的vps去访问

另一种方式就是用chnroute，根据ip地址块去做这个，所有中国的ip段全部都走中国的vps，但是也有个问题，就是dns解析的问题，因为大陆的dns是有污染的，如果这样，就会导致你请求google等网站的dns被污染，也访问不了

那么解决方案就是用国外的dns了，但是用国外的dns也面临着中国的网站会被解析到全球ip，比如淘宝变成淘宝全球

我想的方案智能是chnroute+chinadns了，这样可能会好一些，但是一直苦于没有时间去做，因为没法时时测试

在 2016年10月4日 上午12:23，Gizardry <notifications@github.com>写道：

**Comment by Gizardry** [comment]
果然还是我想的太简单了

不过实际上诉求主要体现在看视频、听音乐等， 可能还是直接建一个cnCoreList收录提供版权服务的网站+各大常见网站会简单一些（国外有些面向华人的ISP似乎偷偷提供了类似的服务）。

还是谢谢你的回复了。

**Comment by Gizardry** [comment]
对了，我现在在做国内网站的列表，cnNetList项目。你看下这样做有没有用，我对这个方面不是太精通，谢谢了。

**Comment by Gizardry** [comment]
还有就是捐赠了点钱到支付宝，不知道你收到没。

**Comment by sadoneli** [comment]
哇，一直没关注，有收到的，谢谢你的支持！

**Comment by sadoneli** [comment]
另外，做回国模式的话，我打算用这个项目的名单，你的项目可以多少参考下

**Comment by sadoneli** [comment]
打算于最近来做回国模式

**Comment by freefrank** [comment]
啊果然有这个issue啊，我在用安卓的ssr客户端，只代理国内IP段，用的chnroute，不知道ks的ss能这么做么。我试着清空gfwlist.conf然后在网页黑名单chnroute，结果是不行。请问应该怎么做？

**Comment by sadoneli** [comment]
可以自己改下脚本内对流量的判断部分，不过因为集成度比较高，所以牵扯比较多
或者是可以等新版本推出这个模式

**Comment by freefrank** [comment]
正在看代码，太久没写代码了有点吃力XD

**Comment by sadoneli** [comment]
国内模式已经添加，未来例行维护
