### ISSUE TITLE
DNS设定中用“dnscrypt-proxy“的问题

### ISSUE THREAD

**Issue by leochien0102** [koolshare/koolshare.github.io#181]
选择dnscrypt-proxy模式，不管选列表中哪个dns，应用后都会跳回列表中的第一个4armed，格式化jffs，重新安装ss，都这样，更新了好几个版本也都一样。

**Comment by lingaoyi** [comment]
好早跟S大反应过，但他没有回复我。

**Comment by antenna2008** [comment]
这个问题在2.9.6中已经修复

**Comment by lingaoyi** [comment]
根本就没有修复。。。。

**Comment by leochien0102** [comment]
嗯，问题还在。应用后看起来是好了（假象？），但如果返回到软件中心再次进入SS，看到的还是列表中的第一个4armed。

**Comment by sadoneli** [comment]
确实bug，不好意思
点击opends应用后实际提交的是opendns，但是这个值没有回传到网页，所以网页上没变

2016-10-27 9:23 GMT+08:00 leochien0102 <notifications@github.com>:

**Comment by antenna2008** [comment]
其实第一项4armed可以移走了，这个DNS一般ping不通的

**Comment by sadoneli** [comment]
已修复

**Comment by leochien0102** [comment]
最新的3.0.7，4armed永生不死
![qq](https://cloud.githubusercontent.com/assets/3915276/20121006/3d04707a-a64a-11e6-9033-71cfe39855fc.png)
![qq 1](https://cloud.githubusercontent.com/assets/3915276/20121011/40cef19e-a64a-11e6-8bef-5acf748cf89e.png)

**Comment by sadoneli** [comment]
这里是显示问题，显示了大陆白名单了的设置，已经修复https://github.com/koolshare/koolshare.github.io/commit/3c22d4056cb6935688797e070e0cfe13e7596463#diff-94b82dc86d3e9f3f7a6eaa8a380c1ed9
下次推送将会包含此修复
