### ISSUE TITLE
希望增加针对端口的shadowsocks代理设置

### ISSUE THREAD

**Issue by hydjan** [koolshare/koolshare.github.io#183]
如题，日常应用中80和443端口已经足够，考虑到ssh等应用，系统保留端口也足够，对这些端口执行透明代理，其他端口正常出入，这样的策略更符合使用规律。一般BT都是通过端口映射占用后面的端口，简单区分一下可有效防止家用电脑BT流量占用ss通道，对一些非常规应用的兼容性也将有所提升。
如能实现，感激不尽！

**Comment by sadoneli** [comment]
近日的版本添加了访问控制，已经实现了这个功能
