### ISSUE TITLE
ss开关时会删除 /jffs/configs/dnsmasq.conf.add，没有办法自定义域名了

### ISSUE THREAD

**Issue by GongT** [koolshare/koolshare.github.io#185]
RT，应该开关时分别备份恢复比较好。。。

**Comment by GongT** [comment]
“DNS设定”里的“自定义dnsmasq”

输入时需要用回车分割
但一保存再读取就变成逗号分割了

由于输入还是需要回车
二次保存整个配置就爆炸了（conf.add里自定义的内容直接清空）

**Comment by sadoneli** [comment]
请更新到最新版本，现在以已经使用base64处理换行问题，不再使用逗号
