### ISSUE TITLE
新版的GFWlist模式有问题，貌似是全局代理。

### ISSUE THREAD

**Issue by woner363** [koolshare/koolshare.github.io#188]
最近shadowsock流量用得很快，一天都要用几十个G，今天偶然打开b站显示504错误，然后就列了我shadowsock的ip地址是日本的ip，我又里面打开ip.cn看我的ip又确实是日本的ip，切换到大陆白名单和游戏模式又没有这个问题了

**Comment by sadoneli** [comment]
请更新到最新版本尝试
