### ISSUE TITLE
Dualwan 1.2 插件 重大Bug报告

### ISSUE THREAD

**Issue by FlyingGitHub** [koolshare/koolshare.github.io#190]
更新dualwan 1.2后策略路由失效，貌似出口随机选择，卸载、重装、重启均无效。烦请告知退回 1.1版的方式，谢谢。

**Comment by jannson** [comment]
从 github 直接下载 1.1 版本,那个 .tar.gz 文件.放到 /tmp 文件夹下解压,然手 sh /tmp/文件夹名字/install.sh

就可以了.

**Comment by FlyingGitHub** [comment]
未找到历史版本的下载路径

**Comment by jannson** [comment]
https://github.com/koolshare/koolshare.github.io/tree/acelan_softcenter_ui/dualwan/history

**Comment by jannson** [comment]
不知道这个是不是,不是的话你找找.反正 github 都有版本管理的.

**Comment by FlyingGitHub** [comment]
那是0.1，最初的版本，1.1不见了

**Comment by sadoneli** [comment]
https://raw.githubusercontent.com/koolshare/koolshare.github.io/b218b45589e97e2eee83d3b0a8ff07228ba8a373/dualwan/dualwan.tar.gz
