### ISSUE TITLE
Dualwan 1.3 插件 轻微Bug报告

### ISSUE THREAD

**Issue by FlyingGitHub** [koolshare/koolshare.github.io#191]
crc.txt文件，第4800行数据为“12”，1.1版的历史数据就有这个问题，下次升版时建议删除此行错误数据。

**Comment by sadoneli** [comment]
https://github.com/koolshare/koolshare.github.io/commit/723e3e1e304b38eadac1f35a18781a498bec13a4

**Comment by FlyingGitHub** [comment]
神同步
