### ISSUE TITLE
更新到3.01后，加载配置的时候出现黑屏

### ISSUE THREAD

**Issue by ilsz** [koolshare/koolshare.github.io#193]
在导入Surge配置文件后，点击恢复配置，提示上传完成，然后马上在屏幕正中出现一个黑色窗口，没有任何内容，没有任何按钮可以点击
![ss](https://cloud.githubusercontent.com/assets/15071117/19625298/45a6c8f0-9947-11e6-85f5-d1330bd59190.png)

**Comment by sadoneli** [comment]
3.0.3已经修复
