### ISSUE TITLE
3.0.4 负载均衡无法设置 

### ISSUE THREAD

**Issue by sxxhlx** [koolshare/koolshare.github.io#195]
今天准备设置负载均衡，但是进入设置页面后不管是点击服务器添加还是点击提交，页面都没有反应。打开Chrome的控制台发现有一个叫做 softcenter的js文件出现 404错误。点击服务器添加后面的按钮或提交按钮Chrome的控制台都有报错，请问有小伙伴碰到同样的问题嘛？
![084426r4zv6oeyp2yoxbbe](https://cloud.githubusercontent.com/assets/3366445/19750420/7fbcfec2-9c23-11e6-8a31-9b8e52bbd7c4.png)

**Comment by sadoneli** [comment]
在ssh或者telnet种运行service restart skipd能解决你的问题

在 2016年10月27日 上午8:58，李潇 <notifications@github.com>写道：

**Comment by sxxhlx** [comment]
@sadoneli 运行 service restart skipd 之后，shadowsocks中负载均衡设置的tab 消失了

**Comment by sadoneli** [comment]
重装ss就行

**Comment by sxxhlx** [comment]
@sadoneli 是的，昨天感觉不知道怎么办，就重装了SS，现在已经搞定了 。谢谢
