### ISSUE TITLE
请问kms是那个版本？今天试激活win server2016失败 能否升级最新的svn1065版本？

### ISSUE THREAD

**Issue by luodaoyi** [koolshare/koolshare.github.io#199]
请问kms是那个版本？今天试激活win server2016失败 能否升级最新的svn1065版本？
>使用svn包内的`floppy144.vfd`用hyper-v搭建的服务器可以激活。但是路由器的版本却不能激活。不知道是不是版本的原因？

**Comment by sadoneli** [comment]
kms插件已经转出：https://github.com/Major-k/merlin-kms.git
