### ISSUE TITLE
是不是脚本有问题。

### ISSUE THREAD

**Issue by yulhun** [koolshare/koolshare.github.io#2]
Jul 10 17:30:01 crond[491]: crond: USER  pid 3294 cmd /bin/sh /jffs/ss/cru/foreign.sh
Jul 10 17:30:01 crond[491]: crond: USER  pid 3295 cmd /bin/sh /jffs/ss/cru/china.sh
我的就出现这个呢 很多为什么呢？满屏就这个呢。
还有http://www.speedtest.net/ 这个网站测速 外网IP总是墙外的呢，

**Comment by yulhun** [comment]
添加不需要走代理的外网ip地址    这个也没用呢。

**Comment by sadoneli** [comment]
@yulhun 这个是后台自动运行的状态检测脚本，两分钟运行一次，这个版本的检测机制尚不成熟，可能有一定的问题，下个版本会改进这部分，你就不会看到这么多的这个日志了

看你用什么模式了，如果你使用大陆白名单模式和游戏模式，那么可能是会解析到国外的
如果你用gfwlist模式，就会解析到国内，除非你添加域名黑名单
另外你每次切换模式或者开关ss，需要清空电脑dns缓存，才能看到speedtest.net显示正确IP地址
