### ISSUE TITLE
merlin固件380.57_X6.5,SS升级到了3.05,国外连接在”working“和"Problem Detect"之间反复切换

### ISSUE THREAD

**Issue by seanyang** [koolshare/koolshare.github.io#200]
merlin固件380.57_X6.5,SS升级到了3.05,国外连接在”working“和"Problem Detect"之间反复切换

SS客户端启用了chacha20，auth_sha1_v4和tls1.2_ticket_auth.

配置选用gwflist，或者大陆白名单，都是这样，一会儿显示working，很快又显示PD，然后又显示working，似乎很不稳定，不知道这样是否正常？因为不稳定，我也不知道是SS的问题，还是DNS的问题。

请帮助解决。

**Comment by sincerywaing** [comment]
我升级3.0.5和3.0.6国外都PD，回退到3.0.4就正常。

**Comment by sincerywaing** [comment]
我升级3.0.5和3.0.6国外都PD，回退到3.0.4就正常。

**Comment by sincerywaing** [comment]
我升级3.0.5和3.0.6国外都PD，回退到3.0.4就正常。

**Comment by sadoneli** [comment]
对于这个问题在插件内部有说明，很难的，我还是怀疑你帐号问题

**Comment by seanyang** [comment]
sincerywaing,怎么回退到3.*04？

**Comment by sadoneli** [comment]
还是建议有稳定良好的线路

**Comment by seanyang** [comment]
账号没问题的，只要我用手机影梭就是好的，用PC的SS也是好的。

2016-12-08 9:46 GMT+08:00 sadoneli <notifications@github.com>:
