### ISSUE TITLE
不支持自定义DNSCrypt

### ISSUE THREAD

**Issue by wdhwg001** [koolshare/koolshare.github.io#201]
同时DNSCrypt的列表存在大量重复（像是复制粘贴了好多遍一样），且有些服务已经不再可用。

**Comment by sadoneli** [comment]
上次更新时同步的官方最新列表，不存在重复的

**Comment by sadoneli** [comment]
可能是生成列表时函数运行了多次导致块重复

**Comment by wdhwg001** [comment]
![image](https://cloud.githubusercontent.com/assets/8943519/20004206/f776f258-a2c5-11e6-9be7-237d8bd6564a.png)

的确是最新版出现的问题。

如果可以复现的话，把issue重新打开吧。

**Comment by sadoneli** [comment]
自定义暂时不会做的，这个区块重复下次会尝试修的哈
