### ISSUE TITLE
希望可以关闭ChinaDNS的转发。

### ISSUE THREAD

**Issue by wdhwg001** [koolshare/koolshare.github.io#203]
对于一些墙内加速的CN2服务来说，即使使用SS-tunnel或DNS2SOCKS均无法得到无污染的解析结果，因此希望支持关闭ChinaDNS的转发功能，由路由器直接与海外DNS通讯并处理污染。

**Comment by sadoneli** [comment]
你好，这样会牺牲国内的cdn，建议你使用全局模式

在 2016年11月4日 下午7:46，wdhwg001 <notifications@github.com>写道：

**Comment by wdhwg001** [comment]
为什么？

我的意思是，目前ChinaDNS使用一个国内DNS和一个海外DNS，海外DNS由SS服务器转发。

但对于一个墙内的SS来说，即使将海外DNS交由它去访问，也仍然会受到污染。

因此，能否允许ChinaDNS不搭配ss-tunnel/DNS2SOCKS，即海外DNS直接由路由器去访问？

**Comment by Max-Sum** [comment]
有类似需求，感觉可以给 ss-tunnel/DNS2SOCKS 增加一个选择其他配置的功能。

**Comment by sadoneli** [comment]
@Max-Sum 你的意思是可以自由配置chinadns的上游dns服务器吧

**Comment by Max-Sum** [comment]
是的
sadoneli <notifications@github.com>于2016年11月5日(土)12:37写道：

**Comment by sadoneli** [comment]
https://github.com/koolshare/koolshare.github.io/commit/11f57e4d0809b74ceda044bc47af2d4845d2c388
已经添加，不过有些值不能沿用，所以如果在chinadns状态下更新了插件，可能导致更新后无法启动，需要重新填写参数

**Comment by shiny** [comment]
@sadoneli 
我在版本 `3.1.5` 中选择 `ChinaDNS 国外DNS` 自定义 为 `8.8.8.8`，通过 ps 命令发现 chinadns 的参数为：`chinadns -p 1053 -s 114.114.114.114,127.0.0.1:1055 -m -d -c /koolshare/ss/redchn/chnroute.txt` 

最近出现的问题：GFW 间歇性屏蔽 UDP Relay， tcp 的未受影响。
但是因为固件里 ChinaDNS 仅仅允许配置一个国内 dns 和一个国外 ss-tunnel 转发后的 dns 地址，导致无法过滤污染后的 DNS 包。

实际上根据 ChinaDNS 的工作原理，不需要走 ss-tunnel 就可以解决 DNS 污染的问题，所以这个额外的「贴心」设置反而给我带来了困扰。

目前我在局域网的 Linux 服务器上架设一个 ChinaDNS，使用默认参数绕过了这个问题。
不知道在固件里能否通过设置直接解决这个问题？
