### ISSUE TITLE
在DNS配置页面中直接关闭SS后存在页面清理不全的Bug。

### ISSUE THREAD

**Issue by wdhwg001** [koolshare/koolshare.github.io#205]
![image](https://cloud.githubusercontent.com/assets/8943519/20005413/04fb49d6-a2cd-11e6-9f08-bfb8e170fb1e.png)

像这样。

**Comment by sadoneli** [comment]
https://github.com/koolshare/koolshare.github.io/commit/46d1fd4518dd027b4257ff92a60d62abdaef11d4
已修复，下次更新会打包进去
