### ISSUE TITLE
升级3.0.6后SS就直接炸了啊

### ISSUE THREAD

**Issue by mahaoying** [koolshare/koolshare.github.io#206]
SSR原本在3.0.5下工作的好好的，升级就检查problem了。死活用不了了，国外连接一直在problem。在电脑上用SSR客户端一切正常。重启两三次无果。R6300V2，6.5固件，求助力。

**Comment by sadoneli** [comment]
尝试卸载后重装

**Comment by JackyRen** [comment]
我是DNSMASQ还有黑白名单里都是乱码，删了就好了

顺颂
      时祺
-----------------------------------------------
任杰
清华大学
计算机科学与技术系计12
Mobile:15652918671
Email:rjjacky@gmail.com

2016-11-04 23:03 GMT+08:00 sadoneli <notifications@github.com>:

**Comment by sadoneli** [comment]
是的，如果升级配置出现问题确实会这样，因为3.0.6开始，这部分数据会经过base64加密，详情看更新日志

2016-11-04 23:45 GMT+08:00 Ren Jie <notifications@github.com>:

**Comment by mahaoying** [comment]
重装了ss无效，重新配置照样报错。

**Comment by zhuchiheng** [comment]
还好升级前过来看了眼..
