### ISSUE TITLE
望增加模式共存

### ISSUE THREAD

**Issue by Max-Sum** [koolshare/koolshare.github.io#209]
家里有一台 PS4，需要同时对 PS4 开启游戏模式，对其他电脑开启白名单模式。
暂时将 Socks5 改造为 PS4 专用代理。

**Comment by sadoneli** [comment]
本来有这个打算，但是因为ss插件从去年一直做到现在，当初的设计逻辑不太适用于这种情况，以后会想办法的

**Comment by jannson** [comment]
新软件中心吧。

**Comment by sadoneli** [comment]
访问控制已经在最近的版本出现，支持你说的这个功能了
