### ISSUE TITLE
KCP参数的文本框长度不够，建议扩容

### ISSUE THREAD

**Issue by choicky** [koolshare/koolshare.github.io#211]
例如，下面的参数，后面1/3被截断了

 --crypt "salsa20" --nocomp --datashard 30 --parityshard 15 --conn 1 --mtu 1400 --sndwnd 128 --rcvwnd 1024 --dscp 46 --autoexpire 300 --keepalive 10 --sockbuf 4194304 --mode "manual" --nodelay 0 --interval 20 --resend 2 --nc 1

**Comment by sadoneli** [comment]
https://github.com/koolshare/koolshare.github.io/commit/f6865e58898da1b6e11f5665ed2ce8e80fbeaf4d

下次推送将包含此更新
