### ISSUE TITLE
3.0.6恢复配置又不能正常工作了

### ISSUE THREAD

**Issue by antenna2008** [koolshare/koolshare.github.io#212]
希望尽快修复。另外请关注http://koolshare.cn/thread-68512-1-1.html

**Comment by sadoneli** [comment]
已修复https://github.com/koolshare/koolshare.github.io/commit/6170ee316da4e5b55c6155567509e53df1e3bd7c

另外需要关注的也已经修复：https://github.com/koolshare/koolshare.github.io/commit/119823ed5336e949344c889650e7fad338387023

下个版本推送将会包含这些修复
