### ISSUE TITLE
建议开发软件中心HAproxy插件

### ISSUE THREAD

**Issue by FlyingGitHub** [koolshare/koolshare.github.io#213]
场景：路由器所在网络（pppoe或者静态ip）访问质量较好，希望能能通过路由器中转。

**Comment by jannson** [comment]
现在已经有了。不过是用于负载均衡。

**Comment by FlyingGitHub** [comment]
希望单纯的haproxy，能对外转发流量。

发自我的 iPhone

在 2016年12月8日，09:25，janson <notifications@github.com<mailto:notifications@github.com>> 写道：


现在已经有了。不过是用于负载均衡。

―

**Comment by sadoneli** [comment]
目前还不会做相关的插件来实现这个想法，不过你可以安装ss插件后，利用里面的haproxy程序来手动配置
