### ISSUE TITLE
ss配置HAproxy生成错误

### ISSUE THREAD

**Issue by tossp** [koolshare/koolshare.github.io#214]
我有20个ss节点，全部做了负载均衡
删除中间一个节点
会生成
```shell
ssconf_basic_use_lb_=1
```
这个样子的配置，原因未知。。。。最终生成错误的HAproxy配置

我尝试了，备份ss配置，手动删除，再恢复，问题依然。。。。

暂时修改了生成HAproxy配置的脚本`ss_lb_config.sh`

在
```shell
nick_name=`dbus get ssconf_basic_name_$node`
```
之后添加一个if判断
```shell
if [ ! -z "$nick_name" ];then
```

额，如果要沿用这个方案，建议在解析域名前判断`$server`变量，，，，毕竟，设置节点的时候`服务器地址`才是必填项

**Comment by tossp** [comment]
还有一个小问题，就不开新的issues了，
编辑节点的时候，服务器地址和端口希望可以自动删除前后的空白字符，有的时候复制会不小心复制到制表符和空格。。。。

或者端口号的输入框直接用`<input type="number">`不过这个只对html5的浏览器有效

**Comment by sadoneli** [comment]
我试了下你说的情境，没能重现ssconf_basic_use_lb_=1这个，
不过为了避免这个情况出现，改动下面的应该比较好
`lb_node=`dbus list ssconf_basic_use_lb_|sed 's/ssconf_basic_use_lb_//g' |cut -d "=" -f 1 | sort -n | sed '/^$/d'``

**Comment by sadoneli** [comment]
节点的名字是必要字段，和server一样重要的如果
```shell
nick_name=`dbus get ssconf_basic_name_$node`
```
这个值是空的，是不会出现在节点列表中的，另外server字段用在了下面kcp的判断赋予不同的server，所以用server来判断就有些不方便书写了，这里逻辑上我想了很久也不能达到完全完美

**Comment by tossp** [comment]
刚测试了一下，节点名为空，提交以后会自动补充节点名为`节点XX`的东西

又导出`ss_conf_backup.txt`来看了一下，还是有`ssconf_basic_use_lb_=1`这个东西

我现在一共是65个节点

当时操作的时候，是已经配置好均衡负载，也在运行中，然后服务商通知，某个节点准备3天后下线，然后新增了2个节点

我就直接在节点编辑里面删除了要下线的节点，然后添加了两个节点，没编辑均衡负载页。直接提交，然后就报错，，，然后就一直这样了，，，

嗯，能想到的大概就这些

**Comment by sadoneli** [comment]
暂时没有找到原因
就用`if [ ! -z "$nick_name" ];then`曲线救国吧先
