### ISSUE TITLE
Dropbear ssh远程端口转发容易断开。

### ISSUE THREAD

**Issue by zechen11** [koolshare/koolshare.github.io#215]
Dropbear ssh远程端口转发到我的vps上，然后ssh特别容易断开，只要输出多一点的命令，就会断开ssh，ls -al / 都断开...
不知道是不是什么地方没有设置好，求教，谢谢！

路由器端执行端口转发命令：
ssh -Nfg -W 1024k  -K 1 -R 21212:localhost:22 VPS_IP
通过公网IP登录到路由器：
ssh -p 21212 VPS_IP
执行以下命令后卡死：
ls -al / 
路由器端报错：
ssh: Connection to zeta@106.187.56.85:22 exited: Keepalive timeout

**Comment by jannson** [comment]
用这种长连接，如果是国为 vps 可能很容易断开。 vps 是国内还是国外？
