### ISSUE TITLE
希望支持SS Scheme。

### ISSUE THREAD

**Issue by wdhwg001** [koolshare/koolshare.github.io#216]
SS Scheme已经成为一个事实标准了，包含以下两种格式：
未加密的 `ss://aes-256-cfb-auth:PassW0rd@sh.ss.com:8235`
Base64简单加密的 `ss://YWVzLTI1Ni1jZmItYXV0aDpQYXNzVzByZEBzaC5zcy5jb206ODIzNQ==`

以及SSR Scheme `ss://http_simple:auth_sha1_v2:aes-256-cfb:PassW0rd@sh.ss.com:8235`

希望能支持。

**Comment by sadoneli** [comment]
这个是应该可以的，但是我还没想到怎么在merlin上的界面逻辑上去做这个

**Comment by wdhwg001** [comment]
在“添加节点”旁边添加一个“导入URL”的按钮如何？
弹出的界面每行有两个输入栏，包括“节点名称”和“URL”两项内容，行的数量可增减。

**Comment by jannson** [comment]
我觉得这个想法非常好。在添加节点的地方添加就可以了。在 js 里面自动解析 schema

**Comment by sadoneli** [comment]
还是暂时不打算支持它了，目前ss插件已经很臃肿了
