### ISSUE TITLE
希望能支持QR Code扫描。

### ISSUE THREAD

**Issue by wdhwg001** [koolshare/koolshare.github.io#217]
二维码在SS应用中较为普遍，可以尝试集成一下。

纯JS的实现（有少量无法识别，尤其是SSR）： https://github.com/LazarSoft/jsqrcode

上传并调用编译好的QR Code Reader，如：https://github.com/glassechidna/zxing-cpp

可以考虑尝试一下。

**Comment by sadoneli** [comment]
未来可能做和ss-panel等面板做接口再考虑这个，目前就路由器上的功能来说还是以完善功能优先
