### ISSUE TITLE
SS 3.0.5 之后版本gfwlist+dnscrypt_proxy 不工作

### ISSUE THREAD

**Issue by sincerywaing** [koolshare/koolshare.github.io#219]
反复测试终于抓住规律：
大陆白名单+ dnscrypt_proxy：工作
gfwlist+ dnscrypt_proxy:不工作
gfwlist+dns2socks:工作

S大能否测试一下看看。

3.0.4及以前版本均工作。

**Comment by sadoneli** [comment]
多谢反馈，已经修复https://github.com/koolshare/koolshare.github.io/commit/3c22d4056cb6935688797e070e0cfe13e7596463

此修复将会包含在下个版本更新中，如果需要现在使用，可以运行build.sh后获得最新离线安装包，上传至路由器手动安装
