### ISSUE TITLE
希望支持SSR的UDP over TCP功能。

### ISSUE THREAD

**Issue by wdhwg001** [koolshare/koolshare.github.io#220]
受网络限制，有许多地区是无法正常使用UDP协议的，因此SSR提供的UDP over TCP功能较为实用。

**Comment by sadoneli** [comment]
你好，ssr-libev本身是不支持udp over tcp的

2016-11-09 17:29 GMT+08:00 wdhwg001 <notifications@github.com>:

**Comment by wdhwg001** [comment]
看了一下，确实是不支持的，上游问题也就没办法了。
