### ISSUE TITLE
希望Pdnsd的TCP查询支持多个DNS。

### ISSUE THREAD

**Issue by wdhwg001** [koolshare/koolshare.github.io#221]
目前国内的无污染DNS服务均不够稳定，因此只填写一个DNS地址可能会出现故障，同时也因为部分新的DNS服务查询冷门域名需要的时间较长，填写多个DNS地址可以较好的缓解这个问题。

**Comment by sadoneli** [comment]
pdnsd目前在merlin上还是不够稳定，它的很久前就停止更新了，我暂时不会改动这个功能
