### ISSUE TITLE
黑白名单的IP/CIDR黑名单 base64 显示的时候起码decode下吧

### ISSUE THREAD

**Issue by fengqi** [koolshare/koolshare.github.io#222]
不然别人还怎么编辑,
还有域名黑名单, 为啥总是给搞成逗号链接的, 挤一起...每次还要自己改成一行一个...

**Comment by sadoneli** [comment]
1 是decode了的，如果显示base64说明有问题，请重新输入正常文本后提交
2 现在已经全部是base64，不再用逗号形式了
