### ISSUE TITLE
长时间启用kcptun时会Problem detected，且无法翻墙

### ISSUE THREAD

**Issue by choicky** [koolshare/koolshare.github.io#223]
通常，连续看Youtube超过20分钟后，就会突然无法翻墙，到路由器里面看就发现国外连接Problem detected

如在shadowsocks界面点击提交，往往又正常了。所以，感觉之前是ss进程或者kcptun进程异常退出了。也许连续观看Youtube 20分钟左右就导致了进程退出。

我昨晚增加了虚拟内存，今晚依然是Problem detected。

**Comment by sadoneli** [comment]
各地运营商对udp发包的限制可能不一样，有些能很快恢复，有些可能需要很久，你可能需要调教kcptun参数来达到稳定
