### ISSUE TITLE
感觉FEC参数与"Problem Detect"有关

### ISSUE THREAD

**Issue by choicky** [koolshare/koolshare.github.io#224]
关闭FEC（即，服务器与客户端都加上 -datashard 0 -parityshard 0）之后，"Problem Detect"出现的概率大幅降低。

之前，FEC采用默认值（ -datashard 10 -parityshard 3）或者自定义的（ -datashard 30 -parityshard 15），都是几十分钟就出现 "Problem Detect"

**Comment by sadoneli** [comment]
这个应该是属于kcptun本身的问题，加上各地运营商对udp的友好程度不一样的
需要自己调教参数实属正常
