### ISSUE TITLE
升级3.1.0报错

### ISSUE THREAD

**Issue by mahaoying** [koolshare/koolshare.github.io#225]
诡异的日志，无法理解为啥fork，是因为github被B了？
Sun Nov 20 23:59:14 GMT 2016: 更新包md5校验一致！ 开始安装！...
Sun Nov 20 23:59:14 GMT 2016: 开始解压压缩包...
/koolshare/ss/ssconfig.sh: line 325: can't fork
tar: write: Broken pipe

**Comment by sadoneli** [comment]
请更新到最新版本，如果无法更新，可以尝试卸载ss后重装或者是格式化jffs分区重装
