### ISSUE TITLE
ss+kcp翻墙失败

### ISSUE THREAD

**Issue by keakon** [koolshare/koolshare.github.io#226]
之前一直是好的，从今天开始突然失效了。

shadowsocks 是 3.1.0 版，不启用 KCP 可翻墙，启用后显示 Problem detected，服务器端完全没有显示任何 stream opened 信息。通过 kcptun 插件直接连接另一台服务器也挂了（昨天升级过这个插件）。

在 mac 上用 ShadowsocksX-NG + kcptun 客户端是好的，说明线路没问题。

**Comment by dogbutcat** [comment]
重新安装看看？我3.1.2是正常的，实在不行就格式化jeff重新装应该就可以了

**Comment by sadoneli** [comment]
确实，情更新到最新版本尝试，另外udp和各地运营商也有关系，情检查网络情况

**Comment by keakon** [comment]
3.1.2 还是不行，但是 3.1.3 好了。
