### ISSUE TITLE
软件中心会出现部分插件无法卸载的情况

### ISSUE THREAD

**Issue by yaojingwu1992** [koolshare/koolshare.github.io#227]
最近把R7000从6.6.1升级到7.1，升级之后格式化了jffs分区，也恢复出厂设置了，在软件中心下载了一个花生壳内网版之后发现它没办法卸载了，点了卸载之后提示是否卸载，确定了没反应，刷新之后还在，其他插件正常卸载安装都没问题。

**Comment by sadoneli** [comment]
没法卸载问题多半出现在状态值上
进入ssh或者telent，输入`dbus set softcenter_installing_status=1`应该能解决
