### ISSUE TITLE
白名单有问题

### ISSUE THREAD

**Issue by 404neko** [koolshare/koolshare.github.io#229]
域名被填入了白名单会解析失败.

C:\Users\Alex>nslookup  www.pixiv.net
服务器:  public1.alidns.com
Address:  223.5.5.5

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** 请求 public1.alidns.com 超时

版本3.10

**Comment by sadoneli** [comment]
请更新到最新版本尝试
