### ISSUE TITLE
开启KCP，上传速度超过带宽最大值

### ISSUE THREAD

**Issue by yuanjun221** [koolshare/koolshare.github.io#231]
开启了SSR及KCP，当苹果设备在进行iCloud备份时，可以看到路由器的上传速率超过最大带宽数倍，并且网络拥堵，SS国外显示PD。备份结束后即恢复正常。以上情况是在R6300V2 X7.2 SS 3.1.0下出现的，其他设备和版本未测试。

**Comment by sadoneli** [comment]
udp流量过多可能会被运营商掐断一下，目前来说很多使用者观察结果都是这样的
