### ISSUE TITLE
如何开发插件

### ISSUE THREAD

**Issue by ZhaoXiangXML** [koolshare/koolshare.github.io#234]
我想用python写一个爬网的插件，并部署到路由器上，大概需要python的运行、安装一些依赖包；访问网络和USB存储；定时运行。

我在论坛也找过了，没有找到这方面的帖子，请问哪里有相关的教程吗？或者有没有可以参考的项目？

谢谢

**Comment by jannson** [comment]
给你思路，你试试：
首先通过 entware 可以安装 python 到 USB 上。
通过 python 可以实现爬虫
本身 python 就在 USB 上，你可以爬文件到 USB 的其它目录。与 linux 开发区别不大。
