### ISSUE TITLE
default.secureserver.net 申请解封

### ISSUE THREAD

**Issue by CarlCCF** [koolshare/koolshare.github.io#236]
default.secureserver.net 可以直连,已经使用超过一年了，建议从GFWlist里面去掉。

**Comment by sadoneli** [comment]
你好，经过本次更新，现在merlin固件的gfwlist已经和官方gfwlist高度一致了（除了少数路由器用于检测ss工作状态的规则外）
https://github.com/koolshare/koolshare.github.io/commit/32161b4c5ff6ad55ec057a5ce1f96b00bb923582#diff-79b75ec1451cc46e5c58658c6ef03e40L2065
