### ISSUE TITLE
白名单依然有Bug

### ISSUE THREAD

**Issue by 404neko** [koolshare/koolshare.github.io#237]
表现为添加了白名单的域名在电脑上无法解析 模式为gfwlist
3.1.0 的时候我提交过一次issues 但是被建议更新版本 现在已经3.1.2 了

**Comment by sadoneli** [comment]
请问你填写的域名是什么？
必须是gfwlist内的域名才有意义

**Comment by 404neko** [comment]
pixiv.net
确实是在gfwlist 内的

**Comment by sadoneli** [comment]
你希望这个网站不能被访问把？

**Comment by 404neko** [comment]
问题不在网站上 问题在于你们的白名单工作有问题 你把任何的域名写在白名单里都是无法访问的

**Comment by sadoneli** [comment]
逻辑上gfwlist内的网址都是被墙的，默认就不能访问
如果走了ss是能访问的，但是如果你添加了某个gfwlist名单内的域名，就是这个域名不走ss，不走当然访问不了啊

**Comment by 404neko** [comment]
你去写个baidu.com 试试
