### ISSUE TITLE
gfwlist模式下，不在gfwlist中的域名还是会走ss

### ISSUE THREAD

**Issue by hyhero127** [koolshare/koolshare.github.io#240]
开启gfwlist模式后，访问一个本地的腾讯云服务器（www.quchu.co)，这个服务器肯定不会在gfwlist中，但是还是走ss。估计是某个bug导致。。。

**Comment by sadoneli** [comment]
.co后缀是哥伦比亚国家域名，koolshare的gfwlist中收了有这部分
