### ISSUE TITLE
shadowsocks + kcp运行30min左右，视频会断

### ISSUE THREAD

**Issue by vonhezhou** [koolshare/koolshare.github.io#241]
1.在路由器上启用shadowsocks + kcp
2.开iqiyi看视频
3.大约30min左右，视频必然断开，说无法连接，必须reload页面才行，直接等播放器里的刷新无效。
可能不是30min，我用的是100m光纤入户，可能有一段时间播的是缓存的内容。

如果关闭ss是没有这个问题的。

**Comment by sadoneli** [comment]
请检查下是否因kcp流量过多而运营商重置你的连接导致国内链接受影响

**Comment by vonhezhou** [comment]
gfw模式。
没有开国外的视频站点。
不会是kcp导致的吧
