### ISSUE TITLE
Samba共享无法访问

### ISSUE THREAD

**Issue by ZhaoXiangXML** [koolshare/koolshare.github.io#242]
路由器是R6300v2，固件版本是380.63_X7.2

之前一直用得挺好的，突然就连不上了，各种客户端都试过。

在后台的管理页面能看到盘和文件夹，迅雷远程下载也还好用，但是共享打不开。

尝试过重启，关掉共享再打开，Format JFFS partition at next boot，均没有效果。还有什么别的可以尝试的吗？

Mac上的提示为：

There are no shares available or you are not allowed to access them on the server. Please contact your system administrator to resolve the problem.

这是最近一次重启后的log

https://github.com/RMerl/asuswrt-merlin/files/666356/syslog.txt

**Comment by sadoneli** [comment]
日志并没什么问题，请检查下：
1. 是否磁盘问题
2. 是否休眠问题

**Comment by ZhaoXiangXML** [comment]
恢复出厂设置之后重新配了就好了
