### ISSUE TITLE
3.1.3版本SS：在最新的gfwlist中碰到的一个奇怪问题

### ISSUE THREAD

**Issue by walnutist** [koolshare/koolshare.github.io#243]
我前几天更新了SS 3.1.3版本，更新之后家里所有的苹果设备都无法正常访问app store了
具体体现为：
1、在Mac上，打开app store所有按钮都是灰色的不可点击。等待很久之后弹出一个莫名其妙的Failure消息
2、在Mac上，iTunes账号无法正常登陆，出错的信息是“网络连接被拒绝”
2、在iphone上app store打开后显示"无法连接到app store"

后来终于发现是gfwlist.conf中有一笔记录如下
server=/.phobos.apple.com/127.0.0.1#7913
ipset=/.phobos.apple.com/gfwlist

我在管理界面的黑白名单中将phobos.apple.com强制放入白名单
终于解决了这个问题 #

**Comment by sadoneli** [comment]
如果你使用了最新的ss规则，还含有这两条，那么这个应该就是官方gfwlist也包含了的
你可以试试到这里反馈一下：https://github.com/gfwlist/gfwlist
