### ISSUE TITLE
3.1.4的$$插件只有gfwlist模式可以正常工作

### ISSUE THREAD

**Issue by JeremyLuan** [koolshare/koolshare.github.io#249]
Asus AC68U X7.2固件，更新3.1.4插件后，只有gfwlist模式能够正常双working上外网，大陆白名单、游戏模式均显示国外网络Problem Detected，更换DNS不起作用，已确定$$服务器支持UDP

**Comment by sadoneli** [comment]
你好，尝试了多种方式，并不能重现你的问题，请尝试：
1. 卸载插件，重装
2. 格式化jffs分区后重装
