### ISSUE TITLE
没有Auth_Sha1协议无法使用SSR

### ISSUE THREAD

**Issue by mmx139** [koolshare/koolshare.github.io#252]
请问3.1.4取消了Auth_sha1协议，我选择了auth_sha1_v2或v4，都无法正常使用SSR。现在只能使用SS。服务供应商提供的协议是auth_sha1，在3.1.3版本可以正常使用。想了解为什么该协议被新版本取消，有没有什么其他的协议兼容呢？

**Comment by sadoneli** [comment]
破娃不建议使用，所以根据建议取消了，请联系服务商更改协议
