### ISSUE TITLE
base64_decode错误

### ISSUE THREAD

**Issue by kakuchichi** [koolshare/koolshare.github.io#254]
* version 3.1.5，开启后有报错
`
2017年01月10日 16:58:37: 创建dnsmasq.postconf软连接到/jffs/scripts/文件夹.
/koolshare/bin/base64_decode: line 1: syntax error: unexpected word (expecting ")")
/koolshare/bin/base64_decode: line 1: syntax error: unexpected word (expecting ")")
echo: write error: Broken pipe
`

* 查看/koolshare/ss/redchn/ss.json会发现密码为空

**Comment by sadoneli** [comment]
清空skipd数据库试试，会丢失所有ss，软件中心数据
killall skipd
rm -rf /jffs/db
service start_skipd
