### ISSUE TITLE
混淆协议能否加回对 auth_sha1 的支持

### ISSUE THREAD

**Issue by iamsweet** [koolshare/koolshare.github.io#256]
以前的版本是支持 auth_sha1 的混淆协议的，升级到最新版之后下拉框里面只有 auth_sha1_v2 和 auth_sha1_v4 了，我的节点都是 auth_sha1 的，所以没法使用了，或者把这个下拉框改成可以手写的模式。

**Comment by sadoneli** [comment]
已经添加回去了
