### ISSUE TITLE
游戏模式V2有时候会无法解析IP？

### ISSUE THREAD

**Issue by lingaoyi** [koolshare/koolshare.github.io#257]
SS服务器地址解析默认是119.29.29.29，换了114.114.114.114，还是有概率出现无法解析，无法解析就马上PD了，正在联机的时候就断线了。

**Comment by sadoneli** [comment]
建议在完全关闭ss的状态下来提交游戏模式，如果在本来pd的状态下提交，是有很大几率不成功的
