### ISSUE TITLE
希望支持电信IPTV模块及采用hash查找的dnsmasq

### ISSUE THREAD

**Issue by apango** [koolshare/koolshare.github.io#260]
1. 部分地区通过修改dhcp option 125可以支持IPTV桥接，希望能够添加应用支持该功能。手动修改较为麻烦，而且在是否使用$$两种不同的情况下需要分别处理。希望软件库中能添加app支持。

2. 另外，dnsmasq有一个采用hash表代替线性查找的版本，在cdn巨大(3w+)的list上实测速度比gfwlist更快。希望能采用这个改进的dnsmasq，而不是将cdn list取消。

**Comment by sadoneli** [comment]
1 独立版本的dnsmasq未来视情况而定，因为现在dnsmasq和ss绑得比较死，况且dnsmasq的设置对fq也直观重要，暂时不打算开放出来单独设置
2 改进版本的确实不错，但是存在严重的bug，时间长了后会有无法解析的问题，所以也不打算上这个
