### ISSUE TITLE
R6300V2更新时经常提示类似/koolshare/ss/ssconfig.sh: line 316: can't fork错误

### ISSUE THREAD

**Issue by zxq1002** [koolshare/koolshare.github.io#261]
一般都是先提示空间不足，但是查看各个分区都有空间，不知道是指哪个分区空间不足呢？难道是下载到根分区，而不是/tmp？
Filesystem                Size      Used Available Use% Mounted on
/dev/root                25.8M     25.8M         0 100% /
devtmpfs                124.8M         0    124.8M   0% /dev
tmpfs                   124.9M     19.2M    105.6M  15% /tmp
/dev/mtdblock5           88.8M     13.9M     74.9M  16% /jffs

**Comment by zxq1002** [comment]
2017年01月17日 23:18:11: 更新过程中请不要做奇怪的事，不然可能导致问题！
2017年01月17日 23:18:11: 开启SS检查更新：正在检测主服务器在线版本号...
2017年01月17日 23:18:14: 检测到主服务器在线版本号：3.1.8
2017年01月17日 23:18:14: 主服务器在线版本号：3.1.8 和本地版本号：3.1.5 不同！
2017年01月17日 23:18:14: 开启下载进程，从主服务器上下载更新包...
--2017-01-17 23:18:14--  https://raw.githubusercontent.com/koolshare/koolshare.github.io/acelan_softcenter_ui/shadowsocks/shadowsocks.tar.gz
Resolving raw.githubusercontent.com... 151.101.100.133
Connecting to raw.githubusercontent.com|151.101.100.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7218482 (6.9M) [application/octet-stream]
Saving to: 'shadowsocks.tar.gz'

     0K .......... .......... .......... .......... ..........  0%  339K 21s
    50K .......... .......... .......... .......... ..........  1%  425K 18s
   100K .......... .......... .......... .......... ..........  2%  433K 17s
   150K .......... .......... .......... .......... ..........  2%  488K 17s
   200K .......... .......... .......... .......... ..........  3%  674K 15s
   250K .......... .......... .......... .......... ..........  4% 1.06M 14s
   300K .......... .......... .......... .......... ..........  4%  755K 13s
   350K .......... .......... .......... .......... ..........  5% 1.06M 12s
   400K .......... .......... .......... .......... ..........  6% 1.17M 11s
   450K .......... .......... .......... .......... ..........  7%  813K 11s
   500K .......... .......... .......... .......... ..........  7% 1.09M 10s
   550K .......... .......... .......... .......... ..........  8% 1.32M 10s
   600K .......... .......... .......... .......... ..........  9% 1.33M 9s
   650K .......... .......... .......... .......... ..........  9% 1.34M 9s
   700K .......... .......... .......... .......... .......... 10% 1.47M 8s
   750K .......... .......... .......... .......... .......... 11% 3.07M 8s
   800K .......... .......... .......... .......... .......... 12% 1.46M 8s
   850K .......... .......... .......... .......... .......... 12% 1.50M 7s
   900K .......... .......... .......... .......... .......... 13% 1.34M 7s
   950K .......... .......... .......... .......... .......... 14% 1.65M 7s
  1000K .......... .......... .......... .......... .......... 14% 3.22M 7s
  1050K .......... .......... .......... .......... .......... 15% 1.72M 6s
  1100K .......... .......... .......... .......... .......... 16% 3.72M 6s
  1150K .......... .......... .......... .......... .......... 17% 1.59M 6s
  1200K .......... .......... .......... .......... .......... 17% 1.83M 6s
  1250K .......... .......... .......... .......... .......... 18% 2.80M 6s
  1300K .......... .......... .......... .......... .......... 19% 2.01M 6s
  1350K .......... .......... .......... .......... .......... 19% 3.40M 5s
  1400K .......... .......... .......... .......... .......... 20% 2.10M 5s
  1450K .......... .......... .......... .......... .......... 21% 3.51M 5s
  1500K .......... .......... .......... .......... .......... 21% 1.95M 5s
  1550K .......... .......... .......... .......... .......... 22% 4.37M 5s
  1600K .......... .......... .......... .......... .......... 23% 1.89M 5s
  1650K .......... .......... .......... .......... .......... 24% 5.38M 5s
  1700K .......... .......... .......... .......... .......... 24% 1.58M 4s
  1750K .......... .......... .......... .......... .......... 25% 7.12M 4s
  1800K .......... .......... .......... .......... .......... 26% 3.18M 4s
  1850K .......... .......... .......... .......... .......... 26% 3.12M 4s
  1900K .......... .......... .......... .......... .......... 27% 2.27M 4s
  1950K .......... .......... .......... .......... .......... 28% 2.98M 4s
  2000K .......... .......... .......... .......... .......... 29% 8.23M 4s
  2050K .......... .......... .......... .......... .......... 29% 3.52M 4s
  2100K .......... .......... .......... .......... .......... 30% 2.52M 4s
  2150K .......... .......... .......... .......... .......... 31% 4.18M 4s
  2200K .......... .......... .......... .......... .......... 31% 4.08M 3s
  2250K .......... .......... .......... .......... .......... 32% 3.36M 3s
  2300K .......... .......... .......... .......... .......... 33% 3.53M 3s
  2350K .......... .......... .......... .......... .......... 34% 3.25M 3s
  2400K .......... .......... .......... .......... .......... 34% 6.38M 3s
  2450K .......... .......... .......... .......... .......... 35% 5.93M 3s
  2500K .......... .......... .......... .......... .......... 36% 2.59M 3s
  2550K .......... .......... .......... .......... .......... 36% 3.84M 3s
  2600K .......... .......... .......... .......... .......... 37% 7.25M 3s
  2650K .......... .......... .......... .......... .......... 38% 3.93M 3s
  2700K .......... .......... .......... .......... .......... 39% 4.29M 3s
  2750K .......... .......... .......... .......... .......... 39% 4.80M 3s
  2800K .......... .......... .......... .......... .......... 40% 6.96M 3s
  2850K .......... .......... .......... .......... .......... 41% 3.41M 3s
  2900K .......... .......... .......... .......... .......... 41% 3.21M 2s
  2950K .......... .......... .......... .......... .......... 42% 6.39M 2s
  3000K .......... .......... .......... .......... .......... 43% 4.12M 2s
  3050K .......... .......... .......... .......... .......... 43% 6.27M 2s
  3100K .......... .......... .......... .......... .......... 44% 4.55M 2s
  3150K .......... .......... .......... .......... .......... 45% 5.08M 2s
  3200K .......... .......... .......... .......... .......... 46% 10.0M 2s
  3250K .......... .......... .......... .......... .......... 46% 3.85M 2s
  3300K .......... .......... .......... .......... .......... 47% 2.39M 2s
  3350K .......... .......... .......... .......... .......... 48% 3.54M 2s
  3400K .......... .......... .......... .......... .......... 48% 3.11M 2s
  3450K .......... .......... .......... .......... .......... 49% 2.24M 2s
  3500K .......... .......... .......... .......... .......... 50% 6.20M 2s
  3550K .......... .......... .......... .......... .......... 51% 3.09M 2s
  3600K .......... .......... .......... .......... .......... 51% 2.97M 2s
  3650K .......... .......... .......... .......... .......... 52% 8.52M 2s
  3700K .......... .......... .......... .......... .......... 53% 5.20M 2s
  3750K .......... .......... .......... .......... .......... 53% 5.23M 2s
  3800K .......... .......... .......... .......... .......... 54% 3.81M 2s
  3850K .......... .......... .......... .......... .......... 55% 9.56M 2s
  3900K .......... .......... .......... .......... .......... 56% 3.79M 2s
  3950K .......... .......... .......... .......... .......... 56% 4.68M 2s
  4000K .......... .......... .......... .......... .......... 57% 4.13M 2s
  4050K .......... .......... .......... .......... .......... 58% 9.71M 1s
  4100K .......... .......... .......... .......... .......... 58% 2.39M 1s
  4150K .......... .......... .......... .......... .......... 59% 4.35M 1s
  4200K .......... .......... .......... .......... .......... 60% 9.54M 1s
  4250K .......... .......... .......... .......... .......... 60% 3.21M 1s
  4300K .......... .......... .......... .......... .......... 61% 3.87M 1s
  4350K .......... .......... .......... .......... .......... 62% 6.34M 1s
  4400K .......... .......... .......... .......... .......... 63% 2.94M 1s
  4450K .......... .......... .......... .......... .......... 63% 6.25M 1s
  4500K .......... .......... .......... .......... .......... 64% 3.71M 1s
  4550K .......... .......... .......... .......... .......... 65% 7.28M 1s
  4600K .......... .......... .......... .......... .......... 65% 3.59M 1s
  4650K .......... .......... .......... .......... .......... 66% 8.45M 1s
  4700K .......... .......... .......... .......... .......... 67% 4.17M 1s
  4750K .......... .......... .......... .......... .......... 68% 6.77M 1s
  4800K .......... .......... .......... .......... .......... 68% 5.48M 1s
  4850K .......... .......... .......... .......... .......... 69% 8.50M 1s
  4900K .......... .......... .......... .......... .......... 70% 6.10M 1s
  4950K .......... .......... .......... .......... .......... 70% 5.65M 1s
  5000K .......... .......... .......... .......... .......... 71% 7.36M 1s
  5050K .......... .......... .......... .......... .......... 72% 4.80M 1s
  5100K .......... .......... .......... .......... .......... 73% 9.03M 1s
  5150K .......... .......... .......... .......... .......... 73% 5.89M 1s
  5200K .......... .......... .......... .......... .......... 74% 5.72M 1s
  5250K .......... .......... .......... .......... .......... 75% 4.50M 1s
  5300K .......... .......... .......... .......... .......... 75% 4.67M 1s
  5350K .......... .......... .......... .......... .......... 76% 6.09M 1s
  5400K .......... .......... .......... .......... .......... 77% 6.70M 1s
  5450K .......... .......... .......... .......... .......... 78% 4.12M 1s
  5500K .......... .......... .......... .......... .......... 78% 7.92M 1s
  5550K .......... .......... .......... .......... .......... 79% 5.32M 1s
  5600K .......... .......... .......... .......... .......... 80% 5.88M 1s
  5650K .......... .......... .......... .......... .......... 80% 6.44M 1s
  5700K .......... .......... .......... .......... .......... 81% 6.43M 1s
  5750K .......... .......... .......... .......... .......... 82% 7.78M 1s
  5800K .......... .......... .......... .......... .......... 82% 4.33M 0s
  5850K .......... .......... .......... .......... .......... 83% 4.76M 0s
  5900K .......... .......... .......... .......... .......... 84% 6.11M 0s
  5950K .......... .......... .......... .......... .......... 85% 8.56M 0s
  6000K .......... .......... .......... .......... .......... 85% 5.05M 0s
  6050K .......... .......... .......... .......... .......... 86% 6.08M 0s
  6100K .......... .......... .......... .......... .......... 87% 4.11M 0s
  6150K .......... .......... .......... .......... .......... 87% 9.03M 0s
  6200K .......... .......... .......... .......... .......... 88% 5.03M 0s
  6250K .......... .......... .......... .......... .......... 89% 5.98M 0s
  6300K .......... .......... .......... .......... .......... 90% 6.36M 0s
  6350K .......... .......... .......... .......... .......... 90% 8.96M 0s
  6400K .......... .......... .......... .......... .......... 91% 8.81M 0s
  6450K .......... .......... .......... .......... .......... 92% 8.59M 0s
  6500K .......... .......... .......... .......... .......... 92% 7.33M 0s
  6550K .......... .......... .......... .......... .......... 93% 8.71M 0s
  6600K .......... .......... .......... .......... .......... 94% 10.3M 0s
  6650K .......... .......... .......... .......... .......... 95% 9.00M 0s
  6700K .......... .......... .......... .......... .......... 95% 8.32M 0s
  6750K .......... .......... .......... .......... .......... 96% 9.53M 0s
  6800K .......... .......... .......... .......... .......... 97% 10.4M 0s
  6850K .......... .......... .......... .......... .......... 97% 11.9M 0s
  6900K .......... .......... .......... .......... .......... 98% 8.75M 0s
  6950K .......... .......... .......... .......... .......... 99% 12.3M 0s
  7000K .......... .......... .......... .......... ......... 100% 15.0M=2.5s

2017-01-17 23:18:17 (2.74 MB/s) - 'shadowsocks.tar.gz' saved [7218482/7218482]

2017年01月17日 23:18:18: 更新包md5校验一致！ 开始安装！...
2017年01月17日 23:18:18: 开始解压压缩包...
/koolshare/ss/ssconfig.sh: line 316: can't fork
tar: write: Broken pipe

**Comment by zxq1002** [comment]
2017年01月17日 23:21:22: 更新过程中请不要做奇怪的事，不然可能导致问题！
2017年01月17日 23:21:22: 开启SS检查更新：正在检测主服务器在线版本号...
2017年01月17日 23:21:24: 检测到主服务器在线版本号：3.1.8
2017年01月17日 23:21:24: 主服务器在线版本号：3.1.8 和本地版本号：3.1.5 不同！
2017年01月17日 23:21:24: 开启下载进程，从主服务器上下载更新包...
--2017-01-17 23:21:24--  https://raw.githubusercontent.com/koolshare/koolshare.github.io/acelan_softcenter_ui/shadowsocks/shadowsocks.tar.gz
Resolving raw.githubusercontent.com... 151.101.100.133
Connecting to raw.githubusercontent.com|151.101.100.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7218482 (6.9M) [application/octet-stream]
Saving to: 'shadowsocks.tar.gz'

     0K .......... .......... .......... .......... ..........  0%  294K 24s
    50K .......... .......... .......... .......... ..........  1%  492K 19s
   100K .......... .......... .......... .......... ..........  2%  685K 16s
   150K .......... .......... .......... .......... ..........  2%  698K 14s
   200K .......... .......... .......... .......... ..........  3%  708K 13s
   250K .......... .......... .......... .......... ..........  4%  727K 12s
   300K .......... .......... .......... .......... ..........  4%  877K 12s
   350K .......... .......... .......... .......... ..........  5% 1.03M 11s
   400K .......... .......... .......... .......... ..........  6%  851K 11s
   450K .......... .......... .......... .......... ..........  7% 1.21M 10s
   500K .......... .......... .......... .......... ..........  7% 1.40M 9s
   550K .......... .......... .......... .......... ..........  8% 1.44M 9s
   600K .......... .......... .......... .......... ..........  9% 1.29M 9s
   650K .......... .......... .......... .......... ..........  9% 1.60M 8s
   700K .......... .......... .......... .......... .......... 10% 1.46M 8s
   750K .......... .......... .......... .......... .......... 11% 1.40M 8s
   800K .......... .......... .......... .......... .......... 12% 1.53M 7s
   850K .......... .......... .......... .......... .......... 12% 1.97M 7s
   900K .......... .......... .......... .......... .......... 13% 2.72M 7s
   950K .......... .......... .......... .......... .......... 14% 1.68M 6s
  1000K .......... .......... .......... .......... .......... 14% 1.99M 6s
  1050K .......... .......... .......... .......... .......... 15% 2.79M 6s
  1100K .......... .......... .......... .......... .......... 16% 1.92M 6s
  1150K .......... .......... .......... .......... .......... 17% 1.82M 6s
  1200K .......... .......... .......... .......... .......... 17% 3.39M 5s
  1250K .......... .......... .......... .......... .......... 18% 1.90M 5s
  1300K .......... .......... .......... .......... .......... 19% 3.86M 5s
  1350K .......... .......... .......... .......... .......... 19% 2.25M 5s
  1400K .......... .......... .......... .......... .......... 20% 3.38M 5s
  1450K .......... .......... .......... .......... .......... 21% 2.06M 5s
  1500K .......... .......... .......... .......... .......... 21% 4.06M 5s
  1550K .......... .......... .......... .......... .......... 22% 2.25M 4s
  1600K .......... .......... .......... .......... .......... 23% 3.35M 4s
  1650K .......... .......... .......... .......... .......... 24% 3.21M 4s
  1700K .......... .......... .......... .......... .......... 24% 3.48M 4s
  1750K .......... .......... .......... .......... .......... 25% 3.35M 4s
  1800K .......... .......... .......... .......... .......... 26% 2.74M 4s
  1850K .......... .......... .......... .......... .......... 26% 5.10M 4s
  1900K .......... .......... .......... .......... .......... 27% 2.82M 4s
  1950K .......... .......... .......... .......... .......... 28% 2.89M 4s
  2000K .......... .......... .......... .......... .......... 29% 4.17M 4s
  2050K .......... .......... .......... .......... .......... 29% 3.93M 3s
  2100K .......... .......... .......... .......... .......... 30% 3.91M 3s
  2150K .......... .......... .......... .......... .......... 31% 3.07M 3s
  2200K .......... .......... .......... .......... .......... 31% 3.85M 3s
  2250K .......... .......... .......... .......... .......... 32% 3.98M 3s
  2300K .......... .......... .......... .......... .......... 33% 5.26M 3s
  2350K .......... .......... .......... .......... .......... 34% 3.19M 3s
  2400K .......... .......... .......... .......... .......... 34% 5.18M 3s
  2450K .......... .......... .......... .......... .......... 35% 10.4M 3s
  2500K .......... .......... .......... .......... .......... 36% 2.47M 3s
  2550K .......... .......... .......... .......... .......... 36% 3.45M 3s
  2600K .......... .......... .......... .......... .......... 37% 3.09M 3s
  2650K .......... .......... .......... .......... .......... 38% 10.2M 3s
  2700K .......... .......... .......... .......... .......... 39% 4.81M 3s
  2750K .......... .......... .......... .......... .......... 39% 5.75M 2s
  2800K .......... .......... .......... .......... .......... 40% 5.15M 2s
  2850K .......... .......... .......... .......... .......... 41% 12.2M 2s
  2900K .......... .......... .......... .......... .......... 41% 2.85M 2s
  2950K .......... .......... .......... .......... .......... 42% 3.29M 2s
  3000K .......... .......... .......... .......... .......... 43% 3.53M 2s
  3050K .......... .......... .......... .......... .......... 43% 2.77M 2s
  3100K .......... .......... .......... .......... .......... 44% 10.1M 2s
  3150K .......... .......... .......... .......... .......... 45% 7.36M 2s
  3200K .......... .......... .......... .......... .......... 46% 10.4M 2s
  3250K .......... .......... .......... .......... .......... 46% 4.13M 2s
  3300K .......... .......... .......... .......... .......... 47% 7.31M 2s
  3350K .......... .......... .......... .......... .......... 48% 1.63M 2s
  3400K .......... .......... .......... .......... .......... 48% 3.30M 2s
  3450K .......... .......... .......... .......... .......... 49% 4.85M 2s
  3500K .......... .......... .......... .......... .......... 50% 5.82M 2s
  3550K .......... .......... .......... .......... .......... 51% 3.89M 2s
  3600K .......... .......... .......... .......... .......... 51% 5.74M 2s
  3650K .......... .......... .......... .......... .......... 52% 3.38M 2s
  3700K .......... .......... .......... .......... .......... 53% 4.22M 2s
  3750K .......... .......... .......... .......... .......... 53% 5.40M 2s
  3800K .......... .......... .......... .......... .......... 54% 3.10M 2s
  3850K .......... .......... .......... .......... .......... 55% 3.42M 2s
  3900K .......... .......... .......... .......... .......... 56% 2.92M 1s
  3950K .......... .......... .......... .......... .......... 56% 4.08M 1s
  4000K .......... .......... .......... .......... .......... 57% 3.45M 1s
  4050K .......... .......... .......... .......... .......... 58% 8.66M 1s
  4100K .......... .......... .......... .......... .......... 58% 3.21M 1s
  4150K .......... .......... .......... .......... .......... 59% 8.48M 1s
  4200K .......... .......... .......... .......... .......... 60% 6.64M 1s
  4250K .......... .......... .......... .......... .......... 60% 10.0M 1s
  4300K .......... .......... .......... .......... .......... 61% 3.60M 1s
  4350K .......... .......... .......... .......... .......... 62% 3.63M 1s
  4400K .......... .......... .......... .......... .......... 63% 7.14M 1s
  4450K .......... .......... .......... .......... .......... 63% 4.25M 1s
  4500K .......... .......... .......... .......... .......... 64% 7.53M 1s
  4550K .......... .......... .......... .......... .......... 65% 7.87M 1s
  4600K .......... .......... .......... .......... .......... 65% 5.48M 1s
  4650K .......... .......... .......... .......... .......... 66% 4.77M 1s
  4700K .......... .......... .......... .......... .......... 67% 9.33M 1s
  4750K .......... .......... .......... .......... .......... 68% 6.32M 1s
  4800K .......... .......... .......... .......... .......... 68% 3.62M 1s
  4850K .......... .......... .......... .......... .......... 69% 5.64M 1s
  4900K .......... .......... .......... .......... .......... 70% 8.68M 1s
  4950K .......... .......... .......... .......... .......... 70% 7.03M 1s
  5000K .......... .......... .......... .......... .......... 71% 3.17M 1s
  5050K .......... .......... .......... .......... .......... 72% 9.50M 1s
  5100K .......... .......... .......... .......... .......... 73% 8.36M 1s
  5150K .......... .......... .......... .......... .......... 73% 5.46M 1s
  5200K .......... .......... .......... .......... .......... 74% 4.35M 1s
  5250K .......... .......... .......... .......... .......... 75% 9.06M 1s
  5300K .......... .......... .......... .......... .......... 75% 7.82M 1s
  5350K .......... .......... .......... .......... .......... 76% 6.90M 1s
  5400K .......... .......... .......... .......... .......... 77% 3.77M 1s
  5450K .......... .......... .......... .......... .......... 78% 9.37M 1s
  5500K .......... .......... .......... .......... .......... 78% 8.74M 1s
  5550K .......... .......... .......... .......... .......... 79% 3.62M 1s
  5600K .......... .......... .......... .......... .......... 80% 3.83M 1s
  5650K .......... .......... .......... .......... .......... 80% 8.61M 1s
  5700K .......... .......... .......... .......... .......... 81% 4.99M 1s
  5750K .......... .......... .......... .......... .......... 82% 6.19M 0s
  5800K .......... .......... .......... .......... .......... 82% 8.23M 0s
  5850K .......... .......... .......... .......... .......... 83% 4.87M 0s
  5900K .......... .......... .......... .......... .......... 84% 8.00M 0s
  5950K .......... .......... .......... .......... .......... 85% 4.50M 0s
  6000K .......... .......... .......... .......... .......... 85% 7.03M 0s
  6050K .......... .......... .......... .......... .......... 86% 8.05M 0s
  6100K .......... .......... .......... .......... .......... 87% 8.21M 0s
  6150K .......... .......... .......... .......... .......... 87% 8.62M 0s
  6200K .......... .......... .......... .......... .......... 88% 9.96M 0s
  6250K .......... .......... .......... .......... .......... 89% 9.07M 0s
  6300K .......... .......... .......... .......... .......... 90% 9.07M 0s
  6350K .......... .......... .......... .......... .......... 90% 7.49M 0s
  6400K .......... .......... .......... .......... .......... 91% 9.36M 0s
  6450K .......... .......... .......... .......... .......... 92% 9.54M 0s
  6500K .......... .......... .......... .......... .......... 92% 10.3M 0s
  6550K .......... .......... .......... .......... .......... 93% 11.1M 0s
  6600K .......... .......... .......... .......... .......... 94% 11.9M 0s
  6650K .......... .......... .......... .......... .......... 95% 11.8M 0s
  6700K .......... .......... .......... .......... .......... 95% 12.4M 0s
  6750K .......... .......... .......... .......... .......... 96% 9.75M 0s
  6800K .......... .......... ...                              96% 14.3M=2.3s


Cannot write to 'shadowsocks.tar.gz' (No space left on device).
/koolshare/ss/ssconfig.sh: line 316: can't fork
2017年01月17日 23:21:27: 更新包md5校验不一致！估计是下载的时候出了什么状况，请等待一会儿再试...
2017年01月17日 23:21:28: 更换备用更新服务器1，请稍后...
2017年01月17日 23:21:30: 开启SS检查更新：正在检测备用服务器在线版本号...
2017年01月17日 23:21:32: 检测到备用服务器在线版本号：3.1.8
2017年01月17日 23:21:32: 备用服务器在线版本号：3.1.8 和本地版本号：3.1.5 不同！
2017年01月17日 23:21:33: 开启下载进程，从备用服务器上下载更新包...
--2017-01-17 23:21:33--  http://koolshare.ngrok.wang:5000/shadowsocks/shadowsocks.tar.gz
Resolving koolshare.ngrok.wang... 221.229.173.116
Connecting to koolshare.ngrok.wang|221.229.173.116|:5000... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7218482 (6.9M) [application/octet-stream]
Saving to: 'shadowsocks.tar.gz'

     0K .......... .......... .......... .......... ..........  0% 1.72M 4s
    50K .......... .......... .......... .......... ..........  1% 2.29M 3s
   100K .......... .......... .......... .......... ..........  2% 3.04M 3s
   150K .......... .......... .......... .......... ..........  2% 1.58M 3s
   200K .......... .......... .......... .......... ..........  3% 3.79M 3s
   250K .......... .......... .......... .......... ..........  4% 1.35M 3s
   300K .......... .......... .......... .......... ..........  4% 8.96M 3s
   350K .......... .......... .......... .......... ..........  5% 8.86M 3s
   400K .......... .......... .......... .......... ..........  6% 1.18M 3s
   450K .......... .......... .......... .......... ..........  7% 11.2M 3s
   500K .......... .......... .......... .......... ..........  7% 1011K 3s
   550K .......... .......... .......... .......... ..........  8% 10.4M 3s
   600K .......... .......... .......... .......... ..........  9% 1.14M 3s
   650K .......... .......... .......... .......... ..........  9% 7.97M 3s
   700K .......... .......... .......... .......... .......... 10% 21.3M 3s
   750K .......... .......... .......... .......... .......... 11%  989K 3s
   800K .......... .......... .......... .......... .......... 12% 10.1M 3s
   850K .......... .......... .......... .......... .......... 12% 1.17M 3s
   900K .......... .......... .......... .......... .......... 13% 11.3M 3s
   950K .......... .......... .......... .......... .......... 14%  969K 3s
  1000K .......... .......... .......... .......... .......... 14% 11.7M 3s
  1050K .......... .......... .......... .......... .......... 15% 1.15M 3s
  1100K .......... .......... .......... .......... .......... 16% 9.48M 3s
  1150K .......... .......... .......... .......... .......... 17%  997K 3s
  1200K .......... .......... .......... .......... .......... 17% 9.50M 3s
  1250K .......... .......... .......... .......... .......... 18% 10.6M 3s
  1300K .......... .......... .......... .......... .......... 19% 1.18M 3s
  1350K .......... .......... .......... .......... .......... 19% 12.4M 2s
  1400K .......... .......... .......... .......... .......... 20%  974K 3s
  1450K .......... .......... .......... .......... .......... 21% 9.87M 2s
  1500K .......... .......... .......... .......... .......... 21% 1.18M 3s
  1550K .......... .......... .......... .......... .......... 22% 10.5M 2s
  1600K .......... .......... .......... .......... .......... 23%  986K 3s
  1650K .......... .......... .......... .......... .......... 24% 10.8M 2s
  1700K .......... .......... .......... .......... .......... 24% 10.4M 2s
  1750K .......... .......... .......... .......... .......... 25% 1.19M 2s
  1800K .......... .......... .......... .......... .......... 26% 11.7M 2s
  1850K .......... .......... .......... .......... .......... 26%  967K 2s
  1900K .......... .......... .......... .......... .......... 27% 11.7M 2s
  1950K .......... .......... .......... .......... .......... 28% 1.16M 2s
  2000K .......... .......... .......... .......... .......... 29% 10.5M 2s
  2050K .......... .......... .......... .......... .......... 29% 10.4M 2s
  2100K .......... .......... .......... .......... .......... 30% 1018K 2s
  2150K .......... .......... .......... .......... .......... 31% 12.2M 2s
  2200K .......... .......... .......... .......... .......... 31% 1.15M 2s
  2250K .......... .......... .......... .......... .......... 32% 10.0M 2s
  2300K .......... .......... .......... .......... .......... 33% 12.9M 2s
  2350K .......... .......... .......... .......... .......... 34% 1015K 2s
  2400K .......... .......... .......... .......... .......... 34% 11.0M 2s
  2450K .......... .......... .......... .......... .......... 35% 1.18M 2s
  2500K .......... .......... .......... .......... .......... 36% 10.7M 2s
  2550K .......... .......... .......... .......... .......... 36%  997K 2s
  2600K .......... .......... .......... .......... .......... 37% 9.43M 2s
  2650K .......... .......... .......... .......... .......... 38% 11.0M 2s
  2700K .......... .......... .......... .......... .......... 39% 1.22M 2s
  2750K .......... .......... .......... .......... .......... 39% 9.90M 2s
  2800K .......... .......... .......... .......... .......... 40% 1017K 2s
  2850K .......... .......... .......... .......... .......... 41% 10.2M 2s
  2900K .......... .......... .......... .......... .......... 41% 10.8M 2s
  2950K .......... .......... .......... .......... .......... 42% 1.18M 2s
  3000K .......... .......... .......... .......... .......... 43% 9.94M 2s
  3050K .......... .......... .......... .......... .......... 43% 1015K 2s
  3100K .......... .......... .......... .......... .......... 44% 11.7M 2s
  3150K .......... .......... .......... .......... .......... 45% 10.5M 2s
  3200K .......... .......... .......... .......... .......... 46% 1.18M 2s
  3250K .......... .......... .......... .......... .......... 46% 10.0M 2s
  3300K .......... .......... .......... .......... .......... 47% 1002K 2s
  3350K .......... .......... .......... .......... .......... 48% 11.7M 2s
  3400K .......... .......... .......... .......... .......... 48% 10.9M 2s
  3450K .......... .......... .......... .......... .......... 49% 1.18M 2s
  3500K .......... .......... .......... .......... .......... 50% 8.60M 2s
  3550K .......... .......... .......... .......... .......... 51% 1.01M 2s
  3600K .......... .......... .......... .......... .......... 51% 12.4M 1s
  3650K .......... .......... .......... .......... .......... 52% 1.14M 1s
  3700K .......... .......... .......... .......... .......... 53% 12.3M 1s
  3750K .......... .......... .......... .......... .......... 53% 10.5M 1s
  3800K .......... .......... .......... .......... .......... 54% 1008K 1s
  3850K .......... .......... .......... .......... .......... 55% 12.4M 1s
  3900K .......... .......... .......... .......... .......... 56% 1.17M 1s
  3950K .......... .......... .......... .......... .......... 56% 5.38M 1s
  4000K .......... .......... .......... .......... .......... 57% 56.0M 1s
  4050K .......... .......... .......... .......... .......... 58% 1020K 1s
  4100K .......... .......... .......... .......... .......... 58% 11.0M 1s
  4150K .......... .......... .......... .......... .......... 59% 1.17M 1s
  4200K .......... .......... .......... .......... .......... 60% 11.5M 1s
  4250K .......... .......... .......... .......... .......... 60% 11.0M 1s
  4300K .......... .......... .......... .......... .......... 61% 1010K 1s
  4350K .......... .......... .......... .......... .......... 62% 11.6M 1s
  4400K .......... .......... .......... .......... .......... 63% 1.15M 1s
  4450K .......... .......... .......... .......... .......... 63% 10.6M 1s
  4500K .......... .......... .......... .......... .......... 64%  958K 1s
  4550K .......... .......... .......... .......... .......... 65% 10.4M 1s
  4600K .......... .......... .......... .......... .......... 65% 18.3M 1s
  4650K .......... .......... .......... .......... .......... 66% 1.22M 1s
  4700K .......... .......... .......... .......... .......... 67% 11.0M 1s
  4750K .......... .......... .......... .......... .......... 68%  998K 1s
  4800K .......... .......... .......... .......... .......... 68% 11.7M 1s
  4850K .......... .......... .......... .......... .......... 69% 9.99M 1s
  4900K .......... .......... .......... .......... .......... 70% 1.20M 1s
  4950K .......... .......... .......... .......... .......... 70% 11.2M 1s
  5000K .......... .......... .......... .......... .......... 71% 1003K 1s
  5050K .......... .......... .......... .......... .......... 72% 9.97M 1s
  5100K .......... .......... .......... .......... .......... 73% 11.3M 1s
  5150K .......... .......... .......... .......... .......... 73% 1.20M 1s
  5200K .......... .......... .......... .......... .......... 74% 10.4M 1s
  5250K .......... .......... .......... .......... .......... 75% 1011K 1s
  5300K .......... .......... .......... .......... .......... 75% 11.1M 1s
  5350K .......... .......... .......... .......... .......... 76% 10.6M 1s
  5400K .......... .......... .......... .......... .......... 77% 1.19M 1s
  5450K .......... .......... .......... .......... .......... 78% 11.8M 1s
  5500K .......... .......... .......... .......... .......... 78%  996K 1s
  5550K .......... .......... .......... .......... .......... 79% 11.1M 1s
  5600K .......... .......... .......... .......... .......... 80% 1.17M 1s
  5650K .......... .......... .......... .......... .......... 80% 10.5M 1s
  5700K .......... .......... .......... .......... .......... 81% 10.5M 1s
  5750K .......... .......... .......... .......... .......... 82% 1001K 1s
  5800K .......... .......... .......... .......... .......... 82% 8.97M 1s
  5850K .......... .......... .......... .......... .......... 83% 1.24M 1s
  5900K .......... .......... .......... .......... .......... 84% 8.77M 0s
  5950K .......... .......... .......... .......... .......... 85% 12.0M 0s
  6000K .......... .......... .......... .......... .......... 85% 1.00M 0s
  6050K .......... .......... .......... .......... .......... 86% 10.0M 0s
  6100K .......... .......... .......... .......... .......... 87% 1.10M 0s
  6150K .......... .......... .......... .......... .......... 87% 5.36M 0s
  6200K .......... .......... .......... .......... .......... 88% 9.06M 0s
  6250K .......... .......... .......... .......... .......... 89% 1.20M 0s
  6300K .......... .......... .......... .......... .......... 90% 9.92M 0s
  6350K .......... .......... .......... .......... .......... 90% 1.20M 0s
  6400K .......... .......... .......... .......... .......... 91% 9.45M 0s
  6450K .......... .......... .......... .......... .......... 92% 11.2M 0s
  6500K .......... .......... .......... .......... .......... 92% 1022K 0s
  6550K .......... .......... .......... .......... .......... 93% 11.6M 0s
  6600K .......... .......... .......... .......... .......... 94% 1.17M 0s
  6650K .......... .......... .......... .......... .......... 95% 10.6M 0s
  6700K .......... .......... .......... .......... .......... 95% 10.9M 0s
  6750K .......... .......... .......... .......... .......... 96% 1012K 0s
  6800K .......... .......... .......... .......... .......... 97% 11.0M 0s
  6850K .......... .......... .......... .......... .......... 97% 1.17M 0s
  6900K .......... .......... .......... .......... .......... 98% 11.8M 0s
  6950K .......... .......... .......... .......... .......... 99%  994K 0s
  7000K .......... .......... .......... .......... ......... 100% 11.7M=3.1s

2017-01-17 23:21:36 (2.25 MB/s) - 'shadowsocks.tar.gz' saved [7218482/7218482]

2017年01月17日 23:21:36: 更新包md5校验一致！ 开始安装！...
2017年01月17日 23:21:36: 开始解压压缩包...
/koolshare/ss/ssconfig.sh: line 316: can't fork
tar: write: Broken pipe

**Comment by sadoneli** [comment]
can‘t fork一般是sh脚本调用sh脚本，不能创建子进程引起的，目前只能建议重启一次路由器

未来会减少脚本调用的次数（其实现在已经减少很多了），来尽量避免这个问题

**Comment by tianyi1111** [comment]
我也出现过一样的问题，后来发现是内存不足，networkmap这个进程占了30%多的内存，把它干掉后就好了，不知道这个是什么程序，过短时间自己又出现了
