### ISSUE TITLE
openvpn client连接以后，无法访问远端资源

### ISSUE THREAD

**Issue by leench** [koolshare/koolshare.github.io#262]
没注意是从哪个版本开始不行的，好像就是最近，排查很久发现是ss的问题

https://github.com/koolshare/koolshare.github.io/blob/acelan_softcenter_ui/shadowsocks/shadowsocks/ss/nat-start.sh
`
/usr/sbin/ip route add local 0.0.0.0/0 dev lo table 310
`

好像是这里引起的，执行删除就可以正常访问远端了。没有仔细看。远端ip是10.10.10..0/24和20.20.20.0/24,添加白名单无效。

**Comment by apango** [comment]
是不是只在游戏模式下无效？我看到这一行在游戏模式下有，而gfwlist模式下无。

**Comment by sadoneli** [comment]
是的
