### ISSUE TITLE
能否在ss游戏模式界面增加自定义mtu的选项？

### ISSUE THREAD

**Issue by wyyzaw** [koolshare/koolshare.github.io#268]
[这是我之前遇到的问题](http://koolshare.cn/forum.php?mod=viewthread&tid=79945&page=1#pid777991)

shadowsocks-libev在去年一次更新增加mtu参数支持后，就把收到大于设定mtu的udp包直接丢弃了，导致一些游戏过程中会连不上，所以想请问下是否可以在ui上增加个ssredir的启动mtu参数配置？

**Comment by sadoneli** [comment]
很早想加的，不过这对用户尤其是小白很不友好，而且加上了，虽然能改mtu，但是并不会对ip碎片之类的有帮助

**Comment by wyyzaw** [comment]
ps4的ip碎片不太清楚，不过现在sslibv的逻辑是遇到mtu大于默认值的udp包会直接丢弃，具体表现可能有些游戏就直接连不上了.....
