### ISSUE TITLE
3.2.3界面小问题

### ISSUE THREAD

**Issue by prolene** [koolshare/koolshare.github.io#269]
节点管理选项卡，点击“添加节点”，再选择“编辑SSR帐号”，因为内容比较多，所以弹出框超过了页面的底端，造成难以关闭的情况。对已有的节点进行编辑也是同样的问题
![2017-01-23 7 28 17](https://cloud.githubusercontent.com/assets/21002741/22202229/270cd238-e1a2-11e6-93e5-12744cc17ffd.png)

**Comment by sadoneli** [comment]
建议使用chrome浏览器

在 2017年1月23日 下午7:29，prolene <notifications@github.com>写道：

**Comment by prolene** [comment]
safari下出现的这个问题，又不是什么非主流浏览器，如果是ie6下出现我就不来提交了

**Comment by sadoneli** [comment]
ss界面主要针对chrome优化，safari如果出现问题，没多大精力去修复，还请谅解
