### ISSUE TITLE
可否增加zerotier支持

### ISSUE THREAD

**Issue by amosbird** [koolshare/koolshare.github.io#273]
entware-ng里已经有这个包了，能不能移植过来呢？

**Comment by jannson** [comment]
看着介绍挺有意思的，可以考虑。有空能在论坛出个 entware-ng 的使用教程么？这样我看看大家怎么用，然后我们才方便实现界面。

**Comment by amosbird** [comment]
谢谢，不过`entware-ng`我也没用过，我是在梅林那看到的，对`zerotier`比较熟。`zerotier`的界面我觉得和`vpn`差不多就行，也是多个网卡，配置一些路由规则。

**Comment by jannson** [comment]
我可以编译一个 独立的没有 entware-ng 依赖的版本。发了个帖子好多人都不明白怎么回事：
http://koolshare.cn/thread-83063-1-1.html

**Comment by amosbird** [comment]
非常感谢。这个很好用的，相当于一个全球交换机。

**Comment by jannson** [comment]
好，我尽快编译出来给你用着。

**Comment by jannson** [comment]
我已经叫 @houzi- 编译中了。等他的结果吧。静态编译。到时候我也想在路由器里面试用下。

**Comment by JackyRen** [comment]
赞！这是个好东西啊

**Comment by jannson** [comment]
是好东西，但是 houzi 还没有编译，好吧。

**Comment by houzi-** [comment]
等我编译吧

**Comment by sadoneli** [comment]
@jannson @houzi- 过来补锅

**Comment by amosbird** [comment]
啊？这个编好了嘛

**Comment by amoboy** [comment]
求编译好的包
