### ISSUE TITLE
ss直接填写ip地址的时候，ip没有被加入白名单

### ISSUE THREAD

**Issue by difujia** [koolshare/koolshare.github.io#275]
挂上ss后，ssh操作vps上的服务端时会导致ssh断开。
猜测是到vps的请求也经过了ss。
阅读`nat-start.sh`和`start.sh`发现当`ss_basic_server`直接为IP地址时（跳过dns解析步骤），`ss_basic_server_ip`没有传值，也无法加入white_list中。

**Comment by sadoneli** [comment]
已经解决了
