### ISSUE TITLE
3.3.0 chacha20-ietf camellia-256-cfb 加密方式无法使用

### ISSUE THREAD

**Issue by Jieee006** [koolshare/koolshare.github.io#277]
ss-libev 3.30 chacha20-ietf camellia-256-cfb chacha20-ietf-poly1305等 这些加密方式都是PD。
chacha20和aes-256-cfb正常。

**Comment by sadoneli** [comment]
服务器端需要最新ss 3.0.0才能支持

**Comment by Jieee006** [comment]
已经是3.0.1了。。。

**Comment by Jieee006** [comment]
而且 chacha20-ietf camellia-256-cfb也不是新的加密方式

**Comment by sadoneli** [comment]
![image](https://cloud.githubusercontent.com/assets/10495520/22689805/99934540-ed6d-11e6-97ab-185d696d0d7d.png)
我本人一直使用chacha20-ietf，没问题的

**Comment by sadoneli** [comment]
另外测试chacha20-ietf-poly1305也是ok的，你检查下你那边

**Comment by Jieee006** [comment]
别的客户端都是可以的，很奇怪，chacha20和aes-256-cfb都可以，chacha20-ietf-poly1305我也不行

**Comment by Jieee006** [comment]
经测试 ss-tunnel不行（包括pdnsd用ss-tunnel),dns2socks可以。。。。。

**Comment by Jieee006** [comment]
你试试看呢ss-tunnel

19:49:55 INFO: UDP relay enabled
 INFO: initializing ciphers... chacha20-ietf

udp relay也是打开的

**Comment by sadoneli** [comment]
3.0.0 ss-tunnel兼容性不行，我服务器+客户端双端一致版本没问题

**Comment by Jieee006** [comment]
就是你的服务端还是3.0.0是吗 升到3.0.1呢

**Comment by sadoneli** [comment]
我已经看到有人服务器端3.0.1 + client 3.0.0有问题了，我将尽快更新client这边

**Comment by Jieee006** [comment]
OK，多谢。

**Comment by jieee006** [comment]
更新到3.3.1了 可是新加密方式 ss-tunnel好像还是不行

**Comment by jieee006** [comment]
测试了还是不行，更新到3.3.1 ss-tunnel和新的加密方式 还是PD。

**Comment by jieee006** [comment]
把密码变短以后可以了。。。。难道是密码太长？

**Comment by jieee006** [comment]
反复测试后发现 长密码（12位或以上密码），ss-tunnel使用chacha20-ietf,camellia-256-cfb以及chacha20-ietf-poly1305等这些新的加密方式，就无法使用(有时候国外连接working但是实际上是没连上）。别的客户端都是可以用的。你试试看密码改长，你那里能不能重现这个问题。
