### ISSUE TITLE
升级shadowsocks3.3.1后ss-tunnel的dns选项失效

### ISSUE THREAD

**Issue by vonhezhou** [koolshare/koolshare.github.io#279]
rt
使用dns选项标签下
国外dns如果使用ss-tunnel,则无论如何都会提示
国外连接 - [ 2017-02-09 22:40:27 ] Problem detected!!!!!

**Comment by xiaodoudou** [comment]
Hey,
you can use dns2socks temporary until its getting fixed.

**Comment by vonhezhou** [comment]
Done that already. THX for the info though

**Comment by vonhezhou** [comment]
3.3.2确认修复
