### ISSUE TITLE
Telegram 在大陆白名单如何加速？

### ISSUE THREAD

**Issue by lingaoyi** [koolshare/koolshare.github.io#28]
我发现载入速度好慢，图片都要转几圈。

**Comment by fengqi** [comment]
想办法找出他尝试连接的 ip列表或者域名就好了，改天有时间抓包看看

**Comment by lingaoyi** [comment]
@fengqi 能抓到吗？我其实不懂 Orz

**Comment by fengqi** [comment]
能的，我这会儿在折腾 react native 后面找时间抓下。

**Comment by yulhun** [comment]
https://github.com/gongjianhui/AppleDNS
能不能这个也加里面，对苹果用户来说福音  谢谢

**Comment by jannson** [comment]
感谢提供，我们测试测试

**Comment by Cavolo** [comment]
的确，https://github.com/gongjianhui/AppleDNS解决了国内强行代理Apple服务效果不好的问题，而且梅林中用脚本配置的hosts貌似在pc上无效，希望可以又一个整合方案

**Comment by fengqi** [comment]
已经可以了。

**Comment by Cavolo** [comment]
Apple dns这个有进展吗

**Comment by fengqi** [comment]
自己 ping 下看看， 在 shadowsocks 里面配置下就行，我上海电信啥不管速度也不错

**Comment by Cavolo** [comment]
我知道在gfwlist模式下是可以配置hosts的，但在大陆白名单下就没有配置的地方了

**Comment by jannson** [comment]
最近 S大 忙，我在弄游戏模式当中。
hosts 可以配置的，通过 dnsmasq 就可以搞定。类似在 dnsmasq.conf.add 里面加：
addn-hosts=/jffs/configs/hosts

这样就相当于在所有路由器下面的设备加 hosts 了

**Comment by yulhun** [comment]
https://github.com/CNMan/unbound.conf
这个可以

**Comment by jannson** [comment]
看了下，可能不够方便移植到路由器里。但是思想可以利用到 dnsmasq + 其它的工具。

**Comment by yulhun** [comment]
这个加里面可以吗
https://github.com/pwnsdx/RandomDNS

**Comment by yulhun** [comment]
https://github.com/zyqf
这个dns加可以吗 做的很不错。

**Comment by NeoZZZZ** [comment]
GFWlist网址更新了：https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt

**Comment by jannson** [comment]
@yulhun 你给的链接，适合放在国内的云服务器上，最好是自己个人的。这样就不需要路由器进行解析了！

**Comment by jannson** [comment]
@NeoZZZZ 感谢，我会叫 S大及时更新上。

**Comment by gongjianhui** [comment]
IP 黑名单：

# Telegram
91.108.56.0/22
91.108.4.0/22
109.239.140.0/24
149.154.160.0/20

**Comment by jannson** [comment]
感谢大牛提供,可以试试.
