### ISSUE TITLE
游戏模式V2国外经常PD，求解决方法

### ISSUE THREAD

**Issue by lingaoyi** [koolshare/koolshare.github.io#282]
V2是不是不更新了？打游戏经常要用到v2，但最近经常PD，必须要提交一次才能解决，打游戏突然就PD了。
Connection setup failed: XX.XX.22.125, error: Connection reset by peer, retry 1: 
Disconnect with reason: Closed by remote (Socket closed by remote peer)

**Comment by jannson** [comment]
不好意思，游戏 V2 需要等未来的 C 语言改进版本。目前暂时没时间更新。
