### ISSUE TITLE
能否考虑加入计划性重启客户端功能

### ISSUE THREAD

**Issue by phlips5437** [koolshare/koolshare.github.io#285]
你好，本人环境如下，自建搬瓦工VPS，使用AC68U路由器，并加了U盘使用32M的虚拟内存

小飞机模式为SS+KCP功能，使用白名单

目前使用下来速度可以，但是基本上1天多一些的时间会出现PD的情况（做了虚拟内存还是如此）

出现这样的情况我是1、切换至gflist，2、切换回白名单。这样又能正常使用1天左右

能否考虑加入客户端的自动重启功能，将客户端重置一下再重新连接VPS？

**Comment by xiaojj** [comment]
路由定时重启。

**Comment by phlips5437** [comment]
我的路由器重启会夯住，每次重启都需要再手动断电一次才行
xiaojj <notifications@github.com>于2017年2月18日 周六21:44写道：

**Comment by sadoneli** [comment]
暂时无该计划，如果需要，请写crontab任务调用/koolshare/scripts/ss_sconfig.sh脚本来实现
