### ISSUE TITLE
关于ss游戏模式

### ISSUE THREAD

**Issue by ccsil** [koolshare/koolshare.github.io#286]
想问下使用游戏模式访问国外网站和加速游戏都没有问题 但是访问国内网站就很卡 甚至无法访问是什么原因呢？ 国内外都是显示的working 国内ip是我的公网ip gfwlis模式和大陆白名单模式都没有问题

**Comment by sadoneli** [comment]
无法重现你的问题哈
请检查固件设置，比如qos等

**Comment by ccsil** [comment]
恢复出厂设置重新安装之后就没这个问题了
