### ISSUE TITLE
解除ShadowSocks插件与其所包含组件的捆绑。

### ISSUE THREAD

**Issue by wdhwg001** [koolshare/koolshare.github.io#287]
![image](https://cloud.githubusercontent.com/assets/8943519/23295213/4776e7cc-faaa-11e6-82b4-7b63aeff0810.png)

想了一下，大致像是这样，或者把组件的按钮做到顶层，与`ShadowSocks设置`等并列。

具体实现的话，或许可以采用二进制+patch的方式，同时引入各个组件的源码和CI…？或许有更好的其他的方案。

移除组件的绑定将会是一个较大规模的工作，有相当的组件也涉及到了许多功能和逻辑上的调整，但我个人觉得是有意义的。

1. 目前ShadowSocks插件所需要的组件数量较多。
2. 其中有部分组件（如dnscrypt-proxy）落后不少版本了。
3. 如ShadowSocks-libev可能存在功能不稳定等问题，且争议较多。

**Comment by sadoneli** [comment]
确实你的方法很好，我很久也想做这样的方案，但是确实二进制版本不同带来插件逻辑的不同，捆住merlin的ss方案的手脚，而merlin最开始是想做小白的一键式傻瓜方案，这与设计目的有些背离。

如果上这样的方案，可能需要重新设计逻辑，让用户得到更多的订制化，比如ss/ssr一个组件,kcp一个组件，haproxy一个组件，dns一个组件，dnsmasq一个组件，iptables（访问控制）一个组件，感觉就更像在做openwrt的方案，组件间的配合更多的需要用户自己去关注

再者在你的方案基础啊上，我们可以将这些组件做好逻辑关系，就对集成的脚本和界面逻辑设计上考虑诸多，不过我想可以先做一个AEAD前后方案的选择

但是鉴于新的软件中心又要上马了，所以对现在的ss我又不太想去改动什么了，，，真是纠结
