### ISSUE TITLE
googleapis.com googlesyndication.com等不要走ss好么

### ISSUE THREAD

**Issue by HisingX** [koolshare/koolshare.github.io#288]
这些域名google早就解析过中国服务器了，北京和上海，现在名单里有这些郁很不方便，老解析到国外IP，影响访问速度。能不能取消啊。

**Comment by sadoneli** [comment]
你解析到国外ip的话就会走国外，解析到国内ip的话就会走国内，所以dns解析很重要

**Comment by HisingX** [comment]
我选的国内优先，但是解析始终是国外的IP。我怎么感觉还是因为地址在列表里走的ss的解析。导致了解析到国外。
因为这个域名是没有墙的，取消掉会更好点。

**Comment by sadoneli** [comment]
我同步的是官方gfwlist，你可以向这里反馈 https://github.com/gfwlist/gfwlist
