### ISSUE TITLE
不升级到ShadowSocks-libev 2.4.5么？

### ISSUE THREAD

**Issue by abc9878** [koolshare/koolshare.github.io#29]
不升级到ShadowSocks-libev 2.4.5么？
看Changlog说降低了ss-redir的延迟。

**Comment by sadoneli** [comment]
待观察

**Comment by sadoneli** [comment]
https://github.com/koolshare/koolshare.github.io/commit/9d6a550bd5f35d040e4428106e9f1439de2538fd
