### ISSUE TITLE
ss插件有没有可能做成由用户自主选择ss客户端版本

### ISSUE THREAD

**Issue by ccsil** [koolshare/koolshare.github.io#293]
完全不懂代码又喜欢追新的用户的小小建议  不知道如果要实现起来会不会很麻烦

**Comment by ccsil** [comment]
还有ss游戏模式与qos不能同时开启 否则会影响国内网站的访问不知道有什么解决方法

**Comment by sadoneli** [comment]
1 应该不会
2 解决办法：需要游戏模式就关闭qos，需要qos就不用游戏模式
