### ISSUE TITLE
话说梅林里开完ss，它的地址跟端口是什么

### ISSUE THREAD

**Issue by yunyu2017** [koolshare/koolshare.github.io#295]
因终端需要利用工具强制给别的应用挂上代理，需要设置代理地址跟端口，如果用桌面版ss 的话默认127.0.0.1：1080，那梅林里是什么？？？还有ss-sever开启后共享出去的ip是哪个😂萌新😘

**Comment by sadoneli** [comment]
merlin里的默认是透明端口，并不能用于sock5
除非你单独配置socks5页面

ss-server当然是你的公网ip

**Comment by yunyu2017** [comment]
哇塞~第一次留言居然就收到回复了耶~好嗨森~
虽然问题已经瞎折腾解决了=。=但真的是非常谢谢呢~





BestWishes!
 
发件人： sadoneli
发送时间： 2017-03-06 09:15
收件人： koolshare/koolshare.github.io
抄送： yunyu; Author
主题： Re: [koolshare/koolshare.github.io] 话说梅林里开完ss，它的地址跟端口是什么 (#295)
merlin里的默认是透明端口，并不能用于sock5
除非你单独配置socks5页面
ss-server当然是你的公网ip

**Comment by jannson** [comment]
路过路过。

**Comment by nsleejian** [comment]
终端如何设置 http_proxy 和 https_proxy？youtube-dl无法使用。
