### ISSUE TITLE
网件6400开启kcptun后国外problem detected

### ISSUE THREAD

**Issue by cokeisnotbest** [koolshare/koolshare.github.io#296]
不开kcptun就没问题，开了就连不上。可是如果路由器不开启ss，只在电脑安装ss和kcp客户端就可以正常连接。
服务器使用搬瓦工的centos7和ubuntu16.04都试过，pip安装的shadowsocks，github上的一键脚本安装的kcptun。
想确定问题在哪需要什么信息吗？
另外路由器里是否有kcp和ss的日志文件，位置在哪。
谢谢。

**Comment by sadoneli** [comment]
无法重现，请检查你的线路和kcptun设置
