### ISSUE TITLE
这个为什么呢？

### ISSUE THREAD

**Issue by yulhun** [koolshare/koolshare.github.io#3]
starting REDSOCKS2...
file parsing error at line 11: Name or service not known
file parsing error at line 11: value can't be parsed
file parsing error at line 11: unclosed section
大陆模式呢。

**Comment by jannson** [comment]
估计是BUG吧，生成配置出错了。要不就是你那里配置错了，导致redsocks2生成它的配置出错了。
你的固件是最新的吗？

**Comment by jannson** [comment]
最近的固件我测试没有这个问题。

**Comment by sadoneli** [comment]
这个是因为你使用了域名，建议使用ip地址
