### ISSUE TITLE
路由器上开ss-server时

### ISSUE THREAD

**Issue by oldskooler** [koolshare/koolshare.github.io#30]
日志里面出现很多下面的东西，如何解决呢
Feb 14 17:08:11 /usr/bin/ss-server[23820]: getpeername: Transport endpoint is not connected
Feb 14 17:08:11 /usr/bin/ss-server[23820]: getpeername: Transport endpoint is not connected
Feb 14 17:08:11 /usr/bin/ss-server[23820]: getpeername: Transport endpoint is not connected
Feb 14 17:08:13 /usr/bin/ss-server[23820]: getpeername: Transport endpoint is not connected
Feb 14 17:08:13 /usr/bin/ss-server[23820]: getpeername: Transport endpoint is not connected
Feb 14 17:08:13 /usr/bin/ss-server[23820]: getpeername: Transport endpoint is not connected
Feb 14 17:08:17 /usr/bin/ss-server[23820]: getpeername: Transport endpoint is not connected
Feb 14 17:08:17 /usr/bin/ss-server[23820]: getpeername: Transport endpoint is not connected
Feb 14 17:08:17 /usr/bin/ss-server[23820]: getpeername: Transport endpoint is not connected
Feb 14 17:09:01 /usr/bin/ss-server[23820]: getpeername: Transport endpoint is not connected
Feb 14 17:09:26 /usr/bin/ss-server[23820]: getpeername: Transport endpoint is not connected
Feb 14 17:10:37 /usr/bin/ss-server[23820]: getpeername: Transport endpoint is not connected
Feb 14 17:13:07 /usr/bin/ss-server[23820]: getpeername: Transport endpoint is not connected
Feb 14 17:15:08 /usr/bin/ss-server[23820]: getpeername: Transport endpoint is not connected

**Comment by sadoneli** [comment]
这个是正常的，无视就行了
