### ISSUE TITLE
shadowsock server Hang when dynamic wan ip changed

### ISSUE THREAD

**Issue by spencerwinston** [koolshare/koolshare.github.io#302]
本人经常回大陆出差，极需要一可靠方法翻墙，但pptp，openvpn 也不行了，其他手机app 又不靠普。无意发现ss，这很方便。但问题来了，因本人家中的wan ip 是动态ip 的，经常会转，之前以为设定了ddns 就可一劳永逸。可是最近发现了，当router 的wanip 一转变，router 内的ss－server 便自动失效，重启router 也没用，一定要去ss－server 界面先关闭再重开，ss－server 才能用。
希望大大可以修正此问题。我对网路编码不太憧，希望可以帮帮手。因为当我在大陆时，我无法登入自家的router 设定页面去关闭并重开ss－server。
我用的是asus 路由ac87u，安装了koolshare 的改版firmware 主要用内置那个ss－server
版本是X7.4 (应该是现时最新的吧）

**Comment by sadoneli** [comment]
try this https://github.com/koolshare/merlin-ssserver/commit/fa9a25b762f4fc807f8f59f194ff89f7ae15f6b9
