### ISSUE TITLE
3.3.5版本是否有问题？

### ISSUE THREAD

**Issue by HUI2125281** [koolshare/koolshare.github.io#303]
下午装的版本还能用，看到新版本升级了一下不行了。
怎么降级？
-------------
国外连接 - [ 2017-03-29 21:27:40 ] Problem detected! 
国内连接 - [ 2017-03-29 21:27:40 ] working... 

---------------

① 程序版本（插件版本：3.3.4）：
-----------------------------------------------------------
程序			版本		备注
ss-reidr		3.0.5		2017年3月28日
ss-tunnel		3.0.5 		2017年3月28日
ss-local		3.0.5		2017年3月28日
obfs-local		0.0.3		2017年3月28日
ssr-reidr		2.5.6 		with mbed TLS 2.4.0
ssr-tunnel		2.5.6 		with mbed TLS 2.4.0
ssr-local		2.5.6 		with mbed TLS 2.4.0
client_linux_arm5	20170322	kcptun
haproxy			1.7.1	
dns2socks		V2.0 	
dnscrypt-proxy		1.7.0 	
ChinaDNS		1.3.2 	
pndsd			1.2.9a-par 	
Pcap_DNSProxy		0.4.8.1
-----------------------------------------------------------

② 检测当前相关进程工作状态：（你正在使用SS-libev,选择的模式是【gfwlist模式】,国外DNS解析方案是：dns2socks）
-----------------------------------------------------------
程序		状态	PID
ss-redir	工作中	pid：8746
ss-local	未运行
dns2socks	工作中	pid：8735 8734 8727
-----------------------------------------------------------

③ 检测iptbales工作状态：
----------------------------------------------------- nat表 PREROUTING 链 --------------------------------------------------------
Chain PREROUTING (policy ACCEPT 174 packets, 13030 bytes)
 pkts bytes target     prot opt in     out     source               destination         
  101  5252 SHADOWSOCKS  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0           
    0     0 VSERVER    all  --  *      *       0.0.0.0/0            192.168.1.4         
   52  3325 DNAT       udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:53 to:192.168.50.1

----------------------------------------------------- nat表 OUTPUT 链 ------------------------------------------------------------
Chain OUTPUT (policy ACCEPT 192 packets, 12468 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set router dst redir ports 3333

----------------------------------------------------- nat表 SHADOWSOCKS 链 --------------------------------------------------------
Chain SHADOWSOCKS (1 references)
 pkts bytes target     prot opt in     out     source               destination         
   47  2444 RETURN     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set white_list dst
   54  2808 SHADOWSOCKS_GFW  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0           

----------------------------------------------------- nat表 SHADOWSOCKS_GFW 链 ----------------------------------------------------
Chain SHADOWSOCKS_GFW (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set black_list dst redir ports 3333
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set gfwlist dst redir ports 3333

----------------------------------------------------- nat表 SHADOWSOCKS_CHN 链 -----------------------------------------------------
Chain SHADOWSOCKS_CHN (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set black_list dst redir ports 3333
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            ! match-set chnroute dst redir ports 3333

----------------------------------------------------- nat表 SHADOWSOCKS_GAM 链 -----------------------------------------------------
Chain SHADOWSOCKS_GAM (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set black_list dst redir ports 3333
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            ! match-set chnroute dst redir ports 3333

----------------------------------------------------- nat表 SHADOWSOCKS_GLO 链 -----------------------------------------------------
Chain SHADOWSOCKS_GLO (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            redir ports 3333
-----------------------------------------------------------------------------------------------------------------------------------

**Comment by sadoneli** [comment]
ss-local没运行，这里出了问题
