### ISSUE TITLE
3.3.4~3.3.6的版本ss-tunnel有问题，导致国外一直PD。

### ISSUE THREAD

**Issue by chuan0932** [koolshare/koolshare.github.io#304]
![qq 20170329225307](https://cloud.githubusercontent.com/assets/20948423/24461012/80d9d0f0-14d2-11e7-91b4-be057568def4.png)

切换到dns2socks就正常。

**Comment by leochien0102** [comment]
我3.3.3时正常，升级到3.3.6就PD了

**Comment by sadoneli** [comment]
ssr-tunnel并没有问题，这里只是后台脚本的一个小问题导致了显示问题
