### ISSUE TITLE
ss-redir in shadowsocks version 3.3.6 does not work

### ISSUE THREAD

**Issue by XingjianXu** [koolshare/koolshare.github.io#305]
`admin@RT-AC68U-ECD8:/jffs/.koolshare/ss# ss-redir -b 0.0.0.0 -c /koolshare/ss/ss.json
 2015-08-01 08:38:37 INFO: initializing ciphers... rc4
Segmentation fault`

Update from shadowsocks plugin version 3.3.3
Router: AC68U
OS version: 380.65_X7.4

**Comment by XingjianXu** [comment]
I fix this by replace `/jffs/.koolshare/bin/ss-redir` with `https://raw.githubusercontent.com/koolshare/koolshare.github.io/master/shadowsocks/shadowsocks/bin/ss-redir`

**Comment by sadoneli** [comment]
rc4 chipher is not support in ss-redir 3.0.5
