### ISSUE TITLE
Resolveip卡住问题

### ISSUE THREAD

**Issue by Easy-Sir** [koolshare/koolshare.github.io#306]
我每次在使用Resolveip解析时，在SS正常运行时，如果直接点击应用按钮（快速更改服务器地址之类的时候），解析一定会失败，必须要在手动关闭后再启动就会解析正常，等待时间较长，不知可否解决一下，路由器R6300V2

**Comment by sadoneli** [comment]
更换nsklookup方式

**Comment by Easy-Sir** [comment]
好的，可能是我自身网络问题吧 ，感谢解答！
