### ISSUE TITLE
可否考虑在SS里加入单独开启UDP转发功能？

### ISSUE THREAD

**Issue by SunZhizhong** [koolshare/koolshare.github.io#308]
现在我所知道的是梅林内SS的gfwlist和大陆白名单并不支持UDP转发，只有游戏模式可以开启UDP功能，但是游戏模式不能使用KCP来优化网络响应时间和丢包率，而且我也不想让很多流量经过VPS，基本只要保证gfwlist模式就可以，UDP流量可以用其他方式代理游戏，并且通过KCP优化网络，请问团队是否会考虑加入UDP转发？

**Comment by Murriouz** [comment]
支持，有些软件是通过 UDP 来传输数据的，也需要翻墙

**Comment by sadoneli** [comment]
kcp的实现虽然用了udp承载kcp流，但是在外部并不能为udp加速，只能tcp

**Comment by SunZhizhong** [comment]
@sadoneli 原来如此，也不一定非要使用KCP，主要还是想在gfwlist模式下实现UDP转发，然后再在电脑端进行设置。
