### ISSUE TITLE
当访问控制里面加入新规则后，接入openvpn的客户端就会出现只能访问墙外网站

### ISSUE THREAD

**Issue by cjt2624** [koolshare/koolshare.github.io#309]
当访问控制里面加入新规则后，接入openvpn的客户端就会出现只能访问墙外网站，无法访问国内网站了，估计是规则处理有问题，
删除自定义规则后就没有问题

**Comment by sadoneli** [comment]
和openvpn有冲突，请关闭其中之一使用
