### ISSUE TITLE
设置页显示不正确

### ISSUE THREAD

**Issue by Murriouz** [koolshare/koolshare.github.io#311]
如截图所示，负载均衡的设置页消失，多了几个不存在的设置页。

路由器：ASUS RT-AC88U

第一次打开的时候负载均衡是在的，打开负载均衡后就变成了这个样子，而且再也回不去了

![image](https://cloud.githubusercontent.com/assets/4125903/24645168/a8700cd0-1949-11e7-937c-42758986ea77.png)

**Comment by sadoneli** [comment]
请刷最新固件，老固件不再解答

**Comment by Murriouz** [comment]
刷的是 koolshare 论坛最新发布的 380.65-X7.4 版本的固件

![image](https://cloud.githubusercontent.com/assets/4125903/24685744/016aa2b2-19e2-11e7-8a4a-6c517b6a168c.png)

**Comment by sadoneli** [comment]
那么请按照刷机流程来哈，恢复出厂设置，格式化jffs分区都做一次

不然旧的文件会残留的
