### ISSUE TITLE
使用全局模式无效？其他模式仍然可以走代理，切换到全局后却变成了所有端口不走代理。

### ISSUE THREAD

**Issue by yunyu2017** [koolshare/koolshare.github.io#312]
以下为日志，gfw或者白名单的时候可以访问，但是用全局却无法访问，在路由器内显示工作正常，也能ping到google.com，但是PC端无法访问被墙地址。
2017年04月05日 01:16:26: ================ 梅林固件 - shadowsocks by sadoneli&Xiaobao ==============
2017年04月05日 01:16:26:
2017年04月05日 01:16:26: ----------------------------- 停止上个SS模式 -----------------------------
2017年04月05日 01:16:27: 删除/jffs/scripts/dnsmasq.postconf
2017年04月05日 01:16:27: 删除ss相关的名单配置文件.
2017年04月05日 01:16:27: 清除nat-start, wan-start中相关的SS启动命令...
2017年04月05日 01:16:27: 关闭ss-redir进程...
2017年04月05日 01:16:28: 关闭ss-local进程:23456端口...
2017年04月05日 01:16:28: 关闭dns2socks进程...
2017年04月05日 01:16:29: 关闭kcp协议进程...
2017年04月05日 01:16:30: ----------------------- shadowsocks 启动前触发脚本 -----------------------
2017年04月05日 01:16:30: ss启动前触发：你选择了普通节点，不触发负载均衡启动！.
2017年04月05日 01:16:30: ------------------------- 梅林固件 shadowsocks --------------------------
2017年04月05日 01:16:30: 检测到你的SS服务器已经是IP格式：[ 此处为服务器ip ] 跳过解析...
2017年04月05日 01:16:30: 创建SS配置文件到/koolshare/ss/ss.json
2017年04月05日 01:16:30: 生成cdn加速列表到/tmp/sscdn.conf，加速用的dns：119.29.29.29
2017年04月05日 01:16:32: 添加nat-start触发事件...用于ss的nat规则重启后或网络恢复后的加载.
2017年04月05日 01:16:32: 添加wan-start触发事件...用于ss的各种程序的开机启动，启动延迟5
2017年04月05日 01:16:32: ss规则定时更新任务未启用！
2017年04月05日 01:16:32: ┣开启ss-local,为dns2socks提供socks5端口：23456
2017年04月05日 01:16:32: 开启dns2socks，监听端口：23456
2017年04月05日 01:16:33: 开启ss-redir进程，用于透明代理.
2017年04月05日 01:16:33: 启动KCP协议进程，为了更好的体验，建议在路由器上创建虚拟内存.
2017年04月05日 01:16:33: 加载nat规则!
2017年04月05日 01:16:33: 尝试先清除已存在的iptables规则，防止重复添加
2017年04月05日 01:16:34: 先清空已存在的ipset名单，防止重复添加
2017年04月05日 01:16:34: 清除重复的ip rule规则.
2017年04月05日 01:16:34: 删除ip route规则.
2017年04月05日 01:16:34: 创建ipset名单
2017年04月05日 01:16:35: 写入iptables规则到nat表中...
2017年04月05日 01:16:36: 加载ACL规则：:80,443模式为：gfwlist模式
2017年04月05日 01:16:36: 加载ACL规则：192.168.1.63:all模式为：全局模式
2017年04月05日 01:16:36: 加载ACL规则：其余主机模式为：全局模式
2017年04月05日 01:16:36: 开启chromecast功能（DNS劫持功能）
2017年04月05日 01:16:36: 重启dnsmasq服务...
2017年04月05日 01:16:38: ------------------------- shadowsocks 启动完毕 -------------------------
2017年04月05日 01:16:38:
2017年04月05日 01:16:38: Enjoy surfing internet without Great Fire Wall!
2017年04月05日 01:16:38:
2017年04月05日 01:16:38: =============== 梅林固件 - shadowsocks by sadoneli&Xiaobao ===============

**Comment by sadoneli** [comment]
贴上你得iptables配置
另外能ping上google说明不对，应该ping不上才对
