### ISSUE TITLE
3.3.1升3.3.7后版本号不更新，无法启动SS

### ISSUE THREAD

**Issue by Daryljocky** [koolshare/koolshare.github.io#314]
3.3.1升3.3.7后版本号不更新，版本号还是显示为3.3.1
启动SS后重新进入管理界面，发现SS没有启动起来
再次点击升级按钮，无反应，除非重启无法进入192.168.1.1页面，但网络没有断

机器为AC87U

**Comment by sadoneli** [comment]
无法重现

建议格式化jffs分区重装
