### ISSUE TITLE
speedtest 运行没反应

### ISSUE THREAD

**Issue by registe** [koolshare/koolshare.github.io#315]
有些时日了，魔都电信
卸载重装还是一样

**Comment by Major-k** [comment]
由于该测试服务器在国外且部分网页代码调用 Google ，加载缓慢属于正常情况。测速尽量不要使用国外环境进行测速，国内电信测速节点很多啊。

**Comment by registe** [comment]
![screenshot 2017-05-11 20 58 15](https://cloud.githubusercontent.com/assets/458892/25950166/94064b0a-368c-11e7-8f00-a249fb934123.png)
请教如何使用国内节点进行测速，我没有说明白，是插件中心的speedtest插件
