### ISSUE TITLE
gfwlist会导致haha.mx强制走代理

### ISSUE THREAD

**Issue by winswd** [koolshare/koolshare.github.io#316]
server=/.mx/127.0.0.1#7913
ipset=/.mx/gfwlist

访问haha.mx后, ip就被加入到ipset的gfwlist组里强制走代理.

**Comment by sadoneli** [comment]
.mx域名为墨西哥(Mexico)国家及地区顶级域（ccTLD）的域名
所以有了
server=/.mx/127.0.0.1#7913
ipset=/.mx/gfwlist
这条，让其都走ss

**Comment by winswd** [comment]
gfwlist的原则不是被Q的才走代理么... 现在这条规则误伤了遨游的部分网站, 走ss会出现ERR_EMPTY_RESPONSE, 而且我这边还发现有其他一些网站访问的时候也会出现ERR_EMPTY_RESPONSE...

目前看ipset里面的规则, 如果被加入到了gfwlist组, 就会强制走ss, 哪怕white_list里面已经定了了也不行... 或者应该让white_list先生效?

**Comment by sadoneli** [comment]
white list是先生效地，你加入后重启后得清楚dns缓存和浏览器缓存再能有效果

**Comment by sadoneli** [comment]
路由上的gfwlist模式其实和pac的gfwlist模式是有差别的，因为没法用正则识别，只能用ipset，所以在效果上肯定是有差别的

**Comment by winswd** [comment]
那现在要怎么解决这个问题呢? 目前我看白名单里面应该有两条规则, 一个是让不走代理的域名加入白名单, 让其用国内dns解析, 一个是把解析后的ip加入到ip白名单, 让其不走代理.

如果是这么解决的话, 要在白名单中增加对应规则, 应该修改哪个文件呢? ~~

**Comment by sadoneli** [comment]
![image](https://cloud.githubusercontent.com/assets/10495520/25030406/55409600-20f7-11e7-8488-37e784842a05.png)

**Comment by winswd** [comment]
好的, 多谢指教~ 再咨询一下, 路由器目录下的cdn.txt和chnroute.txt, 在gfwlist模式下是不会生效的吗? 有没有哪个文件可以在gfwlist模式下定义默认白名单的...

**Comment by sadoneli** [comment]
1 不会生效
2 界面上定义就行，动态生成的
