### ISSUE TITLE
Chrome 看 YouTube 没速度，Safari能跑满，什么情况？

### ISSUE THREAD

**Issue by lingaoyi** [koolshare/koolshare.github.io#319]
V2模式和SSR模式都会这样。

版本：3.3.7

Chrome:
http://i.imgur.com/J9AUyQs.png

Safari:
http://i.imgur.com/f8vTBnH.png

相同视频，相同时间...........

**Comment by matthew728960** [comment]
进入chrome://flags，关闭QUIC

**Comment by lingaoyi** [comment]
上周解决了，感谢楼上，忘记关闭，不过关闭的时候不是马上生效，还要在终端敲入这个命令才行！
sudo killall -HUP mDNSResponder;sudo dscacheutil -flushcache
