### ISSUE TITLE
主机名/IP含有空格导致SS插件无法解析主机

### ISSUE THREAD

**Issue by wntss** [koolshare/koolshare.github.io#320]
我的GCP主机的SS一直无法在路由器使用，web测试失败，在手机上使用正常，在路由器上配置负载均衡时看到报错：
[ALERT] 112/084813 (1376) : parsing [/koolshare/configs/haproxy.cfg:48] : 'server 1.2.3.4' unknown keyword '1.2.3.4'. Registered keywords :[ ALL] id <arg>
[ALERT] 112/084813 (1376) : Error(s) found in configuration file : /koolshare/configs/haproxy.cfg
[ALERT] 112/084813 (1376) : Fatal errors found in configuration.

查看 /koolshare/configs/haproxy.cfg，发现IP后面有空格：
    server 192.168.1.2:5400 192.168.1.2:5400 weight 50 rise 2 fall 3 check inter 2000 resolvers mydns
    server 1.2.3.4       :4321 1.2.3.4    :4321 weight 20 rise 2 fall 3 check inter 2000 resolvers mydns backup

回到SS的节点配置页面编辑这个条目，确实在IP后面发现有空格，删除空格之后，成功加入负载均衡配置。

SS插件版本是3.3.7。

是否应该考虑在加入主机名/IP时，滤除前后空格?

**Comment by wntss** [comment]
SS插件版本为3.3.7

**Comment by sadoneli** [comment]
https://github.com/koolshare/koolshare.github.io/blob/acelan_softcenter_ui/shadowsocks/Changelog.txt#L22
