### ISSUE TITLE
关于xbox限制的新问题

### ISSUE THREAD

**Issue by 88425255** [koolshare/koolshare.github.io#321]
家里是用网件r7000梅林7.4的。家里电视手机xbox都无线联它。用广州移动宽带。
最近发现了一个问题，当科学上网后，家里的手机或电视看网络电视就是爱奇艺，youku,云视听那些。
xbox就自动变成nat严格，我在想这个是不是科学上网之后跟视频端口冲突了。
对这个问题不知道是否属于梅林问题，如果可以，帮忙解决，谢谢。

**Comment by tang1989324** [comment]
SS 版本3.1.5没有这个问题 我降级回来的

**Comment by 88425255** [comment]
tang,这个是因为什么原因导致的，我不知道怎么降，哪里下载？

**Comment by 88425255** [comment]
谢谢tang，真的如你所说，这几天一直都是开放。
真是新版本问题。

**Comment by 88425255** [comment]
3.15版本.好用

**Comment by sadoneli** [comment]
应该还是ss-libev的问题，merlin这边无解
