### ISSUE TITLE
可否开发功能让BT强制不走SS？

### ISSUE THREAD

**Issue by whjiang** [koolshare/koolshare.github.io#324]
我的SS是配置成大陆白名单，但有几次BT下载时都碰到蜜罐，VPS收到了好莱坞的告警信，把VPS封了。

有没办法配置强制BT不走SS？

**Comment by sadoneli** [comment]
试试大陆白名单的端口不用all，只用80,443之类的

2017-05-05 9:23 GMT+08:00 Weihua Jiang <notifications@github.com>:

**Comment by sadoneli** [comment]
![image](https://cloud.githubusercontent.com/assets/10495520/25731013/ee876e96-3174-11e7-88ca-5be829a19063.png)
这里手动填写

**Comment by LevineWoo** [comment]
> ![image](https://cloud.githubusercontent.com/assets/10495520/25731013/ee876e96-3174-11e7-88ca-5be829a19063.png)
> 这里手动填写: 80,443

试过了，没用，我只填了80不行， 选的gfwlist也是不行。
