### ISSUE TITLE
能不能解决一下3.3.9 V2 PD问题？

### ISSUE THREAD

**Issue by lingaoyi** [koolshare/koolshare.github.io#326]
我已经降级到3.1.3来用游戏V2，这个版本真的好稳定，但除了这个版本，3.1.3以上都会PD，但现在我的问题是3.1.3版本用不了自定义一些网站全局不走代理，只有3.1.5以上版本才有，能不能解决这个问题？

**Comment by sadoneli** [comment]
不能重现
如果有开启下列之一，请关闭
1 qos
2 openvpn

**Comment by lingaoyi** [comment]
@sadoneli 这些一直都没用过啊，那里有开启，我汗！
