### ISSUE TITLE
Youtube视频观看缓冲码率速度在游戏模式下差距巨大

### ISSUE THREAD

**Issue by Easy-Sir** [koolshare/koolshare.github.io#329]
在观看Youtube的时候，同一服务器，在所有设置保持一致的情况下，使用大陆白名单或者gfwlist模式Youtube视频缓冲码率能达到20000+，而一旦切换成游戏模式就仿佛被限速了一般，只有5000左右，更新了好几个版本这个现象依然存在，就算更换服务器，更换解析方式，更换DNS，也还是会有这样的现象，目前只测试了Youtube，不知道其他视频网站是否也是这样，这种情况造成一旦我要玩游戏了， 就得去服务器界面切模式，我想看视频了，为了获取最佳的速度，又得去后台把模式从游戏模式改回来到gfwlist或者大陆白名单模式，十分麻烦，望解决

**Comment by sadoneli** [comment]
1 游戏模式下看youtube速度慢是因为视频走了quic协议，quic协议是基于udp的，而这个协议在chrome较新的浏览器中是默认开启的。所以游戏模式下看youtube的快慢和你的udp速度又关。

2 解决你来回切换模式的方法就是使用merlin ss插件的访问控制功能，可以针对不同的主机做不同的ss方案，但是如果的需要都在一台主机上的话，那就关掉quic吧

**Comment by Easy-Sir** [comment]
OK 感谢解答😃
