### ISSUE TITLE
开启侧边栏入口不起作用了

### ISSUE THREAD

**Issue by svmmer** [koolshare/koolshare.github.io#330]
请确认，测试了n次！

**Comment by yyxida** [comment]
今天重新刷了机，确认是新版本下打不开，可以老版本开了再升上来

**Comment by sadoneli** [comment]
报告问题请说明机型，刷机版本，刷机流程

**Comment by yyxida** [comment]
机型：ac66u b1（硬件b2）
固件版本：小宝改版7.4
刷机流程：网页恢复模式（cfe mini web），清除VN RAM后刷入

**Comment by sadoneli** [comment]
不起作用的意思是点击软件中心进入后是空白的吗？

**Comment by yyxida** [comment]
开启ss的侧边显示后，主页的侧边（软件中心图标的上方）没有ss的快捷键，查看日志也发现少了开启ss快捷的报告。

**Comment by sadoneli** [comment]
请在ss附加设置里开启侧边栏入口

**Comment by yyxida** [comment]
开启了，但是没有作用。
