### ISSUE TITLE
SSR 加密方式添加 none

### ISSUE THREAD

**Issue by xlsdg** [koolshare/koolshare.github.io#331]
希望选择 auth_chain_a 协议的时候，加密方式可以选择 none。

**Comment by yezongming** [comment]
这个很有必要，希望下一次更新能加入。

**Comment by alexlabs** [comment]
今天也遇到这问题了 不是简单的把webs/Main_SS_Content.asp 里的加密方法改为none就可以的 好像库得支持？希望SS更新能解决这个问题 现在没法通过路由器翻墙了

**Comment by sadoneli** [comment]
暂无跟进计划
