### ISSUE TITLE
[ss3.4.3]web测试全部失效

### ISSUE THREAD

**Issue by iamggs** [koolshare/koolshare.github.io#332]
前几个版本就存在了，一直未修复：
shadowsocks--节点管理--web测试，全部failed，ping正常，望修复。

![spximage1](https://cloud.githubusercontent.com/assets/22816124/26518567/77bbe788-42e5-11e7-8d83-322cebad3ae1.jpg)

**Comment by sadoneli** [comment]
一些sdk7的 X7.4机型，例如7.4的AC5300会出现这个问题，因为固件自带的libssl出了问题，导致curl无法获取到正常数据，ss本身没有问题

**Comment by iamggs** [comment]
环境是AC68u+x7.4，以前的版本（具体从那个版本的ss开始有这Bug的没注意）不会有这个毛病啊。
