### ISSUE TITLE
Shadowsocks 3.4.3 Web Bug

### ISSUE THREAD

**Issue by AnyoeDove** [koolshare/koolshare.github.io#333]
![bug](https://cloud.githubusercontent.com/assets/10519576/26519010/81eb286a-42ed-11e7-8ed4-56bb35682272.png)

and please remove the useless webtest and ping

div id="vpnc_settings"  class="contentM_qis" margin-top should be -170px because -65px is way to low.

**Comment by sadoneli** [comment]
1 to be fixed
2 maybe webtest and ping is useless to you, but not under my concern to remove it.
3 -65px works fine for me, please tell me your environment.
![image](https://cloud.githubusercontent.com/assets/10495520/26519584/552d809e-42f6-11e7-87f1-e4c8db663a69.png)

**Comment by AnyoeDove** [comment]
1 i tested again and the obfs only not showing on ssr+ss_node_table_mode=3
2 webtest and ping is the cause for another page error like http://koolshare.cn/thread-43621-1-1.html
3 laptop 1366x768
![snipaste20170527_162635](https://cloud.githubusercontent.com/assets/10519576/26519828/bead69dc-42f9-11e7-916b-ab02967e8ee5.png)

**Comment by sadoneli** [comment]
1 yes I will fix that
2 I don't see any related error causing by webtest and ping
3 I think I‘am going to make vpnc_setting panel fixed to the page, not the browser to solve your issue

**Comment by AnyoeDove** [comment]
1 ok~thx
2 ok, but i dont want to test again.....
3 thx~

**Comment by sadoneli** [comment]
2 just leve it there,don't use it.
