### ISSUE TITLE
gfwlist 模式下， 所有流量都走的ss

### ISSUE THREAD

**Issue by flypiggy** [koolshare/koolshare.github.io#339]
国内优先， 3.4.9

**Comment by sadoneli** [comment]
你好，无法重现你的问题，请提供详细设置和测试所有流量都走ss的方法。

**Comment by sadoneli** [comment]
另外，可以访问ip111.cn，看是否分流正常

**Comment by flypiggy** [comment]
应该是某些遗留选项造成的.格式化了 jffs 重新设置一遍就好了..之前的配置文件忘记导出了..

**Comment by Bladeindark** [comment]
Hi, 我也碰到了同样的问题，请问你是如何解决的？能否给出具体步骤

**Comment by flypiggy** [comment]
清空SS 配置. 并且不要备份, 重新设置...
导出的配置文件里面有很多脏数据. 我懒得去排查具体原因了重新设置一遍就好了...
