### ISSUE TITLE
gfwlist模式出现问题

### ISSUE THREAD

**Issue by Bladeindark** [koolshare/koolshare.github.io#340]
所有的流量——不分国内国外，统统走自己部署的VPN服务器了，导致网速非常慢，测了网速之后发现外部IP是米国。固件版本：380.59_X6.6.1，R7000；SS版本3.4.9

**Comment by sadoneli** [comment]
无法重复此问题
请尝试
1 升级到最新固件
2 格式化jffs分区，配置全部重新手动配置

**Comment by sadoneli** [comment]
https://github.com/koolshare/koolshare.github.io/blob/acelan_softcenter_ui/shadowsocks/Changelog.txt#L264
另外最新SS不支持 6.6.1固件，从3.1.6版本就开始了
