### ISSUE TITLE
添加访问控制主机iptables报错：unknown option "-j"

### ISSUE THREAD

**Issue by sincerywaing** [koolshare/koolshare.github.io#341]
2017年06月10日 23:33:20: 清除重复的ip rule规则.
2017年06月10日 23:33:20: 删除ip route规则.
2017年06月10日 23:33:20: 创建ipset名单
2017年06月10日 23:33:21: 写入iptables规则到nat表中...
2017年06月10日 23:33:21: 加载ACL规则：192.168.3.201:all模式为：不通过SS
2017年06月10日 23:33:21: 加载ACL规则：192.168.3.200:all模式为：gfwlist模式
2017年06月10日 23:33:21: 加载ACL规则：其余主机模式为：
iptables v1.4.14: unknown option "-j"
Try `iptables -h' or 'iptables --help' for more information.
2017年06月10日 23:33:21: 开启chromecast功能（DNS劫持功能）
2017年06月10日 23:33:21: 重启dnsmasq服务...
2017年06月10日 23:33:23: ------------------------- shadowsocks 启动完毕 -------------------------
2017年06月10日 23:33:23:
2017年06月10日 23:33:23: Enjoy surfing internet without Great Fire Wall!
2017年06月10日 23:33:23:
2017年06月10日 23:33:23: =============== 梅林固件 - shadowsocks by sadoneli&Xiaobao ===============

**Comment by sadoneli** [comment]
运行dbus list ss_acl，贴出你的运行结果

**Comment by sincerywaing** [comment]
ss_acl_default_mode=
ss_acl_default_port=all
ss_acl_ip_1=192.168.3.200
ss_acl_mode=1
ss_acl_mode_1=5
ss_acl_name_1=FireStick
ss_acl_port=80,443
ss_acl_port_1=all

**Comment by sincerywaing** [comment]
而且现在这个版本好像经常双working但是无法上google。

感觉是与7.5的兼容性问题，7.4没有这个情况。

**Comment by sadoneli** [comment]
运行
dbus set ss_acl_default_mode=2
可以把默认规则设置为大路白名单模式

和7.5应该没多大关系，如果有，我正在找

**Comment by sincerywaing** [comment]
谢谢S大！

我有两个ip，一个不走ss，一个全走ss，剩下的走gfwlist，应该怎么设置？

这样一改不是默认变成大陆白名单了吗？

**Comment by sadoneli** [comment]
ss模式切换成gfwlist模式，提交
进入访问控制添加你要走的ip的行为即可

**Comment by sincerywaing** [comment]
我现在这么配置，ss就完全不工作了。

**Comment by sincerywaing** [comment]
必须把那两个特别的host去掉，然后这个-j的报错才消失，然后要重启ss才可以工作。

**Comment by sadoneli** [comment]
因为你的ss_acl_default_mode值是空的，而其余主机是读取的这里，所以导致这个问题
如果不嫌麻烦，建议你清空ss配置重新手动配置下，这样会好很多

**Comment by sincerywaing** [comment]
谢谢S大

知道为什么了

我之前一次清空后在什么都没有配置的情况下不小心点了一次提交，应该就是这个造成的，你可以看看。
