### ISSUE TITLE
无法开启负载均衡

### ISSUE THREAD

**Issue by wb1992321** [koolshare/koolshare.github.io#343]
AC88U在x7.4上ss一切正常！
但是直接升级x7.5发现负载均衡无法打开，ss版本v3.5.5
## 操作步骤
- 系统管理-->固件升级 直接上传升级，成功升级
- 依照论坛描述 回复出厂设置，并且为了防止意外将插件分区格式化，完成基本设置，温度显示正常
- 下载ss插件  状态显示等待超时  但是刷新发现已经安装；
- 进入ss页面进行基本配置和验证，可以正常代理上网！
- 进入负载均衡页面，打开开关按钮  发现无法添加节点到下面的列表中，选项卡也是空的！
- 卸载ss  重新安装，利用ssh登录进行安装其他版本依然无法开启负载均衡！情况与上面相同！

**Comment by sadoneli** [comment]
下载ss插件 状态显示等待超时 但是刷新发现已经安装；
这里可能会出问题，导致安装不全，建议卸载ss重装，或者使用离线安装

**Comment by wb1992321** [comment]
刚才试了一下又可以开启了！但是实际效果如何需要晚上回去测试一下，目测正常！
至于那个离线安装我试了，我表示无法离线安装，下面那个菊花一直在转就是等不到成功，放在那里等了几乎一个小时！

**Comment by wb1992321** [comment]
这个可以关闭了，刚开始安装无法开启，过一天又可以了！测试正常！
但是还是有一个负载均衡自己的关于session问题：session无法关闭自动清除！
