### ISSUE TITLE
最近访问YOUTUBE的时候会提示We're sorry...

### ISSUE THREAD

**Issue by SunZhizhong** [koolshare/koolshare.github.io#345]
We're sorry...

... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.

我用的是none+auth_chain_a的协议。
但是用WIN版的SSR没有这个问题，访问其他翻墙的网站没有问题，这个问题从昨天开始出现，昨天是打开YOUTUBE的网站会提示，但是过一段时间就好了，今天是打开YOUTUBE网站可以，但是点击连接后就会直接跳转到We're sorry...，我无法判断是升级了最新版本的SS的问题，还是更新了固件7.5的问题，我换了两条线路都是这个提示，有没有人和我出现同样的状况？

好吧，不光是YOUTUBE会出现这个问题……
补充：只在Chrome浏览器才会出问题，并且清空重置之后依然不行，我在想原因为何。
补充：更新了杀毒软件并且扫描不到任何病毒的情况下依然会提示。

**Comment by satifanie** [comment]
我也出现聊。似乎是从升级了59 或者 升级了7.5？或者升级了 插件。 能想到的就这些了

**Comment by satifanie** [comment]
试一下把Chrome的Dont send track 开了 我 现在没有了，不知道是不是这个原因

**Comment by SunZhizhong** [comment]
不行，依然会出现提示，感觉是哪里的联动有问题，我晚上看看重新搞一下VPS。

**Comment by bingall** [comment]
呃，不幸我也出现了。应该是3.5.5的问题，前一个版本还没有这个问题。

**Comment by SunZhizhong** [comment]
我退回3.5.4好像确实没这问题了……正在测试……

**Comment by sharkman2008cn** [comment]
我的也出现相同问题，重启路由器，没有了！

2017年6月16日 00:45，"bingall" <notifications@github.com>写道：

**Comment by sharkman2008cn** [comment]
很不幸的是，刚才试了下，油管子网站直接打不开，手机移动端测试

2017年6月16日 07:02，"hy c" <sharkman2008cn@gmail.com>写道：

**Comment by sharkman2008cn** [comment]
又在电脑端测试，直接打不开了，google访问正常，这是被劫持的节奏吗？

在 2017年6月16日 上午7:06，hy c <sharkman2008cn@gmail.com>写道：

**Comment by sharkman2008cn** [comment]
在客户端不在路由器上ss，相同vps，访问you正常！

在 2017年6月16日 上午8:16，hy c <sharkman2008cn@gmail.com>写道：

**Comment by falian** [comment]
好吧，我也遇到这样的问题...google打开正常，就是YouTube会这样提示，手机连路由器也会无法播放内容

**Comment by satifanie** [comment]
@bingall @SunZhizhong @sharkman2008cn @falian @wangchll  关闭 QUIC试试  具体为： chrome://flags  搜索QUIC 然后，disable 试试

**Comment by SunZhizhong** [comment]
我一直都是关闭状态，应该不是这里的问题。而且昨天不好，今天就好了。

**Comment by Zhang-Siyang** [comment]
同出现

**Comment by Zhang-Siyang** [comment]
@satifanie Chrome关闭QUIC后能正常访问Youtube

**Comment by bingall** [comment]
回滚到3.5.3，问题不在了。但是貌似速度依旧很慢。

**Comment by zhcntiangang** [comment]
我尝试过更改QUIC无效  也降过路由器SS版本同样无效 升级固件至7.5 同样无效  SS服务器（多个HK和US）测试大部份HK不可用  US无问题

**Comment by SunZhizhong** [comment]
我的两个都是是洛杉矶，一样问题，我不管是降级还是升级版本都会出现的问题，但是第二天就好了，如果一定要说的话，我的这个现象多集中在16号前后，就是说这个问题并不单单是路由器问题，难道是长城因为什么原因升级了？

**Comment by jbxkuang** [comment]
亲测Chrome(59)在关闭QUIC后能正常访问Youtube

**Comment by MakersAll8** [comment]
关闭QUIC后点Relaunch，重新打开以后又可以正常看了。

**Comment by zhuchiheng** [comment]
啥也没动自己好了，为了安全还是关闭了QUIC

**Comment by VNY0920** [comment]
3.5.5没处理好Chrome的QUIC功能。
其他浏览器、iPhone里的油管app都正常。
坚持用Chrome的话，chrome://flags 搜索QUIC 然后disable就好了。
