### ISSUE TITLE
请问一下这个ss-libev 3.0.6为什么只有208k？

### ISSUE THREAD

**Issue by qq57240** [koolshare/koolshare.github.io#350]
我用upx解开后也只有500来k，而且这是全静态库编译的，有点厉害，用了什么黑科技呢？
还有，我自行编译出的ss-libev 3.0.6（非全静态编译，libpcre-8.40，libsoduim-1.0.12，libev-4.2.4，mbedtls-2.4.2，udns-0.40以上为静态库）
编译器是arm-linux-uclibcgnueabi-xxx
gcc版本：
Thread model: posix
gcc version 4.8.2 20130603 (prerelease) (crosstool-NG 1.19.0) 

编译一切正常，但运行时总是限制在30mbps，而你的ss-libev 3.0.6却能有50mbps以上

请教原因，望能告知，非常感激！

**Comment by sadoneli** [comment]
工具链是我自己从buildroot编译的，全静态编译完成后编译后先strip再upx的：
```shell
全静态编译完成后：
893K  ss-local
395K  ss-manager
864K  ss-redir
951K  ss-server
780K  ss-tunnel

strip后
523K  ss-local
211K  ss-manager
514K  ss-redir
549K  ss-server
452K  ss-tunnel

upx压缩后
211K  ss-local
87K  ss-manager
208K  ss-redir
220K ss-server
184K ss-tunnel

ss-local:   ELF 32-bit LSB executable, ARM, EABI5 version 1 (GNU/Linux), statically linked, stripped
ss-manager: ELF 32-bit LSB executable, ARM, EABI5 version 1 (GNU/Linux), statically linked, stripped
ss-redir:   ELF 32-bit LSB executable, ARM, EABI5 version 1 (GNU/Linux), statically linked, stripped
ss-server:  ELF 32-bit LSB executable, ARM, EABI5 version 1 (GNU/Linux), statically linked, stripped
ss-tunnel:  ELF 32-bit LSB executable, ARM, EABI5 version 1 (GNU/Linux), statically linked, stripped
```

gcc version 5.4.0 (Buildroot 2017.05-rc2)
组件：
libev-4.24
libsodium-1.0.11
libudns-0.4
mbedtls-2.4.0
pcre-8.39

**Comment by qq57240** [comment]
@sadoneli 
十分感谢S大的解答，经过你给的库和我所用库的对比，问题原因找到了，是因为mbedtls这个库的2.4.2版本引发的。换成你给出的2.4.0就没问题了，播放youtube速度终于正常了。

**Comment by sadoneli** [comment]
good~
