### ISSUE TITLE
Dns2sock自定义DNS时会因输入法而产生问题

### ISSUE THREAD

**Issue by Easy-Sir** [koolshare/koolshare.github.io#351]
在使用dns2socks设置自定义DNS时，如果使用者使用的是中文输入法，填写DNS和端口，然后连接，会造成连接失败
![default](https://user-images.githubusercontent.com/23088231/27514932-ce7cca82-59ca-11e7-9c2c-f17425633177.png)
例如这样（本人用的是搜狗输入法）
如果将输入法切换到英文，输入后就可以正常连接，
![default](https://user-images.githubusercontent.com/23088231/27514947-2f3a1d02-59cb-11e7-9edb-32c08ae0312a.png)
分辨两种状态需要看区分端口的“：”符号，中文模式和英文模式仅仅是在符号间隔上有微小差异，要仔细看才能看出来，英文模式打出来的是这样的“:”，中文模式是这样的“："之前被这个符号坑了，以为SS服务器坏了，希望能改进一下，添加一个提示或者检测什么的

**Comment by Easy-Sir** [comment]
使用SS tunnel自定义DNS时应该是一样的道理 ，我还没测试过

**Comment by sadoneli** [comment]
输入端口或者mac之类的冒号都需要用英文输入法这个是基本常识
或许我可以把字体换下，这样会显得更为明显点？

**Comment by Easy-Sir** [comment]
嗯嗯，主要是区别实在是太小了，有时候根本没注意到自己打错了符号
