### ISSUE TITLE
SS是否可以加入一个测速功能？

### ISSUE THREAD

**Issue by wb1992321** [koolshare/koolshare.github.io#353]
## 版本 x7.5
目前那个网络测速插件我就没有测速成功过一次！所以希望能够有一个测速的工具！
另外对于ss代理希望能够知道目前的国外的访问带宽极限

**Comment by iamggs** [comment]
AC68U+x7.4也不能用测速，之前我反映过。 
见：
https://github.com/koolshare/koolshare.github.io/issues/332

**Comment by sadoneli** [comment]
ss插件节点页面带测速功能的，另外在X7.4版本部分机型因为编译的原因导致没有libssl，所以测试不能正常工作，请升级最新固件安装ss插件后尝试
