### ISSUE TITLE
R6400 Firmware:380.65_X7.4 黑白名单无效

### ISSUE THREAD

**Issue by hnsxxscyx** [koolshare/koolshare.github.io#354]
本人路由上gfw不能正常翻墙，大陆白名单模式翻成功但淘宝为海外、b站为海外、什么值得买也为海外（目前发现），百度正常为大陆ip。
gfw和大陆白名单模式下设置黑白名单域名ip均无效，望修复

**Comment by hnsxxscyx** [comment]
已清空分区重新安装测试，黑白名单还是不能用，忘大大抽空关注一下

**Comment by sadoneli** [comment]
无法重现

**Comment by yuyuks** [comment]
WAN設置裡運營商DNS設置為國內DNS伺服器，重啟一下計算機和路由

**Comment by gtihubAlimjan** [comment]
ss都被下架了

**Comment by gtihubAlimjan** [comment]
反正我吧整个远嘛下载下来了。哈哈。自己手动安装维护了
