### ISSUE TITLE
新版本koolproxy和ss无法过滤墙外广告问题

### ISSUE THREAD

**Issue by LukeTu119** [koolshare/koolshare.github.io#356]
在新版本koolproxy和ss下 是可以过滤墙外网站广告的 然而重启路由器之后 墙外过滤广告会失效 再次重启ss之后问题会解决 希望能修复一下这个问题

**Comment by iamggs** [comment]
放弃KoolProxy吧，机制注定了用它毙大于利。

**Comment by iamggs** [comment]
放弃KoolProxy吧，机制注定了用它弊大于利。

**Comment by sadoneli** [comment]
试试最新的kp和ss，应该修复了这个问题
