### ISSUE TITLE
3.5.7在重啟路由器後無法正常啟動，國外PD

### ISSUE THREAD

**Issue by yuyuks** [koolshare/koolshare.github.io#358]
3.5.7在重啟路由器後無法正常啟動，國外PD，需要手動點一次提交，或者將開關關閉再打開然後提交才可運行。

**Comment by sadoneli** [comment]
请尝试设置ss开机延迟

**Comment by yuyuks** [comment]
延遲60s之後顯示working了。但其實沒在工作，所有連接都未通過ss

**Comment by yuyuks** [comment]
問題解決了，卸載重裝了...

**Comment by yuyuks** [comment]
問題解決了，回到了3.5.5

**Comment by JeffreyFish** [comment]
同样问题，AC66U B1，固件是7.5，ss是最新的3.5.8，为了这个问题，还专门重刷了固件，刷前后都恢复原厂设置，问题还在。也设置了开机延迟60s，但同样重启路由之后一直PD，只有手动提交一次之后，才会连成功，显示working。。。。之前固件7.4和它自带那个版本的ss并没有这个问题。

**Comment by Skyepose** [comment]
我也遇上了这个问题，3.5.8无法正常开机启动。但是之前版本可以，没有问题。

**Comment by yuyuks** [comment]
@sadoneli 請求關注一下這個問題，感謝。
