### ISSUE TITLE
ACL主模式设为游戏模式时，UDP排除问题

### ISSUE THREAD

**Issue by gy6221** [koolshare/koolshare.github.io#359]
主模式设为游戏模式，并且有内网设备被指定为不经过ss或者大陆白名单模式时，未在mangle表中把对应源ip的udp包return掉

**Comment by gy6221** [comment]
感谢修复，不过看了一下脚本实现，我觉得模式5(全局代理)的udp还是应该走ss的

**Comment by sadoneli** [comment]
主模式为游戏模式，设置某个主机为全局模式，她的UDP会被return啊

**Comment by gy6221** [comment]
全局ss不是应该包括tcp和udp吗？还是说这是我的理解出现了偏差？

**Comment by sadoneli** [comment]
全局ss并不包含udp，当udp全局走ss的时候，会出现很多问题的
