### ISSUE TITLE
ss 1.2.9 大陆白名单模式bug

### ISSUE THREAD

**Issue by royzheng** [koolshare/koolshare.github.io#36]
切换到大陆白名单的时候，
自定义dnsmasq 选项
如果比如填写多行
address=/xildiere.com/127.0.0.1
address=/gclick.cn/127.0.0.1
的情况下 submit完之后所有ss的配置全部丢失 估计是update的时候换行之类引起的

**Comment by royzheng** [comment]
@jannson 能不能给个临时解决方案 比如我想在大陆白名单模式下添加自定义hosts的情况 直接ssh上去改那个文件？

**Comment by royzheng** [comment]
已摸索出解决方法了 直接多行之间别换行 用逗号隔开就可以了
应该就是web显示跟提交的时候没做一些转换 我是从GFWLIST模式提交的时候看到值变成逗号分隔得到的灵感 希望下个版本有机会修正

**Comment by lingaoyi** [comment]
确实啊，整个表变成乱的界面，两个host设置就会导致乱的。
