### ISSUE TITLE
 问题求助

### ISSUE THREAD

**Issue by wgnmzgj** [koolshare/koolshare.github.io#361]
mips 安装ss3.0.4时候 使用命令安装提示 提示没有SS/DNS目录文件夹
华硕 AC66U

**Comment by wgnmzgj** [comment]
admin@RT-AC66U:/tmp/shadowsocks# sh install.sh 
chmod: /koolshare/ss/dns/*: No such file or directory
-sh: getcwd: No such file or directory

**Comment by sadoneli** [comment]
怀疑你装错了包

**Comment by wgnmzgj** [comment]
AC66U 我下的是   mips的
这个地址 
https://raw.githubusercontent.com/koolshare/koolshare.github.io/master/shadowsocks_mips/shadowsocks.tar.gz

**Comment by sadoneli** [comment]
别下这个，下mips分支那个

_Sent from my OnePlus ONEPLUS A5000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by wgnmzgj** [comment]
是啊 3.0.4那个版本吧，路由器自己更新也只能更新到3.0.2

**Comment by wgnmzgj** [comment]
看到了谢谢

**Comment by ken-yu-masters** [comment]
下面的地址不存在了
 https://raw.githubusercontent.com/koolshare/koolshare.github.io/master/shadowsocks_mips/shadowsocks.tar.gz

还有mips的shadowsocks 吗？
谢了
