### ISSUE TITLE
SS 3.58国外PD

### ISSUE THREAD

**Issue by ubridge** [koolshare/koolshare.github.io#364]
netgear R7000
3.80.63_x7.2,
software center 1.33
SS 3.57升级到3.58，国外PD，卸载重装SS问题依旧

**Comment by sadoneli** [comment]
无法重现，请检查密码是否乱码等
或者提供详细的运行状态和日志

**Comment by ubridge** [comment]
![img_0169](https://user-images.githubusercontent.com/29905573/27847348-a923f998-616f-11e7-812e-b54b7aa961cc.PNG)
![img_0173](https://user-images.githubusercontent.com/29905573/27847349-a96be6a4-616f-11e7-8ce9-c1e625bd061d.PNG)

日志没什么有价值信息

**Comment by sadoneli** [comment]
你这iptables规则没加载啊，估计是tmp里的locker文件没清除导致的，重启下路由应该就行了吧

**Comment by ubridge** [comment]
试试，谢谢！
