### ISSUE TITLE
R6300V2 SS假死问题较为严重

### ISSUE THREAD

**Issue by Easy-Sir** [koolshare/koolshare.github.io#366]
配置好SS之后点击重启，SS状态会开始刷新，刷新到某个状态时（不固定）就假死了，192.168.1.1就再也进不去了，必须要重启路由器，然而就算重启了路由器，当再次需要开启或者重启SS的时候这个情况又会发生，及其烦人，有一次甚至连续发生四次，这里附上CPU温度图，不知道是不是因为天气热了导致路由器卡顿（可能性较小）
![tim 20170707175746](https://user-images.githubusercontent.com/23088231/27953623-0c333654-633f-11e7-8253-5740316ec665.png)
这种情况下让人尴尬的是路由器和SS其实在正常运行，然而SS假死之后就再也进不去192.168.1.1了。

**Comment by Easy-Sir** [comment]
补充：运行模式是游戏模式
开启SSR

**Comment by Easy-Sir** [comment]
卸载koolproxy插件后居然正常了，虽然可能性不大，但是您可以去看看是不是这个原因

**Comment by Randy000** [comment]
@Easy-Sir 感谢分享。我的也是这个情况。我关闭koolproxy后就恢复正常了。Firmware:380.65_X7.4 SS:3.5.8
koolproxy的只开了视频规则。

**Comment by sadoneli** [comment]
尝试关闭固件自带QOS试试

**Comment by Easy-Sir** [comment]
@Randy000 嗯嗯，最近每次更改ss都先手动关掉koolproxy，到现在就再也没发生过假死了

**Comment by Easy-Sir** [comment]
@sadoneli 如果你说的是主页侧边栏上面的那个QOS，那么QOS全部是关闭的

**Comment by Randy000** [comment]
@Easy-Sir 我的啥也没干。看到淘宝跳转日本站。然后我想重置下DNS设置。然而我连路由器管理页面也登不上。最后。我把koolproxy广告过滤插件卸载了。--|||

**Comment by Easy-Sir** [comment]
@Randy000 我就是这个问题😂假死后死活上不去管理界面
