### ISSUE TITLE
3.5.8在路由重启后无法自动成功连上

### ISSUE THREAD

**Issue by JeffreyFish** [koolshare/koolshare.github.io#367]
AC66U B1，固件是7.5，ss是3.5.8，路由重启后ss无法自动地成功连上，一直国外PD。只有手动点提交按钮，才能成功连上显示working。已经换过各种线路的ss，问题依旧。甚至重刷了固件，刷前后都恢复出厂设置，也是问题依旧。也设置了开机延迟60s，问题也依旧。

**Comment by JeffreyFish** [comment]
也设置了开机延迟60s，问题也依旧。

**Comment by yuyuks** [comment]
我也一樣，換回3.5.5就好了。

**Comment by JeffreyFish** [comment]
@yuyuks 怎样换回低版本？

**Comment by yuyuks** [comment]
首先在軟體中心卸載ss
然後系統設置開啟ssh登錄並使用xshell等工具登錄到路由器
cd /tmp
wget --no-check-certificate https://raw.githubusercontent.com/koolshare/koolshare.github.io/acelan_softcenter_ui/shadowsocks/history/shadowsocks_3.5.5.tar.gz
tar -zxvf /tmp/shadowsocks_3.5.5.tar.gz
chmod +x /tmp/shadowsocks/install.sh
sh /tmp/shadowsocks/install.sh

**Comment by JeffreyFish** [comment]
@yuyuks 好的谢谢哈

**Comment by zaybajlhqwb** [comment]
一样的问题，能否更新一下3.5.9

**Comment by sadoneli** [comment]
请贴上详细状态

**Comment by Jack223** [comment]
@yuyuks 怎么离线安装老版本ss，只用软件中心离线上传并安装，但没有反应啊

**Comment by sadoneli** [comment]
请更新最新的koolproxy插件试试，我想这个问题已经修好了

**Comment by yuyuks** [comment]
@Jack223 ssh登入之後用命令行，不過現在已經更新了，最新版大概已經解決了問題
