### ISSUE TITLE
3.5.8之后，无法连接路由器后台，是不是跟KP还是软件中心冲突

### ISSUE THREAD

**Issue by Jack223** [koolshare/koolshare.github.io#368]
求更新，或者谁有3.5.7

**Comment by Jack223** [comment]
连不上路由器很麻烦，请大神能帮帮忙

**Comment by sadoneli** [comment]
请贴上日志和详细状态

**Comment by sadoneli** [comment]
可能是locker导致nat加载不完整导致的，尝试重启路由器看是否能解决

**Comment by Jack223** [comment]
感谢你的答复。重启路由器都试过，现在的问题是更新了3.5.8之后，连接路由器后台的地址连不上，就类似于一个网页打不开似的，群里其他人也有这个问题，我排查过，最新的ss安装之后就连不上后台

**Comment by sadoneli** [comment]
1 固件版本多少
2 更新到3.5.8后，重启路由后是否能打开
3 是否开了qos等
4 能否贴上日志（系统日志和ss日志）

**Comment by Jack223** [comment]
7.5的固件，R7000，插件只有KP和ss，升级之前一切正常，升级之后一开始是必须切换到游戏模式，再切换到gf模式，gf模式才能正常工作。我记得升级过程中就跟后台发生断链，重启不能保证可以连上，重试几次可能偶尔连接上

**Comment by Jack223** [comment]
我看koolshare论坛，r6900,8500都有这个问题。

**Comment by Jack223** [comment]
后台登陆不上，但是内网，外网一切都好用

**Comment by sadoneli** [comment]
问题是出在升级后，并不是重启路由器？

**Comment by Jack223** [comment]
昨天我某一次登录到后台， 格式化JFFS后，只安装KP（因为是家人需要），后台登陆尝试多次均无问题。但再安装3.5.8后，后台地址就又打不开了，只能多次重启路由器，找机会登陆后台

**Comment by qiuqiuuuu** [comment]
我也遇到。装了最新kp和ss。每次重启完会进不去路由器。还好我路由器上开了pptpvpnserver，从vpn进去，去开关一下kp就能进路由了。。。。

**Comment by Jack223** [comment]
大神还在吗？
今天测试，ss和kp单独安装都能完美使用，一起最新版就登陆不了后台，求帮忙

**Comment by sadoneli** [comment]
@Jack223 你加telegram群找我，我给你远程看看

**Comment by Jack223** [comment]
大神啊，我手机电报都下载好了，可在ss上点加入电报，join group没反应啊
168061068我的qq，谢谢了

**Comment by yuyuks** [comment]
@Jack223 請不要在該討論串留QQ

**Comment by Jack223** [comment]
@sadoneli 手机下了电报，在ss点join group电脑没反应

**Comment by sadoneli** [comment]
更新最新koolproxy试试，我想应该已经修好了这个问题
这个问题不是ss的锅，是koolproxy的问题，所以需要更新koolproxy插件
详情请见软件中心的通知

**Comment by lingaoyi** [comment]
我好像也遇到过，但没安装koolproxy啊。
