### ISSUE TITLE
报告gfwlist模式下youtube和google drive有点问题

### ISSUE THREAD

**Issue by qiuqiuuuu** [koolshare/koolshare.github.io#369]
我的ss在美国，chrome没关quic
gfwlist模式看youtube有时会碰到国家限制(比如sky news live直播)，改游戏模式就可看了，目测是udp的锅。
另外gfwlist模式下goovle drive上传只有500k/s，换游戏模式可以跑到2m/s几乎跑满我的上传带宽，应该也是udp的锅吧。
现在麻烦的是gfwlist不正常，googledrive需要udp，游戏模式开迅雷又不方便，希望能改进gfwlist模式

**Comment by sadoneli** [comment]
需要udp请使用游戏模式，本插件gfwlist模式不打算udp
