### ISSUE TITLE
关于SS+Kcptun启用负载均衡的问题故障

### ISSUE THREAD

**Issue by huxuansong** [koolshare/koolshare.github.io#370]
你好，已经更新到最新版本，
并且已经配置好所有SS结点，

1.如果不勾选Kcptun加速，则负载均衡工作正常，
国外连接 - [ 2017-07-12 07:25:04 ] working... 
国内连接 - [ 2017-07-12 07:25:04 ] working...

2.如果不启用负载均衡，勾选KCPtun加速，则SS工作正常，
国外连接 - [ 2017-07-12 22:35:21 ] working... 
国内连接 - [ 2017-07-12 22:35:21 ] working...

3.如果勾选Kcptun之后，则负载均衡工作不正常
国外连接 - [ 2017-07-12 07:27:36 ] Problem detected! 

百度搜索发现有人勾选Kcptun有成功的案例，不过貌似是SSR，请问是什么问题？配置有误还是SS不支持？

**Comment by qiuqiuuuu** [comment]
开一点swap看看

**Comment by huxuansong** [comment]
LZ的可以负载均衡和KCPtun同时启用吗

**Comment by sadoneli** [comment]
目前kcp和负载均衡还是不建议一起用
1 传统用法，则会导致kcptun多开，kcptun开一个路由已经很着急了，多开就更受不了
2 kcp节点加普通节点负载均衡，实测可用，但是意义不大，因为kcp故障断开后不能自动切换到普通节点

综上，不建议kcp和负载均衡一起使用
