### ISSUE TITLE
游戏模式 ssr+ss-tunnel 容易PD

### ISSUE THREAD

**Issue by lingaoyi** [koolshare/koolshare.github.io#371]
用了半天就突然PD，已经试了好几次。

SS版本：3.5.8

ssr
游戏模式

chacha20
auth_aes128_sha1
http_simple

选择国内DNS：
114.114.114.114

国外DNS：
ss-tunnel 

OpenDNS:
208.67.220.220

① 程序版本（插件版本：3.3.4）：
-----------------------------------------------------------
程序            版本        备注
ss-redir        3.0.7        2017年4月26日
ss-tunnel        3.0.7         2017年4月26日
ss-local        3.0.7        2017年4月26日
obfs-local        0.0.3        2017年3月28日
ssr-redir        2.5.6         with mbed TLS 2.4.0
ssr-tunnel        2.5.6         with mbed TLS 2.4.0
ssr-local        2.5.6         with mbed TLS 2.4.0
client_linux_arm5    20170525    kcptun
haproxy            1.7.5    
dns2socks        V2.0     
dnscrypt-proxy        1.7.0     
ChinaDNS        1.3.2     
pndsd            1.2.9a-par     
Pcap_DNSProxy        0.4.8.1
-----------------------------------------------------------

② 检测当前相关进程工作状态：（你正在使用SSR-libev,选择的模式是【游戏模式】,国外DNS解析方案是：ssr-tunnel）
-----------------------------------------------------------
程序        状态    PID
ssr-redir    工作中    pid：9874
ssr-tunnel    未运行
-----------------------------------------------------------

③ 检测iptbales工作状态：
----------------------------------------------------- nat表 PREROUTING 链 --------------------------------------------------------
Chain PREROUTING (policy ACCEPT 311 packets, 54148 bytes)
 pkts bytes target     prot opt in     out     source               destination         
52633 3322K SHADOWSOCKS  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0           
 2552  144K VSERVER    all  --  *      *       0.0.0.0/0            113.67.166.64       
    0     0 VSERVER    all  --  *      *       0.0.0.0/0            169.254.148.121     
23601 1575K DNAT       udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:53 to:10.0.0.1

----------------------------------------------------- nat表 OUTPUT 链 ------------------------------------------------------------
Chain OUTPUT (policy ACCEPT 57 packets, 3718 bytes)
 pkts bytes target     prot opt in     out     source               destination         
  141  8460 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set router dst redir ports 3333
    0     0 SHADOWSOCKS_EXT  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0xa000000/0xffffff00

----------------------------------------------------- nat表 SHADOWSOCKS 链 --------------------------------------------------------
Chain SHADOWSOCKS (1 references)
 pkts bytes target     prot opt in     out     source               destination         
 8762  522K RETURN     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set white_list dst
 4991  322K SHADOWSOCKS_CHN  tcp  --  *      *       10.0.0.28            0.0.0.0/0           [goto] 
   58  3712 SHADOWSOCKS_CHN  tcp  --  *      *       10.0.0.140           0.0.0.0/0           [goto] 
37780 2418K SHADOWSOCKS_CHN  tcp  --  *      *       10.0.0.224           0.0.0.0/0           [goto] 
    0     0 SHADOWSOCKS_CHN  tcp  --  *      *       10.0.0.213           0.0.0.0/0           [goto] 
 1043 56528 SHADOWSOCKS_GAM  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0           

----------------------------------------------------- nat表 SHADOWSOCKS_EXT 链 --------------------------------------------------------
Chain SHADOWSOCKS_EXT (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 SHADOWSOCKS_CHN  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0           [goto]  mark match 0xa00001c
    0     0 SHADOWSOCKS_CHN  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0           [goto]  mark match 0xa00008c
    0     0 SHADOWSOCKS_CHN  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0           [goto]  mark match 0xa0000e0
    0     0 SHADOWSOCKS_CHN  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0           [goto]  mark match 0xa0000d5
    0     0 SHADOWSOCKS_GAM  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0           

----------------------------------------------------- nat表 SHADOWSOCKS_GFW 链 ----------------------------------------------------
Chain SHADOWSOCKS_GFW (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set black_list dst redir ports 3333
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set gfwlist dst redir ports 3333

----------------------------------------------------- nat表 SHADOWSOCKS_CHN 链 -----------------------------------------------------
Chain SHADOWSOCKS_CHN (8 references)
 pkts bytes target     prot opt in     out     source               destination         
 4079  262K REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set black_list dst redir ports 3333
22760 1460K REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            ! match-set chnroute dst redir ports 3333

----------------------------------------------------- nat表 SHADOWSOCKS_GAM 链 -----------------------------------------------------
Chain SHADOWSOCKS_GAM (2 references)
 pkts bytes target     prot opt in     out     source               destination         
  242 12980 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set black_list dst redir ports 3333
  538 29804 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            ! match-set chnroute dst redir ports 3333

----------------------------------------------------- nat表 SHADOWSOCKS_GLO 链 -----------------------------------------------------
Chain SHADOWSOCKS_GLO (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            redir ports 3333

----------------------------------------------------- nat表 SHADOWSOCKS_HOM 链 -----------------------------------------------------
Chain SHADOWSOCKS_HOM (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set black_list dst redir ports 3333
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set chnroute dst redir ports 3333
-----------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------ mangle表 PREROUTING 链 -------------------------------------------------------
Chain PREROUTING (policy ACCEPT 13M packets, 11G bytes)
 pkts bytes target     prot opt in     out     source               destination         
 708K  172M SHADOWSOCKS  udp  --  *      *       0.0.0.0/0            0.0.0.0/0           

------------------------------------------------------ mangle表 SHADOWSOCKS 链 -------------------------------------------------------
Chain SHADOWSOCKS (1 references)
 pkts bytes target     prot opt in     out     source               destination         
 679K  169M RETURN     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set white_list dst
   24  1824 RETURN     udp  --  *      *       10.0.0.28            0.0.0.0/0           
    0     0 RETURN     udp  --  *      *       10.0.0.140           0.0.0.0/0           
   96  4692 RETURN     udp  --  *      *       10.0.0.224           0.0.0.0/0           
    0     0 RETURN     udp  --  *      *       10.0.0.213           0.0.0.0/0           
28645 3149K SHADOWSOCKS_GAM  udp  --  *      *       0.0.0.0/0            0.0.0.0/0           

------------------------------------------------------ mangle表 SHADOWSOCKS_GAM 链 -------------------------------------------------------
Chain SHADOWSOCKS_GAM (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 TPROXY     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set black_list dst TPROXY redirect 0.0.0.0:3333 mark 0x1/0xffffffff
21208 2664K TPROXY     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            ! match-set chnroute dst TPROXY redirect 0.0.0.0:3333 mark 0x1/0xffffffff
-----------------------------------------------------------------------------------------------------------------------------------

**Comment by lingaoyi** [comment]
Jul 11 23:20:07 dnsmasq[10096]: using nameserver 114.114.114.114#53 for domain zzloop.com 
Jul 11 23:20:07 dnsmasq[10096]: using 38646 more nameservers
Jul 11 23:20:08 lingaoyi: [软件中心]: skipd进程成功启动！
Jul 11 23:24:20 rss-redir[9874]: server recv: Connection reset by peer
Jul 11 23:24:24 watchdog: start ddns.
Jul 11 23:24:24 rc_service: watchdog 627:notify_rc start_ddns
Jul 11 23:24:24 ddns update: ez-ipupdate: starting...
Jul 11 23:24:27 ddns update: connected to dynamic.zoneedit.com (64.68.198.48) on port 80.
Jul 11 23:24:43 ddns update: error processing request
Jul 11 23:24:43 ddns update: server output: HTTP/1.1 200 OK^M Date: Tue, 11 Jul 2017 15:24:38 GMT^M Server: Apache/2.2.22 (Debian)^M X-Powered-By: PHP/5.4.45-0+deb7u5^M Vary: Accept-Encoding^M Content-Length: 104^M Connection: close^M Content-Type: text/html^M ^M <ERROR CODE="702" PARAM="600" TEXT="Minimum 600 seconds between requests" ZONE="home.lingaoyi.network">
Jul 11 23:24:43 ddns update: asusddns_update: 1
Jul 11 23:24:54 watchdog: start ddns.
Jul 11 23:24:54 rc_service: watchdog 627:notify_rc start_ddns
Jul 11 23:24:54 ddns update: ez-ipupdate: starting...
Jul 11 23:24:54 ddns update: connected to dynamic.zoneedit.com (64.68.198.48) on port 80.
Jul 11 23:24:55 ddns update: error processing request
Jul 11 23:24:55 ddns update: server output: HTTP/1.1 200 OK^M Date: Tue, 11 Jul 2017 15:24:55 GMT^M Server: Apache/2.2.22 (Debian)^M X-Powered-By: PHP/5.4.45-0+deb7u5^M Vary: Accept-Encoding^M Content-Length: 104^M Connection: close^M Content-Type: text/html^M ^M <ERROR CODE="702" PARAM="600" TEXT="Minimum 600 seconds between requests" ZONE="home.lingaoyi.network">
Jul 11 23:24:55 ddns update: asusddns_update: 1
Jul 11 23:25:24 watchdog: start ddns.
Jul 11 23:25:24 rc_service: watchdog 627:notify_rc start_ddns
Jul 11 23:25:24 ddns update: ez-ipupdate: starting...
Jul 11 23:25:24 ddns update: connected to dynamic.zoneedit.com (64.68.198.48) on port 80.
Jul 11 23:25:37 ddns update: error processing request
Jul 11 23:25:37 ddns update: server output: HTTP/1.1 200 OK^M Date: Tue, 11 Jul 2017 15:25:36 GMT^M Server: Apache/2.2.22 (Debian)^M X-Powered-By: PHP/5.4.45-0+deb7u5^M Vary: Accept-Encoding^M Content-Length: 104^M Connection: close^M Content-Type: text/html^M ^M <ERROR CODE="702" PARAM="600" TEXT="Minimum 600 seconds between requests" ZONE="home.lingaoyi.network">
Jul 11 23:25:37 ddns update: asusddns_update: 1
Jul 11 23:25:54 watchdog: start ddns.
Jul 11 23:25:54 rc_service: watchdog 627:notify_rc start_ddns
Jul 11 23:25:54 ddns update: ez-ipupdate: starting...
Jul 11 23:25:54 ddns update: connected to dynamic.zoneedit.com (64.68.198.48) on port 80.
Jul 11 23:25:55 ddns update: error processing request
Jul 11 23:25:55 ddns update: server output: HTTP/1.1 200 OK^M Date: Tue, 11 Jul 2017 15:25:55 GMT^M Server: Apache/2.2.22 (Debian)^M X-Powered-By: PHP/5.4.45-0+deb7u5^M Vary: Accept-Encoding^M Content-Length: 104^M Connection: close^M Content-Type: text/html^M ^M <ERROR CODE="702" PARAM="600" TEXT="Minimum 600 seconds between requests" ZONE="home.lingaoyi.network">
Jul 11 23:25:55 ddns update: asusddns_update: 1
Jul 11 23:26:24 watchdog: start ddns.
Jul 11 23:26:24 rc_service: watchdog 627:notify_rc start_ddns
Jul 11 23:26:24 ddns update: ez-ipupdate: starting...
Jul 11 23:26:25 ddns update: connected to dynamic.zoneedit.com (64.68.198.48) on port 80.
Jul 11 23:26:36 ddns update: error processing request
Jul 11 23:26:36 ddns update: server output: HTTP/1.1 200 OK^M Date: Tue, 11 Jul 2017 15:26:36 GMT^M Server: Apache/2.2.22 (Debian)^M X-Powered-By: PHP/5.4.45-0+deb7u5^M Vary: Accept-Encoding^M Content-Length: 104^M Connection: close^M Content-Type: text/html^M ^M <ERROR CODE="702" PARAM="600" TEXT="Minimum 600 seconds between requests" ZONE="home.lingaoyi.network">
Jul 11 23:26:36 ddns update: asusddns_update: 1
Jul 11 23:26:54 watchdog: start ddns.
Jul 11 23:26:54 rc_service: watchdog 627:notify_rc start_ddns
Jul 11 23:26:54 ddns update: ez-ipupdate: starting...
Jul 11 23:26:54 ddns update: connected to dynamic.zoneedit.com (64.68.198.48) on port 80.
Jul 11 23:27:09 ddns update: Server timeout
Jul 11 23:27:09 ddns update: strange server response, are you connecting to the right server?
Jul 11 23:27:09 ddns update: asusddns_update: 1
Jul 11 23:27:24 watchdog: start ddns.
Jul 11 23:27:24 rc_service: watchdog 627:notify_rc start_ddns
Jul 11 23:27:24 ddns update: ez-ipupdate: starting...
Jul 11 23:27:27 ddns update: connected to dynamic.zoneedit.com (64.68.198.48) on port 80.
Jul 11 23:27:42 ddns update: Server timeout
Jul 11 23:27:42 ddns update: strange server response, are you connecting to the right server?
Jul 11 23:27:42 ddns update: asusddns_update: 1
Jul 11 23:27:54 watchdog: start ddns.
Jul 11 23:27:54 rc_service: watchdog 627:notify_rc start_ddns
Jul 11 23:27:54 ddns update: ez-ipupdate: starting...
Jul 11 23:27:54 ddns update: connected to dynamic.zoneedit.com (64.68.198.48) on port 80.
Jul 11 23:27:56 ddns update: error processing request
Jul 11 23:27:56 ddns update: server output: HTTP/1.1 200 OK^M Date: Tue, 11 Jul 2017 15:27:55 GMT^M Server: Apache/2.2.22 (Debian)^M X-Powered-By: PHP/5.4.45-0+deb7u5^M Vary: Accept-Encoding^M Content-Length: 104^M Connection: close^M Content-Type: text/html^M ^M <ERROR CODE="702" PARAM="600" TEXT="Minimum 600 seconds between requests" ZONE="home.lingaoyi.network">
Jul 11 23:27:56 ddns update: asusddns_update: 1
Jul 11 23:28:24 watchdog: start ddns.
Jul 11 23:28:24 rc_service: watchdog 627:notify_rc start_ddns
Jul 11 23:28:24 ddns update: ez-ipupdate: starting...
Jul 11 23:28:24 ddns update: connected to dynamic.zoneedit.com (64.68.198.48) on port 80.
Jul 11 23:28:26 ddns update: error processing request
Jul 11 23:28:26 ddns update: server output: HTTP/1.1 200 OK^M Date: Tue, 11 Jul 2017 15:28:25 GMT^M Server: Apache/2.2.22 (Debian)^M X-Powered-By: PHP/5.4.45-0+deb7u5^M Vary: Accept-Encoding^M Content-Length: 104^M Connection: close^M Content-Type: text/html^M ^M <ERROR CODE="702" PARAM="600" TEXT="Minimum 600 seconds between requests" ZONE="home.lingaoyi.network">
Jul 11 23:28:26 ddns update: asusddns_update: 1
Jul 11 23:28:54 watchdog: start ddns.
Jul 11 23:28:54 rc_service: watchdog 627:notify_rc start_ddns
Jul 11 23:28:54 ddns update: ez-ipupdate: starting...
Jul 11 23:28:57 ddns update: connected to dynamic.zoneedit.com (64.68.198.48) on port 80.
Jul 11 23:28:58 ddns update: error processing request
Jul 11 23:28:58 ddns update: server output: HTTP/1.1 200 OK^M Date: Tue, 11 Jul 2017 15:28:58 GMT^M Server: Apache/2.2.22 (Debian)^M X-Powered-By: PHP/5.4.45-0+deb7u5^M Vary: Accept-Encoding^M Content-Length: 104^M Connection: close^M Content-Type: text/html^M ^M <ERROR CODE="702" PARAM="600" TEXT="Minimum 600 seconds between requests" ZONE="home.lingaoyi.network">
Jul 11 23:28:58 ddns update: asusddns_update: 1
Jul 11 23:29:24 watchdog: start ddns.
Jul 11 23:29:24 rc_service: watchdog 627:notify_rc start_ddns
Jul 11 23:29:24 ddns update: ez-ipupdate: starting...
Jul 11 23:29:27 ddns update: connected to dynamic.zoneedit.com (64.68.198.48) on port 80.
Jul 11 23:29:29 ddns update: error processing request
Jul 11 23:29:29 ddns update: server output: HTTP/1.1 200 OK^M Date: Tue, 11 Jul 2017 15:29:28 GMT^M Server: Apache/2.2.22 (Debian)^M X-Powered-By: PHP/5.4.45-0+deb7u5^M Vary: Accept-Encoding^M Content-Length: 104^M Connection: close^M Content-Type: text/html^M ^M <ERROR CODE="702" PARAM="600" TEXT="Minimum 600 seconds between requests" ZONE="home.lingaoyi.network">
Jul 11 23:29:29 ddns update: asusddns_update: 1
Jul 11 23:29:54 watchdog: start ddns.
Jul 11 23:29:54 rc_service: watchdog 627:notify_rc start_ddns
Jul 11 23:29:54 ddns update: ez-ipupdate: starting...
Jul 11 23:29:54 ddns update: connected to dynamic.zoneedit.com (64.68.198.48) on port 80.
Jul 11 23:29:56 ddns update: request successful
Jul 11 23:29:56 ddns update: asusddns_update: 0
Jul 11 23:29:56 ddns: ddns update ok
Jul 11 23:31:53 miniupnpd[8755]: PCP: External IP in request didn't match interface IP 
Jul 11 23:31:53 miniupnpd[8755]: PCP: External IP in request didn't match interface IP 
Jul 11 23:36:02 rss-redir[9874]: server recv: Connection reset by peer
Jul 11 23:36:02 rss-redir[9874]: server recv: Connection reset by peer
Jul 11 23:36:02 rss-redir[9874]: server recv: Connection reset by peer
Jul 11 23:36:02 rss-redir[9874]: server recv: Connection reset by peer
Jul 11 23:37:29 rss-redir[9874]: server recv: Connection reset by peer
Jul 11 23:47:33 rss-redir[9874]: remote recv: Connection reset by peer
Jul 11 23:53:25 dnsmasq-dhcp[10096]: DHCPREQUEST(br0) 10.0.0.12 28:6c:07:83:40:5b 
Jul 11 23:53:25 dnsmasq-dhcp[10096]: DHCPACK(br0) 10.0.0.12 28:6c:07:83:40:5b rockrobo
Jul 11 23:54:20 rss-redir[9874]: server recv: Connection reset by peer
Jul 11 23:59:21 dnsmasq-dhcp[10096]: DHCPREQUEST(br0) 10.0.0.93 4c:0b:be:bf:f0:0b 
Jul 11 23:59:21 dnsmasq-dhcp[10096]: DHCPACK(br0) 10.0.0.93 4c:0b:be:bf:f0:0b XBOXONE
Jul 11 23:59:21 dnsmasq-dhcp[10096]: DHCPREQUEST(br0) 10.0.0.93 4c:0b:be:bf:f0:0b 
Jul 11 23:59:21 dnsmasq-dhcp[10096]: DHCPACK(br0) 10.0.0.93 4c:0b:be:bf:f0:0b XBOXONE
Jul 11 23:59:21 dnsmasq-dhcp[10096]: DHCPREQUEST(br0) 10.0.0.93 4c:0b:be:bf:f0:0b 
Jul 11 23:59:21 dnsmasq-dhcp[10096]: DHCPACK(br0) 10.0.0.93 4c:0b:be:bf:f0:0b XBOXONE
Jul 12 00:00:43 disk_monitor: Got SIGALRM...
Jul 12 00:10:02 rss-redir[9874]: send: Broken pipe
Jul 12 00:11:05 dnsmasq-dhcp[10096]: DHCPREQUEST(br0) 10.0.0.140 34:12:98:1c:ff:f3 
Jul 12 00:11:05 dnsmasq-dhcp[10096]: DHCPACK(br0) 10.0.0.140 34:12:98:1c:ff:f3 LGY-iPad
Jul 12 00:58:33 rss-redir[9874]: remote recv: Connection reset by peer
Jul 12 01:33:14 rss-redir[9874]: remote recv: Connection reset by peer
Jul 12 01:45:32 rss-redir[9874]: server recv: Connection reset by peer
Jul 12 02:11:54 rss-redir[9874]: remote recv: Connection reset by peer
Jul 12 02:37:08 rss-redir[9874]: server recv: Connection timed out
Jul 12 02:41:33 rss-redir[9874]: remote recv: Connection reset by peer
Jul 12 02:47:04 rss-redir[9874]: server recv: Connection timed out
Jul 12 03:02:21 dnsmasq-dhcp[10096]: DHCPREQUEST(br0) 10.0.0.93 4c:0b:be:bf:f0:0b 
Jul 12 03:02:21 dnsmasq-dhcp[10096]: DHCPACK(br0) 10.0.0.93 4c:0b:be:bf:f0:0b XBOXONE
Jul 12 03:02:21 dnsmasq-dhcp[10096]: DHCPREQUEST(br0) 10.0.0.93 4c:0b:be:bf:f0:0b 
Jul 12 03:02:21 dnsmasq-dhcp[10096]: DHCPACK(br0) 10.0.0.93 4c:0b:be:bf:f0:0b XBOXONE
Jul 12 03:20:02 dnsmasq-dhcp[10096]: DHCPREQUEST(br0) 10.0.0.199 88:1f:a1:3b:84:00 
Jul 12 03:20:02 dnsmasq-dhcp[10096]: DHCPACK(br0) 10.0.0.199 88:1f:a1:3b:84:00 l-g-y-airport-express
Jul 12 03:27:05 rss-redir[9874]: remote recv: Connection reset by peer
Jul 12 03:42:02 dnsmasq-dhcp[10096]: DHCPREQUEST(br0) 10.0.0.12 28:6c:07:83:40:5b 
Jul 12 03:42:02 dnsmasq-dhcp[10096]: DHCPACK(br0) 10.0.0.12 28:6c:07:83:40:5b rockrobo
Jul 12 03:59:39 dnsmasq-dhcp[10096]: DHCPREQUEST(br0) 10.0.0.58 c8:69:cd:36:e2:9f 
Jul 12 03:59:39 dnsmasq-dhcp[10096]: DHCPACK(br0) 10.0.0.58 c8:69:cd:36:e2:9f Apple-TV
Jul 12 04:16:05 dnsmasq-dhcp[10096]: DHCPREQUEST(br0) 10.0.0.93 4c:0b:be:bf:f0:0b 
Jul 12 04:16:05 dnsmasq-dhcp[10096]: DHCPACK(br0) 10.0.0.93 4c:0b:be:bf:f0:0b XBOXONE
Jul 12 04:16:05 dnsmasq-dhcp[10096]: DHCPREQUEST(br0) 10.0.0.93 4c:0b:be:bf:f0:0b 
Jul 12 04:16:05 dnsmasq-dhcp[10096]: DHCPACK(br0) 10.0.0.93 4c:0b:be:bf:f0:0b XBOXONE
Jul 12 04:16:39 rss-redir[9874]: server recv: Connection reset by peer
Jul 12 05:02:06 rss-redir[9874]: remote recv: Connection reset by peer
Jul 12 05:48:29 dnsmasq-dhcp[10096]: DHCPREQUEST(br0) 10.0.0.28 20:3c:ae:58:e5:51 
Jul 12 05:48:29 dnsmasq-dhcp[10096]: DHCPACK(br0) 10.0.0.28 20:3c:ae:58:e5:51 LGY-iPhone
Jul 12 06:01:06 rss-redir[9874]: remote recv: Connection reset by peer
Jul 12 07:00:00 crond[624]: USER lingaoyi pid 20108 cmd /bin/sh /koolshare/scripts/ss_rule_update.sh
Jul 12 07:09:46 rss-redir[9874]: server recv: Connection timed out
Jul 12 08:29:39 dnsmasq-dhcp[10096]: DHCPREQUEST(br0) 10.0.0.58 c8:69:cd:36:e2:9f 
Jul 12 08:29:39 dnsmasq-dhcp[10096]: DHCPACK(br0) 10.0.0.58 c8:69:cd:36:e2:9f Apple-TV
Jul 12 08:35:46 dnsmasq-dhcp[10096]: DHCPREQUEST(br0) 10.0.0.224 28:f0:76:51:c3:36 
Jul 12 08:35:46 dnsmasq-dhcp[10096]: DHCPACK(br0) 10.0.0.224 28:f0:76:51:c3:36 LGY-iMac-5K
Jul 12 08:39:48 rss-redir[9874]: remote recv: Connection reset by peer
Jul 12 08:44:01 rss-redir[9874]: server recv: Connection timed out
Jul 12 08:44:38 rss-redir[9874]: server recv: Connection timed out
Jul 12 09:38:22 dnsmasq-dhcp[10096]: DHCPREQUEST(br0) 10.0.0.93 4c:0b:be:bf:f0:0b 
Jul 12 09:38:22 dnsmasq-dhcp[10096]: DHCPACK(br0) 10.0.0.93 4c:0b:be:bf:f0:0b XBOXONE
Jul 12 09:38:22 dnsmasq-dhcp[10096]: DHCPREQUEST(br0) 10.0.0.93 4c:0b:be:bf:f0:0b 
Jul 12 09:38:22 dnsmasq-dhcp[10096]: DHCPACK(br0) 10.0.0.93 4c:0b:be:bf:f0:0b XBOXONE
Jul 12 09:38:57 rss-redir[9874]: server recv: Connection reset by peer
Jul 12 10:03:01 dnsmasq-dhcp[10096]: DHCPDISCOVER(br0) 20:3c:ae:58:e5:51 
Jul 12 10:03:01 dnsmasq-dhcp[10096]: DHCPOFFER(br0) 10.0.0.28 20:3c:ae:58:e5:51 
Jul 12 10:03:02 dnsmasq-dhcp[10096]: DHCPREQUEST(br0) 10.0.0.28 20:3c:ae:58:e5:51 
Jul 12 10:03:02 dnsmasq-dhcp[10096]: DHCPACK(br0) 10.0.0.28 20:3c:ae:58:e5:51 LGY-iPhone
Jul 12 10:35:00 dnsmasq-dhcp[10096]: DHCPREQUEST(br0) 10.0.0.207 28:6c:07:85:12:df 
Jul 12 10:35:00 dnsmasq-dhcp[10096]: DHCPACK(br0) 10.0.0.207 28:6c:07:85:12:df zhimi-airpurifier-v6_miio52007267
Jul 12 11:13:47 dnsmasq-dhcp[10096]: DHCPREQUEST(br0) 10.0.0.140 34:12:98:1c:ff:f3 
Jul 12 11:13:47 dnsmasq-dhcp[10096]: DHCPACK(br0) 10.0.0.140 34:12:98:1c:ff:f3 LGY-iPad
Jul 12 11:19:45 ntp: start NTP update
Jul 12 11:21:34 rss-redir[9874]: getpeername: Transport endpoint is not connected
Jul 12 11:21:34 rss-redir[9874]: getpeername: Transport endpoint is not connected
Jul 12 11:21:34 rss-redir[9874]: getpeername: Transport endpoint is not connected
Jul 12 11:21:34 rss-redir[9874]: getpeername: Transport endpoint is not connected
Jul 12 11:21:43 rss-redir[9874]: getpeername: Transport endpoint is not connected
Jul 12 11:21:54 rss-redir[9874]: remote recv: Connection reset by peer
Jul 12 11:22:07 rss-redir[9874]: remote recv: Connection reset by peer
Jul 12 11:22:20 rss-redir[9874]: remote recv: Connection reset by peer
Jul 12 12:43:15 dnsmasq-dhcp[10096]: DHCPREQUEST(br0) 10.0.0.12 28:6c:07:83:40:5b 
Jul 12 12:43:15 dnsmasq-dhcp[10096]: DHCPACK(br0) 10.0.0.12 28:6c:07:83:40:5b rockrobo
Jul 12 13:31:46 dnsmasq-dhcp[10096]: DHCPREQUEST(br0) 10.0.0.199 88:1f:a1:3b:84:00 
Jul 12 13:31:46 dnsmasq-dhcp[10096]: DHCPACK(br0) 10.0.0.199 88:1f:a1:3b:84:00 l-g-y-airport-express
Jul 12 13:34:33 dnsmasq-dhcp[10096]: DHCPDISCOVER(br0) 20:3c:ae:58:e5:51 
Jul 12 13:34:33 dnsmasq-dhcp[10096]: DHCPOFFER(br0) 10.0.0.28 20:3c:ae:58:e5:51 
Jul 12 13:34:34 dnsmasq-dhcp[10096]: DHCPREQUEST(br0) 10.0.0.28 20:3c:ae:58:e5:51 
Jul 12 13:34:34 dnsmasq-dhcp[10096]: DHCPACK(br0) 10.0.0.28 20:3c:ae:58:e5:51 LGY-iPhone
Jul 12 14:23:35 rss-redir[9874]: send: Broken pipe
Jul 12 15:12:37 rss-redir[9874]: server recv: Connection reset by peer
Jul 12 16:33:44 rc_service: service 18366:notify_rc restart_dnsmasq
Jul 12 16:33:44 dnsmasq[10096]: exiting on receipt of SIGTERM
Jul 12 16:33:44 dnsmasq[18371]: started, version 2.76 cachesize 1500

**Comment by sadoneli** [comment]
建议用dns2socks来解析dns吧，我看你这个ssr-tunnel并没有工作啊
