### ISSUE TITLE
3.59版本 无法启动。

### ISSUE THREAD

**Issue by ericshunhawk** [koolshare/koolshare.github.io#372]
2017年07月14日 10:51:41: =============== 梅林固件 - shadowsocks by sadoneli&Xiaobao ===============
2017年07月14日 10:51:41:
2017年07月14日 10:51:41: -------------------------- 关闭Shadowsocks ------------------------------
2017年07月14日 10:51:42: 删除/jffs/scripts/dnsmasq.postconf
2017年07月14日 10:51:42: 删除ss相关的名单配置文件.
2017年07月14日 10:51:42: 重启dnsmasq服务...
2017年07月14日 10:51:42: 清除iptables规则...
2017年07月14日 10:51:45: 清空ipset名单...
2017年07月14日 10:51:45: 清除重复的ip rule规则.
2017年07月14日 10:51:45: 删除ip route规则.
2017年07月14日 10:51:45: 清除nat-start, wan-start中相关的SS启动命令...
2017年07月14日 10:51:46: 关闭ss-redir进程...
2017年07月14日 10:51:46: 关闭ss-local进程:23456端口...
2017年07月14日 10:51:47: 关闭dns2socks进程...
2017年07月14日 10:51:48: 删除ss规则定时更新任务.
2017年07月14日 10:51:48: -------------------------- Shadowsocks已关闭 -----------------------------
2017年07月14日 10:51:48: ----------------------- shadowsocks 启动前触发脚本 -----------------------
2017年07月14日 10:51:49: ss启动前触发：你选择了普通节点，不触发负载均衡启动！.
2017年07月14日 10:51:49: ------------------------- 梅林固件 shadowsocks --------------------------
2017年07月14日 10:51:49: 检测是否符合游戏模式启动条件...
2017年07月14日 10:51:49: 未检测到系统设置冲突，符合启动条件！
2017年07月14日 10:51:49: 检测到你的SS服务器已经是IP格式：45.32.38.172,跳过解析...
2017年07月14日 10:51:49: 创建SS配置文件到/koolshare/ss/ss.json
2017年07月14日 10:51:49: 应用域名黑名单
2017年07月14日 10:51:50: 创建gfwlist的软连接到/jffs/etc/dnsmasq.d/文件夹.
2017年07月14日 10:51:50: 添加nat-start触发事件...用于ss的nat规则重启后或网络恢复后的加载.
2017年07月14日 10:51:50: 添加wan-start触发事件...用于ss的各种程序的开机启动，启动延迟5
2017年07月14日 10:51:50: 添加ss规则定时更新任务，每天20自动检测更新规则.
2017年07月14日 10:51:50: 开启ss-local,为dns2socks提供socks5端口：23456
2017年07月14日 10:51:50: 开启dns2socks，监听端口：23456
2017年07月14日 10:51:50: 开启ss-redir进程，用于透明代理.
2017年07月14日 10:51:51: 加载nat规则!
2017年07月14日 10:51:51: 清除iptables规则...
2017年07月14日 10:51:52: 清空ipset名单...
2017年07月14日 10:51:52: 清除重复的ip rule规则.
2017年07月14日 10:51:52: 删除ip route规则.
2017年07月14日 10:51:52: 创建ipset名单
2017年07月14日 10:51:53: 应用IP/CIDR黑名单
2017年07月14日 10:51:54: 写入iptables规则到nat表中...
2017年07月14日 10:51:54: 加载TPROXY模块，用于udp转发...
One or more modules are missing, only 124 are loaded. Can't start.

**Comment by iamggs** [comment]
> **One or more modules are missing, only 124 are loaded. Can't start.**

一样的问题，准备回退回3.5.8了。

**Comment by lingaoyi** [comment]
S大说正在看喔。

**Comment by iamggs** [comment]
3.6.0出来了。
