### ISSUE TITLE
R7000 SS3.5.9 很不稳定

### ISSUE THREAD

**Issue by ash0080** [koolshare/koolshare.github.io#373]
每天至少要重启两回(ss脚本)
3.5.9之前一直挺好, 今天升了3.6.0再观察一下, 如果是脚本问题, 我看应该还是会一样
稍后回报

**Comment by lingaoyi** [comment]
这个我也遇到，我自己明明没有提交过，但也会自动提交。

**Comment by ash0080** [comment]
我的情况不是自动提交 
而是代理会自动断掉 需要手动重启一遍脚本
这个情况在3.5.9之前没有发生过 现在天天如此

**Comment by Clunt** [comment]
AC5300 SS基本处于不能用的状态

**Comment by sadoneli** [comment]
请反馈的朋友带上日志和ss的详细运行状态吧

**Comment by ash0080** [comment]
我升到3.6.0以来   貌似经过24小时尚没有出现过异常
也许好了  我继续观察下   其他楼上的朋友要是有问题请补充

**Comment by zhuchiheng** [comment]
ss被官方下架了...

**Comment by ash0080** [comment]
...
