### ISSUE TITLE
DDNspod的插件问题

### ISSUE THREAD

**Issue by PonyPC** [koolshare/koolshare.github.io#375]
1. 更新dns建议首次开机的时候立即更新
2. 断电再次通电就无法启动服务了，需要手动关闭再打开
3. 更新频率建议提供10分钟

**Comment by PonyPC** [comment]
所以问题是解决了？ @sadoneli

**Comment by sadoneli** [comment]
1 开机后会立即更新
2 断电重启可以启动，请检查你的启动项
3 不建议10分钟，因为ddnspod的api次数有限

**Comment by PonyPC** [comment]
但是实际上使用的时候断电了，下次就不会更新了，麻烦测试一下，每次断电都遇到这种情况


发件人: sadoneli
发送时间: 2017年10月17日 17:35
收件人: koolshare/koolshare.github.io
抄送: PonyPC; Author
主题: Re: [koolshare/koolshare.github.io] DDNspod的插件问题 (#375)

1 开机后会立即更新
2 断电重启可以启动，请检查你的启动项
3 不建议10分钟，因为ddnspod的api次数有限
