### ISSUE TITLE
游戏模式V1导致Switch的马里奥赛车8无法和国内好友联机

### ISSUE THREAD

**Issue by NOirBRight** [koolshare/koolshare.github.io#376]
之前使用游戏模式V1，在PS4上玩命运之类的游戏正常，但现在入了Nintendo Switch后出现问题。
在马里奥赛车8和喷射战士2里，只要开启游戏模式（V1），可以正常和国外玩家联机，但是如果和国内玩家组队，就会出现网络冲突，并且100%出现。

估计可能的情况是，在和国外玩家UDP连接时，走的SS代理，而和国内玩家UDP连接时，走的是直连，而任天堂游戏可能并不允许这样的连接方式，而导致游戏出错。

麻烦小宝能否检查下游戏模式V1下，用Switch联机马里奥赛车8或者喷射战士2的情况，看是否有可能解决。

**Comment by NOirBRight** [comment]
这个Issues被关闭的原因是啥？

**Comment by sadoneli** [comment]
ss下架，不再更新了

**Comment by elric8** [comment]
@sadoneli 
我也是这个问题
