### ISSUE TITLE
chacha20-ietf 消失不见了？？！

### ISSUE THREAD

**Issue by kaneawk** [koolshare/koolshare.github.io#38]
chacha20-ietf 消失不见了？？！
我记得之前的版本是有的。

**Comment by jannson** [comment]
可能是不小心弄丢了。这个现在是支持的。

**Comment by kaneawk** [comment]
不是，你点铅笔图标，新增一个节点，打开“Shadowsocks 节点配置”弹窗界面，加密方式一栏，它是没有 ietf 的，随便选一个加密方式保存以后，在“Shadowsocks 信息”框中切换到这个节点，，才可以选 ietf。

**Comment by sadoneli** [comment]
已经恢复，目前游戏模式v2不支持chacha20-ietf
