### ISSUE TITLE
将SS挂路由器上，google+ Twitter Facebook YouTube 等无法访问

### ISSUE THREAD

**Issue by kaneawk** [koolshare/koolshare.github.io#39]
已经尝试大陆白名单，gfwlist，游戏模式等，全都不正常。

**已确认不是SS账号的问题，win/android/ios/mac 客户端运行完全正常。**

在2016年3月初的时候，挂路由器上还是可以用的，最近全都不行了。

前两天只是 Twitter Facebook 等打不开，现在 G+ 也不行了。

注：Google 搜索、翻译、地图等服务还是正常的。能够完全打开。SS 运行状态均为双 working。

尝试切换DNS解析为 ss-tunnel，不正常。尝试切换 dnscrypt-proxy，不正常。切换 ChinaDNS，不正常。切换 PCap_Proxy，不正常。没有一个能用的。

运营商：河北联通
SS版本：v1.3.3
路由器型号：RT-AC68U

Firefox:

Secure Connection Failed

The connection to www.youtube.com was interrupted while the page was loading.

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

Chrome:

无法访问此网站

www.youtube.com 意外终止了连接。
ERR_CONNECTION_CLOSED

**Comment by jannson** [comment]
以后这种问题请想办法在 Q 群得到解决，谢谢。项目里并不想直接讨论此问题。
讨论起来很慢，并且很可能是使用性问题，最大的原因还是一些其它原因。所以还是在 Q 群里讨论吧，那里可以远程，人也多。嘿嘿。

**Comment by kaneawk** [comment]
并没有找到qq群。
