### ISSUE TITLE
SS 开启游戏模式之后 ping 命令会被转发么？

### ISSUE THREAD

**Issue by feeeei** [koolshare/koolshare.github.io#390]
SS server 端也是自己搭建的，昨晚好奇，尝试在本地敲了
`ping -s 65500 -i 0.1 XXX.XXX.XXX.XXX`
这个命令，只是尝试性的跑了一两分钟而已

然后...

今早就发现服务器被关停了，理由是『发现服务器尝试 Dos 攻击』......

这个跟游戏模式有关么？

**Comment by sadoneli** [comment]
不会
