### ISSUE TITLE
Softcenter

### ISSUE THREAD

**Issue by ocean521** [koolshare/koolshare.github.io#392]
软件中心有历史版本么，没有history 啊

**Comment by ocean521** [comment]
如果有，软件中心是否和其中的软件一样可以离线安装？谢谢

**Comment by sadoneli** [comment]
没有
是

**Comment by ocean521** [comment]
感谢，再问一下如果升级到1.3.4，是否也可以离线安装S……S啊，有无限制，没敢尝试。另外有什么S供应商推荐么，关键字即可。

**Comment by sadoneli** [comment]
1 可以
2 没有限制
3 自己搭建
