### ISSUE TITLE
希望增加锐捷认证！

### ISSUE THREAD

**Issue by kfcceo** [koolshare/koolshare.github.io#398]
学生党希望能增加校园网锐捷认证客户端~~

**Comment by sadoneli** [comment]
你可以提供mentohust或者其它客户端的编译教程和拨号配置教程，方便开发人员开发

**Comment by jannson** [comment]
恩，很不错。

**Comment by sadoneli** [comment]
开发组没有校园网调试坏境，还是希望有环境的朋友来做这个工作，插件的开发可以参考本项目的任何一个插件
