### ISSUE TITLE
merlin的同一血统亲戚(Tomato)过来支持一下

### ISSUE THREAD

**Issue by houzi-** [koolshare/koolshare.github.io#40]
共享自己写的代码，以供他人参考:
http://www.router008.com/2016/03/25/Tomato-adm/
http://www.router008.com/2016/02/03/Tomato-ShadowSocks/

**Comment by jannson** [comment]
看了你的博客，很不错。以后咱们一起玩啊！
对于插件列表的想法，我想重写一个 http server，独立于 tomato 原生的 http server。其实原生的代码我也看了，写得不错。我想重写一个的原因是，我想未来可以直接方便移植到 ddwrt 或其它支持 jffs 的固件上。
你个人怎么看？

**Comment by houzi-** [comment]
@jannson 确实插件列表由于Tomato本身一大堆的定制导致很多并不是适合我们的使用习惯，但要在源码上重新开发一些我们的GUI可能会遇到最重要的一个问题就是nvram空间不足！不知道你的想法是不是弄个外置的http server来通过接口来调用脚本进行配置？我原来也在Tomato用ASP写过一个shadowsocks-gui编译集成到固件，但我修改router/nvram/defaults.c发现由于涉及到太多的方案，要设置很多 value key,想象肯定占用一些nvram空间，无奈直接用脚本实现，这样更新起来更方便，虽然没有界面来得更直观，但是更新方便，维护起来成本也低，出现问题也很容易解决！
哈哈！所以我想看看宝哥你的高见!

**Comment by houzi-** [comment]
@jannson 还有就是想吐槽一下他的toochain，旧的已经无力吐槽了，导致很多新函数支持不完整,<虐我千百遍>，所以我还是觉得基于entware-ng开发比较好，毕竟现在同步了OpenWRT的编译链，GCC都到5.3.0了，编译起来特方便！只要是不依赖kernel version的都可以编译出来，并且OpenWRT有的，也可以往这边移植，简直就是万金油的存在ψ(｀∇´)ψ，我的那些插件就是依靠该工具编译出来的！在TT DD MER都可以部署安装，主要有entware-ng(entware)

**Comment by jannson** [comment]
关于工具链的问题，我平常都用官方的，但是一些程序是无法用官方编译的，我朋友他自己编译了一个工具链，还不错，我分享给你：链接: http://pan.baidu.com/s/1nvktT3b 密码: ch9x

关于存储的问题，我自己写了一个存储的项目，有点类似于 redis，存于内存 + jffs： https://github.com/koolshare/skipdbv2

在这个项目的主页也提到过。目前是所有的配置项都用 skipdbv2 来实现。模块之间的偶尔，也通过它来解决。你可以看看某一个模块的脚本就知道它的作用了。

**Comment by houzi-** [comment]
@jannson
 Thanks ！收下了
 有时间我看看，课余的时间多的是就是太懒了！

**Comment by houzi-** [comment]
这几天抽空看了skipdb的源码，真心写的不错，打算交叉编译一下然后写个makefile向entware提交！

**Comment by sadoneli** [comment]
@houzi- 欢迎来merlin阵营玩啊，不久我们也会转战TT的，相信能成为战友啊~

**Comment by houzi-** [comment]
交叉编译skipdbv2 不成功，`multiple definition`出现重复调用的`libskipdb.a`的问题
