### ISSUE TITLE
抱歉在这里提问, 固件在那里下载? 固件是否支持 tproxy?

### ISSUE THREAD

**Issue by zw963** [koolshare/koolshare.github.io#401]
ss 维护者告诉了我这个 repo, 用好几年华硕路由了, 惭愧竟然不知道.

我要解决的问题, 详见下面的 issue 讨论, 谢谢.
https://github.com/shadowsocks/shadowsocks-libev/issues/1632

**Comment by sadoneli** [comment]
如果你的路由器不支持tproxy，只能关闭浏览器quic了

**Comment by zw963** [comment]
@sadoneli , 谢谢回复,  Firefox 其实蛮快的, Chrome 我又不怎么用, 现在闹心的是 Youtube android app.
你知道有没有办法在 app 端解决这个问题?

**Comment by sadoneli** [comment]
app暂时不知道怎么解决了，我能想到的办法就是换路由器了
PS:AC66U的固件可以到论坛：koolshare.cn下载

**Comment by zw963** [comment]
> 如果你的路由器不支持tproxy，

确实不支持, https://github.com/RMerl/asuswrt-merlin/issues/1449#issuecomment-322207518

**Comment by sadoneli** [comment]
http://firmware.koolshare.cn/merlin_xiaobao_firmware/ASUS-RT-AC66U/

**Comment by sadoneli** [comment]
是的，因为内核版本原因，不够asus的arm架构机器，内核是可以支持tproxy的

**Comment by zw963** [comment]
@sadoneli , 是不是所有 ARM 大系的固件 (应该 linux 内核新很多吧) 都应该支持 tproxy 了?

**Comment by sadoneli** [comment]
asus的arm固件内核也新不到哪里去，也是很老旧的内核了，不过开tproxy没问题
官方固件和merlin固件默认都没有开启的，如果你有arm机型，你可以试试koolshare.cn的改版固件

**Comment by zw963** [comment]
> asus的arm固件内核也新不到哪里去，也是很老旧的内核了，不过开tproxy没问题
> 官方固件和merlin固件默认都没有开启的，如果你有arm机型，你可以试试koolshare.cn的改版固件

明白啦. 谢谢回复.

可否给个候选者? 华硕/非华硕的都行, 只要 koolshare 支持的好. 哈

**Comment by sadoneli** [comment]
推荐上软路由刷LEDE X64固件吧，其它没啥好推荐的

**Comment by zw963** [comment]
> 可否给个候选者? 华硕/非华硕的都行, 只要 koolshare 支持的好. 哈

不过前提普通上网功能要正常, 硬件质量还是要过关吧.
那种完全通用的 OpenWRT 的固件, 刷国外的一些 Router, 总感觉会有坑, 懒得去试, 我只用过 ASUS 几款.

**Comment by sadoneli** [comment]
http://firmware.koolshare.cn/

里面有不少维护机型，你自己选吧

**Comment by zw963** [comment]
> 里面有不少维护机型，你自己选吧

Cool! 看样子我只能选 ac88U 或 ac68U 了.

**Comment by zw963** [comment]
有没有 gitter 可以一起交流呢?? 

我玩路由器非常菜, 因为工作之需, 被逼的.

iptables 只懂一点点非常肤浅的东西, 我在 [这里](https://github.com/zw963/asuswrt-merlin-transparent-proxy/blob/master/route/opt/etc/iptables.sh) 也维护了一个基于白名单的 iptables, tcp 那些 rule 倒是工作的, 用了一两年了,  有空的话, 麻烦指点下了. 哈~ 谢!

**Comment by zw963** [comment]
嘿, 上周梅林发了一个新版 380.68,  全线 ARM 设备支持 tproxy 了.

ac56 ac68 ac1900p ac87 ac3100 ac3200 ac88 ac5300.

**Comment by sadoneli** [comment]
我们早就支持了，支持两年多了

**Comment by zw963** [comment]
> 我们早就支持了，支持两年多了

那为啥不尝试合并到上游?

**Comment by sadoneli** [comment]
我们没有参与维护 auswrt-merlin固件代码
