### ISSUE TITLE
听说开机启动会运行一次U盘asusware\.asusrouter？

### ISSUE THREAD

**Issue by lnedpaul** [koolshare/koolshare.github.io#404]
AC66U使用7.5版本是否真会在启动后运行U盘文件asusware\.asusrouter？
实验了http://koolshare.cn/thread-120911-1-1.html方法不起效。

**Comment by sadoneli** [comment]
是的，参考：https://github.com/RMerl/asuswrt-merlin/blob/master/release/src/router/rc/usb.c#L1510-L1511
