### ISSUE TITLE
readme.md里的连接打不开

### ISSUE THREAD

**Issue by wangyu-** [koolshare/koolshare.github.io#410]
readme.md----->交流场地---->目前我们在 Koolshare 论坛

连接是：
https://koolshare.cn/forum.php

尝试了多个浏览器，打不开。把https换成http可以打开。

**Comment by sadoneli** [comment]
https://github.com/koolshare/koolshare.github.io/commit/fbd2fa05cb69a042ed82f2c4775133a6303af0ce
