### ISSUE TITLE
还有ac66u用的 mips架构的shadowsocks 吗？

### ISSUE THREAD

**Issue by ken-yu-masters** [koolshare/koolshare.github.io#412]
试了 3.5.7 3.5.8 3.5.9 3.6.0都不行 
https://github.com/koolshare/koolshare.github.io/tree/acelan_softcenter_ui/shadowsocks/history
貌似是arm架构的

找到了一个mips的 但下面的地址不存在了
https://raw.githubusercontent.com/koolshare/koolshare.github.io/master/shadowsocks_mips/shadowsocks.tar.gz

谢了

**Comment by sadoneli** [comment]
mips的和arm都停止更新，问题不再作答，见谅

**Comment by thdg21** [comment]
https://www.mianao.info/2017/10/02/asus-merlin-%E5%9B%BA%E4%BB%B6-koolshare-%E6%94%B9%E7%89%88%E7%A6%BB%E7%BA%BF%E5%AE%89%E8%A3%85shadowsocks/ 看一下这篇文章，里面有mips的下载地址。

**Comment by RickyGuo** [comment]
非常感谢

**Comment by thdg21** [comment]
有的，给我你email，邮件发给你吧。

**Comment by RickyGuo** [comment]
Guoqirui2005@gmail.com 谢谢

**Comment by thdg21** [comment]
是否收到邮件

**Comment by xiaosan0318** [comment]
我按这篇文章来安装的，但是还是有这个错误。我固件是RT-AC66U_B1_380.63_X7.2.trx
用的ss是https://github.com/koolshare/koolshare.github.io/raw/mips_softerware_center/shadowsocks/shadowsocks.tar.gz
求助

**Comment by xiaosan0318** [comment]
文章是https://www.mianao.info/2017/10/02/asus-merlin-固件-koolshare-改版离线安装shadowsocks/

**Comment by thdg21** [comment]
链接: https://pan.baidu.com/s/1boH1jl1 密码: w5br
从这里下载

2018-01-02 10:05 GMT+08:00 xiaosan0318 <notifications@github.com>:
