### ISSUE TITLE
Vortex原版r7k固件如何安装此插件

### ISSUE THREAD

**Issue by 666keke** [koolshare/koolshare.github.io#413]
如题，小白一枚

**Comment by sadoneli** [comment]
koolshare软件中心的插件只能在koolshare的改版merlin固件里运行

不过你也可以参考一些插件的脚本，修改下这些脚本，去除dbus的依赖后手动运行

**Comment by 666keke** [comment]
谢谢！
那么请问现在论坛里发布的版本都集成了软件中心的插件吗？有某个不可描述的$$插件吗

**Comment by sadoneli** [comment]
1 是
2 没

**Comment by 666keke** [comment]
那么可以手动安装吗？如何安装

**Comment by 666keke** [comment]
好谢谢麻烦了

**Comment by 666keke** [comment]
哦哦还有最后一个问题
X7.6要刷过渡吗，网件原版

**Comment by sadoneli** [comment]
需要

**Comment by 666keke** [comment]
哪里下的到过渡固件？

**Comment by sadoneli** [comment]
网件固件需要
merlin固件不需要

下载：koolshare.cn

**Comment by 666keke** [comment]
vortex的过渡是否即可？

**Comment by sadoneli** [comment]
可以

**Comment by sadoneli** [comment]
固件刷机等问题，你可以到koolshare.cn论坛找到答案
此处不再做任何解答
