### ISSUE TITLE
Ss两个working情况下，所以网站都打不开

### ISSUE THREAD

**Issue by FreeVicto** [koolshare/koolshare.github.io#421]
重启下居然在2个working的情况下，百度和谷歌都打不开,只能删除ss后重新安装配置，非常麻烦，到底是梅林问题还是ss问题，感觉是dnsmasq的某个关键配置被ss错误配置导致的，求解决办法

**Comment by sadoneli** [comment]
相关的问题请在插件内寻找帮助文档，此处不做解答
