### ISSUE TITLE
Please keep ss-server binary under bin folder and just don't pack it into tar

### ISSUE THREAD

**Issue by uavana** [koolshare/koolshare.github.io#422]
Please keep ss-server binary under bin folder and just don't pack it into tar, so we can manually upgrade ss-server by ourselves thanks xiaobao!

**Comment by sadoneli** [comment]
Not appropriate for normal user, when a regular use this tar for initial install, they will missing ss-server binary.

**Comment by uavana** [comment]
But the version of ss-server is really really old, doesn't support chacha20-ietf-poly1305, and it's really useful, BTW when i install the newest version of shadowsocks plugin it will delete my ss-server binary(i have installed the ss-server plugin)
