### ISSUE TITLE
哪里能找到koolshare版本的ss源码？打算开个小号接手试试

### ISSUE THREAD

**Issue by guijianchou** [koolshare/koolshare.github.io#425]
买网件折腾梅林的唯一理由就是ss比小米之类的openwrt的性能高，看着几个月之前的停更信息和ss里面半死不活的v2模式，真的不知道刷梅林的意义何在？
最后更的版本3.6.0已经很完美了,只是想加入新的ssr混淆模式和剔除不再维护的v2游戏模式。
最近vps的ss被和谐不少，估计ss版本会在gcm加密或者混淆上更新。

**Comment by Johngithubb** [comment]
如果能接手就太好了，恨有关部门，恨自己不会编程。

**Comment by sadoneli** [comment]
就在本项目内
