### ISSUE TITLE
base64_decode问题

### ISSUE THREAD

**Issue by maversxu** [koolshare/koolshare.github.io#427]
启动的时候报错：
/koolshare/bin/base64_decode: line 1: syntax error: unexpected word (expecting ")")
ss.json里密码为空，无法连接ss

搜到并查看下面的帖子：
https://github.com/koolshare/koolshare.github.io/issues/254
https://github.com/koolshare/koolshare.github.io/issues/255

清空jffs后，再重新安装ss，没有任何变化，试过各种版本，都不行。
路由ac66u，Firmware:380.66_4-X7.5。
最近由于加密协议更改，升级了路由固件和ss版本，导致出现这个问题。
在使用老版本固件(X7.0)和老版本ss(2.8.1)的时候，没有问题。。
请问如何修正？是否为ss和路由固件的兼容问题？

**Comment by maversxu** [comment]
终于发现问题了，下错ss版本了，ac66u是mips的，一直下的是arm的，改成mips的就可以了。。。。囧

**Comment by xiaosan0318** [comment]
我启动的时候也是这个错误，我刷的是RT-AC66U_B1_380.63_X7.2.trx， ss用的地址是wget -N -O shadowsocks.tar.gz https://github.com/koolshare/koolshare.github.io/raw/mips_softerware_center/shadowsocks/shadowsocks.tar.gz 
下载的也确实是mips版本。
你用的是哪个版本呢

**Comment by maversxu** [comment]
我下的应该就是你帖的链接里的这个版本，你是不是没装上？那个软件中心自动安装功能好像有问题，我是ssh上去手动安装的
