### ISSUE TITLE
插件在特定情况下会开启失败

### ISSUE THREAD

**Issue by Easy-Sir** [koolshare/koolshare.github.io#429]
具体情形是，在节点管理界面ping所有服务器进行测试，然后直接开启SS，这个时候ss是不会正常开启的，会被再次关闭一遍，需要退出SS界面再次进入之后开启了才会开始正常运行

**Comment by Yohoa** [comment]
@Easy-Sir 您好，我注意到您提到第二步“直接开启SS”，请问具体操作是指？

**Comment by Easy-Sir** [comment]
@Yohoa 也就是直接点击提交，这个时候SS开关是开着的，理论上应该会开启SS，但是点击后将会执行一遍关闭SS的操作

**Comment by sadoneli** [comment]
已修复
