### ISSUE TITLE
关于ADM iptables建议

### ISSUE THREAD

**Issue by houzi-** [koolshare/koolshare.github.io#43]
其实可以你用ipset来创建一个AMD一个广告黑名单集合进行过滤，用法跟gfwlist+dnsmasq差不多！在dnsmasq上解析的domain的IP导入到ADM集合里，然后再用iptables设置match来重定向到18309端口！这样可以避免一些网站被ADM错误地过滤掉

**Comment by jannson** [comment]
你说的确实很有道理，这样的话说不定 ADM 还能跑得更快一些，下个版本用这个思路去完成。
目前 dnsmasq 里面的配置项特别多，如果再加上 ADM 的这个配置项的话，会不会让 dnsmasq 的加载变得特别慢啊？

**Comment by jannson** [comment]
其实我特别想加一个程序，通过 bloomfilter 的思路去解决这个 dnsmasq 的 ipset 与 dns 的关系。

**Comment by houzi-** [comment]
@jannson 这个可以设置用户自定义的方式添加domain，感觉过滤只是过滤一些主要的网站，不会超过百条，dnsmasq加载变慢这个问题丝毫没有感觉到，我在Tomato上就加载20000多条的china_whitelist，但他不会全部加载的，因为已经超过了cache-size的最大值10000,余下的部分应该是临时调用处理！
如果想减轻dnsmasq的负担可以利用ipset的`nomatch` flag功能来处理,并且一个hash:ip 最大为65536！

**Comment by houzi-** [comment]
@jannson 今晚些时候我推送这部分的代码到gfwlist方案测试一下,看看效果如何!
哦！对了，我发现ADM在Tomato V135版本下会出现过滤一些网站的时候会出现进程爆满导致占用资源过高直接被kill掉了！

**Comment by jannson** [comment]
是，目前 ADM 是一个请求会产生一个线程，线程数会比较高。我加了 perp 来对它进行监控！

**Comment by sadoneli** [comment]
好的想法，虽然实现很容易，但是，在ADM的基础上再用ipset+iptables过滤一次的过滤的网站的话，虽然对ADM的负担小了，但是ipset+iptables需要维护域名list，目前开发组这几个人精力有限，如果有基本无维护的方式，或者有人愿意做这个工作，相信ADM应该会工作更好的

**Comment by sadoneli** [comment]
做过尝试了，行不通，视频网站的域名能很容易加进dnsmasq的ipset list中，但是视频流确却是别的地址
这个办法对付静态广告还好，对付视频广告不行

**Comment by houzi-** [comment]
@sadoneli 这个方法也是我的一个想法，没有去test过，我不使用该方法进行过滤，而是依据对内网设备和外网的IP进行控制的方法来进行广告的过滤控制！详见:https://github.com/houzi-/tomato-shadowsocks/commit/717fe889e799a2ae7aadec831cbf1ac39665f56a
不过还是觉得ADM的线程池控制得不好！我使用adbyby就不会这样！不过adbyby的armv7架构的不能很好地在arm的路由器上运行！

**Comment by houzi-** [comment]
可能没有正确的替换掉广告js脚本吧！

**Comment by houzi-** [comment]
这样是可行的！比如优酷address=/static.youku.com/xxx 这是优酷存放广告的地址！

**Comment by houzi-** [comment]
其实也可以利用路由器搭建Nginx的反向代理到youku上的然后替换和插Onens.Clean.Player入 js 脚本而达到去广告的目的，当然这只是我的一个想法！但肯定比ADM资源占用少很多！这是Onens.Clean.Player目前的项目地址http://code.taobao.org/p/noadsplayer/logs/

**Comment by sadoneli** [comment]
那其他视频网站是否也是这样的呢？乐视？爱奇艺？

在 2016年4月10日 上午1:43，PSS <notifications@github.com>写道：

**Comment by houzi-** [comment]
使用浏览器检查元素这一个功能来获取到插入的js脚本地址就可以了！
还有逛论坛看到你的帖子，顺便编译了最新版本的Pcap_DNSProxy,全静态编译的只是strip过没有upx，如果upx过的话二进制文件能到600-700k这样子！
http://pan.baidu.com/s/1mgYlk28  密码:i3q0
在`V5.0-mipselsf(entware-ng)`文件夹下的`static`

**Comment by houzi-** [comment]
golang的mips74K的gccgo编译工具已经弄出来了，能编译一下golang的程序，但是执行却是出错的，可能glibc缺少了libcgo缘故，*context这几个只有eglibc支持。虽然可以backport，但是不了解库的内部结构，无从下手，只能说目前暂时无解了::>_<::

**Comment by sadoneli** [comment]
多谢，PcapDNSproxy取走了，这样说，mips下真的go无望了哇？

**Comment by houzi-** [comment]
@sadoneli 宝哥是我的师兄哈哈！不用客气，能帮忙到的尽量帮！
gccgo这个只能等待go版本的对其支持或者是一些大牛来解决了！

**Comment by sadoneli** [comment]
那你现在还在电子科大？还是毕业了？我在成都的

2016-04-10 23:46 GMT+08:00 PSS <notifications@github.com>:

**Comment by houzi-** [comment]
大二呢！哈哈

**Comment by sadoneli** [comment]
擦，，，有前途，我在温江，博二老人了，有空来电子科大找你哇

2016-04-10 23:49 GMT+08:00 PSS <notifications@github.com>:

**Comment by houzi-** [comment]
OK!😄哈哈真想找个本地人玩玩呢！！！！！

**Comment by houzi-** [comment]
merlin和tt的mips的kernel版本太低了，是时候放弃就放弃了，两头更新真的很麻烦又费神！要是基于DD就很爽了！毕竟DD才是土豪，能搞到3.x内核下的闭源驱动(T＿T)

**Comment by sadoneli** [comment]
确实啊，mips我打算把N66U和AC66U这里发了，就最低限度维护就行了，merlin的话还是先玩arm
按照小宝和我之前的设想，merlin这边过后是TT，至少GUI的SS要有，软件中心要有，然后是DD
总之够得玩

2016-04-10 23:57 GMT+08:00 PSS <notifications@github.com>:

**Comment by houzi-** [comment]
对了，可以把adbyby弄进66U 7620N的也是mips74k架构的！断电休息了，88
