### ISSUE TITLE
SSR订阅设置中，最大节点数量为2，不能添加全部的节点。

### ISSUE THREAD

**Issue by shaonanlee** [koolshare/koolshare.github.io#431]
【2017年10月28日 19:10:51】: 检测到ssr节点格式，共计4个节点...
base64: truncated base64 input
base64: truncated base64 input
【2017年10月28日 19:10:51】: 成功添加了添加SSR节点：德国法兰克福1 - Shadowsocks 到节点列表第 2 位。
【2017年10月28日 19:10:51】: 成功添加了添加SSR节点：新加坡 1 - Shadowsocks 到节点列表第 2 位。
【2017年10月28日 19:10:52】: 成功添加了添加SSR节点：日本东京 2 - Shadowsocks 到节点列表第 2 位。
【2017年10月28日 19:10:52】: 成功添加了添加SSR节点：洛杉矶 3 - Shadowsocks 到节点列表第 2 位。
【2017年10月28日 19:10:52】: 最大SSR节点序号：2
【2017年10月28日 19:10:52】: SSR节点数量：2
【2017年10月28日 19:10:52】: 节点排序正确!
【2017年10月28日 19:10:53】: 本次更新订阅来源 ---------， 新增节点 4 个，修改 0 个，删除 0 个；
【2017年10月28日 19:10:53】: 现共有自添加SSR节点：1 个。
【2017年10月28日 19:10:53】: 现共有订阅SSR节点：1 个。
【2017年10月28日 19:10:53】: 在线订阅列表更新完成!

**Comment by antenna2008** [comment]
telegram群里boom pa写道：

curl下载文件，如果服务器有跳转的话就下载不到内容，改为wget会好点
还有add_ssr_servers()和add_ss_servers()的时候，第98和115行，
dbus list ssconf_basic_password是不是应该为dbus list ssconf_basic_password_$ssrindex

![1d49ffac-c667-4ed8-bfe4-3e2f59159310](https://user-images.githubusercontent.com/22744518/32134639-d08d7ec8-bc23-11e7-811d-9328f933bbd4.jpeg)

**Comment by sadoneli** [comment]
3.6.2已解决
