### ISSUE TITLE
3.6.0 无法升级

### ISSUE THREAD

**Issue by dofine** [koolshare/koolshare.github.io#434]
之前一直使用3.6.0，昨天在界面点升级时一直出现这个错误：

/koolshare/scripts/ss_config.sh: line 3: can't fork

接着主界面的提交按钮等也是这样了。。

**Comment by dofine** [comment]
固件升级到 7.7 之后离线安装，成功~

**Comment by sharkman2008cn** [comment]
ss项目已关闭

2017年10月29日 13:14，"Fan Du" <notifications@github.com>写道：

**Comment by dofine** [comment]
@sharkman2008cn 恩呢这个我清楚，之前主界面都没有检查更新的按钮了好像。昨天上去发现有新版本就没忍住点了一下。
