### ISSUE TITLE
我大概找到了外网不能连接的原因。

### ISSUE THREAD

**Issue by CNJiaxuanChen** [koolshare/koolshare.github.io#436]
在手动添加节点或者订阅后在DNS设定和黑白名单中均会出现多行乱码  测试发现有乱码时网页无法打开但是软件可以正常打开，考虑可能与DNS填写乱码有关，清空乱码后可正常使用。希望开发者可以排查乱码原因。谢谢。

**Comment by CNJiaxuanChen** [comment]
![qq 20171029141759](https://user-images.githubusercontent.com/31591610/32141200-f9bd7b18-bcb4-11e7-941d-3e8a5b946f67.jpg)
![qq 20171029141806](https://user-images.githubusercontent.com/31591610/32141201-f9f2d11e-bcb4-11e7-8114-7885d045d4e4.jpg)
![qq 20171029142454](https://user-images.githubusercontent.com/31591610/32141202-fa2463b4-bcb4-11e7-89af-52e3a5f7bf6a.jpg)

**Comment by CNJiaxuanChen** [comment]
大概还不只是添加节点有问题=-=刚才点规则立即更新也有问题 同样会生成乱码=-=
![qq 20171029143908](https://user-images.githubusercontent.com/31591610/32141271-0e7932d4-bcb7-11e7-9a08-26e804bb2a14.jpg)
![qq 20171029143901](https://user-images.githubusercontent.com/31591610/32141272-0ea4cfac-bcb7-11e7-809d-bb018ae3cac6.jpg)

**Comment by fhwo13** [comment]
遇到同样的问题，可以解决但不知道为什么产生。

**Comment by antenna2008** [comment]
用win 10的ie就有乱码，用ipad的safari就没有任何乱码。

**Comment by sadoneli** [comment]
最新版能减少乱码出现几率，目前还没有完全解决使得任何情况下都不产生乱码
