### ISSUE TITLE
延迟显示null问题

### ISSUE THREAD

**Issue by ccinoo** [koolshare/koolshare.github.io#437]
您好：
我是从3.6.0升级到3.6.1后再升级到3.6.2的，web测试“延时”有部分节点显示“null”。
我尝试了“清空结果”按钮，还有重启路由等，没有解决。还是显示“null”。请问如何解决？

非常感谢~~

**Comment by sadoneli** [comment]
null表示不支持进行web测试

**Comment by ccinoo** [comment]
那奇怪了，升级版本之前都可以测试的，服务器端也没有改变过。就升级后出现的这个问题。
