### ISSUE TITLE
订阅不添加协议参数

### ISSUE THREAD

**Issue by zjmhlxp** [koolshare/koolshare.github.io#438]
用WINDOWS的纸飞机测试订阅，可以正常添加协议参数
使用3.6.3版本更新订阅，订阅后，协议参数丢失。

**Comment by helllkz** [comment]
哪里有3.6.3呢？

**Comment by chuan0932** [comment]
3.6.3是民间改版。

**Comment by sadoneli** [comment]
测试了喵帕斯家，没发现问题，估计是你飞机场的订阅链接格式在订阅识别出现问题
