### ISSUE TITLE
关于内网穿透的另一个工具

### ISSUE THREAD

**Issue by niluanxy** [koolshare/koolshare.github.io#44]
折腾了两天，终于按照论坛教程里的把 ngrok 弄好了，然后闲逛的时候了解到，现在用的是1.0版，据说有内存泄漏等问题。然后就找到了另一个东西，貌似是国人做的，不知道楼主能否尝试下，看看和现在的 ngrok 相比哪个好一点，https://github.com/fatedier/frp 这个是地址。

**Comment by jannson** [comment]
ngrok你先试用几天.这个版本也是 golang 写的, golang 的版本不用内存池,容易运行一段时间把内存用光了.

**Comment by niluanxy** [comment]
嗯，我先用着，我说的那个工具可以的话你们可以试试，看那个好


在2016年04月02日 17:02，janson 写道:

ngrok你先试用几天.这个版本也是 golang 写的, golang 的版本不用内存池,容易运行一段时间把内存用光了.

**Comment by jannson** [comment]
好的,感谢. 我可以先编译成路由器版本,如果你需要的话,可以先拿去试用.

**Comment by niluanxy** [comment]
嗯可以，那发我邮箱，我当个测试的，niluanxy@163.com 完了我把使用结果反馈给你


在2016年04月02日 17:36，janson 写道:

好的,感谢. 我可以先编译成路由器版本,如果你需要的话,可以先拿去试用.

**Comment by houzi-** [comment]
可以用一下ngork-c写的！

**Comment by houzi-** [comment]
可以用一下ngork-c写的！

**Comment by niluanxy** [comment]
@jannson ngrok 服务端确定有大问题，我服务端跑了一段时间后，发现另一个同样用 go 写的 git 服务出现了大问题，反应很慢，强制关掉 ngrok 后才好了

**Comment by houzi-** [comment]
@niluanxy 
@jannson 
全静态编译的frp,试一下能不能用吧！
http://pan.baidu.com/s/1dDNAdXn 密码:pldi

**Comment by houzi-** [comment]
在**static**文件夹下

**Comment by jannson** [comment]
感谢。上次看到你的信息，我有空在与你看看 skipd 怎么回事。

**Comment by niluanxy** [comment]
@houzi- 好的，晚上我回去测试

**Comment by niluanxy** [comment]
@houzi- 能否再帮忙编译一个 x86 架构的，我的服务器是 Centos7 x64 的系统，但是你现在编译的只有 arm 版本，没有服务端可用的。

**Comment by niluanxy** [comment]
@houzi- 我这边服务器好慢，输入make一直卡着不动，不知道能否成功

**Comment by niluanxy** [comment]
@houzi- 不用编译了，已经弄好了，测试了下效果还可以，现在在研究怎么把转发到自己的NAS上，和路由器的通讯已经成功了，直接外网打开了路由器的设置界面

**Comment by niluanxy** [comment]
@houzi- 搞不定，能否说下怎么设置，现在可以直接访问到路由器的，但是NAS的不知道怎么转发，开了端口转发但是不行。我的环境是这个样子的，路由器是 192.168.1.1，然后NAS是群晖的，端口是5000，IP是192.168.1.100，现在可以直接穿透访问 192.168.1.1:80。我添加了端口转发，本地测试 192.168.199.1:5000 但是不行，不知道该怎么设置，有空的话麻烦指点一下。

![qq 20160409182821](https://cloud.githubusercontent.com/assets/7076522/14403203/e224b6ae-fe80-11e5-93d0-aa6e2f9d0d71.png)

**Comment by houzi-** [comment]
@niluanxy 
你可以试一下ngork用C重新写的，资源的占用上会有改善！
老规矩（全静态编译）http://pan.baidu.com/s/1dDNAdXn 密码:pldi
项目地址:
https://github.com/dosgo/ngrok-c.git

**Comment by houzi-** [comment]
😄哈哈！好用就好！我用不着这东西

**Comment by niluanxy** [comment]
下一个固件中可以集成吗😊


在2016年04月12日 11:00，PSS 写道:

😄哈哈！好用就好！我用不着这东西

**Comment by rockts** [comment]
ngrok ， 我折腾了一周。 之前客户端用内网电脑都没有 macos , 或者 虚拟机上 centos 都没有问题。
就想放到我的nas 上出的问题比较。基本上都是在我的服务器上编译 客户端的出的问题。老提示要go1.4，google 后说什么交叉编译。试半天无果。
最后用frp,网上随便找一教程都Ok , 客户端放nas , macos 都没问题。

**Comment by despot-zaza** [comment]
ngrok的内存问题应该是UI组件造成的，运行的时候加上 -log=stdout 会禁用UI组件能够解决这个问题。
