### ISSUE TITLE
3.6.3 ping测试和web测试中清空结果会清空所有节点信息

### ISSUE THREAD

**Issue by jwy090815** [koolshare/koolshare.github.io#441]
不小心点了清空结果，配置的参数全部恢复初始状态，但仍然能上谷歌，重启路由器后配置参数没有恢复，谷歌也上不去，还有配置域名黑名单时发现有名单列表凭空消失的情况，需要重新配置，不知道是什么触发的这个bug

**Comment by sadoneli** [comment]
fixed
