### ISSUE TITLE
安装koolproxy后Pcap_DNSProxy失效无法访问国外

### ISSUE THREAD

**Issue by cianyeah** [koolshare/koolshare.github.io#443]
路由器：网件R6250（R6300v2最新固件）

过程是这样的：
前段时间想把DNS设定改为Pcap_DNSProxy模式，修改之后发现国外网站打不开了，SS检测上也显示红色X不可用，当时以为哪里设置有问题，看详细状态里显示Pcap_DNSProxy未运行。

前几天路由器升级了固件，格式化了jffs，先离线安装了SS，发现Pcap_DNSProxy突然能用了，设置方法和之前完全一样，这时候想到会不会是koolproxy的原因导致的。

纠结着用了几天后还是想装koolproxy，于是今天安装了koolproxy，抱着验证之前想法的心态，重启了一下SS，然后……果然跪了，显示Pcap_DNSProxy未运行，重启几次都不行，然后果然卸载koolproxy，卸载后再重启SS，发现Pcap_DNSProxy是运行状态了，但国外还是访问不了。。。

很无语，现在只能用ChinaDNS + ss-tunnel，希望能早点修复这个问题。

**Comment by sadoneli** [comment]
提供不同的方案就是用来选择的，一个不能用选择另一个就行
Pcap_DNSProxy和koolproxy不能同时使用的问题无法重现，尝试添加虚拟内存试试
