### ISSUE TITLE
订阅报错ss_online_update.sh:line 620:arithmetic syntax error

### ISSUE THREAD

**Issue by fuhmin** [koolshare/koolshare.github.io#445]
![qq 20171101163630](https://user-images.githubusercontent.com/26449591/32266668-37e59bda-bf23-11e7-94d4-d33d96179dc6.png)

如题，难道是不支持我买的这家SS的订阅格式？

**Comment by pzman3** [comment]
一样的问题，也是这家的。但是在ANDROID客户端和WINDOWS中都能正常订阅和更新，在梅林中却不能更新。求指引

**Comment by sadoneli** [comment]
服务商的不同订阅链接导致的，我没那么多飞机场用来调试

**Comment by greennyreborn** [comment]
我知道问题了，我和楼主用的是同一家服务商。这家的订阅地址是http，其实会跳转到https。
所以curl http链接的结果是301 跳转，后续解析自然是不对的。

@fuhmin @pzman3 你们暂时可以把链接替换成https来解决

@sadoneli 我提了个PR哈， curl 加个 -L的参数用于获取跳转后的结果 

https://github.com/koolshare/koolshare.github.io/pull/480

**Comment by fuhmin** [comment]
@greennyreborn 我尝试使用https，还是没法订阅，请教解决办法
PS：使用的是3.6.7版本

**Comment by greennyreborn** [comment]
@fuhmin 我已经可以了，页面的输出结果贴一下

**Comment by pzman3** [comment]
@greennyreborn 解决成功。怎么忘了很多订阅都 是HTTPS的啊，应该先自己试下的的。谢谢
