### ISSUE TITLE
ss升级3.6.3后路由器重启后不能ss不能开机自动启动

### ISSUE THREAD

**Issue by cxfly** [koolshare/koolshare.github.io#446]
ss升级3.6.3后路由器重启后不能ss不能开机自动启动

**Comment by Myoko** [comment]
刚刚试过了！可以开启启动。

**Comment by cxfly** [comment]
3.5.9没问题，升级到3.6.0~3.6.3这几个版本都不行，把路由器断电开机后，状态显示进程没有运行
程序		状态	PID
ss-redir	未运行
ss-tunnel	未运行

**Comment by sadoneli** [comment]
无法重现，请检查是否个人行为破坏了开机启动文件
