### ISSUE TITLE
希望能把kcptun和udp2raw-tunnel这个插件整合在ss里面

### ISSUE THREAD

**Issue by elric8** [koolshare/koolshare.github.io#450]
原因现在运营商对udp协议的干扰很厉害，那我举例子上海电信我只要ps4联机有udp加密数据包我的ss国外线路就会被重置，无法ping通，tcp也被断。我的解决方案是用ssr的udp in tcp来解决
但是ssr已经停更了年久失修，最新还在维护的解决方案udp2raw-tunnel（https://github.com/wangyu-/udp2raw-tunnel      @wangyu-，这位大大写的）个人能力不足没法把这个插件装在梅林上。往小宝能采纳，万分感谢！

**Comment by sadoneli** [comment]
kcptun很早就支持了
udp2raw和udpspeeder后续会做支持
