### ISSUE TITLE
R7000 ss-local总是自动停止

### ISSUE THREAD

**Issue by yezigl** [koolshare/koolshare.github.io#451]
R7000 梅林7.6，运行一段时间ss就自动停止了。

详细状态里显示3.6.1，实际安装的是3.6.3。

> ① 程序版本（插件版本：3.6.1）：
> -----------------------------------------------------------
> 程序			版本		备注
> ss-redir		3.1.0		2017年9月25日编译
> ss-tunnel		3.1.0 		2017年9月25日编译
> ss-local		3.1.0		2017年9月25日编译
> obfs-local		0.0.3		2017年9月25日编译
> ssr-redir		2.5.6 		2017年9月25日编译
> ssr-tunnel		2.5.6 		2017年9月25日编译
> ssr-local		2.5.6 		2017年9月25日编译
> client_linux_arm5	20171021	kcptun
> haproxy			1.7.5	
> dns2socks		V2.0 	
> dnscrypt-proxy		1.7.0 	
> ChinaDNS		1.3.2 	
> pndsd			1.2.9a-par 	
> Pcap_DNSProxy		0.4.8.1
> -----------------------------------------------------------
> 
> ② 检测当前相关进程工作状态：（你正在使用SS-libev,选择的模式是【gfwlist模式】,国外DNS解析方案是：dns2socks）
> -----------------------------------------------------------
> 程序		状态	PID
> ss-redir	未运行
> ss-local	未运行
> dns2socks	工作中	pid：1678 1677 1665
> -----------------------------------------------------------
> 
> 
> ③ 检测iptbales工作状态：
> ----------------------------------------------------- nat表 PREROUTING 链 --------------------------------------------------------
> Chain PREROUTING (policy ACCEPT 1081 packets, 95011 bytes)
>  pkts bytes target     prot opt in     out     source               destination         
>   896 65623 KOOLPROXY  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0           
>   889 65303 SHADOWSOCKS  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0           
>     2   128 DNAT       tcp  --  *      *       0.0.0.0/0            192.168.1.1          tcp dpt:80 to:192.168.50.1:18017
>    38 11573 VSERVER    all  --  *      *       0.0.0.0/0            10.34.239.49        
>     0     0 VSERVER    all  --  *      *       0.0.0.0/0            169.254.33.140      
>   317 20466 DNAT       udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:53 to:192.168.50.1
> 
> ----------------------------------------------------- nat表 OUTPUT 链 ------------------------------------------------------------
> Chain OUTPUT (policy ACCEPT 903 packets, 59542 bytes)
>  pkts bytes target     prot opt in     out     source               destination         
>     0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set router dst redir ports 3333
>    56  3360 SHADOWSOCKS_EXT  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0xc0a83200/0xffffff00
> 
> ----------------------------------------------------- nat表 SHADOWSOCKS 链 --------------------------------------------------------
> Chain SHADOWSOCKS (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
>   653 50330 RETURN     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set white_list dst
>   237 15037 SHADOWSOCKS_GFW  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0           
> 
> ----------------------------------------------------- nat表 SHADOWSOCKS_EXT 链 --------------------------------------------------------
> Chain SHADOWSOCKS_EXT (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
>    56  3360 SHADOWSOCKS_GFW  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0           
> 
> ----------------------------------------------------- nat表 SHADOWSOCKS_GFW 链 ----------------------------------------------------
> Chain SHADOWSOCKS_GFW (2 references)
>  pkts bytes target     prot opt in     out     source               destination         
>     0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set black_list dst redir ports 3333
>     0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set gfwlist dst redir ports 3333
> 
> ----------------------------------------------------- nat表 SHADOWSOCKS_CHN 链 -----------------------------------------------------
> Chain SHADOWSOCKS_CHN (0 references)
>  pkts bytes target     prot opt in     out     source               destination         
>     0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set black_list dst redir ports 3333
>     0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            ! match-set chnroute dst redir ports 3333
> 
> ----------------------------------------------------- nat表 SHADOWSOCKS_GAM 链 -----------------------------------------------------
> Chain SHADOWSOCKS_GAM (0 references)
>  pkts bytes target     prot opt in     out     source               destination         
>     0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set black_list dst redir ports 3333
>     0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            ! match-set chnroute dst redir ports 3333
> 
> ----------------------------------------------------- nat表 SHADOWSOCKS_GLO 链 -----------------------------------------------------
> Chain SHADOWSOCKS_GLO (0 references)
>  pkts bytes target     prot opt in     out     source               destination         
>     0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            redir ports 3333
> 
> ----------------------------------------------------- nat表 SHADOWSOCKS_HOM 链 -----------------------------------------------------
> Chain SHADOWSOCKS_HOM (0 references)
>  pkts bytes target     prot opt in     out     source               destination         
>     0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set black_list dst redir ports 3333
>     0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set chnroute dst redir ports 3333
> -----------------------------------------------------------------------------------------------------------------------------------
> 
> -----------------------------------------------------------------------------------------------------------------------------------

**Comment by yezigl** [comment]
This system doesn't provide enough entropy to quickly generate high-quality random numbers Installing the rng-utils/rng-tools or haveged packages may help. On virtualized Linux environments, also consider using virtio-rng. The service will not start until enough entropy has been collected.

**Comment by lzfmars** [comment]
请问你有用混淆功能吗？我这边开了混淆功能，貌似路由器出现PPPOE重新拨号会出现进程自动停止

**Comment by yezigl** [comment]
用了混淆功能，没注意是不是pppoe引起的，后来升级到7.7，报错不是下面那个了，偶尔也会自动停止，但没有7.6那么频繁了
