### ISSUE TITLE
3.6.3在移动设备中查看节点管理会出现bug

### ISSUE THREAD

**Issue by yyxida** [koolshare/koolshare.github.io#454]
3.6.3在移动设备中查看节点管理会出现节点列表过高盖过上栏选单的bug，问题在于我的节点数量过多，大概有200个

另外提两个建议
1，希望加入Group的显示选择开关
由于订阅功能的引入，现在会在“账号设置”的“节点选择"中显示Group
这样就会使节点名显示过长，不方便移动设备选择节点

2，希望加入订阅白名单
因为有些人只会使用部分国家/地区的节点
但现在订阅功能不可选择性的订阅
所以希望可以加入订阅白名单的功能
比如白名单设置“”日本，上海“”那么在更新订阅的时候就会排除名称带日本，上海以外的节点

**Comment by sadoneli** [comment]
请在电脑上使用chrome浏览器，其它浏览器没法一一修正和支持
