### ISSUE TITLE
3.6.3中ss-local、ss-redir莫名消失

### ISSUE THREAD

**Issue by lzfmars** [koolshare/koolshare.github.io#455]
查看/tmp/syslog.log发现此记录：
Nov  3 18:10:51 pppd[713]: LCP terminated by peer                                 
Nov  3 18:10:51 pppd[713]: Connect time 2875.0 minutes.                           
Nov  3 18:10:51 pppd[713]: Sent 3620326841 bytes, received 1491742648 bytes.      
Nov  3 18:10:51 miniupnpd[15559]: Failed to get IP for interface ppp0             
Nov  3 18:10:51 miniupnpd[15559]: SendNATPMPPublicAddressChangeNotification: cannot get public IP address, stopping
Nov  3 18:10:51 dnsmasq[5645]: read /etc/hosts - 5 addresses                       
Nov  3 18:10:51 dnsmasq[5645]: read /etc/hosts.dnsmasq - 1 addresses               
Nov  3 18:10:51 dnsmasq-dhcp[5645]: read /etc/ethers - 1 addresses                 
Nov  3 18:10:51 dnsmasq[5645]: using nameserver 127.0.0.1#7913 for domain zzux.com 
。。。。。。
Nov  3 18:10:51 dnsmasq[5645]: using nameserver 127.0.0.1#7913 for domain zh.wikisource.org
Nov  3 18:10:51 dnsmasq[5645]: using 44325 more nameservers                        
Nov  3 18:10:54 pppd[713]: Connection terminated.                                   
Nov  3 18:10:54 pppd[713]: Sent PADT                                                   
Nov  3 18:10:54 pppd[713]: Modem hangup                                            
Nov  3 18:10:54 kernel: EMF_ERROR: Interface ppp0 doesn't exist                   
Nov  3 18:10:54 kernel: EMF_ERROR: Interface ppp0 doesn't exist                   
Nov  3 18:10:56 WAN_Connection: Fail to connect with some issues.                 
Nov  3 18:10:56 DualWAN: skip single wan wan_led_control - WANRED off             
Nov  3 18:10:56 stop_nat_rules: apply the redirect_rules!                         
Nov  3 18:11:04 pppd[713]: PPP session is 51328 (0xc880)                          
Nov  3 18:11:04 pppd[713]: Connected to 5c:33:3b:7f:bb:c8 via interface eth0                                       
Nov  3 18:11:04 pppd[713]: Using interface ppp0                                    
Nov  3 18:11:04 pppd[713]: Connect: ppp0 <--> eth0                                 
Nov  3 18:11:04 pppd[713]: syncppp: first pppd checked, waitting for 2 second      
Nov  3 18:11:06 pppd[713]: Remote message: Authentication Successful,Welcome!      
Nov  3 18:11:06 pppd[713]: PAP authentication succeeded                                
Nov  3 18:11:06 pppd[713]: peer from calling number 5C:33:3B:7F:BB:C8 authorized   
Nov  3 18:11:07 miniupnpd[15559]: Failed to get IP for interface ppp0              
Nov  3 18:11:07 miniupnpd[15559]: SendNATPMPPublicAddressChangeNotification: cannot get public IP address, stopping
Nov  3 18:11:07 miniupnpd[15559]: Failed to get IP for interface ppp0                
Nov  3 18:11:07 miniupnpd[15559]: SendNATPMPPublicAddressChangeNotification: cannot get public IP address, stopping
Nov  3 18:11:07 miniupnpd[15559]: Failed to get IP for interface ppp0              
Nov  3 18:11:07 miniupnpd[15559]: SendNATPMPPublicAddressChangeNotification: cannot get public IP address, stopping
Nov  3 18:11:07 pppd[713]: local  IP address 100.64.xxx.xxx                          
Nov  3 18:11:07 pppd[713]: remote IP address 100.64.0.1                             
Nov  3 18:11:07 custom_script: Running /jffs/scripts/wan-start (args: 0)            
Nov  3 18:11:07 rc_service: ip-up 2051:notify_rc start_firewall                    
Nov  3 18:11:07 dnsmasq[5645]: read /etc/hosts - 5 addresses                          
Nov  3 18:11:07 dnsmasq[5645]: read /etc/hosts.dnsmasq - 1 addresses                          
Nov  3 18:11:07 dnsmasq-dhcp[5645]: read /etc/ethers - 1 addresses                   
Nov  3 18:11:07 dnsmasq[5645]: using nameserver 127.0.0.1#7913 for domain zzux.com        
。。。。。。
Nov  3 18:11:07 dnsmasq[5645]: using nameserver 127.0.0.1#7913 for domain zh.wikisource.org
Nov  3 18:11:07 dnsmasq[5645]: using 44325 more nameservers                            
Nov  3 18:11:07 syslog: [server] Failed to find any available port!                  
Nov  3 18:11:07 syslog: [server] Aborting...                                                                       
Nov  3 18:11:07 syslog: Check failed at shellinabox/launcher.c:721 in closeAllFds(): nullFd > 2
Nov  3 18:11:07 syslog: [server] Aborting...                                                                       
Nov  3 18:11:07 miniupnpd[15559]: shutting down MiniUPnPd                                 
Nov  3 18:11:07 start_nat_rules: apply the nat_rules(/tmp/nat_rules_ppp0_eth0)!                                    
Nov  3 18:11:07 custom_script: Running /jffs/scripts/nat-start                          
Nov  3 18:11:08 miniupnpd[2173]: HTTP listening on port 49181                                                                                                                                                  
Nov  3 18:11:08 miniupnpd[2173]: Listening for NAT-PMP/PCP traffic on port 5351     
Nov  3 18:11:09 rc_service: ip-up 2051:notify_rc stop_upnp                          
Nov  3 18:11:09 rc_service: ip-up 2051:notify_rc start_upnp                           
Nov  3 18:11:09 rc_service: waitting "stop_upnp" via ip-up ...                                
Nov  3 18:11:09 miniupnpd[2173]: shutting down MiniUPnPd                                                                                                                                                       
Nov  3 18:11:10 ntp: start NTP update                                                     
Nov  3 18:11:10 miniupnpd[2232]: HTTP listening on port 51160                             
Nov  3 18:11:10 miniupnpd[2232]: Listening for NAT-PMP/PCP traffic on port 5351  
Nov  3 18:11:10 miniupnpd[2232]: Listening for NAT-PMP/PCP traffic on port 5351           
Nov  3 18:11:12 WAN_Connection: WAN was restored.                                             
Nov  3 18:11:14 rc_service: ip-up 2051:notify_rc start_firewall                            
Nov  3 18:11:15 miniupnpd[2232]: shutting down MiniUPnPd                             
Nov  3 18:11:15 start_nat_rules: apply the nat_rules(/tmp/nat_rules_ppp0_eth0)!      
Nov  3 18:11:15 custom_script: Running /jffs/scripts/nat-start                              
Nov  3 18:11:16 miniupnpd[2508]: HTTP listening on port 38833                       
Nov  3 18:11:16 miniupnpd[2508]: Listening for NAT-PMP/PCP traffic on port 5351     
Nov  3 18:11:20 ss-local[2769]: initializing ciphers... chacha20-ietf-poly1305            
Nov  3 18:11:20 ss-local[2769]: This system doesn't provide enough entropy to quickly generate high-quality random numbers Installing the rng-utils/rng-tools or haveged packages may help. On virtualized Linu
Nov  3 18:11:20 ss-local[2769]: udprelay enabled                                              
Nov  3 18:11:20 ss-local[2769]: listening at 0.0.0.0:23456                                    
Nov  3 18:11:20 ss-local[2769]: running from root user                                     
### _**Nov  3 18:11:20 ss-local[2769]: plugin service exit unexpectedly**_                     
Nov  3 18:11:20 ss-redir[2793]: initializing ciphers... chacha20-ietf-poly1305            
Nov  3 18:11:20 ss-redir[2793]: This system doesn't provide enough entropy to quickly generate high-quality random numbers Installing the rng-utils/rng-tools or haveged packages may help. On virtualized Linu
Nov  3 18:11:20 ss-redir[2793]: UDP relay enabled                                       
Nov  3 18:11:20 ss-redir[2793]: listening at 0.0.0.0:3333                           
Nov  3 18:11:20 ss-redir[2793]: running from root user                                 
### **_Nov  3 18:11:20 ss-redir[2793]: plugin service exit unexpectedly_**                                      
Nov  3 18:11:55 rc_service: service 3492:notify_rc restart_dnsmasq                 
Nov  3 18:11:55 dnsmasq[5645]: exiting on receipt of SIGTERM                          
Nov  3 18:11:55 custom_script: Running /jffs/scripts/dnsmasq.postconf (args: /etc/dnsmasq.conf)                    
Nov  3 18:11:57 dnsmasq[3641]: started, version 2.78 cachesize 9999                  
Nov  3 18:11:57 dnsmasq[3641]: warning: ignoring resolv-file flag because no-resolv is set
Nov  3 18:11:57 dnsmasq[3641]: asynchronous logging enabled, queue limit is 5 messages
Nov  3 18:11:57 dnsmasq-dhcp[3641]: DHCP, IP range 192.168.0.2 -- 192.168.0.254, lease time 1d
Nov  3 18:11:57 dnsmasq[3641]: using nameserver 127.0.0.1#7913 for domain zzux.com         
。。。。。。

没有进行任何动作，回家就发现路由器这两个进程消失。

**Comment by cxfly** [comment]
我也报同样的问题，每次关闭或重启路由器后，ss没有开机自动启动。

① 程序版本（插件版本：3.6.1）：
-----------------------------------------------------------
程序			版本		备注
ss-redir		3.1.0		2017年9月25日编译
ss-tunnel		3.1.0 		2017年9月25日编译
ss-local		3.1.0		2017年9月25日编译
obfs-local		0.0.3		2017年9月25日编译
ssr-redir		2.5.6 		2017年9月25日编译
ssr-tunnel		2.5.6 		2017年9月25日编译
ssr-local		2.5.6 		2017年9月25日编译
client_linux_arm5	20171021	kcptun
haproxy			1.7.5	
dns2socks		V2.0 	
dnscrypt-proxy		1.7.0 	
ChinaDNS		1.3.2 	
pndsd			1.2.9a-par 	
Pcap_DNSProxy		0.4.8.1
-----------------------------------------------------------

② 检测当前相关进程工作状态：（你正在使用SS-libev,选择的模式是【大陆白名单模式】,国外DNS解析方案是：pdnsd）
-----------------------------------------------------------
程序		状态	PID
ss-redir	未运行
ss-tunnel	未运行
pdnsd		工作中	pid：2060 2059 2056 2025
-----------------------------------------------------------

**Comment by sadoneli** [comment]
检查你的ss.json文件是否生成正确

**Comment by lzfmars** [comment]
@sadoneli 就这样提交启动ss没有问题，过一段时间才出现ss-local、ss-redir进程消失；从日志来看像是电信PPPOE出现重新拨号时候，ss启动（restart？）的时候obfs-local插件无法启动？

进程消失之后，在网页重新提交一次，又可以使用了

**Comment by lzfmars** [comment]
3.6.4仍然这样，3.6.5待观察

**Comment by lzfmars** [comment]
3.7.x版本使用正常，关闭
