### ISSUE TITLE
为何ss里面没有chacha20-itef-poly135

### ISSUE THREAD

**Issue by wubin223** [koolshare/koolshare.github.io#457]
为何ss里面没有chacha20-itef-poly135

**Comment by Myoko** [comment]
没有就是没有支持！等吧

**Comment by liyiecho** [comment]
chacha20-itef-poly135是什么鬼，不应该是chacha20-ietf-poly1305嘛？
chacha20-ietf-poly1305是有的，如图所示
![3073b9c4-f221-4a31-bce7-18314d39ad42](https://user-images.githubusercontent.com/5213722/32401339-36adf462-c147-11e7-8183-edd4dc8fbf73.png)

**Comment by shui02666888** [comment]
chacha20-ietf-poly1305是有，但是无法使用

**Comment by liyiecho** [comment]
等等，你们是使用SS什么版本的啊？

**Comment by shui02666888** [comment]
3.6.4最新版

**Comment by liyiecho** [comment]
@shui02666888 我的正常使用，

**Comment by shui02666888** [comment]
服务端加密方式chacha20-ietf-poly1305，梅林的ss3.6.4无法使用，windows的shadowsocks 4.0.6正常

**Comment by shui02666888** [comment]
@liyiecho 路由固件是7.7，我还特意格式化过，依然不行

**Comment by sadoneli** [comment]
不能重现
