### ISSUE TITLE
大陆白名单模式下，只重定br0的流量至redsocks

### ISSUE THREAD

**Issue by Enzo-Liu** [koolshare/koolshare.github.io#46]
我在使用openvpn的时候，发现从vpn来的流量没有翻墙。
shadowsocks切换成其他模式没有问题。

看了一下代码，在重定向流量的时候，

        # 重定所有流量到 REDSOCKS2
        iptables -t nat -A PREROUTING -i br0 -p tcp -j REDSOCKS2

这里限定了 -i br0

我修改了网卡的限定之后就工作的很正常。

不知道有没有什么特别的考虑？

**Comment by jannson** [comment]
估计是写错了！
如果限定 br0 openvpn 就无法使用了。

**Comment by sadoneli** [comment]
我会测试后改过来的

**Comment by sadoneli** [comment]
https://github.com/koolshare/koolshare.github.io/commit/7be025031d2cdff93b3155fef95ed78d4bd05927#diff-9803b3f71732e2949cfa1fcf94f43687R67
