### ISSUE TITLE
3.6.x外网出错，3.59就没问题，和解？

### ISSUE THREAD

**Issue by hellojiaru** [koolshare/koolshare.github.io#460]
从3.6.3一直装到3.6.1都不行，总是外网不能访问，最后换到3.5.9就可以了。但是我又需要用到3.6.x的指定IP强制代理功能，怎么办啊，好头大

**Comment by sadoneli** [comment]
指定IP强制代理功能是什么？

**Comment by pengweiqhca** [comment]
指IP黑名单吧

**Comment by sadoneli** [comment]
IP黑名单 所有版本都有此功能

**Comment by hellojiaru** [comment]
还真有。。怪了，昨天看还没有的，黑白名单那个选项卡只有2个输入框，今天一看变4个了。。。

**Comment by hellojiaru** [comment]
@sadoneli  IP黑名单有数量限制吗？我导入了2200个IP，但是最后里面保存的只有1900多个

**Comment by cxfly** [comment]
3.5.9后，ss进程开机启动失败了，需要手动重启下 

程序 状态 PID
ss-redir 未运行
ss-tunnel 未运行

**Comment by sadoneli** [comment]
不建议填写很多，默认已经有分流了
回国模式下只有两个，其它是4个
ss进程这个无法重现，可能是其它原因
