### ISSUE TITLE
节点订阅功能保存之后能不能把地址隐藏一下，比如换成********之类的

### ISSUE THREAD

**Issue by kangmya** [koolshare/koolshare.github.io#462]
节点订阅功能保存之后能不能把地址隐藏一下，比如换成********之类的，地址万一泄露就会比较麻烦了，还有节点管理里面的密码也可以隐藏一下的

**Comment by sadoneli** [comment]
泄露行为一般是个人截图造成的，插件管理表格内密码信息并未显示，如果需要更加保密，请点击核科技按钮
