### ISSUE TITLE
更新3.6.4后无法国外

### ISSUE THREAD

**Issue by virtualcca** [koolshare/koolshare.github.io#463]
某第三方购买的ss账号，所以服务器配置不详
更新3.6.4后总是国外连接不通
但是电脑本机用shadowsockes 4.0.6(windows版)是一切都好的
更新前用3.6.3也是ok的

**Comment by havoctang** [comment]
我也是，还以为服务器问题，自搭和买的都不行

**Comment by laozhou1688** [comment]
3.6.3升级3.6.4不能用  ,在系统用Shadowsocks-4.0.6可以

**Comment by havoctang** [comment]
重新安装了服务端，可用了，但是经常pd，重启后一段时间正常，不知道是不是gfw阻拦

**Comment by virtualcca** [comment]
gfw阻拦解释不通为啥本地用shadowsockes 4.0.6是可以的。。。。

**Comment by wulol** [comment]
我刚从3.6.0升到3.6.4也是不能外网，心想，这也被和谐了吗，经过一番排查发现是设置问题。
进入节点里面有些参数没有自动配置，手动加上后就好了。我的情况是SSR设置有单端口多用户，每个用户有如同XXX:password形式的密码，填入后正常了。

**Comment by HakunaMatataLLL** [comment]
我也是这个问题，请问你解决了吗？

**Comment by cxfly** [comment]
3.5.9后，ss进程开机启动失败了，需要手动重启下 ，期待能下个版本修复掉

程序 状态 PID
ss-redir 未运行
ss-tunnel 未运行
