### ISSUE TITLE
订阅无法修改节点

### ISSUE THREAD

**Issue by antenna2008** [koolshare/koolshare.github.io#465]
日志如下

2017年11月06日 06:25:16】: 开始解析节点信息...
【2017年11月06日 06:25:17】: 检测到ssr节点格式，共计4个节点...
help:
dbus set key=value
dbus ram key=value
dbus replace key=value
dbus get key
dbus list key
dbus remove key
dbus export key
dbus update key
dbus delay key tick path_of_shell.sh
dbus time key H:M:S path_of_shell.sh
dbus fire key
dbus event key path_of_shell.sh
dbus inc key=value
dbus desc key=value
help:
dbus set key=value
dbus ram key=value
dbus replace key=value
dbus get key
dbus list key
dbus remove key
dbus export key
dbus update key
dbus delay key tick path_of_shell.sh
dbus time key H:M:S path_of_shell.sh
dbus fire key
dbus event key path_of_shell.sh
dbus inc key=value
dbus desc key=value
help:
dbus set key=value
dbus ram key=value
dbus replace key=value
dbus get key
dbus list key
dbus remove key
dbus export key
dbus update key
dbus delay key tick path_of_shell.sh
dbus time key H:M:S path_of_shell.sh
dbus fire key
dbus event key path_of_shell.sh
dbus inc key=value
dbus desc key=value
help:
dbus set key=value
dbus ram key=value
dbus replace key=value
dbus get key
dbus list key
dbus remove key
dbus export key
dbus update key
dbus delay key tick path_of_shell.sh
dbus time key H:M:S path_of_shell.sh
dbus fire key
dbus event key path_of_shell.sh
dbus inc key=value
dbus desc key=value
help:
dbus set key=value
dbus ram key=value
dbus replace key=value
dbus get key
dbus list key
dbus remove key
dbus export key
dbus update key
dbus delay key tick path_of_shell.sh
dbus time key H:M:S path_of_shell.sh
dbus fire key
dbus event key path_of_shell.sh
dbus inc key=value
dbus desc key=value
help:
dbus set key=value
dbus ram key=value
dbus replace key=value
dbus get key
dbus list key
dbus remove key
dbus export key
dbus update key
dbus delay key tick path_of_shell.sh
dbus time key H:M:S path_of_shell.sh
dbus fire key
dbus event key path_of_shell.sh
dbus inc key=value
dbus desc key=value
help:
dbus set key=value
dbus ram key=value
dbus replace key=value
dbus get key
dbus list key
dbus remove key
dbus export key
dbus update key
dbus delay key tick path_of_shell.sh
dbus time key H:M:S path_of_shell.sh
dbus fire key
dbus event key path_of_shell.sh
dbus inc key=value
dbus desc key=value
help:
dbus set key=value
dbus ram key=value
dbus replace key=value
dbus get key
dbus list key
dbus remove key
dbus export key
dbus update key
dbus delay key tick path_of_shell.sh
dbus time key H:M:S path_of_shell.sh
dbus fire key
dbus event key path_of_shell.sh
dbus inc key=value
dbus desc key=value
help:
dbus set key=value
dbus ram key=value
dbus replace key=value
dbus get key
dbus list key
dbus remove key
dbus export key
dbus update key
dbus delay key tick path_of_shell.sh
dbus time key H:M:S path_of_shell.sh
dbus fire key
dbus event key path_of_shell.sh
dbus inc key=value
dbus desc key=value
【2017年11月06日 06:25:19】: 修改SSR节点：新加坡 1 - 443 端口单端口多用户
help:
dbus set key=value
dbus ram key=value
dbus replace key=value
dbus get key
dbus list key
dbus remove key
dbus export key
dbus update key
dbus delay key tick path_of_shell.sh
dbus time key H:M:S path_of_shell.sh
dbus fire key
dbus event key path_of_shell.sh
dbus inc key=value
dbus desc key=value
help:
dbus set key=value
dbus ram key=value
dbus replace key=value
dbus get key
dbus list key
dbus remove key
dbus export key
dbus update key
dbus delay key tick path_of_shell.sh
dbus time key H:M:S path_of_shell.sh
dbus fire key
dbus event key path_of_shell.sh
dbus inc key=value
dbus desc key=value
help:
dbus set key=value
dbus ram key=value
dbus replace key=value
dbus get key
dbus list key
dbus remove key
dbus export key
dbus update key
dbus delay key tick path_of_shell.sh
dbus time key H:M:S path_of_shell.sh
dbus fire key
dbus event key path_of_shell.sh
dbus inc key=value
dbus desc key=value
help:
dbus set key=value
dbus ram key=value
dbus replace key=value
dbus get key
dbus list key
dbus remove key
dbus export key
dbus update key
dbus delay key tick path_of_shell.sh
dbus time key H:M:S path_of_shell.sh
dbus fire key
dbus event key path_of_shell.sh
dbus inc key=value
dbus desc key=value
help:
dbus set key=value
dbus ram key=value
dbus replace key=value
dbus get key
dbus list key
dbus remove key
dbus export key
dbus update key
dbus delay key tick path_of_shell.sh
dbus time key H:M:S path_of_shell.sh
dbus fire key
dbus event key path_of_shell.sh
dbus inc key=value
dbus desc key=value
help:
dbus set key=value
dbus ram key=value
dbus replace key=value
dbus get key
dbus list key
dbus remove key
dbus export key
dbus update key
dbus delay key tick path_of_shell.sh
dbus time key H:M:S path_of_shell.sh
dbus fire key
dbus event key path_of_shell.sh
dbus inc key=value
dbus desc key=value
help:
dbus set key=value
dbus ram key=value
dbus replace key=value
dbus get key
dbus list key
dbus remove key
dbus export key
dbus update key
dbus delay key tick path_of_shell.sh
dbus time key H:M:S path_of_shell.sh
dbus fire key
dbus event key path_of_shell.sh
dbus inc key=value
dbus desc key=value
help:
dbus set key=value
dbus ram key=value
dbus replace key=value
dbus get key
dbus list key
dbus remove key
dbus export key
dbus update key
dbus delay key tick path_of_shell.sh
dbus time key H:M:S path_of_shell.sh
dbus fire key
dbus event key path_of_shell.sh
dbus inc key=value
dbus desc key=value
help:
dbus set key=value
dbus ram key=value
dbus replace key=value
dbus get key
dbus list key
dbus remove key
dbus export key
dbus update key
dbus delay key tick path_of_shell.sh
dbus time key H:M:S path_of_shell.sh
dbus fire key
dbus event key path_of_shell.sh
dbus inc key=value
dbus desc key=value
【2017年11月06日 06:25:21】: 修改SSR节点：美国 3 - 443 端口单端口多用户
【2017年11月06日 06:25:21】: 最大SSR节点序号：25
【2017年11月06日 06:25:21】: SSR节点数量：25
【2017年11月06日 06:25:21】: 节点排序正确!
【2017年11月06日 06:25:22】: 本次更新订阅来源 【神网加速器】， 新增节点 0 个，修改 2 个，删除 0 个；
【2017年11月06日 06:25:22】: 现共有自添加SSR节点：2 个。
【2017年11月06日 06:25:22】: 现共有订阅SSR节点：17 个。
【2017年11月06日 06:25:22】: 在线订阅列表更新完成!

**Comment by sadoneli** [comment]
节点没写入成功

**Comment by sadoneli** [comment]
需要具体飞机场的订阅链接才能调试，暂时没法解决
