### ISSUE TITLE
建议增加6个模式：“（默认）不通过SS模式”，“禁止网络模式”，“屏蔽大陆白名单模式”，“屏蔽GFWLIST模式”，“仅大陆白名单模式”，“仅GFWLIST模式”

### ISSUE THREAD

**Issue by RigHakiko** [koolshare/koolshare.github.io#467]
“（默认）不通过SS模式”：现在的“不通过SS”只能对某个设备使用，而不能设置为默认。而我的家里有多个设备，只有个别设备要翻墙，而且有时客人也会连接WIFI，所以能否在默认模式中加入不通过SS模式呢（只有被设置的设备才能翻墙）；（因为没有这个功能，我手动又加了230多个规则，正好一共254个（没有0个1））

“禁止网络模式”：禁止相应设备的连网（Merlin的家长控制功能太弱了，最多只能禁止32个设备的连网）；

“屏蔽大陆白名单模式”：屏蔽大陆白名单中的网站；

“屏蔽GFWLIST模式”：这与“不通过SS模式”不同的是，它直接屏蔽掉对GFWLIST中网站的访问，使GFW不会检测到任何行为；

“仅大陆白名单模式”：只能访问大陆白名单中的网站；

“仅GFWLIST模式”：只能访问GFWLIST中的网站（通过代理）；

**Comment by sadoneli** [comment]
默认模式只能是 当前节点的模式或者不通过ss两种选择

**Comment by antenna2008** [comment]
太复杂了

**Comment by sadoneli** [comment]
默认模式只能是 当前节点的模式  或者  不通过ss  两种选择，不复杂的
