### ISSUE TITLE
订阅报错

### ISSUE THREAD

**Issue by greennyreborn** [koolshare/koolshare.github.io#468]
报错信息: /koolshare/scripts/ss_online_update.sh: line 620: arithmetic syntax error

**Comment by guqikay** [comment]
我是提示 7.7固件可以订阅，然后就没了

**Comment by pzman3** [comment]
一样的问题。但是在ANDROID客户端和WINDOWS中都能正常订阅和更新，在梅林中却不能更新。求指引

**Comment by sadoneli** [comment]
可能是飞机场不同订阅格式造成的，没有条件一一调试
