### ISSUE TITLE
R6900，用游戏V2模式，会使路由重启

### ISSUE THREAD

**Issue by MikeNg2018** [koolshare/koolshare.github.io#469]
R6900，固件7.7，用游戏V2模式（3.6.4），PS4联机时，路由器会自动重启（从3.6开始就是这样），请问如何解决？

**Comment by lingaoyi** [comment]
半年前我就说过了，但好像后来没人回复我，现在都不敢用v2了。
https://github.com/koolshare/koolshare.github.io/issues/346

**Comment by sadoneli** [comment]
golang程序运行请添加虚拟内存
