### ISSUE TITLE
求解决下在[大陆白名单模式]下Mac苹果地图强制使用TomTom数据？

### ISSUE THREAD

**Issue by lingaoyi** [koolshare/koolshare.github.io#47]
显示数据由 ￼TomTom 等提供 ￼，能不能在白名单下恢复正常显示方式，我记得默认使用境内的数据是AutoNavi数据的，谢谢！

**Comment by sadoneli** [comment]
大陆白名单模式使用的ip名单来源于chinands项目内的chnroute.txt：
<pre>curl 'http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest' | grep ipv4 | grep CN | awk -F\| '{ printf("%s/%d\n", $4, 32-log($5)/log(2)) }' > chnroute.txt</pre>
具体需要什么走国内什么走国外，我们没有精力去维护，请自行在大陆白名单模式高级设置中添加你需要的方式。

**Comment by lingaoyi** [comment]
其实我也不知道那个IP是地图数据 Orz。。。

**Comment by sadoneli** [comment]
这个应该可以通过抓包得到，你可以尝试下，大陆白名单的宗旨就是除了大陆ip段，其它都走ss，不管是否被墙。
个别的ip和域名，可以通过高级设置，来设置黑白名单，应该能满足绝大部分的需求。
