### ISSUE TITLE
在laptop上用ss可连，但是在路由上不工作

### ISSUE THREAD

**Issue by ChuPa1980** [koolshare/koolshare.github.io#470]
在Azure上自建的SS,用的docker
https://hub.docker.com/r/mritd/shadowsocks/
shadowsocks-libev 版本: 3.1.0
kcptun 版本: 20171021
手机wingy,电脑SS client都可以工作

在路由上
国外连接 - Problem detected!
国内连接 - working...
路由是AC68U刷的merlin 380.63_X7.2
SS 3.6.0

尝试了恢复出厂设置和格式化jffs分区,无果.
不清楚是不是哪个部件版本不一致造成的?
望给点提示.谢谢.

**Comment by sadoneli** [comment]
我也不清楚，先升级到7.7看看

**Comment by sadoneli** [comment]
尝试更换dns解析方案
