### ISSUE TITLE
R8500/Merlin7.7/shadowsocks3.6.4，国外连接problem detected

### ISSUE THREAD

**Issue by HakunaMatataLLL** [koolshare/koolshare.github.io#473]
ss节点没有问题，纸飞机（4.0.2）使用正常

在插件上设置好之后，刚开始国外连接是working，然后就一直problem detected，分流检测里三个框都有ip地址，可以打开youtube等网站，但是开的时候非常慢，开起来之后看视频什么就正常了

各种模式都试过，刚换模式的时候是working，然后就problem detected

DNS也换过一遍，也是刚换的时候是working，然后就problem detected

**Comment by sadoneli** [comment]
请检查线路
