### ISSUE TITLE
SSH无法远程登录

### ISSUE THREAD

**Issue by NeoZZZZ** [koolshare/koolshare.github.io#48]
局域网可以，wan登录的话在验证用户名密码前就断开，目测Allow SSH access from WAN 选项失效。如何解决？
LOG：
Apr  7 10:57:26 dropbear[8250]: Child connection from 60.2.44.XXX:2008
Apr  7 10:57:26 dropbear[8250]: Exit before auth: Exited normally

**Comment by sadoneli** [comment]
请尝试端口转发
