### ISSUE TITLE
3.6.7导致路由器重启，国外连接为X

### ISSUE THREAD

**Issue by liuguangmao** [koolshare/koolshare.github.io#489]
3.6.7在修改参数过程中会导致路由器重启，梅林7.7固件，netgear R6300v2.
国外连接无论怎么配置dns，国外连接都是X，已确认ss服务器可以正常响应，使用SSpc客户端可以正常使用。

**Comment by crazymjj** [comment]
同样的毛病7.7，刷回7.6，复位R7000，重新安装SS3.6.7解决问题
