### ISSUE TITLE
ss在电脑上配置可以访问google，但是在路由器上就不行

### ISSUE THREAD

**Issue by shellus** [koolshare/koolshare.github.io#49]
自己搭建的ss在电脑上配置可以访问google，但是在路由器上就不行.
也尝试过使用别人的开放ss服务器，都是在本机测试可用，路由器上配置就不行

无论我如何配置，始终提示：
国外连接 - [ 2016-04-07 12:18:02 ] Problem detected! 
国内连接 - [ 2016-04-07 12:18:02 ] working...

按照网上的方法清空过 JFFS ，也是不行。
更关键的问题是，我新开一个窗口来查看Shadowsocks日志，然后在基本设置页面更改设置后，在日志窗口根本看不到任何输出。
所以我无法找到问题出现的原因及解决办法。

我使用网件6300V2，梅林固件：380.57_X6.5
Shadowsocks版本：1.3.7

可以使用ssh登陆。

请问我该如何知道出现了什么问题？

**Comment by shellus** [comment]
刚才我手动启动服务器上面的ss-server.查看输出。
使用电脑连接时是正常输出访问的url。
使用路由器配置时没有任何输出。
说明路由器根本没有发送任何数据包到我的ss服务器。
路由器配置中使用ip或域名都是这样

**Comment by shellus** [comment]
我想我快要发现问题所在了，我的路由器ip是192.168.2.1。
而我在 /jffs/configs/dnsmasq.conf.add 文件中发现了显式定义的 192.168.1.1 
而这个值，是由 /jffs/.koolshare/ss/ipset/start.sh:94 中的：
```bash
# append router output chain rules for ss status check
echo $(date): append router output chain rules
cat /koolshare/ss/redchn/output.conf >> /jffs/configs/dnsmasq.conf.add
echo $(date): done
echo $(date):

```
跟踪到的。
我会继续寻找原因

**Comment by shellus** [comment]
我发现我错了。
这里的server=192.168.1.1
其实是dns_server。那么就应该是192.168.1.1没错。
唉，线索又断了。

**Comment by shellus** [comment]
状态检查原来是使用：
```bash
wget -4 --spider --quiet --tries=2 --timeout=2 www.google.com.tw
```
实现的。那么wget -4是什么意思呢?

**Comment by shellus** [comment]
虽然不知道为什么wget -4 ,但是应该是错误码之类的吧。
这个插件使用的iptables来实现代理，所以应该没问题的。
到底问题出在哪里呢！！！

**Comment by sadoneli** [comment]
@shellus -4是用ipv4的意思

**Comment by shellus** [comment]
@sadoneli  明白了。

我刚才重置了路由器，然后设置ss，还是不行，我准备重新刷一遍固件

**Comment by shellus** [comment]
最终参照这篇教程：[http://koolshare.cn/thread-30748-1-1.html](http://koolshare.cn/thread-30748-1-1.html) 配置成功。

我觉得关键点应该是，重置设备后，勾选
Format JFFS partition at next boot	
Enable JFFS custom scripts and configs
这两项后，重启路由器。

另一个关键点是：onetime authentication 必须关闭

好了，至此问题结束

**Comment by sadoneli** [comment]
onetime authentication这项，必须服务端支持，才能开启的哦，谨记
我看过好多ss错误的人都开了ota，结果服务端并不支持ota

2016-04-07 18:55 GMT+08:00 娃娃脾气 <notifications@github.com>:

**Comment by shellus** [comment]
是的，其实普通人根本搞不懂OTA是什么，我是一个老程序员，我也不懂那是什么。

另外，现在看ss有日志了。我估计还是和“Enable JFFS custom scripts and configs”选项有关。

也许是两个错误产生的双重攻击也可能哦。

**Comment by sadoneli** [comment]
总之服务端怎么配置，客户端就怎么弄好了，其实ota那里有链接的
我看什么时候给ota加上说明好了

在 2016年4月7日 下午7:44，娃娃脾气 <notifications@github.com>写道：

**Comment by jannson** [comment]
双重攻击??? 哈哈~~~
OTA 是沿用官方的名字，默认是关闭的。

**Comment by shalala33** [comment]
你好，我从谷歌搜到这个链接的。
我也遇到跟你一样的情况，WIN 10客户端可以用，但是路由器端一直无法使用。

之前没有更新的时候是可以的，前天头脑发热更到3.6就出问题了。

也勾选了Format JFFS partition at next boot并重启。

但是还是不行。

请教下，你上面回复里说到的onetime authentication 必须关闭。这个选项在哪，我没有找到。

**Comment by shalala33** [comment]
折腾了一天终于搞定了，降级到1.4版本，再改改DNS终于working了

**Comment by delai** [comment]
@shellus 正解，谢谢

**Comment by penghangph** [comment]
自己搭建的ss在电脑上配置可以访问google，但是在路由器上(6300v2)就不行.
路由器上显示:国外无法连接,但是国内正常.

修改了选择国外DNS选项:pcap-dnsproxy
问题解决.
