### ISSUE TITLE
通过SS/SSR链接添加服务器-没有作用

### ISSUE THREAD

**Issue by Suxwx** [koolshare/koolshare.github.io#491]
通过SS/SSR链接添加服务器
然后输入SS/SSR链接
点击并解析并保存为节点

出现下列画面

【2017年11月12日 21:54:56】: 检测到X7.7固件，支持订阅！
【2017年11月12日 21:54:56】: ===================================================================
【2017年11月12日 21:54:57】: 通过SS/SSR链接添加节点...
【2017年11月12日 21:54:58】: 添加链接为：
【2017年11月12日 21:54:58】: ===================================================================
 

然后就没有然后了，是什么问题啊

**Comment by xiaobangk** [comment]
对，这问题3.6.7和3.6.8都有，3.6.5还没这问题
