### ISSUE TITLE
网件R7000，固件版本koolshare merlin改版固件X7.7， 科学上网插件3.67无法开机启动

### ISSUE THREAD

**Issue by cinwellzjw** [koolshare/koolshare.github.io#493]
我的路由器是网件R7000，固件版本koolshare merlin改版固件X7.7， 科学上网插件3.67
设置定时重启路由器。但是每次路由器重启后科学上网插件无法开机启动，状态检测显示
ss-redir   ss-local为未运行，必须到插件中心关闭开启一次科学上网插件才行，不知是怎么回事?

**Comment by Nicepaul** [comment]
这个问题前几个版本就出现了，大概是3.6.3开始的吧
