### ISSUE TITLE
3.6.8 速度还是不够 3.6.4 快

### ISSUE THREAD

**Issue by lingaoyi** [koolshare/koolshare.github.io#499]
相同模式，相同配置，唯独版本不同。

视频测试：
https://www.youtube.com/watch?v=YswLmE5MxJk
视频质量：4K 60FPS

3.6.8
https://www.dropbox.com/s/ljys2gi7vqebqgi/3.6.8.jpg?dl=0

3.6.4
https://www.dropbox.com/s/chk4rbjb7lifne3/3.6.4.jpg?dl=0

**Comment by havoctang** [comment]
麻烦问一下你是什么vps……我感觉我尝遍百草从来没上过20000kbps，成都200M电信

**Comment by lingaoyi** [comment]
3.6.9 修正此问题。
