### ISSUE TITLE
大陆白名单模式下的自定义白名单无效。

### ISSUE THREAD

**Issue by yycomyy** [koolshare/koolshare.github.io#500]
如题，因为懒得一个个设置，索性将所有外网走代理来提高速度。
但是，有一些外网是不想走代理的，比如steam、speedtest等等，所以需要在白名单中设置不走代理。
现在情况是域名都可以保存进白名单，但是访问的话白名单无效，也就是steam显示美元价格，speedtest显示代理ip。
正常情况下不应该是单独设置白名单的域名应该是走国内ip么？
测试环境：宁夏电信100m光纤，ac68u梅林7.5,ss插件最新版3.6.8.

**Comment by 4iller** [comment]
统一遇到这种问题,AC88U,不知道是升级7.5后还是SS版本从3.6.3之后自定义黑白名单全部失效,主要是speedtest,也是用的大陆白名单模式
