### ISSUE TITLE
一个很奇怪的问题-墙外连接不稳定

### ISSUE THREAD

**Issue by Suxwx** [koolshare/koolshare.github.io#502]
hostus自建的SSR,原来没这么频繁的国外连接不上，偶尔的次把通过更换DnS就好了，最近老更新，发现频繁的出现国外无法连接，更改多次Dns也不行，后来发现啥也不换，把gfwlist模式改成全局或者大陆白名单模式，问题好了，这又是啥原因呢？

**Comment by zycboss** [comment]
电信是这样的，新建的VPS速度都很快，过一段时间似乎就会被发现然后线路不知道是被封还是被污染，总之就是不稳定了，但是换一个IP重新建一个VPS， 速度又会正常。

开混淆协议，能用的久一点，如果不开基本上几天就炸了。

仅针对电信，移动联通随意
