### ISSUE TITLE
手滑升级3.6.9 原来的节点都不能用了

### ISSUE THREAD

**Issue by pedroye666** [koolshare/koolshare.github.io#505]
有没有老哥能教教我怎么退回原来的版本去

**Comment by ColinZeb** [comment]
重新添加节点不就行了吗。如果是配置好了不能用再升级到3.7.1试试。再不行就换个dns解析类型

**Comment by pedroye666** [comment]
重新添加就可以了的话我就不会发帖了呀老哥。。

**Comment by ColinZeb** [comment]
你升级到最新版本试了吗，DNS解析模式换了没。
DNS模式切换后需要执行命令
`ipconfig /flushdns`
chrome需要重启，或者访问chrome://net-internals/#dns
然后点右上角clear cache和flush sockets
最后告诉你下载历史版本的办法
访问[version](https://github.com/koolshare/koolshare.github.io/blob/acelan_softcenter_ui/shadowsocks/version)点击history。找到你想要的版本，点进去，找到shadowsocks.tar.gz，然后点击View，在新的页面里点击Download。

**Comment by pedroye666** [comment]
谢谢哥。。我回家试试
