### ISSUE TITLE
PS4使用游戏模式 无法和基友组队

### ISSUE THREAD

**Issue by MonoKmm** [koolshare/koolshare.github.io#506]
身边十几个好友都是同样的问题，开启游戏模式在全境封锁／使命召唤这类游戏中无法组队。
具体症状：1、同样使用游戏模式的两人互相无法加入各自开启的游戏房间。2、两人其中有一人开启游戏模式，有大概率进不了各自开启的房间。
另外使用其他两个模式不会碰到组队困难的问题，表现十分流畅。也因此失去了连接官方服务器的加速(UDP)，导致虽然可以组队了 却经常无法顺利登陆游戏的尴尬境地。
大家都是电信网络／同一个酸酸乳
以COD：WW 为例
连接官方服务器UDP(3074-44999)
组队玩家之间UDP(3074-3074)
做过很多尝试，我发现自己没有这个能力解决，希望老哥能帮帮我。

**Comment by athx** [comment]
全境是tcp联机没有用udp。全境加不了好友看一下你们联的服务器。
使命没买不清楚看你说的是用udp联机，先检查你的运营商对udp干扰，自己测试，有干扰就串udp2raw。。
ps4的udp联机只用酸酸乳的udp转发问题很多很多。最好并联udpspeeder v2，必须是v2 用mode 0， -f参数也必须设置好。可以解决ip碎片问题ps4 mtu选自动。
命运2udp联机我也是你说的情况，我是用v2串udp2raw解决的。问题出在命运2联机有时mtu会达到1600

**Comment by MonoKmm** [comment]
感谢你的解答，按照你办法安装了V2和udp2raw，可以明显感觉出游戏登陆变快了。
不过和一起用同一个酸酸乳好友组队依然是与主机连接错误。
回想起以往游戏模式下登陆游戏并没有不顺畅，推断运营商没有干扰我与酸酸乳服务器（HK）的udp通信（但屏蔽了我与动视服务器UDP通信）
曾经尝试过游戏模式V2，依然不能组队。
只有在GW模式和大路白名单模式才可以与朋友顺利组队（100%）
我在想无法组队的问题是否出在其他地方？@athx
