### ISSUE TITLE
在firefox浏览器中节点显示有规范

### ISSUE THREAD

**Issue by freebsdjlu** [koolshare/koolshare.github.io#507]
环境是linux firefox 55.0 64位,几个tab已经被覆盖掉了
![deepinscreenshot_select-area_20171115082525](https://user-images.githubusercontent.com/7206812/32812203-d348ff52-c9de-11e7-9588-2405eaa29a75.png)

**Comment by freebsdjlu** [comment]
chrome显示正常，同平台，别的浏览器没有测试

**Comment by sadoneli** [comment]
新版本应该没有此问题
