### ISSUE TITLE
梅林SS升级到3.6.9中的KCP加速如何设置

### ISSUE THREAD

**Issue by jackdanny77** [koolshare/koolshare.github.io#508]
梅林SS升级到3.6.9中的KCP加速如何设置，梅林软件中心装好SS，已经升级到3.6.9了，也能正常工作，但发现有KCP加速，不知道如何配置，还有SSR订阅功能，在网上找了好半天也找不到能订阅的地址

**Comment by antenna2008** [comment]
订阅要你的飞机场支持才有的。不是所有的飞机场都支持订阅的。
