### ISSUE TITLE
3.6.9版本gfwlist模式跟大陆白名单模式下自定义的黑白名单都无效。

### ISSUE THREAD

**Issue by 4free4ever** [koolshare/koolshare.github.io#509]
几个服务器在国外但又封国外IP的网站都没办法访问，把域名添加到强制不走代理的白名单下也没啥用。感觉黑白名单都起不到作用。

**Comment by 4free4ever** [comment]
刚才试了下把谷歌加到白名单就访问不了了，看来白名单有效果，但是为啥，www.gaoqingkong.com这个网站加进去还是死活打不开。把代理关了就能打开。。。

**Comment by 4iller** [comment]
3.7也是这样,黑白名单无效,主要是要把speedtest不走代理,,,,结果大陆白名单下再加白名单还是不行

**Comment by 4free4ever** [comment]
黑名单也不行。。。都特么搞不懂了。

**Comment by yycomyy** [comment]
同样大陆白名单模式的黑白名单无效。今天更新了3.7.2仍然不行。。

**Comment by sadoneli** [comment]
dns模式是国内优先还是国外优先啊？

**Comment by sadoneli** [comment]
黑名单无效是ip/cidr黑名单还是域名黑名单
黑名单的具体内容方便贴上来看看吗？

**Comment by yycomyy** [comment]
大陆白名单模式 然后把speedtest.net和steampowered.com加入域名白名单。如果白名单有效，效果是speedtest显示国内ip，steam的游戏显示人民币计价。反之白名单无效的话，显示的是代理ip和代理国货币的计价。（steam会根据访问ip的国家来显示对应的货币价格）

**Comment by sadoneli** [comment]
@yycomyy 问题大概找到了，开启koolproxy的情况下，白名单确实会 发生失效，下次修复

**Comment by sadoneli** [comment]
你可以关闭koolproxy后试试看是否还是有问题

**Comment by 4free4ever** [comment]
找到原因了，kp问题。我试了几天才发现，特么还不如到你这边来看一下，原来你早已知道。

**Comment by 4free4ever** [comment]
我想问下，ps4港服的ip是不是强制代理的？

**Comment by sadoneli** [comment]
@4free4ever 大陆白名单模式下应该是的，因为大陆以外的ip都会走ss
