### ISSUE TITLE
梅林里面的SS升级到3.7了，但增加的KCP加速和UDP加速如何配置

### ISSUE THREAD

**Issue by jackdanny77** [koolshare/koolshare.github.io#510]
梅林里面的SS升级到3.7了，但增加的KCP加速和UDP加速如何配置，有没有具体的教程可以指导一下，看了网上半天也没有找到相关的配置教程，我的SS是能连接到外网了，但怎么加速
![image](https://user-images.githubusercontent.com/32319302/32834049-0816d706-ca3c-11e7-8a60-e53b9b2c03db.png)

**Comment by havoctang** [comment]
https://github.com/wangyu-/UDPspeeder/blob/master/doc/README.zh-cn.md
一清二楚，请多学习

**Comment by lingaoyi** [comment]
还是不会安装啊，求大佬来个一键安装包 Orz...........

**Comment by havoctang** [comment]
大佬把客户端都做好给你了，仔细看看github吧，一行代码的事

**Comment by chengxiao** [comment]
两周前在 V2看到了 UDPspeeder的配置,没想到这么快就跟进了,好顶赞一个
