### ISSUE TITLE
update to 3.7.0 後的問題

### ISSUE THREAD

**Issue by kujourin** [koolshare/koolshare.github.io#513]
首次升級，從3.6.9升級，進行到一半卡住，然後刷新頁面之後軟件中心和插件消失。無法使用。
路由器完全重置，全新安裝3.7.0
出現了很多版本之前的bug，開機國內外全部ok但是客戶端無法使用。
必須每次重啟完路由器點一次保存&應用之後才生效。

**Comment by kujourin** [comment]
延遲啟動可以解決該問題，但希望默認還是和以前一樣能延遲啟動。
另外，更新規則列表的邏輯有問題，無法手動更新，點立即更新會提示沒有勾選不能更新，但是勾選就要先打開自動更新，然後更新玩再關閉自動更新。

**Comment by sadoneli** [comment]
应该是固件的skipd进程挂掉了，尝试运行service restart_skipd
规则更新哪里逻辑是有点问题
