### ISSUE TITLE
遇到几个比较大的bug，感觉改版的SS插件目前很不稳定

### ISSUE THREAD

**Issue by ioversleep** [koolshare/koolshare.github.io#516]
今天首先是发现重启路由后，所有线路全部X了，但是服务器又都能ping通，于是不停上服务器改配置，结果怎么改都不行。无知的我还以为自己被老大哥盯上了。在改配置的过程中，又发现选择编辑会变成添加，改一次多一个配置…………真是……于是想删除插件，但是又删不了，不得已只能再次重启，格式化JFFS，唉，真够折腾的。最后回滚回3.5.9，发现能用了。也许是我小白吧，如果有知道怎么回事的希望给我解惑

**Comment by pedroye666** [comment]
老哥 请问怎么滚回3.5.9啊 我跟你一样的问题 能教教我吗 wx:1850871862 谢谢

**Comment by sadoneli** [comment]
抱歉，急于增加功能，没测试好，稍后会修复

**Comment by ioversleep** [comment]
我就是格式化了JFFS，然后离线安装，安装文件这里有下载，在历史文件里。

LS不用道歉，软件有bug很正常，大家都希望越来越好，加油。

**Comment by pedroye666** [comment]
啊。。我是终极小白 有啥傻瓜操作可以回滚吗 jffs是啥
