### ISSUE TITLE
求大神帮忙，研究到凌晨5点越看越蒙蔽，关于kcp加速和udp加速的问题

### ISSUE THREAD

**Issue by karisis** [koolshare/koolshare.github.io#517]
我刚刚更新到了3.7.1，想研究研究这两个新功能，udp加速好歹看明白了，主要是kcp加速的问题。
首先要确认一个概念，就是现在ss插件里面的kcp加速就是指kcptun，如果不是，下面的都是废话。。。。
如果是的话，我在wangyun写的使用经验里面看到：
”可以让kcptun负责加速TCP，UDPspeeder负责加速UDP。”
然后我就疯狂的找关于kcptun的教程贴，找了半天也就找到下面这一个，还是16年的
https://blog.kuoruan.com/110.html
里面倒是有服务器端最新的kcptun的下载地址，然后继续找，发现了这个帖子
https://github.com/wangyu-/udp2raw-tunnel/issues/19
然后我就蒙蔽了，这里面又说因为udp限速需要用到udp2raw，kcptun不是加速tcp的吗，怎么还和udp扯上了，udp加速不是要用udpspeeder吗？
求解惑，另外，求个新的关于kcp的使用教程，让我这个萌新也能愉快的用上大神开发的新功能。。
另外我是阿里云香港服务器，有个大神貌似说这两个加速功能我不是很会用的到，是给服务器不是特别好的人用的，但是看了相关说明后又感觉这两个功能用处很大，求解惑

**Comment by kersay** [comment]
KCPTUN是把TCP转换成UDP的，运营商会对UDP进行限速

**Comment by wangyu-** [comment]
udp2raw是可选的，不用也可以。

你需要做的只是用kcptun加速s的tcp，用udpspeeder加速s的udp。

kcptun的客户端下载和使用说明可以看kcptun的repo：

https://github.com/xtaci/kcptun

**Comment by wangluyichen** [comment]
@karisis 那kcp会把tcp转换成udp，那我现在的线路就是udp不好，那用kcp得不偿失啊！

**Comment by wangluyichen** [comment]
@karisis 你这个有点难度，好几个软件配合
