### ISSUE TITLE
udp加速只有游戏模式才能用

### ISSUE THREAD

**Issue by ligf** [koolshare/koolshare.github.io#520]
是否能支持其他模式呢

**Comment by sadoneli** [comment]
不支持，其它模式ss-redir有udp流量

**Comment by ligf** [comment]
udp流量走ss后 ss会使用upd加速吗

**Comment by koolca** [comment]
@sadoneli 有点没有理解。理论上应该在任何模式下都可以使用udpspeeder加速udp啊。是不是可以用iptables将ssr的tcp和udpspeeder的udp端口合并为同一个端口号？
https://github.com/wangyu-/UDPspeeder/blob/master/doc/README.zh-cn.md   有这么一段：
另外，如果没有kcptun只有BBR/锐速的话，也可以把kcptun换成ncat/socat/ssh tunnel/iptables/tinyPortMapper。这样，TCP流量由锐速/BBR加速，UDP由UDPspeeder加速。
