### ISSUE TITLE
GFWList 更新问题

### ISSUE THREAD

**Issue by Kingson** [koolshare/koolshare.github.io#522]
显示：4142 条，最后更新版本： 2016-04-05
点击日期会跳转到  https://github.com/koolshare/koolshare.github.io/blob/master/maintain_files/gfwlist.conf
页面显示404

如何更新到最新的GFWList
谢谢

**Comment by ColinZeb** [comment]
你版本号多少，我这地址是正确的。[gfwlist](https://github.com/koolshare/koolshare.github.io/blob/acelan_softcenter_ui/maintain_files/gfwlist.conf)

不过这域名列表里没有google.com.tw 不知道是否正常。

**Comment by Kingson** [comment]
当前版本：ARM 1.4.4

**Comment by Kingson** [comment]
我看大家说的都是3.6.x，我还没有找见在哪看版本号

**Comment by ColinZeb** [comment]
检查更新旁边，或者你检查更新升级一下。最新版本3.7.1

**Comment by Kingson** [comment]
@ColinZeb 我的是路由器里的，没找见版本号
![screen shot 2017-11-17 at 9 53 58 am](https://user-images.githubusercontent.com/468509/32925593-9b7122ee-cb7d-11e7-9a80-7b6562a3bd7f.png)

**Comment by ColinZeb** [comment]
点进去Shadowsocks页面。

**Comment by Kingson** [comment]
@ColinZeb 不好意思，点进去后，还是没找见，你能截个图吗？谢谢

**Comment by ColinZeb** [comment]
![png](https://i.loli.net/2017/11/17/5a0e4428ae22c.png)
你的版本可能跟我不一样，但是界面 应该差不多。

**Comment by Kingson** [comment]
原来就是这个啊
![screen shot 2017-11-17 at 10 08 41 am](https://user-images.githubusercontent.com/468509/32925905-61830e24-cb7f-11e7-81c6-25736ed96bce.png)

**Comment by ColinZeb** [comment]
版本太旧了
赶紧升级试试

**Comment by sadoneli** [comment]
你的ss版本太古老了，当时1.5.7之前的版本是能够升级到1.5.7，然后通过1.5.7再升级到最新
现在已经不能通过这种办法进行升级，请通过格式化jffs分区，清理干净你已经安装的旧的ss，然后通过离线安装来安装最新的版本

2017-11-17 10:09 GMT+08:00 Kingson.zhou <notifications@github.com>:

**Comment by Kingson** [comment]
@ColinZeb @sadoneli 非常感谢二位的帮助，刚开始折腾刷路由器，好多东西不太清楚，再次感谢
