### ISSUE TITLE
关于升级了3.7.1后，访问控制获取nat失败，用来玩ps4朋友有这样问题吗？

### ISSUE THREAD

**Issue by vic195465354** [koolshare/koolshare.github.io#523]
关于升级了3.7.1后，访问控制获取nat失败，用来玩ps4朋友有这样问题吗？未升级之前是没有问题的，主模式我用时大陆白名单，然后指定ps4的ip地址走游戏模式，升级软件后，死活获取不到nat类型，导致无法正常连线游戏，现在只能改主模式来玩，每次玩游戏前都要改。好不方便。请尽快修复更新此问题！谢谢

**Comment by sadoneli** [comment]
fixed https://github.com/koolshare/koolshare.github.io/commit/239cf04954f5e61691c384be3bcbafa9527f5065
