### ISSUE TITLE
希望增加全局+UDP转发模式

### ISSUE THREAD

**Issue by murdererdu** [koolshare/koolshare.github.io#524]
RT 最近在玩堡垒之夜 因为tx收购了游戏开发商 导致封大陆IP 并且封大陆IP的是TX的云IP 导致游戏必须使用全局才可以过验证 但是过了验证 又想用ss加速udp 就没有办法了！

**Comment by sadoneli** [comment]
udp全局不可取，全部udp都走ss后路由器会出现很多问题
现在可以做到大陆外的ip，的全端口都走ss
另外如果你有特殊的ip，请使用ip/cidr黑名单功能
