### ISSUE TITLE
请问目前版本是需要手动设置udp才能实现加速吗？

### ISSUE THREAD

**Issue by phenomx100** [koolshare/koolshare.github.io#525]
原先采用给游戏机固定走游戏模式 其他走主模式的方式 今天3.64误升到3.71 发现游戏模式下的几个全失效了 主模式直接切到游戏模式也不行 看到udp加速设置那显示服务没启动 因为比较蠢下面的参数空着也不会弄 只能全局使用
看了下其他几位反应游戏不正常的大概也都是类似情况？ 是否能提供3.64版本时那样比较傻瓜的设置方式呢

**Comment by sadoneli** [comment]
fixed https://github.com/koolshare/koolshare.github.io/commit/239cf04954f5e61691c384be3bcbafa9527f5065
