### ISSUE TITLE
希望能出一篇UDP加速的使用教程

### ISSUE THREAD

**Issue by xeonman0822** [koolshare/koolshare.github.io#526]
UDP加速提示:UDPspeederV2进程未运行，插件自带的UDP加速功能没有教程真心不会用啊，只能眼巴巴每个月月供加速器给网易，期待小哥哥能出使用方法

**Comment by gordengan** [comment]
这个你要服务器端支持的吧~~要自己搭的~~

**Comment by sadoneli** [comment]
请参考插件内给出的帮助信息

**Comment by sadoneli** [comment]
@clangcn 会做集成udpspeeder的一件脚本
