### ISSUE TITLE
3.7.1修正后的节点编辑问题

### ISSUE THREAD

**Issue by zxysm** [koolshare/koolshare.github.io#528]
3.7.0升级到3.7.1后确实现在可以编辑节点了，但是保存结果是有问题的，我随意找了个之前的节点编辑，只修改了一下使用模式，然后点击保存，结果变成了：
模式正常修改完成，节点名称变为节点XX，和之前不同了，服务器地址变成undefined已丢失配置，端口和服务器地址一样丢失，加密方式变成aes-256-cfb跟之前不同了。
然后如果点击编辑想再次编辑这个节点已经没有反应。

**Comment by sadoneli** [comment]
储存的数据估计出问题了，请清空ss配置后，重新添加节点，然后再编辑试试，看看是不是还有这个问题

**Comment by zxysm** [comment]
OK，晚点试试重新配置，只是个人节点，没订阅，加节点慢死
