### ISSUE TITLE
3.7.1 koolgame模式和SSR模式互相切换会导致路由器系统崩溃

### ISSUE THREAD

**Issue by Se7enMuting** [koolshare/koolshare.github.io#529]
koolgame模式和SSR模式互相切换会导致我路由器崩溃,路由器是AC3100，7.7的版本.我昨天3.7.0玩koolgame模式就发现这个问题了,主要是koolgame模式切到SSR模式时会崩溃.有一点我建的koolgame的server是在墙内的.

**Comment by sadoneli** [comment]
我这里用koolgame的游戏模式和ssr的大陆白名单模式来回切了三次，没有发现这个问题
建议使用koolgame开启虚拟内存试试，因为golang的内存占用要多得多

**Comment by gordengan** [comment]
koolgame开启虚拟内存是指是client端梅林开吗？怎么开求点拨下....

**Comment by sadoneli** [comment]
以后每次重启，当U盘挂载到/tmp/mnt/sda1后，都可以运行swapon tmp/mnt/sda1/swapfile来进行挂载虚拟内存，你也可以写个开机脚本，使其自动挂载。卸载虚拟内存使用 swapoff tmp/mnt/sda1/swapfile

**Comment by bernie1011** [comment]
我也遇到同样问题，从koolgame切换到游戏模式时路由崩溃，运行时间重置了。路由是ac88u，版本是7.5

**Comment by Mizeron** [comment]
另外求教一下s大，软件中心那个 虚拟内存 应用不好使吗？开启了时常是显示0占用…

**Comment by gordengan** [comment]
s大有指令看虚拟内存是否确实挂载成功且运行中吗？

**Comment by gordengan** [comment]
s大，虚拟内存挂载成功，挂了1个G。但是问题依旧！
我发现我开koolgame的时候路由本身内存也只占用25%（有512内存），free -m看虚拟内存的used一直是0。我开koolgame玩switch，nat从B能提升到A，开启koolgame的玩游戏的过程中路由一切正常，没有问题，所以我觉得不是内存问题。
我现在在koolgame模式下把SS整个插件关掉，大约10S后，页面就跳白，提示和路由器连接断开，过一会就断网了，再过一会就恢复了。每次都是如此。
我的koolgame-server是在墙内的，国外连接是X，不知道和这个有没有关系~~

**Comment by chengxiao** [comment]
AC-5300 同上,也是两种模式切换回崩溃,不知道是不是 Udpspeeder 引起的

**Comment by sadoneli** [comment]
@chengxiao 有日志或者截图吗？

**Comment by chengxiao** [comment]
![default](https://user-images.githubusercontent.com/1379545/32955001-a83d1e3e-cbef-11e7-9d37-499f3d03ea92.png)
![default](https://user-images.githubusercontent.com/1379545/32955144-155dafec-cbf0-11e7-8bf6-e665a7490f44.png)
日志没有了 基本一奔溃就重启了 wifi 也断了

**Comment by chengxiao** [comment]
昨天用 SSR 的节点配置 Udpspeeder没有问题
今天配了小宝的游戏模式在服务器上 再用 Udpspeeder 就崩了

**Comment by sadoneli** [comment]
koolgame下不支持udpspeeder的

**Comment by sadoneli** [comment]
只有ss或者ssr的游戏模式才支持udpspeeder的
koolgame自带了udp优化

**Comment by gordengan** [comment]
@sadoneli 在koolgame模式下能关掉SS，日志走完，然后会等10S开始断线重启。但是切换到SS/SSR时，日志是走不完的，每次停的地方都不一样的。

**Comment by chengxiao** [comment]
非常感谢耐心回答 这下了解了

**Comment by sadoneli** [comment]
刚才测试了下koolgame 游戏模式下关闭ss，什么也没发生
然后切换ssr后也是正常的

要不你尝试清空下ss的数据重新手动配置下看还有这个问题存在不

**Comment by gordengan** [comment]
@sadoneli 我貌似发现问题了，在koolgame切换到SSR模式的时候，网络里有类似QQ的程序开着，路由器就会崩溃。
具体情况:我清除了插件配置，然后重装，再手动配置。去除和路由器的所有网络设备连接，只留一台PC来登录用。登录的PC关掉一切程序，用干净的chrome（没有插件，cookie清除，没有登录google帐号），在这样的环境下我来回切很多次都没有出现崩溃的问题，切换后墙内外网都能上。**但是一旦在koolgame切SSR的过程中开着QQ（我QQ里几乎每时每刻都有消息），切换后我这台PC必定要和路由器断开连接一会，QQ也自然会断开，过一会在自动连上。**

**Comment by sunao2002002** [comment]
> ```shell
> 1. 插上你的U盘后，进入SSH，输入df -h命令
> 2. 找到你的磁盘那行，记下Filesystem和Mounted on两个参数；
> 3. 比如我的分别是/dev/sda1和/tmp/mnt/sda1；
> 4. 输入umount /tmp/mnt/sda1，卸载该磁盘；
> 5. 输入mkfs.ext3 /dev/sda1，将磁盘格式化为ext3格式；
> 6. 先mkdir -p /tmp/mnt/sda1，创建挂载点文件夹；
> 7. 再mount /dev/sda1 /tmp/mnt/sda1，重新完成磁盘挂载。
> 8. 运行命令 dd if=/dev/zero of=/tmp/mnt/sda1/swapfile bs=1024 count=524292
> 9. 如果需要其它大小，请参考 256Mb：count=262148；512Mb：count=524292；1024Mb：count=1024004
> 10. 运行命令 mkswap /tmp/mnt/sda1/swapfile
> 11. 运行命令 chmod 600 /tmp/mnt/sda1/swapfile
> 12. 运行命令 swapon /tmp/mnt/sda1/swapfile
> ```

这个方式会很伤U盘，很容易把U盘写坏。一般嵌入式设备都不会在flash启用swap。
