### ISSUE TITLE
自动更新dnscrypt列表功能及dnscrypt客户端更新需求

### ISSUE THREAD

**Issue by VersusClyne** [koolshare/koolshare.github.io#53]
官方发布的dnscrypt列表文件位于
https://download.dnscrypt.org/dnscrypt-proxy/dnscrypt-resolvers.csv
验证签名
https://download.dnscrypt.org/dnscrypt-proxy/dnscrypt-resolvers.csv.minisig
https://download.dnscrypt.org/dnscrypt-proxy/dnscrypt-resolvers.csv.sig

感谢菊苣啦～

**Comment by sadoneli** [comment]
这个list以前长期保持不变的原因就是怕更新后少了一些服务器，而用户却正在使用这个服务器，更新后就没法使用原来的服务器
因为不仅仅涉及到`/koolshare/ss/dnscrypt-resolvers.csv`一个文件的变化，相应的gfwlist模式，大陆百名但模式的高级设置页面中的选项也要据此动态变化才行，所以每次更新带来的改动就会很多

我将在以后的版本中尝试在gfwlist模式，大陆百名但模式的高级设置页面中根据`/koolshare/ss/dnscrypt-resolvers.csv`这个文件，动态来生成选择的option list，这样才更为方便
