### ISSUE TITLE
主模式与访问控制冲突？

### ISSUE THREAD

**Issue by LMX58** [koolshare/koolshare.github.io#530]
在主模式选择白名单，再从访问控制指定某主机游戏模式，UDP转发会失效。
AC66U_B1,
380.68.4-X7.7
科学上网V3.7.1
节点支持UDP，无KCP

**Comment by sadoneli** [comment]
已知bug，待修

**Comment by sadoneli** [comment]
fixed https://github.com/koolshare/koolshare.github.io/commit/239cf04954f5e61691c384be3bcbafa9527f5065
