### ISSUE TITLE
节点选择中怎么只有SSR节点, 配置不了SS吗

### ISSUE THREAD

**Issue by icewalf** [koolshare/koolshare.github.io#532]
我自己建的ss服务上没有 账号设置里的 协议 (protocol) ,协议参数 (protocol_param) , 混淆 (obfs) ,混淆参数 (obfs_param) 这些参数, 这些都是SSR上的吧! 请问怎么配置SS的参数
求助
版本：3.7.2

**Comment by Myoko** [comment]
SSR支持混淆建议还是用SSR的服务器吧！

**Comment by Mizeron** [comment]
节点管理——添加节点——点“添加ss帐号”标签

还找不到，建议去看眼科
