### ISSUE TITLE
奇怪了同样的节点，同样设置。sstap能跑到160m，插件最高值能到50m

### ISSUE THREAD

**Issue by hnhhzy** [koolshare/koolshare.github.io#535]
奇怪了同样的节点，同样设置。sstap能跑到160m，插件最高值能到50m
路由器里的cpu,内存都还有很大余地。R8500

**Comment by sadoneli** [comment]
智能用到单核跑满，所以性能问题，另外如果加混淆，对路由器性能消耗更高
