### ISSUE TITLE
为什么升级后会报很多错误，包括iptables v1.4.14: Set white_list doesn't exist.错误？

### ISSUE THREAD

**Issue by padfan** [koolshare/koolshare.github.io#536]
哪位大神帮着看看：升级到3.7.1后，就一直报
2017年11月17日 09:35:46: 创建ipset名单
ipset v4.5: Unknown arg `-!'
Try `ipset -H' or 'ipset --help' for more information.
ipset v4.5: Unknown arg `-!'
Try `ipset -H' or 'ipset --help' for more information.
ipset v4.5: Unknown arg `-!'
Try `ipset -H' or 'ipset --help' for more information.
ipset v4.5: Unknown arg `-!'
Try `ipset -H' or 'ipset --help' for more information.
ipset v4.5: Unknown arg `-!'
Try `ipset -H' or 'ipset --help' for more information.
ipset v4.5: Line 1 does not start as a valid restore command

Restore failed at line 1:
Try `ipset -H' or 'ipset --help' for more information.
2017年11月17日 09:35:46: 写入iptables规则到nat表中...
iptables v1.4.14: Set white_list doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.14: Set black_list doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.14: Set gfwlist doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.14: Set black_list doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.14: Set chnroute doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.14: Set black_list doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.14: Set chnroute doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.14: Set black_list doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.14: Set chnroute doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
2017年11月17日 09:35:46: 加载ACL规则：【全部主机】【全部端口】模式为：gfwlist模式
iptables v1.4.14: Set router doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.

**Comment by padfan** [comment]
我的固件版本是梅林的AC88U-X7.1

**Comment by sadoneli** [comment]
https://github.com/koolshare/koolshare.github.io/blob/acelan_softcenter_ui/shadowsocks/Changelog.txt#L432

**Comment by padfan** [comment]
果然如此，我记得原先是不能升级的，因为当时我的固件7.1，一点升级，就会说不支持；但是昨天误点，居然可以升级，瞬间炸了。
不过我目前升级了固件到X7.7，已经恢复正常。谢谢！
