### ISSUE TITLE
关于添加虚拟内存问题【借个楼】

### ISSUE THREAD

**Issue by qswx2007** [koolshare/koolshare.github.io#538]
S大这“懒人”写个虚拟内存步骤又不给开机启动，总是觉得缺点啥子？。。另外梅林7.7软件中心的虚拟内存插件整了，命令“free -m”又显示0，推荐大家用B大这个脚本：
http://koolshare.cn/thread-42723-1-1.html

**Comment by sadoneli** [comment]
很棒棒，是不是应该给你再置个顶，加个粗，再搞个颜色？

**Comment by qswx2007** [comment]
哈哈，随你啊！！给你一颗”star“，哈哈，，那个脚本说的swap推荐32M，其实还是不行，这个得听S大大的，推荐256M或者512M.

**Comment by sadoneli** [comment]
结果都一样
