### ISSUE TITLE
路由器自身的流量不走代理

### ISSUE THREAD

**Issue by Enzo-Liu** [koolshare/koolshare.github.io#54]
ss 1.37 版本。使用国内白名单模式。（试验下来，全局模式也一样不行，其他没有试）
在安装entware的时候，发现路由上（`192.168.1.1`）无法连接 `pkg.entware.net`。
但是在连上路由的电脑（`192.168.1.86`)上都是可以访问的。

对iptables不是很熟，OUTPUT chain到底是啥也不是很肯定，不过查找了一下资料，最后加上
`iptables -t nat -A OUTPUT -p tcp -j REDSOCKS2` 就可以了。

另外，对于原先的这句
`iptables -t nat -A OUTPUT -p tcp -m set $MATCH_SET router dst -j REDIRECT --to-ports 1089`

我的理解是，如果是router的请求，重定向到1089端口，也就是走代理。但是看了一下`ipset -L router`的结果，就不太懂了。
```
admin@R6300V2-F2A7:/jffs/.koolshare/ss/redchn# ipset -L router
Name: router
Type: iphash
References: 1
Header: hashsize: 1024 probes: 8 resize: 50
Members:
192.30.252.91
192.30.252.130
192.30.252.125
192.30.252.124
103.245.222.133
192.30.252.131
192.30.252.127
192.30.252.88
216.58.197.131
192.30.252.92
192.30.252.86
192.30.252.120
192.30.252.121

```

所以，[`router itself`](https://github.com/koolshare/koolshare.github.io/blob/master/shadowsocks/shadowsocks/ss/redchn/nat-start#L112)的配置是什么意思，可否辛苦解释一下，tks~

参考链接：https://github.com/shadowsocks/openwrt-shadowsocks/issues/9

**Comment by sadoneli** [comment]
你好，是这样的，merlin改版固件的ss经历了太多的变化，去年为了给ss加上状态检测，需要路由器本身具有出墙能力，所以加了<pre>iptables -t nat -A OUTPUT -p tcp -j REDSOCKS2<pre>来着，但是这样一个很大的问题就是路由器所有外网访问都出墙了，遇到很多各种问题（具体什么问题我也记不得了，不过当时有人反对这么做），最后没办法，就限制了出墙范围，改成了这样<pre>iptables -t nat -A OUTPUT -p tcp -m set $MATCH_SET router dst -j REDIRECT --to-ports 1089</pre>，这样就只有<pre>/koolshare/ss/redchn/output.conf</pre>里的域名，就是router itself，路由器才会有ss去访问。

如果你需要用到entware官方源，可以把pkg.entware.net按照格式加到文件<pre>/koolshare/ss/redchn/output.conf</pre>里去

**Comment by Enzo-Liu** [comment]
明白了，多谢！
