### ISSUE TITLE
3.7.2显示运行状态都正常但分流检测不正常实测也是不正常

### ISSUE THREAD

**Issue by MythHack** [koolshare/koolshare.github.io#540]
![image](https://user-images.githubusercontent.com/7798759/32954220-74195868-cbed-11e7-8e62-f3bfe3c1438d.png)

**Comment by sadoneli** [comment]
清除浏览器缓存试试

**Comment by ioversleep** [comment]
分流检测好像是本地进行的，如果我在外网访问路由器的话，好像检测不准。不知道我说的对不对。
