### ISSUE TITLE
升级至3.7x以后，填写好的节点信息自动会清空

### ISSUE THREAD

**Issue by JNUKing** [koolshare/koolshare.github.io#542]
不知道是什么原因，节点信息会保存一段时间
睡一觉，节点全空了
不知道怎么解决啊

**Comment by sadoneli** [comment]
1 如果你的节点是订阅而来的，尝试关闭订阅的定时任务，有时候定时订阅出问题有很小的几率会导致节点丢失
2 检查路由器下skipd进程是否运行
