### ISSUE TITLE
希望在访问控制中加入类似黑白名单的功能。

### ISSUE THREAD

**Issue by SunZhizhong** [koolshare/koolshare.github.io#543]
是这样的，这个功能我觉得可以增强一下，主要是自己想加入多个游戏端口，或排除多个BT或P2P端口，前一种比较麻烦，但如果可以用后一种方式，就可以只排除几个BT或P2P端口就可以实现了，不知道你们未来有没有这个打算？希望可以增强一下关于访问控制设置里的功能。

**Comment by sadoneli** [comment]
目前可以实现对端口的更改，添加到访问控制列表后就能更改了
比如把22,80,443更改为 ```80,,443,5555:7777,12000:42000,54321```
不想走ss的端口排除在外就行了

**Comment by SunZhizhong** [comment]
不好意思，我没有找到那个“添加访问控制列表”这样的设置，以前是可以直接在后面修改端口的，现在不可以了，请问这个功能在哪里？

**Comment by SunZhizhong** [comment]
@sadoneli 能加入的端口数量有限，而且有时候不能添加端口，比如战地4一个游戏所需要的端口数量就不够了，如果需要添加大量端口可能不太现实。
Battlefield 4 - PC
TCP: 80,443,9988,17502,20000-20100,22990,42127
UDP: 3659,14000-14016,22990-23006,25200-25300
