### ISSUE TITLE
希望科学上网插件能增加支持双拨功能

### ISSUE THREAD

**Issue by LEGEND-911** [koolshare/koolshare.github.io#545]
现在有不少地方可以双拨，这样可以最大限度利用宽带，但是科学上网插件只会自动连接其中一个。
希望科学上网插件可以增加针对双拨用户的选项，如增加选项“在WAN1连接科学上网”，“在WAN2连接科学上网”，“同时连接WAN1，WAN2，叠加接科学上网”这类的能力。谢谢。

**Comment by Myoko** [comment]
双拨不用科学上网插件吧！KOOLSHARE论坛有双拨的教程如何你的线路支持双拨的不然也是白搭

**Comment by sadoneli** [comment]
没有双拨环境，难以调试，暂时不考虑这个功能
