### ISSUE TITLE
3.7.2发现的一个小BUG，清除配置后重新手动添加节点，会出现

### ISSUE THREAD

**Issue by gordengan** [koolshare/koolshare.github.io#546]
1.清除配置后，会跳出一个新的三选一的对话框，选择手动添加节点，在添加节点的页面重新选一个SS的模式，比如改成游戏模式，这个时候又会重新跳出那个新的三选一的对话框。
   2.也是清楚配置后，出现下面的图
![default](https://user-images.githubusercontent.com/889925/32977404-b1e333f6-cc67-11e7-8d63-38a6ae16efd4.png)

另一个问题：
   “SS服务器地址解析”选resolveip方式，右侧会出现“114.114.114.114”，然后选nslookup方式，再选回resolveip方式，右侧“114.114.114.114”会消失。我记得以前resolveip方式右侧是没有IP地址的。

**Comment by sadoneli** [comment]
1 待修
2 3 无法重现，请更换浏览器或看看

**Comment by gordengan** [comment]
第三条截图 firefox 57.0 (64 位)
![scs](https://user-images.githubusercontent.com/889925/32978393-6dc01fb2-cc7c-11e7-839d-03fc633d81b6.png)

**Comment by sadoneli** [comment]
1 3 确认问题，下次更新修复

**Comment by sadoneli** [comment]
fixed in 3.7.3
