### ISSUE TITLE
希望能增加BT识别功能

### ISSUE THREAD

**Issue by Easy-Sir** [koolshare/koolshare.github.io#547]
很多的SS供应商为了公平起见，禁止了BT/PT下载，我们这些用户也很尊重供应商的选择，哪怕是自己建的SSR，也不想因为BTPT走掉太多流量，但是作为翻墙党来说基本都在使用白名单模式或者游戏模式，每次想要下载BT的时候还要去路由器页面设置，一个不小心忘了设置的话就会被........如果能增加一个选项，可以在所有模式下都允许/禁止BT/PT下载就好了。不知可否有可能做到？SS的供应商使用Bt protocol。或者说其实插件已经带了禁止BTPT下载的功能而我太傻不知道？

**Comment by sadoneli** [comment]
路由器端现在没有更好的方案去识别这些流量，请设置你的bt下载设备如nas等不走ss

**Comment by Easy-Sir** [comment]
好吧~知道了，谢谢
