### ISSUE TITLE
今天升级梅林7.7，发现左侧菜单没有科学上网了。

### ISSUE THREAD

**Issue by ColinZeb** [koolshare/koolshare.github.io#548]
这个功能是不支持7.7，还是最近去掉了

**Comment by sadoneli** [comment]
侧边栏需要固件做支持，从7.7开始，固件里移除了和ss任何相关的东西，因此不能再支持
https://github.com/koolshare/koolshare.github.io/blob/acelan_softcenter_ui/shadowsocks/Changelog.txt#L114

**Comment by ColinZeb** [comment]
明白
