### ISSUE TITLE
3.7.2 路由器重启后，国外连接不工作

### ISSUE THREAD

**Issue by jorking** [koolshare/koolshare.github.io#550]
router: AC66u B1  X7.7, 插件版本 3.7.2

使用SS，gfwlist模式，每次重启路由器之后国外链接就不工作了，国内链接始终正常。如果点击"保存和应用“，就都正常了。最近几个版本都这样。
检测状态如下：

2017年11月18日 22:26:36:
① 程序版本（插件版本：3.6.5）：
-----------------------------------------------------------
程序			版本		备注
ss-redir		3.1.0		2017年11月13日编译
ss-tunnel		3.1.0 		2017年11月13日编译
ss-local		3.1.0		2017年11月13日编译
obfs-local		0.0.4		2017年11月13日编译
ssrr-redir		3.5.2 		2017年11月13日编译
ssrr-tunnel		3.5.2 		2017年11月13日编译
ssrr-local		3.5.2 		2017年11月13日编译
client_linux_arm5	20171021	kcptun
haproxy			1.7.5	
dns2socks		V2.0 	
dnscrypt-proxy		1.7.0 	
ChinaDNS		1.3.2 	
pndsd			1.2.9a-par 	
Pcap_DNSProxy		0.4.8.1
-----------------------------------------------------------

② 检测当前相关进程工作状态：（你正在使用SS-libev,选择的模式是【gfwlist模式】,国外DNS解析方案是：koolgame内置）
-----------------------------------------------------------
程序		状态	PID
ss-redir	工作中	pid：1670
ss-local	工作中	pid：1644
dns2socks	工作中	pid：1654 1653 1648
-----------------------------------------------------------

③ 检测iptbales工作状态：
----------------------------------------------------- nat表 PREROUTING 链 --------------------------------------------------------
Chain PREROUTING (policy ACCEPT 11172 packets, 1347K bytes)
 pkts bytes target     prot opt in     out     source               destination         
11292  666K KOOLPROXY  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0           
 3156  329K VSERVER    all  --  *      *       0.0.0.0/0            183.15.111.118      
    0     0 VSERVER    all  --  *      *       0.0.0.0/0            169.253.83.228      
 2000  178K PCREDIRECT  all  --  br0    *       0.0.0.0/0            0.0.0.0/0            MAC 10:48:B1:88:FF:D3
    0     0 PCREDIRECT  all  --  br0    *       0.0.0.0/0            0.0.0.0/0            MAC 00:9E:C8:D2:CC:07

----------------------------------------------------- nat表 OUTPUT 链 ------------------------------------------------------------
Chain OUTPUT (policy ACCEPT 3176 packets, 238K bytes)
 pkts bytes target     prot opt in     out     source               destination         

----------------------------------------------------- nat表 SHADOWSOCKS 链 --------------------------------------------------------
iptables: No chain/target/match by that name.

----------------------------------------------------- nat表 SHADOWSOCKS_EXT 链 --------------------------------------------------------
iptables: No chain/target/match by that name.

----------------------------------------------------- nat表 SHADOWSOCKS_GFW 链 ----------------------------------------------------
iptables: No chain/target/match by that name.

----------------------------------------------------- nat表 SHADOWSOCKS_CHN 链 -----------------------------------------------------
iptables: No chain/target/match by that name.

----------------------------------------------------- nat表 SHADOWSOCKS_GAM 链 -----------------------------------------------------
iptables: No chain/target/match by that name.

----------------------------------------------------- nat表 SHADOWSOCKS_GLO 链 -----------------------------------------------------
iptables: No chain/target/match by that name.

----------------------------------------------------- nat表 SHADOWSOCKS_HOM 链 -----------------------------------------------------
iptables: No chain/target/match by that name.
-----------------------------------------------------------------------------------------------------------------------------------

-----------------------------------------------------------------------------------------------------------------------------------

**Comment by sadoneli** [comment]
iptables内没规则，尝试设置下插件的启动延迟

**Comment by jorking** [comment]
试过设置延迟5秒， 30秒，还是一样的问题。
插件我只安装了KoolProxy，webshell，虚拟内存。

**Comment by jorking** [comment]
3.59的时候是正常的。

**Comment by jorking** [comment]
卸了koolproxy就好了，装上koolproxy又出现同样的问题。过一阵子我把jffs重新格式化下试试。

**Comment by zycboss** [comment]
和koolproxy冲突比较多，大部分莫名其妙的不工作，卡代码，都是KP引起的，KP关掉就好了
