### ISSUE TITLE
更新3.7.3 重启报错，国外连接X

### ISSUE THREAD

**Issue by red0319** [koolshare/koolshare.github.io#551]
router: R6300V2 Firmware:380.59_beta2-X6.6.0 插件版本 3.7.3
更新 3.7.3 重启服务报错，日志如下：
2017年11月19日 00:39:12: =============== 梅林固件 - shadowsocks by sadoneli&Xiaobao ===============
2017年11月19日 00:39:12:
2017年11月19日 00:39:12: -------------------------- 关闭Shadowsocks ------------------------------
2017年11月19日 00:39:12: 删除ss相关的名单配置文件.
2017年11月19日 00:39:12: 重启dnsmasq服务...
2017年11月19日 00:39:12: 清除iptables规则...
2017年11月19日 00:39:15: 清空ipset名单...
2017年11月19日 00:39:15: 清除重复的ip rule规则.
2017年11月19日 00:39:15: 删除ip route规则.
2017年11月19日 00:39:15: 清除nat-start, wan-start中相关的SS启动命令...
2017年11月19日 00:39:16: -------------------------- Shadowsocks已关闭 -----------------------------
2017年11月19日 00:39:16: ----------------------- shadowsocks 启动前触发脚本 -----------------------
2017年11月19日 00:39:16: ss启动前触发：你选择了普通节点，不触发负载均衡启动！.
2017年11月19日 00:39:16: ------------------------- 梅林固件 shadowsocks --------------------------
2017年11月19日 00:39:16: 使用nslookup方式解析SS服务器的ip地址,解析dns：114.114.114.114
2017年11月19日 00:39:16: SS服务器的ip地址解析成功：47.74.151.146.
2017年11月19日 00:39:16: 创建SS配置文件到/koolshare/ss/ss.json
2017年11月19日 00:39:17: 创建gfwlist的软连接到/jffs/etc/dnsmasq.d/文件夹.
2017年11月19日 00:39:17: 添加nat-start触发事件...用于ss的nat规则重启后或网络恢复后的加载.
2017年11月19日 00:39:17: 添加wan-start触发事件...用于ss的各种程序的开机启动，启动延迟0
2017年11月19日 00:39:17: ss规则定时更新任务未启用！
2017年11月19日 00:39:17: 设置订阅服务器自动更新订阅服务器在每天 3 点。
2017年11月19日 00:39:17: 开启ss-local，提供socks5代理端口：23456
2017年11月19日 00:39:17: 开启dns2socks，监听端口：23456
2017年11月19日 00:39:17: 开启ss-redir进程，用于透明代理.
2017年11月19日 00:39:17: ss-redir的 tcp 走ss-redir.
2017年11月19日 00:39:17: ss-redir的 udp 未开启.
2017年11月19日 00:39:18: ss-redir 启动完毕！.
2017年11月19日 00:39:18: 加载nat规则!
2017年11月19日 00:39:18: 清除iptables规则...
2017年11月19日 00:39:19: 清空ipset名单...
2017年11月19日 00:39:19: 清除重复的ip rule规则.
2017年11月19日 00:39:19: 删除ip route规则.
2017年11月19日 00:39:19: 创建ipset名单
ipset v4.5: Unknown arg `-!'
Try `ipset -H' or 'ipset --help' for more information.
ipset v4.5: Unknown arg `-!'
Try `ipset -H' or 'ipset --help' for more information.
ipset v4.5: Unknown arg `-!'
Try `ipset -H' or 'ipset --help' for more information.
ipset v4.5: Unknown arg `-!'
Try `ipset -H' or 'ipset --help' for more information.
ipset v4.5: Unknown arg `-!'
Try `ipset -H' or 'ipset --help' for more information.
ipset v4.5: Line 1 does not start as a valid restore command

Restore failed at line 1:
Try `ipset -H' or 'ipset --help' for more information.
2017年11月19日 00:39:19: 写入iptables规则到nat表中...
iptables v1.4.14: Set white_list doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.14: Set white_list doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.14: Set black_list doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.14: Set gfwlist doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.14: Set black_list doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.14: Set chnroute doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.14: Set black_list doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.14: Set chnroute doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.14: Set black_list doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.14: Set chnroute doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
2017年11月19日 00:39:20: 加载ACL规则：【全部主机】【全部端口】模式为：gfwlist模式
iptables v1.4.14: Set router doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
2017年11月19日 00:39:20: 开启chromecast功能（DNS劫持功能）
2017年11月19日 00:39:20: 设置0秒开机延迟...
2017年11月19日 00:39:20: 设置使用nslookup方式解析SS服务器的ip地址.
2017年11月19日 00:39:20: 重启dnsmasq服务...
2017年11月19日 00:39:22: ------------------------- shadowsocks 启动完毕 -------------------------
2017年11月19日 00:39:23:
2017年11月19日 00:39:23: Across the Great Wall we can reach every corner in the world!
2017年11月19日 00:39:23:
2017年11月19日 00:39:23: =============== 梅林固件 - shadowsocks by sadoneli&Xiaobao ===============

**Comment by ioversleep** [comment]
我之前也遇到过重启后外国就一直X了，莫非这个bug还没修复吗？都不敢再重启了。

**Comment by sadoneli** [comment]
https://github.com/koolshare/koolshare.github.io/blob/acelan_softcenter_ui/shadowsocks/Changelog.txt#L470

**Comment by sbitpdc** [comment]
我的也是，版本号是3.8.4，也是出现这个提示。
