### ISSUE TITLE
建议去掉steamcommunity.com！

### ISSUE THREAD

**Issue by dsyo2008** [koolshare/koolshare.github.io#552]
可以去掉steamcommunity.com，没必要加上去，影响steam，比如SS突然断开，没法开steam！
这地址基本不被墙。

**Comment by ioversleep** [comment]
这个可能要去GFWLIST反映了

**Comment by kujourin** [comment]
自行添加黑白名單

**Comment by dsyo2008** [comment]
这是半年前反映。。。现在已经不被墙！

**Comment by cicku** [comment]
GFWList 从未添加过steamcommunity.com全站（本人是Steam 13年老用户，天天在线），这是由于转换脚本缺陷造成的，这种问题无解。
