### ISSUE TITLE
请教大神关于科学上网的几个问题

### ISSUE THREAD

**Issue by china-mao** [koolshare/koolshare.github.io#555]
非常感谢大神分享的科学上网神插件，受益匪浅，在此致以诚挚的感谢和敬意！！

在使用插件过程中遇到以下几个问题，还希望大神能不吝赐教：
1.插件是如何判断国外线路是否正常工作的。最近用的SS服务器不太稳定，经常更换地址端口或密码，所以想自己写个监控脚本，若发现国外线路出现Problem，则自动获取最新参数进行更换。大神能否公开插件自动刷新状态的代码或调用方式？

2.发现有时候参数都正常，但国外线路显示Problem，这个时候什么都不更改，直接重新提交一下，就显示OK了，不知道是不是个BUG。如上若能获取插件检测线路的方式，则可以在监控脚本里进行自动提交。

3.我用的路由器是R7000，路由器已可以科学上网，直接接路由器的设备包括台式电脑手机啥的都没有问题。同时我用有线连了个天猫魔盒做热点，以弥补房间里路由器无线覆盖问题，但发现连接到天猫魔盒上的设备，https方式能科学上网，普通http方式却不可以，不知是什么原因？

以上问题，还望大神不吝赐教，非常感谢！！

**Comment by china-mao** [comment]
自己也琢磨了下大神的源码，看到有如下地址是用于获取线路状态的：
url: '/ss_status'

但前提是必须得先登录WEB才能获取到正常结果，这样的话，就无法应用到后台监控脚本了。

所以还是希望大神能多多指教。

**Comment by china-mao** [comment]
还有一个问题，不知道是我验证的方法不对，还是其他什么原因，就是同样一个服务器，配置在路由器科学上网后再用手机通过WiFi连接，与直接配置在手机客户端上进行比较，明显发觉后者响应要更迅速，但是在电脑上用测速软件测，则又差别不是很明显，很是奇怪。

**Comment by sadoneli** [comment]
通过对路由器内ss访问(https://www.google.com.tw/)状态的检测，返回状态信息。状态检测默认每10秒进行一次，可以通过附加设置中的选项，更改检测时间间隔，每次检测都会请求https://www.google.com.tw/，该请求不会进行下载，仅仅请求HTTP头部，请求成功后，会返回working信息，请求失败，会返回Problem detected!

状态检测只在SS主界面打开时进行，网页关闭后，后台是不会进行检测的，每次进入页面，或者切换模式，重新提交等操作，状态检测会在此后5秒后进行，在这之前，状态会显示为watting... 如果显示Waiting for first refresh...则表示正在等待首次状态检测的结果。

**Comment by china-mao** [comment]
嗯。非常感谢大神的回复，已经搞定了，是在论坛里clang大神告知的。
