### ISSUE TITLE
3.7.3的UdpSpeedUp开启ssconfig.sh脚本有bug造成启动不能

### ISSUE THREAD

**Issue by weizhen199** [koolshare/koolshare.github.io#557]
if条件判断有bug
![image](https://user-images.githubusercontent.com/10826758/32988321-be8a5028-cd3c-11e7-9f07-3b52c723a2e8.png)
应该是这一段， 起 ss-redir的时候 进了tcp udp all go ss的分支

**Comment by sunpf** [comment]
更新了之后UPDSPEEDER就不起作用了，服务端收不到任何数据，

**Comment by sunpf** [comment]
udp2raw貌似也不起作有

**Comment by helaobibi** [comment]
我也是，我服务端也没有任何日志显示

**Comment by weizhen199** [comment]
服务端脚本写错了2333

**Comment by LockVer** [comment]
我还以为只有我的有问题。。。
