### ISSUE TITLE
3.7.3 UdpSpeedUp V2 自定义参数BUG

### ISSUE THREAD

**Issue by weizhen199** [koolshare/koolshare.github.io#558]
自定义参数没起作用，我看进程里的我加的-q1参数没有

**Comment by casparpoon** [comment]
應該是升級到3.7.3後, 整個UDPSpeeder也沒用了, server端的log在now listening at x.x.x.x後便沒有顯示

**Comment by weizhen199** [comment]
@casparpoon #557 不能启动是这个问题 #

**Comment by casparpoon** [comment]
@weizhen199 我的啟動沒有問題, 就是升到3.7.3後, server收不到client的信息, 請問你如果不加-q1能用嗎?

**Comment by weizhen199** [comment]
@casparpoon  -q1参数bug不会影响正常使用，不能用是我提的另外一个bug
