### ISSUE TITLE
kcptun进程总是挂掉

### ISSUE THREAD

**Issue by cnekol** [koolshare/koolshare.github.io#559]
不知是我个人问题还是大家都有这问题。现在版本似乎kcptun特别容易崩溃。我路由器上就跑了一个transmission（已限速）和aliddns，内存留有大半。已经删除重装尝试了很多次，甚至格式化了jffs和重置了路由器，依旧如此。
kcptun启动正常，刚开始运行一切正常，不过很快就会挂掉。kcptun显示未运行。

另离线安装包（不论新旧）进行安装时似乎总是把程序版本定为3.6.5(与UI上显示不一致)。不过升级正常ss内UI显示版本也正常，可以正常更新。各程序版本也是最新。
![Image](https://i.imgur.com/rkrQlb1.jpg)

**Comment by grapehunter** [comment]
> kcptun启动正常，刚开始运行一切正常，不过很快就会挂掉。kcptun显示未运行。
同遇到，网上查也有别人遇到，似乎和koolproxy有冲突，我没有验证，暂时把插件关闭了等修复

**Comment by cnekol** [comment]
我并没有使用koolproxy。
所有使用的软件只有上述的：
1. transmission
2. aliddns
3. shadowsocks

* 型号：AC68U

**Comment by msn1983aa** [comment]
可能是内存小了，我的6300V2也是经常挂掉，重启下kcp又可以坚持几天，不过更新到373版本后又要好一点了

2017-11-20 5:08 GMT+08:00 cnekol <notifications@github.com>:

**Comment by Myoko** [comment]
关键还是看线路你用劣质线路 再怎么用KCP多发包都是那样

**Comment by cnekol** [comment]
我已经持续使用kcptun一年以上了。VPS只我自己私人使用，不存在线路问题。手机，路由，电脑都在使用，无楼上所述线路是否劣质，且我们这里在单纯讨论的是kcptun的运行，与线路没有任何关系。

内存问题也没有，长久以来一直正常运行的，内存我留有一半及以上（AC68U）。之前也是采用离线安装的，实际上当时在最新版本时候仍然正常使用。
我因为硬盘挂载问题折腾了一番，再重新离线安装了一次，这之后就无法正常运行了。我一直使用histroy目录中最新的次新版本包安装后再升级处理的。出现kcptun会挂掉的问题后我选择了重置路由器但仍然如此。如有必要，我会选择重刷路由器做一次测试。

**Comment by cnekol** [comment]
@msn1983aa 

    可能是内存小了，我的6300V2也是经常挂掉，重启下kcp又可以坚持几天，不过更新到373版本后又要好一点了

内存我留有一半以上，出问题之前一切正常运行。我是前两天硬盘挂载有问题，所以去掉硬盘格式化后重新装的，transmission也重装了。

刚才ssh连接路由器手动加参数启动了kcptun客户端，显示是内存溢出，以下是手动启动kcptun输出的数据。

    fatal error: runtime: out of memory

    runtime stack:
    runtime.throw(0x204aae, 0x16)
            /usr/local/go/src/runtime/panic.go:605 +0x70 fp=0xbe9b6b58 sp=0xbe9b6b4c pc=0x3aab8
    runtime.sysMap(0xf5a0000, 0x1060000, 0x1ee01, 0x32e7b0)
            /usr/local/go/src/runtime/mem_linux.go:227 +0x104 fp=0xbe9b6b7c sp=0xbe9b6b58 
    pc=0x246c0
    runtime.(*mheap).mapBits(0x321dc0, 0x10600000)
            /usr/local/go/src/runtime/mbitmap.go:160 +0x8c fp=0xbe9b6b94 sp=0xbe9b6b7c pc=0x212dc
    runtime.(*mheap).setArenaUsed(0x321dc0, 0x10600000, 0x0)
            /usr/local/go/src/runtime/mheap.go:525 +0x24 fp=0xbe9b6ba0 sp=0xbe9b6b94 pc=0x32160
    runtime.(*mheap).init(0x321dc0, 0x400000, 0x200000)
            /usr/local/go/src/runtime/mheap.go:510 +0x414 fp=0xbe9b6bb4 sp=0xbe9b6ba0 pc=0x31dfc
    runtime.mallocinit()
            /usr/local/go/src/runtime/malloc.go:392 +0x1f4 fp=0xbe9b6bfc sp=0xbe9b6bb4 pc=0x1f018
    runtime.schedinit()
            /usr/local/go/src/runtime/proc.go:481 +0x30 fp=0xbe9b6c18 sp=0xbe9b6bfc pc=0x3d1c0
    runtime.rt0_go(0xbe9b6c64, 0xb, 0xbe9b6d8f, 0xbe9b6da3, 0xbe9b6da8, 0xbe9b6db5, 0xbe9b6dbc, 
    0xbe9b6dc4, 0xbe9b6dca, 0xbe9b6dd0, ...)
            /usr/local/go/src/runtime/asm_arm.s:61 +0x84 fp=0xbe9b6c58 sp=0xbe9b6c18 pc=0x684e8


不知是否个例。看样子是库有问题？也不知是否entware有影响，但之前使用都是正常的。烦请问下有无解决办法。

另，插件中心提供的虚拟内存插件，在安装时似乎会直接覆盖 /jffs/scripts/post-mount 配置。如果说是使用了entware的用户不修改并加上其挂载点的话，会在重启后无法正确挂载entware目录导致安装在其目录下的软件无法使用。目前还未测试重启后 虚拟内存插件 在路由器重启后是否会再次覆盖配置。

@Myoko 

    关键还是看线路你用劣质线路 再怎么用KCP多发包都是那样

此处我们并未讨论vps线路问题而是在讨论kcptun运行的问题。所以你提出的这个论点在此处没有意义。

**Comment by cnekol** [comment]
完全重置路由器后一切恢复正常。应该是我之前把系统搞乱了，应当属于个例。

**Comment by grapehunter** [comment]
@cnekol 
我回滚到3.6.0了，可以正常用

**Comment by cnekol** [comment]
@grapehunter 
我是完全重置路由器，包括格式化jffs和恢复原厂。参数使用手动填写。
然后使用3.6.0安装包进行离线安装然后再升级到最新版本，现在回归正常。
