### ISSUE TITLE
路由器上的透明代理

### ISSUE THREAD

**Issue by liuminglm** [koolshare/koolshare.github.io#560]
我是在路由器上部署了v2ray，局域网内完美实现透明代理，但是v2ray只能直连。请问怎么才能让v2ray发出来的请求走ssr的透明代理

**Comment by gbmeco** [comment]
你的V2RAY路由器透明代理是怎么实现的，能分享个详细点的说明吗？我看到推上有人说用科学上网工具连路由的透明代理V2RAY，然后实现科学上网。也就是部署了V2RAY 透明代理之后，用科学上网插件判断是走V2RAY还是直连。但是不知道怎么实现的。。。。。。
