### ISSUE TITLE
UDPspeederV2的默认模式已经改成mode 0

### ISSUE THREAD

**Issue by wangyu-** [koolshare/koolshare.github.io#561]
非常感谢作者集成我的软件。

之前的默认模式是`--mode 1`。虽然我在readme里推荐了使用--mode 0，这样可以避免MTU问题。无奈很多人都不认真看readme，造成一些游戏玩不了，现在我直接把默认模式改成了`--mode 0` 。

希望这里集成的UDPspeederV2也能更新一下。谢谢。

(client 和server的mode即使不一致，也能正常工作，所以即使暂时不更新的话，也不用担心兼容性问题。只是更新以后默认参数能免去MTU的麻烦，推荐更新)

===分割线===
一个插件里的描述问题：
![koolshare](https://user-images.githubusercontent.com/4922024/32990701-d6116344-cce2-11e7-9d55-2f85469996e3.PNG)

`--timeout仅在mode 0模式起作用`.

我以前在`使用经验`里确实这么说过，不过这是一个笔误，实际上没有这回事>< .

**Comment by cnekol** [comment]
非常感谢各位作者的辛勤付出。

**Comment by LockVer** [comment]
感谢大佬

**Comment by huayuanp** [comment]
感谢大佬

**Comment by sadoneli** [comment]
好的大佬

**Comment by wangyu-** [comment]
不敢😅

**Comment by wangyu-** [comment]
看了一下更新log，里面提到：

>KCPTUN先串联UDPspeeder，再串联UDP2raw、甚至UDP2raw串KCPTUN。我知道这很绕，不过只要知道下面的关系，相信如何配置，就难不到你~

kcptun自带基本的FEC功能，如果不需要更复杂的功能的话，一般不需要和UDPspeeder串联。

一般kcptun串udp2raw就够用了。

**Comment by wangyu-** [comment]
@sadoneli

**Comment by wangyu-** [comment]
@sadoneli 大佬
