### ISSUE TITLE
koolgame游戏模式。登录GTA5线上模式。路由器会重启。

### ISSUE THREAD

**Issue by 344796521** [koolshare/koolshare.github.io#565]
6300V2 梅林7.7 测试过老版本和各种版本的ss，PC 使用   每次登录GTA5的时候，路由器都会重启，CSGO和吃鸡正常。偶尔CSGO会无法连接服务器。
大概路由器重启是因为日志里面出现PCP: External IP in request didn't match interface IP。

**Comment by lingaoyi** [comment]
https://github.com/koolshare/koolshare.github.io/issues/469

**Comment by 344796521** [comment]
@lingaoyi 添加虚拟内存还是一样。连接线上服务器就崩溃。阿里云香港节点。

**Comment by lingaoyi** [comment]
我也是无解，酸酸乳游戏模式才叫正常一点。

**Comment by MikeNg2018** [comment]
对，我也会这样，添加了SWAP都不行，所以都不用了

**Comment by icetea0822** [comment]
我也是这样啊，但是路由器不是重启，是Wi-Fi自动断开，路由器上两个Wi-Fi的灯都亮着，过一会就又自动连接上了，这个问题解决了么？

**Comment by skyhsiao** [comment]
我还以为只有我一个人是这样,我也是这种情况,路由会重启
