### ISSUE TITLE
3.7.3关于UDP加速的2个bug综述

### ISSUE THREAD

**Issue by DimGG** [koolshare/koolshare.github.io#568]
1.udpspeeder以及udp2raw串联的情况下运行正常，但是单开udpspeeder或者udp2raw的情况下服务器无收包，怀疑插件的引流逻辑有漏洞。
2.udpspeederV2添加mode0以及-q1后，与udp2raw串联也无法正常启动，参数设置有bug。

**Comment by imsaoray** [comment]
碰到同样BUG，udpspeederV2填上-q1参数后，udp2raw就无法正常启动

**Comment by w12928293** [comment]
@imsaoray  原来是这个参数的问题，昨天我折腾了半天，始终只有udpspeeder可以运行，就放弃了，刚刚试了试去掉-q1参数，udp2raw果然就可以了。
但是有一点很疑惑，这个-q1参数是在梅林上（vps上的udpspeeder根本就没运行），而且我也没勾选udpspeeder，也会影响udp2raw的启动。。。

**Comment by helaobibi** [comment]
我串联2个，udp2raw有日志刷新，udpspeeder什么日志都不显示，我用的是mode0，没有加-q1参数

**Comment by wangyu-** [comment]
https://github.com/wangyu-/UDPspeeder/issues/69

有人反馈3.7.3单开udpspeeder不可以用，但是降级到3.7以后就可以了。

**Comment by helaobibi** [comment]
@DimGG 请问兄弟，你串联起来后udpspeeder的服务端有日志刷新吗？
我的情况是串联后，udp2raw有日志刷新，udpspeeder界面没有日志刷新！
@wangyu- 谢谢反馈啊，我还是想用udp2raw，3.7没有udp2raw

**Comment by imsaoray** [comment]
@helaobibi udp2raw只是在你UDP被限制或屏蔽的情况下用，一般只需要加速就行了

**Comment by helaobibi** [comment]
@imsaoray 我这里udp肯定屏蔽，我是移动的宽带，我单开udp2raw服务端也没有日志

**Comment by imsaoray** [comment]
@helaobibi 你那udp2raw的端口指向弄对了么，单开的话应该直接指向SS的监听端口，如果没弄错的话那就有可能梅林这边有BUG，不行你就试下KOOLgame模式的UDP IN TCP吧。如果再不行，我只能建议你用国内中转了

**Comment by DimGG** [comment]
@helaobibi 串联启动后只要看udp2raw的日志就可以了，服务器上运行一下netstat -u 看看有没有udp连接起来，一般会有一个到你udpspeeder端口的记录，然后很多到你$$的记录，就说明启动成功了。
如若没成功，一条记录都不会有。

**Comment by helaobibi** [comment]
@DimGG 也就是说只要看到udp2raw服务端看到日志就行了对吧，udpspeeder服务端没有日志对吧？

**Comment by sadoneli** [comment]
新版本应该没这个问题了
