### ISSUE TITLE
更新后所有流量都走代理了

### ISSUE THREAD

**Issue by zxszx** [koolshare/koolshare.github.io#570]
更新3.7.3之前是好的，更新后设置也是国内优先，使用运营商DNS，模式是gfwlist,无论下载，还是微博，打开网页，都走得代理的流量。之前尝试关闭重启后，微博，上网等好了，BT下载还走得代理流量，一天跑了几十G流量。

**Comment by Myoko** [comment]
你自己看看你是怎么设置的用的什么模式

**Comment by sadoneli** [comment]
一般是dns解析问题，请检查
