### ISSUE TITLE
单开udpspeederv2不起作用

### ISSUE THREAD

**Issue by apango** [koolshare/koolshare.github.io#572]
1. 环境：
   我有两个VPS和一个梅林。
   VPS一个A一个B，A用来做$$服务端，B用来测试。
   $$插件版本3.7.3，游戏模式，并单开udpspeederv2加速。
   
2. 配置参数
    $$插件:
    
![1](https://user-images.githubusercontent.com/7135616/33078232-fe2af558-cf0c-11e7-9148-c6c2321b35cb.png)

    
![2](https://user-images.githubusercontent.com/7135616/33078250-0bdb022e-cf0d-11e7-9588-8f15a9174042.png)

 3. 问题描述：
     开启$$+udpspeederv2后，tcp连接正常，udp连接其实也正常。但是没有加速。
     梅林上用netcat发送，B上面用nc监听，udp流量应该从梅林经过A上的$$并由udpspeeder加速，发送到B。B上面确实可以接受到梅林上发来的udp包，但是A上面的$$日志和udpspeederv2日志均无显示。
     
     梅林上用命令netcat -u [B的IP] [udp测试端口] 发送udp数据到B
     B上面用 nc -ul [udp测试端口] 监听外部发来的udp数据
     A上面$$和speederv2均通过systemctl做成系统服务，用systemctl和journalctl查看日志。

      通过梅林发送的udp包在systemctl status shadowsocks和systemctl status speederv2输出的日志中均无显示，在journalctl输出的日志中也无显示。在连上梅林的PC测试ping也能有问题，谷歌网址ping不通，自己的vps可以ping通。

    说明梅林上的测试udp包没有经过A的$$插件和udpspeederv2直接发送给了B。

**Comment by casparpoon** [comment]
同樣情況, 降至3.7.2一切正常

**Comment by helaobibi** [comment]
@casparpoon 3.7.2哪里有下载history好像没有

**Comment by sunpf** [comment]
梅林上难道不是应该填写本地IP 和端口到1092吗 直接写服务器IP 端口不是就没经过UDPSPEEER？

**Comment by apango** [comment]
我把vps上的配置也贴一下，我配置为systemd的服务了，.service文件内容如下

[Unit]
Description=speedev2-ss service
After=syslog.target network.target auditd.service
[Service]
Type=simple
User=nobody
ExecStart=/usr/local/bin/speederv2 --report 10  -s -l0.0.0.0:[udp监听端口号，即梅林上的udpspeeder远程服务端口号] -r127.0.0.1:[$$服务的端口号]  -f20:10 -k ****** --mode 0
ExecReload=/bin/kill -HUP
ExecStop=/bin/kill -s QUIT  PrivateTmp=true
Restart=always
[Install]
WantedBy=multi-user.target

启动服务后的滚动日志最后一行如下，即使发送了测试udp包该日志也不滚动：
Nov 22 00:54:35 vultr.guest speederv2[进程号]: [2017-11-22 00:54:35][INFO]now listening at 0.0.0.0:[加速服务端口号]

**Comment by casparpoon** [comment]
@apango 這位仁兄把它backup了
 [https://github.com/heweiye/Merlin_Shadowsocks/blob/master/shadowsocks_3.7.2.tar.gz](url)

**Comment by sadoneli** [comment]
单开确实有问题，待修

**Comment by apango** [comment]
@sadoneli  更新到3.7.4后该问题修复，谢谢
