### ISSUE TITLE
设置ss/ss-redir mtu不起作用

### ISSUE THREAD

**Issue by DimGG** [koolshare/koolshare.github.io#574]
设置成了1200，但是udpspeederv2 mode1下报错数据包是1432，没有起到作用

**Comment by wangyu-** [comment]
我搜了下 s的mtu选项，能查到的资料只有：

>--mtu <MTU>
Specify the MTU of your network interface.

简单看了眼s的代码，貌似s并不能帮你把udp包拆分到指定的mtu以下，只是会打印一条日志警告你一下。

```
       packet_size = mtu - 1 - 28 - 2 - 64;
```

```
    if (buf->len > packet_size) {
        if (verbose) {
            LOGI("[udp] remote_recv_sendto fragmentation");
        }
    }
```

所以在udpspeederv2 mode1的日志里报warning是正常的。
