### ISSUE TITLE
求助SS插件3.7.3+shadowsocks-libev v3.1.1服务器国外链接不稳定

### ISSUE THREAD

**Issue by sunbo186** [koolshare/koolshare.github.io#576]
RT-AC66U_B1 380.68_4-X7.7固件
SS插件3.7.3
自建SS服务器 shadowsocks-libev v3.1.1
没有使用任何加速

国外连接不稳定有时连接不上, 回退到shadowsocks-libev v3.0.8的服务器, 国外连接稳定正常.
有没有人遇到同样问题?

**Comment by DimGG** [comment]
3.7.3用的是3.1.0 libev，不匹配啊

**Comment by sunbo186** [comment]
降到3.1.0 还是同样现象
