### ISSUE TITLE
3.7.3超级大BUG-SSR没有起作用

### ISSUE THREAD

**Issue by daodaodaren** [koolshare/koolshare.github.io#579]
使用ssr模式，打开或者关闭科学上网，连接的ps4主机都没有断网，使用起来也是没有挂上ss的效果，暂时没有测试挂上ss后的ip是否是本地。求尽快修补或者提供3.7.2的history下载，目前只能回滚到3.6.6版本，看起来比较稳定。

**Comment by imsaoray** [comment]
cd /tmp
    wget --no-check-certificate https://raw.githubusercontent.com/koolshare/koolshare.github.io/acelan_softcenter_ui/shadowsocks/history/shadowsocks_3.6.4.tar.gz
    tar -zxvf /tmp/shadowsocks.tar.gz
    chmod +x /tmp/shadowsocks/install.sh
    sh /tmp/shadowsocks/install.sh

其中3.6.4改成你要的版本就行

**Comment by daodaodaren** [comment]
使用这种方式根本找不到自己想要的版本，而且文件夹下也没有3.7.2的下载。历史版本打包归档太过随意了一些。。。我最后只能下到本地一个一个离线安装去试版本。
history最新版本的3.7.1=3.7.0，安装之后也显示3.7.0版本号，两个gz包的文件大小一丝不差。3.6.4安装上去等于3.6.2,3.6.8=3.6.9，经过我十几次的安装卸载，终于找到了3.6.6，忘了下载的是哪个gz包了。。。

**Comment by daodaodaren** [comment]
说一下自己的路由器配置，ac68ub1,xiaobao梅林7.7...

**Comment by saikm01** [comment]
2楼的命令粘贴复制来的吧？下载的历史包没改名成shadowsocks.tar.gz，解压肯定进行不了啊
