### ISSUE TITLE
3.7.3很神奇，国外显示PD,实际使用正常。

### ISSUE THREAD

**Issue by orrzz** [koolshare/koolshare.github.io#580]
GCM搭的梯子，SSR+BBR

之前3.7.2一直正常。升了3.7.3，国外显示一直PD，但实际使用却正常。不知道怎么回事。

路由器R6300v2，7.7固件。

**Comment by sadoneli** [comment]
通过对路由器内ss访问(https://www.google.com.tw/)状态的检测，返回状态信息。状态检测默认每10秒进行一次，可以通过附加设置中的选项，更改检测时间间隔，每次检测都会请求https://www.google.com.tw/，该请求不会进行下载，仅仅请求HTTP头部，请求成功后，会返回working信息，请求失败，会返回Problem detected!

状态检测只在SS主界面打开时进行，网页关闭后，后台是不会进行检测的，每次进入页面，或者切换模式，重新提交等操作，状态检测会在此后5秒后进行，在这之前，状态会显示为watting... 如果显示Waiting for first refresh...则表示正在等待首次状态检测的结果。

状态检测反应的是路由器本身访问https://www.google.com.tw/的结果，并不代表电脑或路由器下其它终端的访问结果，透过状态检测，可以为使用SS代理中遇到的一些问题进行排查,一下列举一些常见的情况：

**Comment by orrzz** [comment]
升级了最新版3.7.5 全部正常
