### ISSUE TITLE
SRR是否支持ipv6？该如何设置？

### ISSUE THREAD

**Issue by Suxwx** [koolshare/koolshare.github.io#581]
查看了下vps的设置，是有ipv6的，但是在科学上网的设置中填写ipv6的地址后反而不能科学上网了，更别提上ipv6的网络。是我的设置问题还是插件不支持？
    "server":"0.0.0.0",
    "server_ipv6":"::",
    "local_address":"127.0.0.1",
    "local_port":1089,
 "port_password":{
        "18080":{"protocol":"auth_aes128_sha1", "protocol_param":"", "password":"5Lu85dO9eoesIqtW", "obfs":"tls1.2_ticket_auth", "obfs_param":""}

**Comment by msn1983aa** [comment]
srr是什么？

2017-11-23 13:50 GMT+08:00 Suxwx <notifications@github.com>:
