### ISSUE TITLE
更新到3.7.3之后ss订阅失败

### ISSUE THREAD

**Issue by lightmotion** [koolshare/koolshare.github.io#585]
我有两个ss服务提供商的连接，一个成功，一个失败。失败的提示：下载订阅失败...请检查你的网络...

不确定是不是3.7.3开始，因为从3.7.0开始一阵子没手动更新过，之前是没有问题的。

订阅成功的那个连接地址比较短，订阅失败的那个连接地址是很长一串的（338字符，不知道是不是这原因）。pc+mac+手机端都测试过可以订阅成功，只有梅林失败。

**Comment by sadoneli** [comment]
关闭订阅走ss试试

**Comment by lightmotion** [comment]
一直是关闭的。。。。。
