### ISSUE TITLE
3.7.3 无法使用 UDP2Raw 

### ISSUE THREAD

**Issue by LisonFan** [koolshare/koolshare.github.io#587]
配置好保存，没有进程

**Comment by sadoneli** [comment]
照说明启用

**Comment by LisonFan** [comment]
@sadoneli 按照是说明启用的了，节点和设备都改成了游戏模式，
![image](https://user-images.githubusercontent.com/9424775/33219374-ec8f24a0-d17c-11e7-883e-0ac26071244e.png)

**Comment by LisonFan** [comment]
@sadoneli 路由器进程没有 udp2raw，页面上也没显示 udp2raw 在运行

**Comment by LisonFan** [comment]
@sadoneli 
![image](https://user-images.githubusercontent.com/9424775/33219419-189ab8ca-d17d-11e7-963a-0c7a1c220e8a.png)
![image](https://user-images.githubusercontent.com/9424775/33219427-236addf2-d17d-11e7-94a0-fd9c7ecd145d.png)

**Comment by LisonFan** [comment]
@sadoneli 
udp2raw 项目文档上连接成功会滚 log，我看我服务器端木有滚 log

![image](https://user-images.githubusercontent.com/9424775/33219470-4e309b12-d17d-11e7-85f2-c764288a256c.png)

**Comment by LisonFan** [comment]
@sadoneli 
![image](https://user-images.githubusercontent.com/9424775/33219510-7adf7c5a-d17d-11e7-88bf-564fab7c5edb.png)

这是服务端启动的命令
