### ISSUE TITLE
请问如何检测kcptun是否生效？

### ISSUE THREAD

**Issue by phlips5437** [koolshare/koolshare.github.io#589]
我记得在之前的版本中，只有在白名单模式下支持内置kcptun加速，其他模式不支持

此前在3.5x版本下，开启内置kcptun加速后，youtube带宽可以跑到15M-30M，不开启只有5M带宽

但最近升级到3.73后，不管是白名单模式、游戏模式，开启或不开启kcptun加速，带宽都只用到了8M左右。请问如何判断这个情况？

**Comment by jianjam** [comment]
确实，感觉这几个版本kcptun压根就没启用过。设置好了，一点效果都没。

**Comment by sadoneli** [comment]
看看进程，看看日志就知道是否启用了

**Comment by wangyu-** [comment]
下载东西，或者用测速网站测速，用top看kcptun的cpu。如果kcptun进程的cpu占用变高了，就说明有流量流过。

**Comment by jianjam** [comment]
路由器页面显示 kcptun 工作中，也能看youtube，但是连接速度很慢只有几百，，和只用ssr一样慢，top看cpu占用 。client_linux_arm5也很低。最高不超过5%的来回跳。明显不正常。同样参数我把ssr和kcp在pc端上跑就可以加速成功。应该是还是插件的问题，前几个版本出现过一次，后来好像3.7.1 修复了。再往后更新就一直不行。

**Comment by phlips5437** [comment]
我是通过路由器占用了多少内存来判断的（已开启虚拟内存）
之前正常情况（内置KCPTUN加速生效的情况下）：不开启-整个路由器内存占用在90M以下；开启后-整个内存占用在100M以上

昨天晚上，我又进行了下测试：
1、关闭路由器上整个SS功能
2、在PC端安装SS客户端（内置KCPTUN模块）
3、访问视频网站，可以跑到15M带宽左右
因此我判断KCPTUN在我现有路由器中并未生效
