### ISSUE TITLE
3.7.4之后，国外一直PD

### ISSUE THREAD

**Issue by Fyred** [koolshare/koolshare.github.io#591]
用了SSR+KCP，以前一直好好的，直到昨晚更新了3.7.4，国外就PD了，尝试恢复默认设置重配参数均无效，只能回滚到3.7.3版本，问题消失。今天中午发现出了3.7.5，更新了一下，又是PD，等下再回滚3.7.3吧。
科技发展的太快，插件集成了udp加速的一堆功能，感觉脑袋有点跟不上节奏了。。。

**Comment by liwx56** [comment]
@saikm01 请问如何回到3.7.3？ 我更新到3.7.5, 结果全部都是PD,原先的不这样。
