### ISSUE TITLE
目前3.7.5插件没法实现KCP和upd并联吧

### ISSUE THREAD

**Issue by sunpf** [koolshare/koolshare.github.io#595]
监听端口都固定死的，好像没法实现并联？

**Comment by sadoneli** [comment]
并联只需要改绑定端口就行了啊
比如把kcptund的-r 改成127.0.0.1:1092

**Comment by sunpf** [comment]
多谢，还有个问题，路由上udpspeeder进程不知道为啥无法启动

**Comment by sunpf** [comment]
KCP 直接转发到服务器，或者直接串到UDP2RAW ，不经过SPEEDER,然后$$的UDP 流量走SPEEER到UDP2RAW，这种连法是不是不行，好像只能是1091 到1092到1093这样
