### ISSUE TITLE
升级后国外一直 PD

### ISSUE THREAD

**Issue by licao404** [koolshare/koolshare.github.io#597]
![image](https://user-images.githubusercontent.com/20166747/33232748-4b33f0de-d246-11e7-83b5-a896647993b6.png)

**Comment by huxuansong** [comment]
我也是

我用的SS+KCPtun，升级到3.7.5也出现了国外无法连接的问题。

但是，我的安卓客户端上和电脑客户端上的KCPtun+SS均正常，就是ac88u上的无法国外连接

升级之后我的服务器端未做任何修改，也就是3.7.3完全正常，现在升级到3.7.5国外无法连接

**Comment by liwx56** [comment]
我的也是。求解。

**Comment by luckyjamesriver** [comment]
我的也是一样，手机和电脑客户端都可以访问；netgear r8500,梅林 7.7 版本，一直和楼主一样的情况；也没有找到3.7.3安装包可以离线下载。

**Comment by huxuansong** [comment]
@luckyjamesriver 
退回3.7.3就正常了
可以在这里下载 https://github.com/koolshare/koolshare.github.io/tree/acelan_softcenter_ui/shadowsocks/history

**Comment by koolca** [comment]
3.7.5需要在kcptun页面配置服务器地址

**Comment by huxuansong** [comment]
@koolca 那样的切换服务器不是也需要重新填写kcptun的服务器地址？

**Comment by zynbasil** [comment]
对啊~应该一个节点有一套kcptun的配置才对

**Comment by luckyjamesriver** [comment]
@huxuansong 
谢谢高手！
退回了3.7.3，重新配置了服务器。
现在正常了！
看来还是梅林的插件出现了问题，还请大神尽快完善！

**Comment by ONEBOYS** [comment]
@luckyjamesriver 我回退到3.7.3还是不行。你的服务器是怎么配置的？

**Comment by ONEBOYS** [comment]
配置KCP加速后，账号变成 SS+KCP后可以了。

**Comment by cikichen** [comment]
回退到3.7.3后正常

**Comment by wyx409** [comment]
弱弱问下，请问怎么手动降级？下载了.gz文件，不会降级。感谢！
