### ISSUE TITLE
百度网盘有什么办法强制外网走呢。

### ISSUE THREAD

**Issue by yulhun** [koolshare/koolshare.github.io#6]
百度网盘有什么办法强制外网走呢。
外网白名单

添加需要强制走代理的外网ip地址
pan.baidu.com/*
pan.baidu.com/
yun.baidu.com/*
yun.baidu.com/
不行啊。我们公司屏蔽呢。只要这样呢  麻烦你谢谢。
PC上无法打开，CHORME  IE  EDGE都不行，可是手机上可以呢。为什么呢？

**Comment by yulhun** [comment]
还有192.168.1.1  用微软的最新浏览器EDGE不支持。进入以后修改某项提交还是没变。希望你看一下。

**Comment by sadoneli** [comment]
1 你添加的知识百度网盘或者百度云的域名，要想下载走ss，需要添加如下域名走代理(可能不全)
<pre>p.baidupcs.com
nj.baidupcs.com
qd.baidupcs.com
cdn.baidupcs.com
hot.baidupcs.com
www.baidupcs.com
hot.cdn.baidupcs.com
d.pcs.baidu.com</pre>

**Comment by sadoneli** [comment]
EDGE和IE都一样，不能保存配置的，因为js的一些问题，所以还是请用chrome浏览器
