### ISSUE TITLE
可以添加新版的负载均衡和高可用性么？

### ISSUE THREAD

**Issue by levinxu** [koolshare/koolshare.github.io#60]
$$ 2.5版之后出了负载均衡和高可用性，可以添加进来么？有多vps想提高速度，，谢谢～～

**Comment by jannson** [comment]
我们也是用开源项目的客户端。貌似$$-libev 并没有这样的功能吧？

**Comment by houzi-** [comment]
@levinxu 可以考虑使用haproxy来做负载均衡！

**Comment by woaihsw** [comment]
用haproxy的确可以...虽然我总觉得haproxy自己会因为大材小用而哭晕在厕所

但是与其说负载均衡，我觉得还是故障转移意义更大一点...

实现起来其实没什么难度...多开几个ss-local就可以...
