### ISSUE TITLE
电脑手机SS工作正常，路由器国外一直都是X

### ISSUE THREAD

**Issue by yonmarcea** [koolshare/koolshare.github.io#600]
![image](https://user-images.githubusercontent.com/34024972/33259830-0ddeb4ea-d399-11e7-9a8a-8c8edce8f660.png)
SS的配置完全和电脑和手机的SS配置一样，电脑手机上工作正常。在路由器上设置了怎么就一直都显示X呢？？没有使用KCP. 看看论坛的不少同样的问题，也做了版本降级，没有效果；做了延时，也没有效果。请高手指点，谢谢！

**Comment by ONEBOYS** [comment]
同样问题。插件升降级好几次了，服务器也装了3个服务。都是电脑直连能通，路由器配置不行。

**Comment by liwx56** [comment]
我也遇到一摸一样的问题，网上有人说降级插件可以解决，还没有试过。

**Comment by zycboss** [comment]
如果你是买的SS账号，很有可能是服务端的版本太低了，路由器上版本高不兼容

**Comment by Jamsen** [comment]
我遇到的问题是 SS 可以工作  SSR不行。。。 电脑可以。而且降级没法安装了。悲剧

**Comment by he1226** [comment]
我也是这个问题，求解
