### ISSUE TITLE
希望能为每个节点单独配置kcp加速

### ISSUE THREAD

**Issue by Colinelleo** [koolshare/koolshare.github.io#601]
3.7.5版本kcp加速设置了会变成全局的加速设置。希望能单独为每个节点配置kcp加速。

**Comment by gordengan** [comment]
顶一下，我好几个节点都是带kcp，虽然kcp参数端口都是一样的，但是每次kcp的IP地址还是要改一下，能不能先折中一下，kcp加个选项，地址自动和节点的服务器地址保存一致。我看现在KCP加速开关是带记忆功能的~~

**Comment by sadoneli** [comment]
IP地址留空即代表使用当前节点的服务器地址

**Comment by gordengan** [comment]
3Q~~get了~~
