### ISSUE TITLE
可否提供udp2raw和UDPspeeder串联的完整配置？

### ISSUE THREAD

**Issue by wangyu-** [koolshare/koolshare.github.io#602]
我收到了一些串联模式无法使用的反馈，但是我没有能刷梅林的路由器，没法自己测试。

我在论坛上和github上跟几个人讨论了好几页，也没得出一个确认可用的配置。

http://koolshare.cn/forum.php?mod=viewthread&tid=128995
http://koolshare.cn/forum.php?mod=viewthread&tid=128756
https://github.com/wangyu-/udp2raw-tunnel/issues/99#issuecomment-347191055

请@sadoneli看一下，希望能提供一个串联模式确认可用的完整的配置，包括服务端运行的命令和路由器端的配置截图。

谢谢。

**Comment by wangyu-** [comment]
貌似已经解决了，有人贴出了个可用的配置。

http://koolshare.cn/thread-128995-1-1.html

**Comment by wangyu-** [comment]
UDPspeeder wiki里面也增加了一个关于完整配置的文章。

https://github.com/wangyu-/UDPspeeder/wiki/koolshare版梅林固件UDPspeeder和udp2raw串联的完整设置

**Comment by uncledu** [comment]
@wangyu-  你好，请教一下，我使用梅林路由器，在路由器的web界面配置完，教程当中的服务端配置，是否也是指的路由器，即通过ssh登录路由器去运行2条串联的命令，还是指的我使用的机场的那个真正的vps的服务器？
