### ISSUE TITLE
shadowsocks【游戏模式】匹配玩家问题

### ISSUE THREAD

**Issue by halflifecs** [koolshare/koolshare.github.io#604]
玩ps4的nba live 18，设置ss为【游戏模式】后只有第一次匹配能正常匹配到人，打完这场再匹配，游戏就会提示一个错误。只有重新启动ss或者ps4重新连下网络才能再次联机匹配，然后第二局又是报错。非游戏模式下不会出错，应该是udp有问题。（正常匹配到游戏后udp加速是有效果的）
![image](https://user-images.githubusercontent.com/31009131/33331939-ea272432-d49d-11e7-9f98-0742b45715b2.png)
![image](https://user-images.githubusercontent.com/31009131/33331738-5f3e69d4-d49d-11e7-892d-c499fbd11692.png)
![image](https://user-images.githubusercontent.com/31009131/33331779-7741a078-d49d-11e7-94c8-e0f01e3cf13f.png)

**Comment by wangyu-** [comment]
关闭udp加速之后，是否仍然存在此问题？

**Comment by halflifecs** [comment]
关闭udp加速后好像也是有问题，我今晚再确定一下

**Comment by halflifecs** [comment]
@wangyu- 关闭udp加速就一次都匹配不上了
![image](https://user-images.githubusercontent.com/31009131/33374582-be0f3bd8-d541-11e7-808b-1d221f87cb8e.png)

**Comment by halflifecs** [comment]
ss换成3.7.3版本，不管开没开udp加速，都是只能匹配到一次。

**Comment by zycboss** [comment]
还是建议部署游戏模式v2，这个自带的UDP加速非常不稳定，效果也不好

**Comment by wangyu-** [comment]
>还是建议部署游戏模式v2，这个自带的UDP加速非常不稳定，效果也不好

你配置不明白就别误导别人了；而且楼主也说了，这个问题不管开不开UDP加速都存在。

**Comment by halflifecs** [comment]
貌似跟熵池大小有点关系，在服务器和路由器里面都用了rngd之后，游戏隔一段时间能匹配上一次。

**Comment by halflifecs** [comment]
dns解析偏好改成国外优先之后成功率更高了，之前没注意dns规则和游戏模式无关，以为连国外就会用国外dns

**Comment by halflifecs** [comment]
服务端ss-libev更新到最新3.1.3即可解决!!!
