### ISSUE TITLE
3.75下KCPTUN功能不生效

### ISSUE THREAD

**Issue by phlips5437** [koolshare/koolshare.github.io#605]
大家好，我目前在3.75下感觉KCPTUN功能并未生效，我从以下几个情况罗列了下现在状况：
1、内存占用：之前的几个版本中，一旦开启KCPTUN插件后内存占用明显飙高，会在110M上下，若不开启则80M左右。现在基本80M内存占用。
2、带宽占用：开启后在视频网站下带宽能跑到20M，不开启则5M。现在基本5M带宽。
3、与PC端对比：路由器不开启SS功能，在PC端开SS+KCPTUN，视频网站带宽可以跑到20M

基于以上3点，特别是第3条，我个人判断KCPTUN在3.75插件下并不生效（路由器AC68U，软件版本目前最新）

想请教下大家有没有什么解决方法（目前我已将整个软件中心卸载并重新安装过）

**Comment by sadoneli** [comment]
1 请更新3.7.6
2 看是否生效请命令运行`ps|grep client_linux_arm5` 查看进程是否启动

**Comment by phlips5437** [comment]
@sadoneli 
好的，今晚回去操作一下，给你反馈

**Comment by phlips5437** [comment]
@sadoneli 
刚才已完成3.7.6的更新，目测应该还是未启用，然后我想用你给我的命令来看，但在server端输入后没有反应
接下来该如何排错？

**Comment by gordengan** [comment]
3.7.6 用 KCPTUN，一段时间后会PD~~直接 保存&应用 来刷新还是PD，一定要开关一次插件才正常，不知道是不是我个案.....

**Comment by phlips5437** [comment]
你的这个情况是我在蛮久以前的版本碰到过的问题，后来我也尝试了部署虚拟内存，但情况依旧会发生。再后来我是定期两天左右自己手动开关一下kcptun插件，释放一下内存，才保证路由器不夯死，后来连续运行120多天路由器依旧正常
gordengan <notifications@github.com>于2017年11月29日 周三21:32写道：

**Comment by gordengan** [comment]
楼上
你连续运行120天都是要每2天手动开关一次吗？

**Comment by phlips5437** [comment]
对的，两到三天。不然会pd或者断流或者路由夯住各种不正常
gordengan <notifications@github.com>于2017年11月29日 周三22:06写道：

**Comment by luckyjamesriver** [comment]
更新到了3.7.6，一打开Kcp加速，就PD；现在退回到了3.7.3，结果也是这样的。
难道是服务器端出的问题？
手机和电脑的客户端都可以正常使用，因为没有Kcp加速功能，可以用这个逻辑来理解么？

**Comment by zycboss** [comment]
开KCP的正确姿势：
1.加载虚拟内存
2.关Koolproxy
3.开KCP
4.关SS
5.重新开SS

一般这样就正常了。

不过我R7000电信网还是用一段时间就PD，长也就1两个小时，短则几分钟，KCP进程就死掉了，也不会自己重启，必须手动开关SS。

但是很奇怪的是同样的R7000用在移动网上的时候，KCP基本上就不PD，不知道为什么

**Comment by luckyjamesriver** [comment]
强迫症犯了！其实是从来就没有好过！
再次安装了服务器，这次用的是ubantu 16.04X64;
一次性脚本，和原来的设置一模一样。
终于都OK了。

服务器系统原来选用的是centos6 及 7 ；如果打开KCP加速，都是PD状态。

俺是一枚老小白，反复的实践是笨手段，但是也试出了一个OK结果。
供大家参考。
