### ISSUE TITLE
netgear r7000 7.7固件 插件中心消失

### ISSUE THREAD

**Issue by vonhezhou** [koolshare/koolshare.github.io#608]
设备: netgear r7000
rom: koolshare改版梅林，v7.7
从v7.4升级到v7.7后一直都好好的。前几天突然发现，插件中心的版本变为0.0。
但是能够看到"未安装插件"，但是点击任何一个都没有反应。
点击"更新"，也没有反应。
此前已经安装的插件(SS)还正常的跑着，但是“已安装插件”中列表为空。

**Comment by zycboss** [comment]
只能格JFFS了，用一段时间貌似就会出现这种情况，和KP也有关系，这插件不稳定

**Comment by martinsol** [comment]
我的设备是rt-ac56u,格式了JFFS，还是无效

**Comment by sadoneli** [comment]
和jffs等关系比较大，有些机器会出现这些问题，导致skipd数据库出问题，需要格式化jffs后重新手动配置

**Comment by vonhezhou** [comment]
确认。格式化之后重装就ok了。kp没装，应该是别的什么东西导致的
