### ISSUE TITLE
AC5300从X7.5升级到X7.7后，由于SS节点被识别成了Koolgame类型，造成科学上网不能工作

### ISSUE THREAD

**Issue by Yonsm** [koolshare/koolshare.github.io#609]
如题，AC5300从X7.5升级到X7.7，科学上网不能工作，折腾了各种尝试，都没能解决，最后发现编辑节点时显示Koolgame类型，同时国外DNS中只能选择Koolgame模式。于是重新添加SS节点并应用，删除原来的节点，问题解决。

我确定在X7.5时添加的是SS节点，升级到X7.7后没有识别成功，请检查。

**Comment by xutao1224** [comment]
兄弟 同ac5300 跟你一样的问题 我是把ss插件升到了最新之后出的bug 删掉原来的被识别成koolgame的节点 添加新的ss节点就行,一开始以为是我服务端的ss依赖库版本太低了一顿折腾
