### ISSUE TITLE
Gfwlist模式的域名黑名单怎么设置？

### ISSUE THREAD

**Issue by hisune** [koolshare/koolshare.github.io#61]
```
server=/.test.com/127.0.0.1#7913
ipset=/.test.com/gfwlist
```
我在 域名黑名单 这样设置没用
![test](https://cloud.githubusercontent.com/assets/7941669/14586808/0f564af0-04d7-11e6-980b-3540be5ac74e.png)

求告知

**Comment by hisune** [comment]
vi /jffs/ss/ipset/gfwlist.conf
往这里面加，加完重启路由也不行

**Comment by sadoneli** [comment]
直接填入域名

**Comment by hisune** [comment]
@sadoneli 并没有用
![ttt](https://cloud.githubusercontent.com/assets/7941669/14675173/40983848-073a-11e6-99f8-4cf0513345cb.png)
![tt2](https://cloud.githubusercontent.com/assets/7941669/14675186/575222ba-073a-11e6-96f2-bfff96826bd6.png)

google.com 可以
google.com.sg 不可以

**Comment by sadoneli** [comment]
你添加这个作甚？gfwlist里应该都有了吧？

2016-04-20 20:56 GMT+08:00 Hisune <notifications@github.com>:

**Comment by hisune** [comment]
并没有，list里面只有google.com和google.com.hk
主要是就算是我手动vi /jffs/ss/ipset/gfwlist.conf加
```
server=/.google.com.sg/127.0.0.1#7913
ipset=/.google.com.sg/gfwlist
```
都没有用。。。conf文件好像根本不起任何作用，已经关闭了自动更新conf

**Comment by sadoneli** [comment]
google.com.sg
加进去

然后提交ss

电脑清空dns缓存，再开网页

2016-04-20 21:06 GMT+08:00 Hisune <notifications@github.com>:
