### ISSUE TITLE
同时开启kcptun+udp2raw和UDPspeeder+udp2raw

### ISSUE THREAD

**Issue by wangyu-** [koolshare/koolshare.github.io#610]
有些游戏会同时用到tcp和udp。同时开启kcptun+udp2raw和UDPspeeder+udp2raw，主要是为了同时加速tcp和udp流量，并且把底层的udp流量伪装成tcp。这种情况需要开2个udp2raw。

貌似目前插件里只允许开一个udp2raw，不能支持这种用法。如果能支持就完美了。

仅仅是建议，仅供参考。。。😀

**Comment by sunpf** [comment]
监听端口现在都是锁死的，没法并联的样子

**Comment by wangyu-** [comment]
>监听端口现在都是锁死的，没法并联的样子

跟端口锁死关系不大，关键是能开1个还是2个。

**Comment by sunpf** [comment]
嗯，不过路由器目前也没法用KCP 和SPEEDER 同时监听SS 的同一个端口

**Comment by sadoneli** [comment]
看来我理解错了，我以为同时开启kcptun+udp2raw和UDPspeeder+udp2raw只需要一个udp2raw，得想想怎么设计了，现在这已经比较复杂了

**Comment by gordengan** [comment]
wangyu-大也来用S大的插件了啊~~哈哈~~
我也来顶一下！！
ss-redir:TCP-->kcptun-->(udp2raw)
ss-redir:UDP-->UDPspeeder-->(udp2raw)
希望能搞成上面这样感觉就完美了，哈哈。主要是ss-redir出去的TCP和UDP分离开，然后udp2raw要开2个
