### ISSUE TITLE
非游戏模式开启udp2raw

### ISSUE THREAD

**Issue by jimmywmt** [koolshare/koolshare.github.io#611]
目前需要游戏模式才能开启udp2raw
但如果想要串接kcptun和udp2raw的话
就只有到terminal去开启
能取消这个限制吗?

**Comment by gordengan** [comment]
亲测kcptun+udp2raw串联~~不需要设置成游戏模式也能正常使用得
不开游戏模式只是udp不经过ss-redir，kcptun本来就是指只针对TCP的
