### ISSUE TITLE
求科学上网3.7.4版

### ISSUE THREAD

**Issue by china-mao** [koolshare/koolshare.github.io#613]
之前用的科学上网是3.7.4版的，一直很稳定，今天登陆电脑看到有升级3.7.6，就随手点了升级，结果升级后国外线路很不稳定，想回退到3.7.4，却发现History里3.7.4版的其实是3.7.3的。安装了也不稳定。
求真正的3.7.4版，感谢！

**Comment by sadoneli** [comment]
那就是3.7.4，依包名字为准
