### ISSUE TITLE
ssr不稳定，易掉线

### ISSUE THREAD

**Issue by holyXhit** [koolshare/koolshare.github.io#616]
有时早上起来国外连接就会显示X，重新启动插件才连得上；
或者重启路由器插件自动开启有时会连不上，仍需要重启插件。

**Comment by Edelwiess** [comment]
我也和你遇到了相同的问题。
我使用的是tomato版的插件。
希望开发者能提供个一键脚本，能自动重启，让我们加入到路由器计划任务中，重启路由器后1分钟或2分钟后自动重启一次ssr

**Comment by holyXhit** [comment]
附加功能里有开机启动延时的

**Comment by sadoneli** [comment]
插件本身只提供相关进程开启和iptables配置，不稳定和掉线等请检查其他地方

如果是开机启动有问题，请检查你的开机启动项
