### ISSUE TITLE
SS1.4.1 PSN测速 登入playstation network：失败，但是其他正常，可以看到好友可以登录商店

### ISSUE THREAD

**Issue by cjameslynn** [koolshare/koolshare.github.io#62]
SS1.4.1 
PSN测速 登入playstation network：失败
但是其他正常，可以看到好友可以登录商店

关闭SS后没有问题

**Comment by cjameslynn** [comment]
补充：PSN无法使用，之前可以看到好友是没开ss之前的状态

**Comment by xxcai** [comment]
我也是这样，好久了。换过ss也还存在这个问题，登不上psn。但是ps4可以上网页和商店下载。。。

**Comment by xxcai** [comment]
还有 开着ss为什么gitbub竟然提交不了评论。。。

**Comment by jannson** [comment]
最新版本如何？

**Comment by sadoneli** [comment]
请更新到最新ss版本并测试
