### ISSUE TITLE
求助：回滚SS是遇到的问题。

### ISSUE THREAD

**Issue by zjbr** [koolshare/koolshare.github.io#623]
自从手滑点了SS的升级以后，我的版本就由3.1.5升到了3.7.6，原来3.1.5升级的时候提示梅林必须是7.2版以上（我是6.6.1）结果这次没有提示，直接就升上来了，结果出国变X，想降级会3.1.5。按照方法操作，结果遇到新问题。我从历史文件夹中下载的3.1.5存档好像没有文件没有标称的6.2M大，解压也遇到这样的提示：
zjbr@R7000-F2A7:/tmp# 
tar -zxvf /tmp/shadowsocks_3.1.5.tar.gz                                            
tar: invalid magic                                                                                       
tar: short read                                                                                          
zjbr@R7000-F2A7:/tmp# 

大神给解答一下，这是怎么回事。

**Comment by zjbr** [comment]
zjbr@R7000-F2A7:/tmp# wget --no-check-certificate https://github.com/koolshare/k                         
oolshare.github.io/blob/acelan_softcenter_ui/shadowsocks/history/shadowsocks_3.1                         
.5.tar.gz                                                                                                
--2017-12-06 19:30:26--  https://github.com/koolshare/koolshare.github.io/blob/acelan_softcenter_ui/shado
wsocks/history/shadowsocks_3.1.5.tar.gz                                                                  
Resolving github.com... 192.30.255.112, 192.30.255.113                                                   
Connecting to github.com|192.30.255.112|:443... connected.                                               
WARNING: cannot verify github.com's certificate, issued by '/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=D
igiCert SHA2 Extended Validation Server CA':                                                             
  Unable to locally verify the issuer's authority.                                                       
HTTP request sent, awaiting response... 200 OK                                                           
Length: unspecified [text/html]                                                                          
Saving to: 'shadowsocks_3.1.5.tar.gz'                                                                    
                                                                                                         
shadowsocks_3.1.5.t     [  <=>                 ]  33.25K   130KB/s   in 0.3s                             
                                                                                                         
2017-12-06 19:30:29 (130 KB/s) - 'shadowsocks_3.1.5.tar.gz' saved [34052]                                
                                                                                                         
zjbr@R7000-F2A7:/tmp#

**Comment by zjbr** [comment]
自问自答喽，经过学习，摸索与迂回，问题最终解决了，但是不知道大神知道不，我最后一个安装步骤在webshell里显示都是乱码。还好，最终好用了

**Comment by iamltt** [comment]
请问最后是怎么解决的，我现在想回滚到以前的版本回滚不了

**Comment by sportfit** [comment]
I also want to know how to solve the final, although the firmware and plug-ins have done a good job in advance of the full backup, but ultimately hold back no upgrade, now seems to be right.
