### ISSUE TITLE
关于通过SSServet科学上网的问题

### ISSUE THREAD

**Issue by china-mao** [koolshare/koolshare.github.io#625]
R7000路由器，刷的最新版X7.7固件，在软件中心装的SSServer和科学上网，直接连接路由器什么都正常。但是远程通过SSServer连接想进行科学上网时，却发现国内的都正常，国外的却只能访问https的网站，同样的在家里用天猫魔盒做热点时，也是同样的情况。请问大神是哪里需要进行设置，还是本身就是这样的？

**Comment by dsc022** [comment]
same question
