### ISSUE TITLE
“sh: ss_config.sh: not found"

### ISSUE THREAD

**Issue by CoolDrinELiu** [koolshare/koolshare.github.io#628]
已经重新安装过ss，使用的安装ss步骤：

cd /tmp
wget --no-check-certificate https://raw.githubusercontent.com/koolshare/koolshare.github.io/acelan_softcenter_ui/shadowsocks/shadowsocks.tar.gz

tar -zxvf /tmp/shadowsocks.tar.gz

chmod +x /tmp/shadowsocks/install.sh

sh /tmp/shadowsocks/install.sh

切换节点、查看更新都是这样报错。是因为缺少ss_config.sh文件吧？但我不知道ss安装后在具体哪个目录。求帮助...

**Comment by xlighting2017** [comment]
jffs 开了么？ 默认在  
```bash
admin@xxxxxxxxxx: /jffs/.koolshare/scripts # ls -la
...
-rwxr-xr-x    1 admin    root           190 Nov 29 15:16 ss_config.sh*
...
```

**Comment by CoolDrinELiu** [comment]
@xlighting2017  enable jffs 一直是勾选着 “是”，这个文件夹的权限：

drwxrwxrwx    2 admin    root             0 Aug  1  2015 .                                               
drwxrwxrwx   11 admin    root             0 Aug  1  2015 ..
