### ISSUE TITLE
377版 很吃内存！

### ISSUE THREAD

**Issue by Myoko** [koolshare/koolshare.github.io#629]
刚升级到377版！发现开了科学上网之后内存占用75到80多！关闭之后内存占用48 还有一次路由器莫名其妙的自动重启了！并没有开定时重启的任务！之前从来没有发现过。

**Comment by Suxwx** [comment]
吃内存吃到路由自动重启。
而且有个问题
② 检测当前相关进程工作状态：（你正在使用SSR-libev,选择的模式是【gfwlist模式】,国外DNS解析方案是：Pcap_DNSProxy）
-----------------------------------------------------------
程序		状态	PID
ssr-redir	工作中	pid：6515
kcptun		工作中	pid：6532
Pcap_DNSProxy	未运行
-----------------------------------------------------------

经常性的pcap_DNSProxy启动不起来，要重启ss多次才能把pcap_DNSProxy启动

**Comment by Myoko** [comment]
② 检测当前相关进程工作状态：（你正在使用SSR-libev,选择的模式是【gfwlist模式】,国外DNS解析方案是：Pcap_DNSProxy）
-----------------------------------------------------------
程序		状态	PID
ssr-redir	工作中	pid：4871
Pcap_DNSProxy	工作中	pid：4845
-----------------------------------------------------------

**Comment by mingtochu** [comment]
3.7.7版本，使用Pcap_DNSProxy无法正常工作，我只好换成ss-tunnel暂时用着。

**Comment by sadoneli** [comment]
![image](https://user-images.githubusercontent.com/10495520/33793666-5c59b302-dcf6-11e7-8f3e-54519197be28.png)

Pcap_DNSProxy 0.4.9.5 极度吃内存的，尝试挂载虚拟内存看是否能正常使用

**Comment by Suxwx** [comment]
应该是Pcap_DNSProxy的问题，平均10分钟不到重启一遍，换成ss-tunnel后就不会重启了。
