### ISSUE TITLE
希望能把Pcap_DNSproxy增加回去

### ISSUE THREAD

**Issue by alisontnt** [koolshare/koolshare.github.io#635]
Pcap_DNSproxy很好用功能很强大啊，为什么要移除它呢😭

**Comment by Myoko** [comment]
因为之前377 的Pcap_DNSproxy4.95很吃内存会导致路由器自动重启

**Comment by casparpoon** [comment]
同感, 請問能否將3.7.6中的Pcap_DNSProxy 0.4.8.1加進新版本中
