### ISSUE TITLE
cdns解析国外的结果不是最优的

### ISSUE THREAD

**Issue by kxjhcmc** [koolshare/koolshare.github.io#636]
打个比方说，我SS服务器是美国那边的，解析GOOGLE的地址确实台湾的IP，因为台湾离我们物理距离最近，这个方案有这个问题存在。

**Comment by sadoneli** [comment]
![image](https://user-images.githubusercontent.com/10495520/33802863-a0ac4c9c-ddbc-11e7-9f35-e665fa0c6b5b.png)
HK 阿里云，facebook和google.com 解析得到的都是hk的，暂时未发现问题，请贴出你的解析结果我看看

**Comment by kxjhcmc** [comment]
如果你的ss服务器本身就在香港，可能发现不了这个问题

**Comment by kxjhcmc** [comment]
![image](https://user-images.githubusercontent.com/32127921/33802897-693a366a-ddbd-11e7-8aa5-3f8516e980d0.png)
这个是cdn解析结果

**Comment by sadoneli** [comment]
切了日本和新加坡测试，确实国外解析结果都是返回在香港

**Comment by kxjhcmc** [comment]
![image](https://user-images.githubusercontent.com/32127921/33802904-8673e1f4-ddbd-11e7-9e03-7d7164abbcbf.png)
他 的物理地址是中国台湾

**Comment by sadoneli** [comment]
回滚下版本，看看Pcap_DNSproxy之类的呢

**Comment by kxjhcmc** [comment]
![image](https://user-images.githubusercontent.com/32127921/33802906-ac5bccec-ddbd-11e7-875f-ff23914a0e6a.png)
我使用sstunnel，解析结果在美国，我SS服务器在美国，这个结果是正常的

**Comment by kxjhcmc** [comment]
这样的话，国外解析的结果不是最优的，相对于ＳＳ服务器来说

**Comment by sadoneli** [comment]
不过Pcap_DNSproxy也不是走代理，是直链的，国外cdn应该也不好
国外cdn加国内cdn最好的应该是原先chinadns，配合dns2socks或者ss-tunnel作为上游解析工具

**Comment by kxjhcmc** [comment]
对，确实是这样

**Comment by sadoneli** [comment]
或者就直接用dns2socks或者ss-tunnel，这样国外cdn也有，国内cdn有3万多条的那个cdn.txt提供，但是这样dnsmasq的消耗活导致路由的负担更大

**Comment by kxjhcmc** [comment]
能不能考虑，加个原先chinadns，配合dns2socks或者ss-tunnel作为上游解析工具？这样路由器负担也小了，也不需要cdn.txt名单了，国内国外的cdn也都比较好了

**Comment by sadoneli** [comment]
先观察下

**Comment by sadoneli** [comment]
又测试了下
![image](https://user-images.githubusercontent.com/10495520/33803255-68baac34-ddc6-11e7-9651-f603493bb7c6.png)

![image](https://user-images.githubusercontent.com/10495520/33803258-6f8c9f90-ddc6-11e7-8be7-4f1ad103f2c1.png)

dns2socks和cdns解析结果是一样的，这可能不是一个问题?空的话你也测试试试

**Comment by sadoneli** [comment]
用的是新加坡的vps节点测试的

**Comment by kxjhcmc** [comment]
换解析方式测试，有没有清空dns缓存，可能和缓存有关系

**Comment by kxjhcmc** [comment]
![image](https://user-images.githubusercontent.com/32127921/33803566-478d8d08-ddce-11e7-89d5-f8d84bcfbd02.png)
测试出来，还是那样的，图片上面是sstunnel,下面是cdns

**Comment by sadoneli** [comment]
我在路由上测试的，每次测试前重启过dnsmasq即代表清空了dns缓存
