### ISSUE TITLE
3.7.9 SSR所有DNS方案 不可以使用

### ISSUE THREAD

**Issue by mingtochu** [koolshare/koolshare.github.io#637]
3.7.8～3.7.9，SSR无法使用任何DNS方案。全局代理模式就可以。

**Comment by c939984606** [comment]
me，too

**Comment by walkerflyer** [comment]
me,too

**Comment by sadoneli** [comment]
无法重现，请贴出日志，运行状态，dns查询结果

**Comment by mingtochu** [comment]
<img width="499" alt="2017-12-10 4 41 39" src="https://user-images.githubusercontent.com/11163821/33803362-47a26a48-ddc9-11e7-85ff-7c3680c218ef.png">
<img width="582" alt="2017-12-10 4 42 15" src="https://user-images.githubusercontent.com/11163821/33803364-49f5c344-ddc9-11e7-9821-590d1f2edcf8.png">

**Comment by walkerflyer** [comment]
经测试是在内部网络-DHCP服务器中指定DNS的问题，所有域名都会使用该DNS解析，取消这个地方的DNS设置后就正常了

**Comment by mingtochu** [comment]
@walkerflyer 有效哦，改了确实正常了！ 但是之前不是这样子的。

**Comment by houchang1991** [comment]
dns的确是有问题，楼上说跟DHCP里指定dns有关，但是实测无关，我没有在lan内指定dns，一样只能全局模式才能用

**Comment by EricX1** [comment]
3.7.9确实有问题，只有全局模式才能正常用。内部网络我也没指定dns

**Comment by wee911** [comment]
无法使用，dns有问题

**Comment by mingtochu** [comment]
@sadoneli 
<img width="410" alt="2017-12-10 5 29 15" src="https://user-images.githubusercontent.com/11163821/33803670-e8bf3c52-ddcf-11e7-8dc7-5fe1e5910cfb.png">
<img width="342" alt="2017-12-10 5 30 13" src="https://user-images.githubusercontent.com/11163821/33803671-e9c68f9c-ddcf-11e7-8099-a8a699376354.png">
如图DNS Server什么都不填 且 自动接上DNS服务器
Ver: 3.7.7 DNS Server 1和2 填了 114.114.114.114, 114.114.115.115 使用ss-tunnel运行状态☑️工作不正常
Ver: 3.7.9 DNS Server 1和2 清除不填 使用ss-tunnel运行状态☑️工作正常
原因未知，大佬辛苦了！

**Comment by adam7757** [comment]
只有全局模式才能正常用

**Comment by sadoneli** [comment]
不能自定义dns的，国内dns都有污染
