### ISSUE TITLE
请问是不是不可以回滚到3.6.5之前的版本了

### ISSUE THREAD

**Issue by iamltt** [koolshare/koolshare.github.io#638]
一直没有升级，昨天升级之后，所有ss都不能用了，但是在其他终端都可以用，所以我想回滚到以前的版本，但是试过所有3.6.5之前的版本无论是用离线安装还是webshell安装都安装不了，3.6.6以上的都可以，请问应该如何回滚到3.6.5之前的版本

**Comment by c939984606** [comment]
在其他终端都可以用，是因为你当前的电脑dns缓存被污染了

**Comment by iamltt** [comment]
可能我表达错了，是在手机用其他SS客户端可以用我买的ss账号，但是在路由器的国外连接一直是×的，连到路由器的终端都不行
