### ISSUE TITLE
关于ADM和阿里旺旺的问题

### ISSUE THREAD

**Issue by tianshi1987** [koolshare/koolshare.github.io#64]
各位，我今天发现同事开启SS和ADM的时候，出现阿里旺旺无法登陆出现数据交换错误的提示，刚开始以为是我电脑的问题，后来我换成了MBA以后，OSX仍然提示数据接收错误，后我关闭了ADM以后就可以正常使用了，不知道这其中有问题没有？？

**Comment by sadoneli** [comment]
这个是ADM本身的问题，因为我们没有ADM源码，ADM作者那边又不积极，估计以后ADM都会是这样的

看以后的adbyby或者是开发组自己写的去广告插件吧

在 2016年4月21日 下午9:50，GePengWei <notifications@github.com>写道：

**Comment by tianshi1987** [comment]
谢谢，我知道了，我总体感觉ADBYBY的效率要比ADM高一些。不过这些都是业余的，也不好强求，还是感谢你们的努力付出，另外SADONELI你的1.4.3是否取消了pdnsd的模式呀？？，我更新1.4.2的时候还有的。

在 2016年4月21日 下午9:51，sadoneli <notifications@github.com>写道：

**Comment by sadoneli** [comment]
@tianshi1987 没取消，需要输入命令才能使用，因为pdnsd的一些原因，我不愿意让大家太依赖pdnsd，但是希望使用的，还是可以输入dbus set ss_basic_user=1,来开启pdnsd的显示

**Comment by tianshi1987** [comment]
thank you


2016-04-21 22:46 GMT+08:00 sadoneli <notifications@github.com>:
