### ISSUE TITLE
3.8.0版本DNS解析失败

### ISSUE THREAD

**Issue by shanlianboy** [koolshare/koolshare.github.io#641]
你好，更新版本之前因为dns失效，我的游戏设备自定dns成功连接，但是更新之后无论走什么dns都不好使，想离线安装3.7.9版本，但是安装失败，请问怎样才能禁用插件里自带的dns？或者成功降级，谢谢！

**Comment by wee911** [comment]
用gfwlist 就会dns出问题，用大陆白名单或者全局可以正常用
