### ISSUE TITLE
SSR 外网无效 SS可以正常工作  （电脑端没问题）

### ISSUE THREAD

**Issue by Jamsen** [koolshare/koolshare.github.io#644]
请教：

   路由器设置SSR 无法连接外网  服务器解析正常  电脑，手机（小火箭）都可以正常使用
   SS可以使用。 

   请问是什么问题？

感谢大神

**Comment by china-mao** [comment]
应该是服务端和客户端版本不匹配的原因。

**Comment by Jamsen** [comment]
谢谢。估计是这个原因 。
