### ISSUE TITLE
1.4.5 无限刷新 shadowsocks 那个配置界面

### ISSUE THREAD

**Issue by wd** [koolshare/koolshare.github.io#65]
停留在那个页面就会开始自动刷新，感觉是更新失败了，我看 ss-local 的版本是 2.4.4

**Comment by sadoneli** [comment]
/koolshare/bin/ss-local -v



2016-04-24 10:02 GMT+08:00 wd <notifications@github.com>:

**Comment by wd** [comment]
/koolshare/bin/ss-local -v

shadowsocks-libev 2.4.6

$ /usr/bin/ss-local -v

shadowsocks-libev 2.4.4

**Comment by sadoneli** [comment]
那就是更新成功的，也有可能更新不完整

下面办法认取其一
1 格式化jffs分区，后重新更新
2 修改/koolshare/ss/version,改成其它小的版本号，运行sh /koolshare/scripts/ss_update.sh


2016-04-24 10:13 GMT+08:00 wd <notifications@github.com>:

**Comment by wd** [comment]
我选择了2，然后执行没有报错。我看 version 里面也是 1.4.5 了。

但是进入 shadowsocks web 配置页面，会提示 '升级成功，重启 ss'，然后就开始不停刷这个页面，是不是有什么地方失败了？我看会起来好多这种进程。

26991 admin     1384 S    sh -c /koolshare/scripts/ss_config.sh > /tmp/syscmd.log 2>&1 && echo 'XU6J03M6' >> /tmp/syscmd.log &

**Comment by sadoneli** [comment]
估计是某个进程死循环了
先killall sh
再来一次2

2016-04-24 10:21 GMT+08:00 wd <notifications@github.com>:

**Comment by wd** [comment]
应该不是进程死循环。我只要关闭页面，等一会，看进程就都正常了。但是一旦打开页面，就会不停的启动个这些。刚打开页面的时候，能看到那个版本那里显示的就是 1.4.5，不过等页面完全打开，那个版本号的地方就会提示 「升级成功，重启 ss」然后读秒。system.log 里面的内容我截取一下如下

Sun Apr 24 10:18:54 GMT 2016: ------------------ Shadowsock gfwlist mode Started-----------------------
Sun Apr 24 10:18:56 GMT 2016:
Sun Apr 24 10:18:56 GMT 2016: Congratulation!
Sun Apr 24 10:18:56 GMT 2016: Enjoy surfing internet without Great Fire Wall!
Sun Apr 24 10:18:56 GMT 2016:
Sun Apr 24 10:18:56 GMT 2016: ================= Shell by sadoneli, Web by Xiaobao =====================
n Apr 24 10:18:51 GMT 2016: done
Sun Apr 24 10:18:51 GMT 2016:
Sun Apr 24 10:18:51 GMT 2016: ------------------ Shadowsock gfwlist mode Started-----------------------
Sun Apr 24 10:18:53 GMT 2016:
Sun Apr 24 10:18:53 GMT 2016: Congratulation!
Sun Apr 24 10:18:53 GMT 2016: Enjoy surfing internet without Great Fire Wall!
Sun Apr 24 10:18:53 GMT 2016:
Sun Apr 24 10:18:53 GMT 2016: ================= Shell by sadoneli, Web by Xiaobao =====================
XU6J03M6
XU6J03M6

**Comment by sadoneli** [comment]
升级成功后会自动重启一次ss，这是正常行的

2016-04-24 10:27 GMT+08:00 wd <notifications@github.com>:

**Comment by wd** [comment]
那我感觉是程序认为重启没成功？我看是有一个正在运行的 ss-tunnel 和 ss-redir 进程的。

目前主要是我每次打开那个页面就开始不断循环「正在升级」

**Comment by sadoneli** [comment]
是一直显示正在升级？

2016-04-24 10:34 GMT+08:00 wd <notifications@github.com>:

**Comment by sadoneli** [comment]
那我估计是某次升级被打断了还是什么，
dbus set ss_basic_install_status=0试试
不行最后就用之前说到的方法1

**Comment by wd** [comment]
执行  dbus set ss_basic_install_status=0   之后好了。

**Comment by wd** [comment]
建议考虑下增加检查一下是不是已经启动了一个配置脚本了，我刚才如果一直打开那个页面，就会启动很多个配置脚本，启动太多可能会导致路由器死机。
