### ISSUE TITLE
CDNS会让steam走ss

### ISSUE THREAD

**Issue by vonhezhou** [koolshare/koolshare.github.io#650]
Windows客户端，开启cdns，gfwlist模式下，steam商店的区域会变为ss服务器所在的地区。

**Comment by Myoko** [comment]
换 dns2sock吧！

**Comment by vonhezhou** [comment]
换dns2sock会导致手机无法翻墙。
ss-tunnel再3.6.0之后就不能用了，不知道是为什么
在用chinadns2,但是ps4上安装的youtube竟然可以用。我的ps4根本没有配置到翻墙的名单里面。不知道时什么情况。有空再看看

**Comment by paladin4fan** [comment]
GFWlist会判定Steam社区走SS
商店的话我这里CDNS的方案解析到的CDN地址是靠近本机IP的
ss服务器是洛杉矶 解析的地址在香港

**Comment by vonhezhou** [comment]
嗯，这几天使用下来发现，即使是ChinaDns2方式，偶尔也会变成美区的，应该是别的什么原因导致的。
ps4可以翻墙是因为升级了之后，默认变成全局gfwlist模式了。
