### ISSUE TITLE
同一个账号 路由器登录后 显示国外链接失败 但是手机用ss上没问题啊

### ISSUE THREAD

**Issue by ydl825312** [koolshare/koolshare.github.io#657]
路由器上保存后没用 只能上国内
如果用手机单独挂ss 可以用 非常流畅 
请问是为啥啊？

**Comment by liumengjkkl** [comment]
我也是这个问题  同一个账号    电脑上可以   梅林上国外连接为显叉   用不了    换了几个账号都一样   koolgame可以正常使用

**Comment by angryleilei** [comment]
我最近也是路由器更新到ss最新然后上不了外网了，离线安装3.7.0暂时解决问题了

**Comment by liumengjkkl** [comment]
同上   离线安装3.7.0解决！
