### ISSUE TITLE
Feature Request: SS账号信息输入支持*.json及其它更方便的import/export模式（见内）

### ISSUE THREAD

**Issue by gdillainepub** [koolshare/koolshare.github.io#66]
多数的$$服务商提供*.json直接下载，其中包含多个节点信息。

1. 似乎目前koolshare的SS账号信息配置方法，不支持导入一次性包含多个节点信息的*.jason文件、或者包含多个节点配置的txt文件。（见附件demo.txt）有些$$服务提供10多个server，这样一个个手工输入不是太方便。

2. 我尝试过“恢复配置”我的jason配置文件，结果没有任何反应。我也尝试导出配置，结果似乎文件是另一种格式，并且只包含了1个节点的信息。

3. 另外还看到有的$$ provider用类似下面URL来表示配置：
ss://rc4-md5:passwd@server.shadowsocks.com:65535

我不知道这是他们自创的还是目前$$服务器已成标准的URL表达法，如果是公认标准的话，希望不久Koolshare的SS模块也能识别这种SS账号！

[demo.txt](https://github.com/koolshare/koolshare.github.io/files/233260/demo.txt)

**Comment by houzi-** [comment]
这是可以实现的，可以使用sed和awk的文本处理功能

**Comment by houzi-** [comment]
这样还不如直接使用upload上传json文件，这样实现起来有点low！

**Comment by jannson** [comment]
是的，直接上传 json 文件更直接。估计好实现。

**Comment by sadoneli** [comment]
这个已经实现了啊，现在ss_develop分支已经可用

**Comment by jannson** [comment]
master 可以用的时候再 close 掉。
