### ISSUE TITLE
科学上网开关，能否通过固件里的定时脚本，每天重启

### ISSUE THREAD

**Issue by zynbasil** [koolshare/koolshare.github.io#663]
R7000 
380.65_X7.4

就是写个脚本，定时重启下（比如晚上4点）
跑久了会挂，然后需要手动开关下

**Comment by zxq1002** [comment]
同需要定时重启功能
发现跑一段时间国外连接就不通了，点击保存重启下又恢复了

**Comment by xlighting2017** [comment]
进shell,     

cru -a ssrestart 0 3 * * * /koolshare/ss/ssconfig.sh restart

ssrestart 是起的名字，随便写
0 3 * * * 每天3:00重启
/koolshare/ss/ssconfig.sh restart   这个是重启

**Comment by zynbasil** [comment]
cru a ssrestart 0 3 * * * /koolshare/ss/ssconfig.sh restart
