### ISSUE TITLE
ShadowsocksR可用，但3.83的科学上网插件不可用的原因

### ISSUE THREAD

**Issue by Totalcall** [koolshare/koolshare.github.io#665]
如题，请教下大家在ShadowsocksR下可正常使用的数个SSR，完全相同的加密方式，协议和混淆，放到AC68U的科学上网插件3.83里就不可用了。
梅林的固件是380.59.X6.6.1，不太清楚是否是固件不支持的原因?Merlin AM380 2.6.36.4内核的固件是指7？

**Comment by Totalcall** [comment]
自问自答吧，固件升级到7.7，ss降级到3.70就正常可以用了。

**Comment by dakezuo** [comment]
你有开kcptun吗，我ssr可以但是一开kcptun就GG了

**Comment by Totalcall** [comment]
@dakezuo 没开，代理比较快，感觉没需要。
