### ISSUE TITLE
开启SS 3.8.3 电脑刚开机能上网，过几分钟上不去

### ISSUE THREAD

**Issue by jwy090815** [koolshare/koolshare.github.io#666]
打开SS电脑刚开机能上网，过几分钟上不去，ping路由器能ping通网站能ping通就是上不去网，同路由器下的NAS也访问不了，但是手机连接WIFI却一切正常，我也不相信和SS有关，但关闭SS后电脑一切恢复了正常，期间重置过路由器，重给电脑装过系统，都没用，也没对SS做过访问控制，希望开发人员能看到并注意一下

**Comment by jwy090815** [comment]
确认是SS的问题，但是奇怪的是，原来能用的3.7.7版本我退回去之后同样会出现关闭SS一切正常，开启SS几分钟后上不去网，而不论是电脑直接和光猫连接还是路由器不开SS和电脑连接用很长时间一点问题都没有

**Comment by hhyhd9000** [comment]
我也是这个样子，你解决了吗

**Comment by jwy090815** [comment]
我还是不知道是什么原因造成的，但是我原来装的是WIN10企业版，我用WIN10专业版重装一遍系统竟然没问题了，但是系统在我出问题前后什么设置都没动过，反而路由器上的SS被我更新到了3.8.3，目前使用没问题，但是原因到底是什么呢

**Comment by hhyhd9000** [comment]
我也是企业版，问题跟你一摸一样，今天回去重制路由器试试

**Comment by jwy090815** [comment]
我也重置过，电脑和路由器都彻底刷过机，只有重装成专业版是有用的，你最好像我一样换成专业版
