### ISSUE TITLE
kcptun未运行

### ISSUE THREAD

**Issue by dakezuo** [koolshare/koolshare.github.io#667]
-----------------------------------------------------------
程序		状态	PID
ssr-redir	工作中	pid：6497
kcptun		未运行
ssr-local	工作中	pid：6474
dns2socks	工作中	pid：6484 6483 6478

ssr已经设置了，国内国外连接也是OK的，但是我明明把kcptun加速勾上了，确显示未运行，而且我也确实没感觉到加速

**Comment by asan2006** [comment]
我也是这样
