### ISSUE TITLE
希望可在github里保存历史各版本的koolshare firmware

### ISSUE THREAD

**Issue by gdillainepub** [koolshare/koolshare.github.io#67]
宝哥、各位开发者,

之前论坛某个帖子，谈及某个6.5的某个模块（不记得是迅雷还是SS），有站友说6.3版本该模块更稳定。我原以为肯定可在koolshare@github找到，结果找了半天也没有。后来发现论坛6.5固件的置顶帖也没了，还是搜索找了好一会。

希望开发小组在koolshare@github 能有一个branch可保存目前所有硬件类型、和历史版本的firmware，并且有关的changelog除了在论坛发布帖、和固件GUI里有以外，在github上也能找到。。还望考虑！谢谢 :)

**Comment by sadoneli** [comment]
这个以前照过人来做，不过他估计也比较忙，所以收集工作一直没人搞
