### ISSUE TITLE
376以後版本取消了延遲啟動導致國外不工作

### ISSUE THREAD

**Issue by kujourin** [koolshare/koolshare.github.io#679]
關於「開機國外不工作，必須點一下保存設置或設置延遲啟動」的問題，出現於359版本以前，後一度修復，從36x版本開始又出現此情況。於是一直以來，都設置了延遲啟動。376以後取消了此選項，導致不能正常啟動。且目前的版本383，首次重啟路由器後，軟體中心線上版本顯示為空，國外不工作，日誌頁面為空白，必須每次手動點擊保存設置。路由環境為88u，7.7，安裝插件為kms和本插件。

**Comment by szhyf** [comment]
68U同样问题，路由器设置了每天定时开关，所以只能退回老版本

**Comment by kujourin** [comment]
3.8.4問題依舊，重啟後國外不工作。還是需要點一下保存設置。
