### ISSUE TITLE
dbconf 可能缺少对用户输入过滤的 bug

### ISSUE THREAD

**Issue by lxyu** [koolshare/koolshare.github.io#68]
碰到一个 bug，导致 http://192.168.19.1/dbconf?p=ss 请求返回的值无法解析。

发生错误的代码段如下:

```js
o['ss_game_dnsmasq']='server=/xxx.com/8.8.8.8
server=/yyy.com/8.8.8.8';
```

如上，这个用户输入的换行符没有被合法过滤，导致 js 解析异常。进一步导致设置页面 UI 错误，全部按钮无法点击。

`dbus remove ss_game_dnsmasq` 之后错误解决。

---

发现的步骤是 chrome 的 console 出现报错

```
Uncaught SyntaxError: Unexpected token ILLEGAL
Uncaught ReferenceError: db_ss is not defined
```

**Comment by sadoneli** [comment]
这里换行是在js里处理过，然后返回给dbus的，不过有时候还是会出问题，暂时没有想到更好的办法

**Comment by lxyu** [comment]
这个问题是升级 1.4.5 引发的。之前一直 work。

可以看一下是否有相应的修改。

**Comment by sadoneli** [comment]
![image](https://cloud.githubusercontent.com/assets/10495520/14778760/5f467b8a-0b07-11e6-97c0-64e762ab167e.png)
你好，我测试了下，游戏模式并没有这个问题，1.4.5的更新，除了ss二进制文件的改动，其它的都和游戏模式无关的，如果可能，还麻烦你测试下ss-libev2.4.5和2.4.6在游戏下的区别

**Comment by lxyu** [comment]
嗯，直接重现也没有重现出来，比较诡异。升级到 1.4.6 也是正常的。以后如果碰到了再来补充。
