### ISSUE TITLE
升级3.8.3之前国内国外都是√，升级3.8.3之后国内√，国外X。此时用其他ss-client测试ss-server无问题。

### ISSUE THREAD

**Issue by y11022053** [koolshare/koolshare.github.io#680]
升级3.8.3之前国内国外都是√，升级3.8.3之后国内√，国外X。此时用其他ss-client测试ss-server无问题。
似乎是merlin里的ss-client-3.8.3有问题？
请问各位有没有遇到？如何解决？
如果要退回版本，具体如何操作，还请高手指点，谢谢！

**Comment by daids** [comment]
一样的问题，最近很频繁的X，而且自己用其他客户端登录没问题，而且加了一个U盘弄虚拟内存

**Comment by y11022053** [comment]
我已经换了一种方式规避这个问题了；
1、重新格式化R8000的，系统管理->系统设置->Format JFFS partition at next boot；
2、重新离线安装3.8.3版本，软件中心->离线安装；
目前稳定且正常，供各位参考。

**Comment by msn1983aa** [comment]
现在稳定性是比较差一点（也有可能是比较耗资源），我是遇到的情况是路由器在跑迅雷下载跑到20M/S或以上的时候SSR+KCP就很容易PD，估计是6300V2性能不行了带不动了

2017-12-21 10:04 GMT+08:00 Daidongsheng <notifications@github.com>:

**Comment by daids** [comment]
@msn1983aa 用楼主 @y11022053 的方法，确实稳定一些，现在google play下载应用会PD，R8000的性能感觉也不行啊

**Comment by liyanszh** [comment]
试过了也不行
