### ISSUE TITLE
ChinaDNS2恩山论坛会解析到国外

### ISSUE THREAD

**Issue by kxjhcmc** [koolshare/koolshare.github.io#686]
www.right.com.cn
会被解析到美国IP，看来chinadns2还不完善，
而使用chinadns1，会发现部分域名无法解析，比如：www.bubulai.com
不知道原因

**Comment by tommyonsn** [comment]
百度都跑国外去了，不知道怎么回事啊

**Comment by lurui45** [comment]
怎么查看是否解析到国外

**Comment by kxjhcmc** [comment]
ping得到IP后，去www.ipip.net查询
