### ISSUE TITLE
3.8.3全走ssr了呢

### ISSUE THREAD

**Issue by tommyonsn** [koolshare/koolshare.github.io#687]
无论上什么网站都是走代理，是不是有bug啦？好像昨天还好好的呢

**Comment by tommyonsn** [comment]
我把国内dns换成百度就好了，以前是阿里。

**Comment by lurui45** [comment]
我也碰到这个问题了，gfwlist和大陆白名单 都不起作用，全走ssr
我国内DNS一般选择运营商，国外选择DNS1，
![image](https://user-images.githubusercontent.com/9017003/34324429-8fb90d8e-e8ad-11e7-8c87-286280e47013.png)
![image](https://user-images.githubusercontent.com/9017003/34324434-b7002e7c-e8ad-11e7-99ca-c3409a029fb2.png)
这个国内dns到底是走我上面选的那个呢，还是走下面那个里面的chinadns

**Comment by lurui45** [comment]
@tommyonsn 我这边换了DNS也没有用啊

**Comment by 0jack-lei0** [comment]
同求，我改了dns还是全局，百度搜索ip显示的国外的。
