### ISSUE TITLE
尽管看到留言那么多,我还是想提一条,关于性能的问题

### ISSUE THREAD

**Issue by DrDoa** [koolshare/koolshare.github.io#689]
请问大佬,我在电脑上跑可以到8mb/s ,但是放路由器只有2m/s, 看了r6400 cpu 只用了单核,而且高峰不到40%,这个是否是程序性能问题. 看能不能优化>?
rc4-md5
origin
plain

**Comment by Daopr** [comment]
可能这种 arm路由器还是不行,要上x86
