### ISSUE TITLE
shadosocks gfwlist  设置自定义hosts 后部分js文件加载失败

### ISSUE THREAD

**Issue by beney** [koolshare/koolshare.github.io#69]
我在路由器上设置了自定义hosts，不知道是不是规则写错了，点提交保存后部分js 加载失败。然后页面显示不完整(其它页面都正常)，自定义 hosts文本框里的内容为空，再点保存也保存不了。  
    so，这里的规则是写到哪里，如果能直接 telnet 到路由器里直接改规则文件就好了，因为我现在只能通过重置来恢复。

**Comment by sadoneli** [comment]
通过dbus list ss,你就能看到异常的值，用dbus remove XXX 删掉那个值就行

**Comment by beney** [comment]
之前用的版本是 5.9的，升到 6.5就好了
