### ISSUE TITLE
请加回 chromecast 设置项

### ISSUE THREAD

**Issue by liwanglin12** [koolshare/koolshare.github.io#691]
这样直接阉掉未免太不友好了，一些特殊的 DNS 设置都失效了

**Comment by benjaminlei2007** [comment]
我提过好几次了，没人响应 ，最后直接在脚本里把那条劫持53端口的iptable命令删了，就好了。

**Comment by liwanglin12** [comment]
@benjaminlei2007 然而怕是每次更新都会加回去。。。

感觉这个操作真是恶心到我了，本来有选项还去掉，下一步是不是可以来 DNS 劫持了，然后再强制把 80 也滤一遍。。。
