### ISSUE TITLE
3.8.4 全走SSR GFWlist和大陆白名单模式没有用

### ISSUE THREAD

**Issue by lurui45** [koolshare/koolshare.github.io#692]
RT，DNS国内国外怎么设置都没有用，全局走SSR，搞不懂了。

**Comment by wee911** [comment]
3.7.8以后一直这样，退回377

**Comment by lurui45** [comment]
@wee911  你也是这样？

**Comment by lurui45** [comment]
@wee911 实测 退到3.7.7 没有用

**Comment by 0jack-lei0** [comment]
同样，现在是3.8.4  走的全局，怎么解决的？

**Comment by lingaoyi** [comment]
我也遇到这个问题，我点击好几次提交才能解决，很多站走了全局代理了。

**Comment by lurui45** [comment]
@lingaoyi  可能过一会儿就又不好了。

**Comment by lurui45** [comment]
有人关注一下吗

**Comment by jiguanglizipao** [comment]
@lurui45 遇到了同样的问题，退回到3.7.7后清空配置，设置好dns后就行了
