### ISSUE TITLE
384問題依舊

### ISSUE THREAD

**Issue by kujourin** [koolshare/koolshare.github.io#695]
#679

**Comment by lukapool** [comment]
在这两个文件里面添加 sleep 代码可以解决
/jffs/scripts/nat-start
/jffs/scripts/wan-start

**Comment by kujourin** [comment]
感謝，不過384關閉和卸載時不會清理scripts文件中的代碼，所以我覺得腳本邏輯還是有問題的，於是全部照搬了360版本的腳本，整合了一下最新的bin文件。用的還行，反正後續那些功能我也用不上。
