### ISSUE TITLE
是否可以解决一下路由器重启后无法自动启动的问题呢？

### ISSUE THREAD

**Issue by yerz** [koolshare/koolshare.github.io#696]
为啥每次路由器断网后 这个插件就会停掉 显示国外无网络连接 需要我手动去重启保存一下才可以？能不能解决一下呢？

**Comment by szhyf** [comment]
可以试一下回退到3.7.8以前版本，在延迟启动里时间稍微设置时间长一点，3.7.8以后版本去掉了延迟启动功能
