### ISSUE TITLE
静态DHCP中文显示乱码

### ISSUE THREAD

**Issue by cjameslynn** [koolshare/koolshare.github.io#7]
在”网络地图“里锁定设备IP，并取中文名字，可以保存和正常显示，在”网络监控家“也可以正常显示。
但是在”手动指定 IP 的 DHCP 列表“里显示为乱码

**Comment by sadoneli** [comment]
这个是因为nvram的问题，虽然能储存中文，但是显示部分是有问题的，所以merlin估计那不支持中文wifi
