### ISSUE TITLE
shadowsocks gfwlist建议增加google.com.sg

### ISSUE THREAD

**Issue by Coolkids** [koolshare/koolshare.github.io#70]
建议增加新加坡的google.
另外gfwlist里面的域名黑名单有编写教程么?是参考配置文件
.google.com.sg/127.0.0.1#7913 
这样写么?

**Comment by sadoneli** [comment]
server行和ipset行都要有的哈，你也可以自己在页面中自己添加域名黑名单，只填写域名就行了
