### ISSUE TITLE
3.8.4版本，使用一键脚本安装到搬瓦工，国外打叉

### ISSUE THREAD

**Issue by hbumen** [koolshare/koolshare.github.io#705]
原来是3.6版本，配合秋水逸冰的一键脚本安装到搬瓦工，可以使用。
现在升级到7.7配合3.8.4，不能科学上网。开始怀疑服务器端版本底，又使用梅林自带的一键脚本教程安装了一遍，还是不行。
另，在网上找的免费账号，填入到3.8.4版本竟然可以用，说明路由器端的软件还是没问题。

整了一天了，求大家帮助。

**Comment by sportfit** [comment]
Since the 7.5 + 3.6.0 version of the use of relatively stable, there is no need to upgrade to an alternative version, as you may know, all the elements after the 3.6 version have changed unless you also have the problem-solving knowledge and ability.

**Comment by zhanghaoipp** [comment]
楼主解决了吗？我得也是升到3.8，ss打叉，我是用搬瓦工自己带的ss server，用ss客户端是可以上的，路由上就不行

**Comment by zhanghaoipp** [comment]
梅林的ss客户端需要额外的端口吗？我发现我的iptables设置导致打叉，清空就好了。但是我的iptables规则（只开80,53,443，ss和ssh端口）不影响pc客户端。

**Comment by hbumen** [comment]
还没解决呢，忙于工作，只能等空闲时间搞一下，哥们你解决了吗？

**Comment by hbumen** [comment]
刚刚试了一下，早上的时候使用PC客户端可以，使用路由器的插件也可以。
但是持续了不到几分钟就都不行了，我现在怀疑是搬瓦工自己的问题。

**Comment by maxhis** [comment]
应该不是ss服务器的原因，我的阿里云香港和Google Cloud的都出现这样的问题，在电脑和手机上很稳定。

而且我这边的情况是刚配置好是没问题的，过一段时间就打叉了，重新设置一下又能正常几个小时，如此反复。。。

**Comment by hbumen** [comment]
是的，七点多我有试了一下，客户端和路由器插件都能用了又。

**Comment by maxhis** [comment]
看起来是DNS污染的原因，我昨晚上把DNS改成chinadns1以后到现在还没出过问题。

![image](https://user-images.githubusercontent.com/1464097/34474231-49a81c02-efb7-11e7-9cf0-5e00ec256ea0.png)

**Comment by yinguo520** [comment]
和楼主装的一个版本，电脑端没有任何问题。
梅林固件怎么都没有设置好，请问是否ssr就不行。

**Comment by everfe** [comment]
我在.vultr.上面搭建的VPS，路由器是华硕的AC68U，固件是改版梅林，也是出现类似的问题，手机和电脑用SS客户端都没有问题，路由器上面无论设置什么模式，国外的都是打叉。

**Comment by bestboylm** [comment]
我也遇到这个问题， 楼上有说有改dns可以成功， 请问下dns我这边默认只显示koolgame内置的那个8.8.8.8:53 ，需要填哪个dns？

**Comment by everfe** [comment]
我用了4.4.4.4也不行。

**Comment by chalau** [comment]
楼上有没有启动KCP？

**Comment by everfe** [comment]
没有。是启动好还是不要启动？

**Comment by chalau** [comment]
谢谢Maxhis：DNS设置里改成chinadns1，解决了经常PD的问题。
致Everfe：KCP启动为好（需设置服务器VPS端），可加速。

**Comment by bestboylm** [comment]
楼上请问下启动KCP具体怎么配置服务端和客户端； 有相关教程链接可以分享一下么？

**Comment by chalau** [comment]
有点难度：对老菜鸟而言😂
https://doub.io/ss-jc36/

**Comment by chalau** [comment]
一开始比较koolshare和老毛子：以为经常性PD是kcp造成的；现在确认是koolshare的DNS问题。
当然：Kcp没设置好，也会PD。

**Comment by MaoCon** [comment]
好像是端口的问题，改回443就可以

**Comment by everfe** [comment]
我的国外DNS选项里面没有chinadns，难道需要另外安装吗？

**Comment by letmeformatyou** [comment]
国外DNS没有chinadns 求解如何安装？

**Comment by guaitai** [comment]
我上次也是这个问题，一直拨号中，后来更新路由版本就可以了
