### ISSUE TITLE
请教ss如何降级？有教程吗？

### ISSUE THREAD

**Issue by zhanghaoipp** [koolshare/koolshare.github.io#707]
升了3.8.4，国外就一直红x，ss PC客户端可用，原来用的3.5，搬瓦工自带的ss sever，怀疑是版本不兼容，查了半天也没找到有降级的教程，哪位大神帮忙指点一下，十分感谢！

**Comment by china-mao** [comment]
卸载后，重新离线安装想安装的版本即可。

**Comment by zhanghaoipp** [comment]
谢谢@china-mao, 我今天又测试了一下，跟版本没关系，是我在vps上设置的iptables的问题，因为前几天被suspended了三次了，都是mass mailing，没办法设置了一下iptables，只开了几个端口，有53,80,443，ss端口和ssh端口，梅林上的ss需要额外的端口吗？客户端倒是能用，您能帮我看一下我的iptables设置吗？还需要开哪些端口？谢谢！
*filter
#  Allow all loopback (lo0) traffic and drop all traffic to 127/8 that doesn't use lo0
-A INPUT  -i lo -j ACCEPT
-A OUTPUT -o lo -j ACCEPT
-A INPUT  -d 127.0.0.0/8 -j REJECT
#  Allow input establish
-A INPUT  -m state --state ESTABLISHED,RELATED -j ACCEPT
-A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
#SS端口
-A INPUT  -p tcp --dport xxxx -m state --state NEW,ESTABLISHED -j ACCEPT
-A OUTPUT -p tcp --dport xxxx -m state --state NEW,ESTABLISHED -j ACCEPT
#  HTTP / HTTPS
-A INPUT  -p tcp -m multiport --dports 80,443 -m state --state NEW,ESTABLISHED -j ACCEPT
-A OUTPUT -p tcp -m multiport --dports 80,443 -m state --state NEW,ESTABLISHED -j ACCEPT
#  SSH端口
-A INPUT  -p tcp --dport xxxx -m state --state NEW,ESTABLISHED -j ACCEPT
#  SSH(this can not be state = NEW, since we only validate the source port)
-A OUTPUT -p tcp --sport xxxx -m state --state ESTABLISHED     -j ACCEPT
#  DNS(not need this rule, as we only accept the input with [ESTABLISHED,RELATED])
#-A INPUT  -p udp --dport 53 -j ACCEPT
#  DNS
-A OUTPUT -p udp --dport 53 -j ACCEPT
#  PING(IN->OUT)
-A OUTPUT -p icmp --icmp-type echo-request -j ACCEPT
-A INPUT  -p icmp --icmp-type echo-reply   -j ACCEPT
#  DDoS
-A INPUT  -p tcp --dport 80 -m limit --limit 25/minute --limit-burst 100 -j ACCEPT
#  Log
-A INPUT  -m limit --limit 5/min -j LOG --log-prefix "iptables denied: " --log-level 7
-A OUTPUT -m limit --limit 5/min -j LOG --log-prefix "iptables denied: " --log-level 7
#  Drop all other inbound - default deny unless explicitly allowed policy
-A INPUT  -j DROP
-A OUTPUT -j DROP
-A FORWARD -j DROP
COMMIT
