### ISSUE TITLE
负载均衡在收到新的订阅以后不会自动更新的问题

### ISSUE THREAD

**Issue by alipapabi** [koolshare/koolshare.github.io#709]
我的订阅链接经常会更新，但是订阅设置每天3点自动更新以后，打开负载均衡的状态下，负载均衡里面的设置没有跟随更新，然后就导致翻墙失败。

时候应该有一个功能就是负载均衡能伴随订阅自动更新，谢谢BOSS~~

**Comment by huangjinbo** [comment]
我也是因为这个问题而取消了负载均衡。
