### ISSUE TITLE
dnsmasq的见逗号就换行规则导致cname语句没法使用

### ISSUE THREAD

**Issue by VersusClyne** [koolshare/koolshare.github.io#71]
dnsmasq有个功能,比如：

cname=itunes.apple.com,itunes.apple.tel.ccgslb.com.cn

可以将itunes.apple.com解析到itunes.apple.tel.ccgslb.com.cn上

但是现在编辑完dnsmasq一保存就逗号自动给我换行了，然后启动失败
so，麻烦改一下dnsmasq的识别规则？

**Comment by sadoneli** [comment]
这个功能是不是需要什么模块支持？
`mjy211@R7000-F2A7:# dnsmasq -v
Dnsmasq version 2.76-g0007ee9  Copyright (c) 2000-2015 Simon Kelley
Compile time options: IPv6 GNU-getopt no-RTC no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset no-auth no-DNSSEC no-loop-detect no-inotify

This software comes with ABSOLUTELY NO WARRANTY.
Dnsmasq is free software, and you are welcome to redistribute it
under the terms of the GNU General Public License, version 2 or 3.`

**Comment by VersusClyne** [comment]
@sadoneli 
http://www.thekelleys.org.uk/dnsmasq/CHANGELOG
看官方changelog的话，是2.46版开始支持的

Add --cname option. This provides a limited alias function, usable for DHCP names. Thanks to AJ Weber for suggestions on this.

**Comment by sadoneli** [comment]
嗯，那应该是支持的，不过因为ss的web里的js会自动气短逗号，所以建议你手工添加

**Comment by VersusClyne** [comment]
@sadoneli 
http://www.thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html
官方说明书－ －要用到逗号的地方挺多的呀呀呀－，－

**Comment by VersusClyne** [comment]
@sadoneli 请问是不是在configs/dnsmasq.d/ 下新建个*.conf就可以自动加载了么？

**Comment by sadoneli** [comment]
是的哈，旧版固件得gfwlist模式才能加载，新版固（大于等于X6.5.1）件开不开ss都能加载

2016-05-01 10:15 GMT+08:00 VersusClyne <notifications@github.com>:
