### ISSUE TITLE
更新后GOOGLE PLAY商店无法获取索引信息

### ISSUE THREAD

**Issue by youngchengcn** [koolshare/koolshare.github.io#714]
如题，GOOGLE PLAY商店无法获取索引信息（从服务器检索信息时出错。【DF-FDERH-01】），该问题在3.8以前的版本一直存在，在3.8.0-3.8.2的版本中，该问题消失。
但更新3.8.3之后，问题又存在了，即使是使用全局模式也仍然存在该问题。
请问能否解决？

**Comment by RyRonHeo** [comment]
更换非HK节点再试试，我叫雷锋

**Comment by youngchengcn** [comment]
手里有jp和hk两个服务器，都是一样的。
每次更新app我都得在手机上使用客户端，获取到索引后，点击更新，然后关闭客户端，使用wifi可正常下载更新= =

**Comment by jjandnn** [comment]
和383、节点都没关系。
请在路由器里设置一条规则：services.googleapis.cn强制走代理。
然后google卸载更新，清理缓存。
再上。
