### ISSUE TITLE
只要我在黑白名单里添加黑名单，就是变成全局走ss

### ISSUE THREAD

**Issue by 0jack-lei0** [koolshare/koolshare.github.io#717]
只要我在黑白名单里添加黑名单，就是变成全局走ss，原本我一直以为是版本的问题，今天突然发现这个问题，如果我再黑名单里加入强制走ss的域名和ip，之后就会变成全局都走SS，把黑名单清空之后，就好了，不知道有没有一样问题的。

**Comment by lurui45** [comment]
大兄弟，谢谢你哦，我说我怎么一开就是全局，原来我黑名单里面有域名。。删掉就好了，这个bug以前好像没有
