### ISSUE TITLE
路由器重启后或者ss服务器重启后  我的ssr就不能连接国外了

### ISSUE THREAD

**Issue by lei551** [koolshare/koolshare.github.io#718]
我的路由器重启后或者ss服务器重启后  我的ssr插件就不能使用了 必须关下开关重新打开才能打开国外网站 好烦躁啊，我每天打开路由器后台手动解决。求大佬解决

**Comment by angryleilei** [comment]
试着格式化一下jffs分区重装插件，如果还不行就重置路由器
