### ISSUE TITLE
路由器重启以后SS线路不通

### ISSUE THREAD

**Issue by alipapabi** [koolshare/koolshare.github.io#722]
我设置了路由器每天早晨自动重启，结果每次重启路由器以后线路就不通了，必须要我重新选择一条新的线路然后保存&应用一遍以后才会重新可以正常使用，求修复~~~我的路由器是华硕AC87R

**Comment by wdl214311131** [comment]
我的也有这个问题，估计是普遍问题，相当于是路由器关机了，然后科学上网没有正常关机，所以重新连接就连接不上了

**Comment by alipapabi** [comment]
希望开发者可以解决一下~~~~路由器不重启链接速度经常会慢下去，所以只好让它每天都重启，但是每次重启都得重新设置SSR
