### ISSUE TITLE
我在刚买的阿里云日本线路上搭建的koolgmae账号无法使用

### ISSUE THREAD

**Issue by miku6600** [koolshare/koolshare.github.io#723]
我在刚买的阿里云日本线路上搭建的koolgmae账号无法使用，严格按照一键安装来执行的，安装也都成功了，但是在路由器上一直是国外PD无法使用。有没有大佬可以为我解答下。

**Comment by Se7enMuting** [comment]
试下换成udp in tcp 模式，还有建议用香港CN2服务器~~
