### ISSUE TITLE
上网速度慢

### ISSUE THREAD

**Issue by wdl214311131** [koolshare/koolshare.github.io#724]
硬件是：AC1900P
梅林是：7.7版本
科学上网是：3.8.4版本
宽带是：电信200M光纤
遇到的问题是，反复使用多个节点测试梅林软件中心的科学上网，下载速度最高基本稳定在2mB/s，CPU和内存占用都还好。但是我关闭梅林软件中心的科学上网之后，直接用电脑测试节点，很多能达到8mB/s。我就想问问，是设置不对，还是梅林中的科学上网现在普遍存在这个问题？并且有解决方案没有？
谢谢！
--

**Comment by wdl214311131** [comment]
找到问题了，原来是在DNS设置页面，设置成chinadns1即可，CPU占用下降到几乎可以不计，同时速度和电脑直接上基本一致！！！
给有同样问题的朋友提供一个思路！！！

**Comment by david4423** [comment]
ea6200同样的问题，电脑手机能跑满100M,路由却只能跑20mbps左右
