### ISSUE TITLE
路由器定时重启 就无法上了.

### ISSUE THREAD

**Issue by tvrcfdfe** [koolshare/koolshare.github.io#728]
可以做个定时重启的功能,
或者解决路由器定时重启,该插件也能拨号上去

**Comment by alipapabi** [comment]
我也遇到同样的问题，其实可以做一个这样的机制，在几点几分SSR重新自动连接一次。因为我每次路由器自动重启完成以后，关闭一下SSR，再重新打开连一下就能上去了。

**Comment by LYJSPEEDX** [comment]
我也遇到同样的问题，有时候重启后，国外莫名X，手动关闭重启后恢复正常？
貌似是新版本出现的问题

**Comment by chiangdm** [comment]
我也遇到一模一样的问题，电信每隔48小时强制重新连接后SS插件的国外连接就断开了，要手工将SS关闭再打开才可以正常功能，梅林固件7.7，SS版本3.8.4，以前是没有这个问题的。。

**Comment by JasonChanJJ** [comment]
遇到同样问题,建议插件增加一个定时重启的功能
