### ISSUE TITLE
为什么没有设置捐助？

### ISSUE THREAD

**Issue by shellus** [koolshare/koolshare.github.io#73]

**Comment by jannson** [comment]
谢谢，主要是不想泄漏个人信息。我们想想怎么操作好一些。

**Comment by shellus** [comment]
使用paypal应该可以不被官方轻易查到真实身份

**Comment by jannson** [comment]
是的，目前就是这个考虑。不过我身份肯定是泄漏了，就是不想太多人知道而已。

**Comment by jannson** [comment]
加了个微信的非个人账户。paypal 本身我有，但是以后再加 paypal 吧。
