### ISSUE TITLE
电信moden重启以后，SSR访问国外就连不上了

### ISSUE THREAD

**Issue by alipapabi** [koolshare/koolshare.github.io#731]
家里电信光猫因为设置了每天重启（拨号是路由器负责，光猫重启路由器再拨号就更换一个IP），每天电信猫重启以后SSR连接就连不进去了，需要手动关闭SSR服务，再打开然后就好了。
我试过电信猫先重启，路由器后重启，重启以后还是访问失败，必须手动关闭一次SSR,然后在重新打开，才可以。

所以想问问有什么办法可以设置定时重启SSR服务。
另外重启路由器为啥SSR还是连接失败，难道路由器重启不能重启SSR,百思不得其姐～～

**Comment by chiangdm** [comment]
我也遇到一模一样的问题。。
