### ISSUE TITLE
Merlin X7.7 Shadowsocks 无法正常工作

### ISSUE THREAD

**Issue by hy3301** [koolshare/koolshare.github.io#738]
我有两个路由器，Netgear R7000和Asus AC88U，都刷了最新版KoolShare改版Merlin固件。都安装了最新版软件中心，用离线安装安装了最新版（3.8.4）Shadowsocks，安装文件是从Koolshare Github上下载的。
我买的是Rixcloud，用他网站提供的服务器列表配置回复文件设置了节点信息。第一次在R7000上设置完完美，YouTube 4K都没有压力。三天之后开始出现问题，国内网无法连接，只能连接国外。再过了一个晚上，从第四天起，就不管国内国外都无法连接了。在AC88U上用同样方法设置了一遍，问题依旧，完全无法连接。已经试过了旧版Shadowsocks安装文件，依旧。Rixcloud的节点用Windows, Android 客户端连接完全没有问题。
这里不能贴截图，问题就是国内国外连接两个状态都是叉叉。
希望又开发组大神能解答一下，感激不尽！

**Comment by jack6liu** [comment]
我的R7000上用3.7.7没问题，升级到之后的版本就有问题。貌似是DNS的问题，你可以试试离线安装3.7.7的版本试试。

**Comment by cserlzy** [comment]
我也是！

**Comment by cserlzy** [comment]
你解决了吗 兄弟 我是ac88u

**Comment by hy3301** [comment]
悲催没有啊，试了3.7.7版Shadowsocks ，没用。准备试试X7.7之前的版本了。实在不行只好研究Entware 了，路由器弄翻墙还是新手

**Comment by hy3301** [comment]
悲催没有啊，试了3.7.7版Shadowsocks ，没用。准备试试X7.7之前的版本了。实在不行只好研究Entware 了，路由器弄翻墙还是新手

**Comment by hy3301** [comment]
悲催没有啊，试了3.7.7版Shadowsocks ，没用。准备试试X7.7之前的版本了。实在不行只好研究Entware 了，路由器弄翻墙还是新手

**Comment by hy3301** [comment]
悲催没有啊，试了3.7.7版Shadowsocks ，没用。准备试试X7.7之前的版本了。实在不行只好研究Entware 了，路由器弄翻墙还是新手

**Comment by hy3301** [comment]
悲催没有啊，试了3.7.7版Shadowsocks ，没用。准备试试X7.7之前的版本了。实在不行只好研究Entware 了，路由器弄翻墙还是新手

**Comment by hy3301** [comment]
悲催没有啊，试了3.7.7版Shadowsocks ，没用。准备试试X7.7之前的版本了。实在不行只好研究Entware 了，路由器弄翻墙还是新手

**Comment by hy3301** [comment]
悲催没有啊，试了3.7.7版Shadowsocks ，没用。准备试试X7.7之前的版本了。实在不行只好研究Entware 了，路由器弄翻墙还是新手

**Comment by hy3301** [comment]
悲催没有啊，试了3.7.7版Shadowsocks ，没用。准备试试X7.7之前的版本了。实在不行只好研究Entware 了，路由器弄翻墙还是新手

**Comment by zhoutao428** [comment]
我也有这样类似情况 国外经常连不上，时断时续，谁有配置方案吗 。

**Comment by jjandnn** [comment]
Firmware:380.68_4-X7.7，
[shadowsocks.tar.gz](https://github.com/koolshare/koolshare.github.io/files/1671969/shadowsocks.tar.gz)，
离线安装，升级到1.3.5，
![default](https://user-images.githubusercontent.com/33235405/35491187-d0f7a690-04df-11e8-8ab4-d815cd9a2a6d.png)
![1](https://user-images.githubusercontent.com/33235405/35491191-d4e8b8ca-04df-11e8-9cc9-c452d8d07601.png)
不要在路由内开kcp，
vps端bbr。
路由端关闭负载均衡。
要负载均衡，直接在pc或mac上开。

**Comment by hy3301** [comment]
我发现我的问题是路由器时间无法更新造成的。运营商给的调制解调器是附带路由器的，我的路由器只能接成二级路由。不知是否是这个关系，路由器无法更新时间，时间一直是两年前。现在用telnet命令强制更新了时间，目前使用正常。
命令: ntpclient -h time.windows.com -i 3 -l -s
