### ISSUE TITLE
自建局域网内部dns在开启科学上网后无法解析内部dns

### ISSUE THREAD

**Issue by s524797336** [koolshare/koolshare.github.io#742]
无论是否开启科学上网都能ping通内部dns服务器
开启科学上网后无法解析内部dns，关闭后可正常解析

**Comment by s524797336** [comment]
我修改了dnsmasq.conf的生成文件，将no-resolv和no-poll干掉以后就好了，没用过dnsmasq不确定会有什么副作用，目前我用着是没什么问题，能否应用此修复发布个新版本？

**Comment by xlighting2017** [comment]
自己在 /jffs/configs/dnsmasq.d/   下面加一个 .conf 文件， 里面 将你的内部域，比如    .abc  指向内部dns  服务器就行， 比如  
server=/neibu/192.168.x.x,    这样所有的    
a.neibu   b.neibu  c.def.neibu  都会去找  192.168.x.x

**Comment by s524797336** [comment]
@xlighting2017 如果我内部域特别多是不是得加很多啊，如果我那种方法没啥副作用的话不打算改了，毕竟管理内部dns还得管理路由器的配置改两次特别不爽，不过谢谢你这个方法不用改源码里的文件也挺好

**Comment by xlighting2017** [comment]
内部域 还有多个 顶级域？ 难道不是 都在一个顶级域的下面么。。。。。
一劳永逸 V.S. 每次 切换模式/开关 都可能被改回去， 自己选择吧
