### ISSUE TITLE
不知道几时开始，SS节点断掉的话，国内也就也掉了

### ISSUE THREAD

**Issue by Devenge7** [koolshare/koolshare.github.io#743]
以前国外显示Problem detected!的话国内也可以继续使用

现在国内显示working，国内也不可以上了，除非国外节点再次可用

请问如何解决？

**Comment by Devenge7** [comment]
没有人吗

**Comment by sky300** [comment]
我也遇到这个问题，有时候连WIFI都连不上。找了半天发现是SS的问题。而且换到大陆白名单以后会好。

**Comment by Devenge7** [comment]
又多了一个问题，白名单无效，偶尔还是会把不需要加速的外网给走代理。

**Comment by he1226** [comment]
我也是这个问题，就这几天，你们怎么解决的？

**Comment by Devenge7** [comment]
我干脆不用插件直接开软件了……有点受不了

**Comment by he1226** [comment]
我用软件也不行，服务器都连接不上

**Comment by Devenge7** [comment]
还不如不更新呢，3.6以前没出过这么多问题

**Comment by toloy** [comment]
gfw 模式下看下 /etc/dnsmasq.conf 里server=后面是什么，如果是127.0.0.1#xx的话 dns 解析会走国外dns的

**Comment by Devenge7** [comment]
/koolshare/scripts/ss_update.sh: export: line 1: ssconf_basic_ping_原版图像: bad variable name

**Comment by toloy** [comment]
https://github.com/koolshare/koolshare.github.io/pull/769 .
即可解决
