### ISSUE TITLE
请问现行版本3.8.4有办法实现 全局模式+udp 转发吗？

### ISSUE THREAD

**Issue by Se7enMuting** [koolshare/koolshare.github.io#746]
游戏模式只是大陆白名单+udp转发
而全局代理模式又不转发udp
我现在需求是全局代理+全局udp转发，请问有办法实现吗？比如进scp改点东西，或者SSH打点命令之类的。

**Comment by Se7enMuting** [comment]
自己瞎改了下，貌似能用，哈哈，小白乱改不供参考，想让 全局 变成 全局tcp+udp，但不确定这个upd是否全局，不知道国内方向的udp怎么测试......
[](https://github.com/Se7enMuting/blog/commit/cfb0eb4d915ac55a972f2cb2684c04677635eede)
就是不知道下面这条算不算建立了全局的upd链路，TPROXY完全不懂.....
`iptables -t mangle -A SHADOWSOCKS_GLO -p udp -j TPROXY --on-port 3333 --tproxy-mark 0x07`

**Comment by elric8** [comment]
@Se7enMuting 
兄弟，你的方法可行
但是很容易出错
不知道兄弟有没有相同的问题

**Comment by sadoneli** [comment]
不行的，还需要改其它地方
全局udp很容易出问题，因此完全不建议这么做，插件也是为了避免问题没做类似开关

**Comment by elric8** [comment]
@sadoneli
那有没有办法提供一个端口，让主机通过这个端口走tcp和udp
主机游戏都是p2p连接，游戏模式连不到国内的人很苦恼，貌似因为国内的ip就不走ss，但是服务器识别我是ss的ip导致无法连接
