### ISSUE TITLE
刚刚捐助了¥100，要跟谁讲？

### ISSUE THREAD

**Issue by realmx** [koolshare/koolshare.github.io#75]
名字：Realm
不知道这样能不能查得到。。。

![1](https://cloud.githubusercontent.com/assets/6071313/15091701/7ae03acc-1483-11e6-8f40-673bf4dfd95d.jpg)
![2](https://cloud.githubusercontent.com/assets/6071313/15091703/80e2b94a-1483-11e6-8b6c-4cd617e8d5be.jpg)
![3](https://cloud.githubusercontent.com/assets/6071313/15091704/84130dae-1483-11e6-8ee9-75bbb67cd8ae.jpg)

**Comment by sadoneli** [comment]
你好，多些支持，我们后台能看到并追溯

**Comment by sadoneli** [comment]
已经添加贡献名单，再次感谢支持！
