### ISSUE TITLE
华硕梅林固件 有办法让路由器自动执行开关科学上网开关 功能吗

### ISSUE THREAD

**Issue by alipapabi** [koolshare/koolshare.github.io#751]
有没有办法通过定时任务之类的设置让路由器执行关闭科学上网开关，打开科学上网开关的功能。
因为现在遇到的问题是每天电信猫早晨更换IP地址以后，科学上网就完全没法用了，即便是我重启路由器也不行。
唯一解决方式就是我关闭科学上网开关以后再打开，网络就正常了。
所以向大神求教，有没有路由器script命令可以设置好每天路由器在电信更换ip前前先关闭科学上网功能，等IP更换好以后再重新打开。。。

**Comment by alipapabi** [comment]
tmp/syslog.log日志有很多这样的内容：

Jan 25 22:35:10 rss-local[8344]: getsockopt: Operation now in progress
Jan 25 22:35:10 rss-local[8344]: getsockopt error code 0 111
Jan 25 22:35:10 rss-local[8344]: getsockopt: Operation now in progress
Jan 25 22:35:10 rss-local[8344]: getsockopt error code 0 111
Jan 25 22:35:10 rss-local[8344]: getsockopt: Operation now in progress
Jan 25 22:35:11 rss-local[8344]: getsockopt error code 0 111
Jan 25 22:35:11 rss-local[8344]: getsockopt: Operation now in progress
Jan 25 22:35:12 rss-local[8344]: getsockopt error code 0 111
Jan 25 22:35:12 rss-local[8344]: getsockopt: Operation now in progress
Jan 25 22:35:13 rss-local[8344]: getsockopt error code 0 111
Jan 25 22:35:13 rss-local[8344]: getsockopt: Operation now in progress

**Comment by alipapabi** [comment]
虽然不是很理解，不过研究了一晚上把路由器WAN-START和NAT-START文件修改了一下能解决路由器重启以后没办法SS的问题，方案如下：

wan-start
#!/bin/sh
dbus fire onwanstart
/usr/bin/plugin.sh start
sh /koolshare/ss/ssconfig.sh stop
sleep 60s
sh /koolshare/scripts/ss_config.sh

nat-start
#!/bin/sh
dbus fire onnatstart
sh /koolshare/ss/ssconfig.sh stop
sleep 60s
sh /koolshare/ss/ssconfig.sh

大概原理就是启动时候先运行一次关闭ss服务，保证路由器能正常上网链接上NTP服务之类的，然后过60秒再重新启动SS服务。

**Comment by cngzsunny** [comment]
我改成sleep 10好像 也可以了

**Comment by Mattosx** [comment]
现在解决了吗? 同遇到这个问题, 最好的解决方案 还是在pppoe拨号的时候 自动把ss 重启

**Comment by 2huYa0** [comment]
同样遇到此问题，按 @alipapabi 的方案修改路由器WAN-START和NAT-START文件也无法解决，请问各位还有其他的解决方案吗？
