### ISSUE TITLE
设置完毕后一直显示Waiting

### ISSUE THREAD

**Issue by zzy659781** [koolshare/koolshare.github.io#754]
填写完SSR的相关信息后国外连接和国内连接都一直显示Waiting无法科学上网，同样的设置在电脑和手机上就没问题

**Comment by FFllFF** [comment]
和你遇到同样的问题，感觉是SS插件的事情，我开始装的3.8.4，后面是3.7几，也不行。。最后换成个3.6几的就可以了。。。现在能用了。。所以不行的话你试试换个老版本的插件？
