### ISSUE TITLE
各位大神,小白求指点,路由器SS问题

### ISSUE THREAD

**Issue by jdlovefg** [koolshare/koolshare.github.io#756]
路由器R6900 7.4固件 上周更新完SS插件到3.8.4后,出现如下问题:
启动以后插件内显示国内外连接都是打钩,但实际上不行,换任何一条线路都是如此,感觉上就是路由器能翻墙,但是电脑OR手机上就是不行.
对此毫无头绪...蒙头乱搞了几天,很惭愧.还是一点都不懂.
之前路由器一直常驻的SS 被我一个更新全部毁了..
请各位大神指点一下...小弟感激不尽..

**Comment by yahuudang** [comment]
7.4+3.8.4版本确实问题多，我这边是R7000经常Wan闪断十几秒，但是拨号地址又没变。
ss是每天晚上就会断开，重新应用就可以用了。

**Comment by jjandnn** [comment]
楼上的问题，和你的7000,7.7，384没关系，请电话10000号，报故障，让他们调整，报号前，把光猫的后面的所有设备记录全部记在小本上。一次解决。若果对方爱理不理，约他来上门，呵呵，他不会来。因为他知道是咋回事儿。7000+7.7是最稳定的，没有之一。

**Comment by jjandnn** [comment]
另，你得告诉他一个真相，就是你经常连着线，开udp玩游戏。
