### ISSUE TITLE
关于使用科学上网插件正确填写参数后的连接问题

### ISSUE THREAD

**Issue by ChaoYihu** [koolshare/koolshare.github.io#757]
在填写完参数之后(Gfwlist模式),上面双勾显示国外连接正常,但是访问Google的时候,Chrome提示我"您的连接不是私密连接",在Windows端使用SS的GUI客户端一切正常.这是为什么呢?

**Comment by jjandnn** [comment]
这是http未跳转https，和你的路由没关系。和浏览器有关系。如果是手机端，直接在私密这个页面打开不安全链接，强制刷新。开启pc模式，不要用手机模式。如果是pc端，选择地址栏前面的小圈，定义为安全。或自己搜索强制https字样，一堆操作指南。当然，还有就是彻底还原浏览器默认设置。

**Comment by jjandnn** [comment]
前面给你的留言容易误导，我删了。出这个状况，一般和路由器的设置模式无关。你自己上网查中间人攻击及解决办法。

**Comment by ChaoYihu** [comment]
@jjandnn我可以确定不是中间人攻击，因为证书是没有问题的，另外是我自己搭建的VPS，SS连接没有问题。在Android端和Windows端的SS客户端连接都没有问题

**Comment by jjandnn** [comment]
呵呵，我说一下，iphone，我当时问题是在iphone上，其他所有设备均没有发生。我解决的办法是，关闭了该网页的手机模式，改为桌面模式，无论是safari还是chrome。这个就是我先前删掉的答案。

**Comment by jjandnn** [comment]
你的情况是浏览还在pc端？只要不直接在设备上开启ss，用路由器就会发生这个情况，是吗？

**Comment by ChaoYihu** [comment]
@jjandnn我是在路由器科学上网插件上填写完SS信息之后，打开科学上网开关，显示国内连接和国外连接都是√。但是一上Google之类在墙外的网站就会提示“您的连接不是私密连接”。在PC  Chrome浏览器上。

**Comment by jjandnn** [comment]
你的路由器神器里的dns国内是自动，国外是dhs2socks 8888:53，是吗？然后浏览器上证书是由谷歌的G3发的，发给google.com.hk？

**Comment by jjandnn** [comment]
昨晚，google要求浏览器强制更新，右上角出现小箭头，你更了没？

**Comment by jjandnn** [comment]
除火绒外，其余国内防火墙你肯定都关闭了？

**Comment by jjandnn** [comment]
![2](https://user-images.githubusercontent.com/33235405/35493182-70e6fab4-04ec-11e8-9c15-b19529b2fc3e.png)
这部分一样吗？

**Comment by ChaoYihu** [comment]
@jjandnn 
刚重新看了一下,证书无效,颁发者koolproxy.com  颁发给*.google.com

**Comment by ChaoYihu** [comment]
@jjandnn 
我使用Windows的SS客户端,证书没有问题.

**Comment by ChaoYihu** [comment]
@jjandnn 
路由器的时间同步也没有问题

**Comment by ChaoYihu** [comment]
@jjandnn 
我已经搞定了!就是证书的问题,不过是koolproxy.com证书安装的存储区选错了,应该安装在受信任的根证书颁发机构存储区.
问题解决,非常感谢!

**Comment by jjandnn** [comment]
对，你把k大的证搞没了。http://koolshare.cn/thread-79889-1-1.html，我放个链接，以防别的兄弟遇到问题，重复发生。：）

**Comment by jjandnn** [comment]
koolshare是个平台，就像手机上iTools、兔兔一样，所有与它关联的插件安装都得有它认证，才能有作用于终端，终端必须许可这个总的平台，平台下的应用才能安全使用。祝好！
