### ISSUE TITLE
3.8.4无法正常工作了。

### ISSUE THREAD

**Issue by mojieitanshi** [koolshare/koolshare.github.io#759]
今天突然外网访问失败，服务器并没有问题，我用ssr客服端测试可用，今天突然3.8.4就故障了。

**Comment by lukapool** [comment]
是重启后失效吗

**Comment by jjandnn** [comment]
和3.8.4没关系，只和个人设置、浏览器、安全证书过期、dns解析有关。

**Comment by mojieitanshi** [comment]
是重启以后失效的。

2018-01-30 12:58 GMT+08:00 Toly <notifications@github.com>:

**Comment by lukapool** [comment]
我也遇到重启后外国地址无法获取的情况，需要手动点一次保存&应用才能使用。如果是我这种情况，可以解决。

**Comment by mojieitanshi** [comment]
一样的问题，我下次试试。

2018-01-30 17:11 GMT+08:00 Luka <notifications@github.com>:

**Comment by lukapool** [comment]
# ssh 登录你的路由器
# 修改 
** /jffs/scripts/wan-start**
```
#!/bin/sh
dbus fire onwanstart
sleep 60 
sh /koolshare/scripts/ss_config.sh
/usr/bin/plugin.sh start
```
**sh /koolshare/ss/ss_config.sh 前添加 sleep 60**
# 修改 
** /jffs/scripts/nat-start**
```
#!/bin/sh
dbus fire onnatstart
sleep 60
sh /koolshare/ss/ssconfig.sh
```
**sh /koolshare/ss/ssconfig.sh 前添加 sleep 60**

## 目前我设置了等待60秒，重启测试了几次都没出现这问题了。

**Comment by mojieitanshi** [comment]
谢谢

2018-01-30 17:21 GMT+08:00 Luka <notifications@github.com>:

**Comment by szm123321** [comment]
@lukapool 按照你的设置来还是不行，重启后还是连接不上求解

**Comment by lukapool** [comment]
@szm123321 把时间调久一点 120？

**Comment by szm123321** [comment]
@lukapool 老铁，刚试过了，还是不行(┬＿┬)

**Comment by lukapool** [comment]
@szm123321 老哥，先确认账号能用先，然后确认重启后是不是国外IP显示X，点击保存并应用后又正常使用。如果是这种情况，我设置了120秒，要等待5min才完全启动所有插件，要不你在这5min钟期间先别打开路由器管理界面或上要翻墙的网站。或者你安装那个ServerChan微信推送插件来提醒你路由器什么时候等待完那120秒并成功运行所有已装插件。

**Comment by paceyuan** [comment]
@lukapool 兄弟加了sleep 60以后，用vi的:wq命令保存，但是随后重启路由以后就没了，貌似没保存下来，是我的保存方式有问题吗？求指导，拜谢！
