### ISSUE TITLE
希望固件越来越好

### ISSUE THREAD

**Issue by WangYue7477** [koolshare/koolshare.github.io#76]
![520629906193279858](https://cloud.githubusercontent.com/assets/1797810/15096450/950b8e0e-152a-11e6-82c8-1f250d997095.jpg)

使用梅林固件好长时间了，解决了家里所有设备科学上网问题。希望我这微不足道的捐赠能帮上忙！

**Comment by jannson** [comment]
谢谢，我会尽快加上你的ID。感谢支持！！！

**Comment by jannson** [comment]
捐献已经可以自动生成名单： http://c.koolshare.io
如果想修改名字情告知。
