### ISSUE TITLE
开发组大大们可有发布V2Ray插件的打算？

### ISSUE THREAD

**Issue by sagexy** [koolshare/koolshare.github.io#760]
2018/01/24日当天大规模ip被办，从此$$/$$R变得不再安全，目前也就V2Ray还算靠谱一点，从论坛中搜索到2016年那会就有V2Ray的demo了，现在到了上插件的时间了么？

**Comment by Nehalem-Lf** [comment]
同希望尽快推出v2ray插件

**Comment by sadoneli** [comment]
没有
