### ISSUE TITLE
身处国外【回国模式】遇到许多问题，恳请开发者答疑解惑

### ISSUE THREAD

**Issue by gujia9999** [koolshare/koolshare.github.io#766]
我连回国内目的是：
1、国内外家中两台NAS同步文件的时候能快点，因gfw的存在，使同步奇慢无比，通常只有几十 KB/s，通过在国内家中的NAS上搭建一个 SSR+KCP私服，经测试速度提高到1 MB/s左右的水平，令人满意。

2、其次国外很多国内的音乐，电影版权受限，连回国才能解决。

使用插件时遇到的问题总结：

1、首先我想了解一下这个【回国模式】的机制，是不是取决于<chnroute.txt>或是< cdn.txt>中的国内域名或者IP？我仔细看了一下，我国内家里IP落在chnroute.txt名单中，是不是意味着当我需要访问国内家中的NAS时也走ss?  或者因为不在cdn.txt名单中而被【回国模式】自动bypass? 如果是被bypass了我就很无语了，因为这正是我建这个服的目的。。。

2、【回国模式】貌似存在很严重的问题，打开【回国模式】就上不了google, facebook等被墙网站。
貌似这些被墙网站走的是国内??    或者DNS走国内错误解析了google, facebook?? 

3、【回国模式】下的DNS设定栏里，{国内DNS} 与 {国外DNS} 的逻辑是不是跟其他模式的相反？也就是说此时的国内指的是国外？而国外是国内的意思？

4、【全局代理模式】看似是一劳永逸的方法，可是也存在小BUG，经测试在android Shadowsocks客户端下，我能顺利远程访问smb://192.168.2.xx（就是在国外，通过SMB协议访问国内家中NAS里的文件）, 但是【全局代理模式】却不行。我估计是DNS设定里面的问题，192.168.2.xx的请求询问了本地而不是远程（或者SMB被ss插件阉掉了？？）。
    希望开发者能在DNS设定栏里添加一个类似【内网开关】，或者/以及 添加一个能让所有DNS请求，不论国内、国外全部走SS。毕竟SS本质上也是VPN，VPN就是要访问远程资源的对不对。

5、【gfwlist模式】是怎么运作的呢？我把gfwlist.conf清空，只添加了一个百度，原本以为这样就可以自定义翻墙网站，可却发现虽然百度确实是走的国内，但是此时google, youtube等一众网站也上不去了。。。很无语。
    希望开发者能够添加一个【自定义模式】，在此模式下用户可以自己添加需要走ss的域名与IP，比如对我而言，我只需要添加我国内的IP以及域名，这样就能实现NAS文件快速同步且不会造成不必要的拥堵！

**Comment by gujia9999** [comment]
就【内网访问】的问题，我最近和几个IOS SSR客户端开发者探讨了一下，他们表示这确实是一个问题，并且计划在下一个版本中添加【内网排除开关】来解决问题！

希望下一版本SS插件也能改进一下

**Comment by gujia9999** [comment]
仔细看了一下代码，192.168.0.0/16被排除了，难怪访问不了内网。。改成192.168.x.0/8就搞定内网访问了

**Comment by ArtixZ** [comment]
为什么没回复直接close了啊
