### ISSUE TITLE
聊表心意

### ISSUE THREAD

**Issue by zhengyu13** [koolshare/koolshare.github.io#77]
固件更新需要开发者投入大量的心血与精力，捐赠也只是聊表心意。
期待ss和x1游戏部分的完善，也祝愿开发者们诸事顺利。

**Comment by jannson** [comment]
谢谢，我会尽快加上你的ID。感谢支持！！！

游戏请多试用我的游戏模式V2，有问题及时向我反馈。

**Comment by jannson** [comment]
捐献已经可以自动生成名单： http://c.koolshare.io
如果想修改名字情告知。
