### ISSUE TITLE
版本3.8.4，运行久了会断开，然后只能开关科学上网才能上去

### ISSUE THREAD

**Issue by etimes2008** [koolshare/koolshare.github.io#770]
版本3.8.4，运行久了会断开，然后只能开关科学上网才能上去

**Comment by deanwong** [comment]
同上，如果无法定位问题，是否可以增加定时重启功能

**Comment by blowaway** [comment]
同样也遇到这一问题，显示可以上，但实际不行，需要重新提交一下设定才可以，希望尽快可以解决，非常感谢！

**Comment by toloy** [comment]
gfwlist 模式吗？

**Comment by blowaway** [comment]
是的，gfwlist模式，当前版本：3.8.4  之前好早的版本的没遇到这个问题，很久没更新，刚刚升级了最新版

**Comment by jyogyou** [comment]
我发现3.8.4这个版本有个问题，就是长时间不走国外流量的时候国外就会PD掉，一定要重启插件，就是点下 保存&应用 才能够正常连接，我一直在下如果插件里面加一个像KOOLPROXY那种定时重启一下，是不是就能够解决这个问题，希望大神采纳下意见。

**Comment by wangwei8828** [comment]
我的也是。长时间不用会pd。需要重启插件才行

**Comment by jkyeo** [comment]
同样的问题，gfwlist 模式

**Comment by jkyeo** [comment]
@toloy 添加var 问题依然没有解决

**Comment by jyogyou** [comment]
我也是gfwlist模式和游戏模式都是同一个情况，只要长时间不走国外流量，国外显示OK，其实是PD的，重新提交后又正常。

**Comment by toloy** [comment]
我这里没有问题，国外dns使用的chinadns，连着开几天了国内国外都很快
看下 /etc/dnsmasq.conf 里 server= 后面跟的是国内dns还是127.0.0.1#

**Comment by deanwong** [comment]
@toloy /etc/dnsmasq.conf 里面 server=127.0.0.1#7913

**Comment by icewind7030** [comment]
同样遇到这个问题了，请问有办法解决吗

**Comment by paceyuan** [comment]
回退了之前稳定的373貌似也有类似问题

**Comment by youngchengcn** [comment]
看来不是我一个人的问题- -并且之前都是正常的，就最近出现了问题。版本3.8.4

**Comment by nullllunA** [comment]
我也有这个问题。。。我还把威皮恩supplier给骂了一顿。。

**Comment by youngchengcn** [comment]
经过测试，将科学上网插件重置后可解决问题。目前24小时未复发，看后续情况= =

**Comment by liubangjain** [comment]
我是用中国电信，是公网ip，路由器有安装ServerChan，绑定了手机微信，可以推送路由器状态信息，经过观察发现一个规律，只要微信收到ServerChan发来收到网络重启的信息（应该是光猫和电信服务端的连接的重启，实际路由器是没有重启的，但是公网ip地址是会变化），这是科学上网的外网连接状态就是不工作的状态，只能把插件关闭了再重新开启才行。各位可以验证一下，还有希望作者可以改进这个问题，几个版本都存在这个问题。谢谢

ps：gfwlist模式
       SSR
       自建的vps

**Comment by ccloving** [comment]
谁用python写个脚本，自动重启，这个问题真的很困扰。

**Comment by cxfksword** [comment]
同样这问题,看状态ss-redir/ss-local	/dns2socks都停止了，没PID，需要重启下

**Comment by zfiber** [comment]
我也碰到了这个问题，以前的版本也会出现突然连不上，但是频率比较小，但是升级到3.8.4之后频率高了很多，点击保存&应用之后，又可以正常连上了，希望能增加个功能：比如国外连接打叉了，能自动重启下ss。

**Comment by chinaunpay** [comment]
3.8.4 我也是同样的问题，点一下保存应用之后又可以连接了。。。

**Comment by DollyHa** [comment]
我还以为是我自己的问题原来大家都会，请问3.8.3会出现这样的问题吗？？ 我的3.8.4也是会国外间歇pd 更换国外dns才能好！

**Comment by deanwong** [comment]
有办法退到之前的版本吗

**Comment by xiaosong** [comment]
同样的问题，困扰已久，之前版本貌似没这问题

**Comment by ccloving** [comment]
在座的是不是都没开虚拟内存？昨天把虚拟内存开开了，已经24小时没掉线了。

**Comment by liubangjain** [comment]
基本是2天一次，基本是固定的时间段，也挺烦的。

**Comment by ccloving** [comment]
基本是2天一次，基本是固定的时间段，也挺烦的。  ---你会python吗？可以写个监控程序，登录路由器后台，一旦发现PD，就触发重启，然后找台NAS或者电脑守护就可以了。我觉得这是一个折中的办法。

**Comment by liubangjain** [comment]
直接设置路由器每天重启来规避这个掉线的问题。

**Comment by chinaunpay** [comment]
我AU88每天定时重启一样有这个问题。

**Comment by ccloving** [comment]
建议大家设置一下命令行版的虚拟内存，貌似好多了。

**Comment by fancyzhu** [comment]
基本是2天一次.... 有高手给点操作提示么？小白

**Comment by hao1707** [comment]
3.8.4 我也是同样的问题，点一下保存应用之后又可以连接了。。。

**Comment by liyanszh** [comment]
我的也是，最近一直不稳定

**Comment by ccloving** [comment]
我的终于稳定了。去掉kcptun的加密，并将SSR的加密设置为rc4.同时开启虚拟内存。 屡试多次，已经不再PD。

**Comment by ddqp** [comment]
我的也是如此，一段时间不用就只能点一下保存，才能使用，一段时间是指按小时算

感觉线程什么的自己会自动断开，又不知道如何具体看问题在哪，每次都需要点一下保存才能继续。

**Comment by deanwong** [comment]
3.8.9 版本依旧

**Comment by wangwei8828** [comment]
加入虚拟内存后稳定多了。

Dean Wong <notifications@github.com> 于 2018年4月23日周一 11:55写道：

**Comment by leeyang1991** [comment]
可以定时重启 koolss解决这个问题
在crontab 里添加定时任务
crontab -e
在最后一行输入
* */1 * * * /koolshare/ss/ssstart.sh restart #restart shadowsocks every 1 hr#
每隔一个小时重启一下ss
