### ISSUE TITLE
服务器可以ping通但国外链接一直是x

### ISSUE THREAD

**Issue by Lecter0406** [koolshare/koolshare.github.io#776]
【2018年02月09日 14:58:33】: 创建ipset名单
ipset v4.5: Unknown arg `-!'
Try `ipset -H' or 'ipset --help' for more information.
ipset v4.5: Unknown arg `-!'
Try `ipset -H' or 'ipset --help' for more information.
ipset v4.5: Unknown arg `-!'
Try `ipset -H' or 'ipset --help' for more information.
ipset v4.5: Unknown arg `-!'
Try `ipset -H' or 'ipset --help' for more information.
ipset v4.5: Unknown arg `-!'
Try `ipset -H' or 'ipset --help' for more information.
ipset v4.5: Line 1 does not start as a valid restore command

Restore failed at line 1:
Try `ipset -H' or 'ipset --help' for more information.
【2018年02月09日 14:58:34】: 写入iptables规则到nat表中...
iptables v1.4.14: Set white_list doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.14: Set white_list doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.14: Set black_list doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.14: Set gfwlist doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.14: Set black_list doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.14: Set chnroute doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.14: Set black_list doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.14: Set chnroute doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.14: Set black_list doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.14: Set chnroute doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
【2018年02月09日 14:58:34】: 加载TPROXY模块，用于udp转发...
iptables v1.4.14: Set white_list doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.14: Set black_list doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.14: Set chnroute doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
【2018年02月09日 14:58:34】: 加载ACL规则：【全部主机】【全部端口】模式为：游戏模式
iptables v1.4.14: Set router doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
【2018年02月09日 14:58:35】: 开启chromecast功能（DNS劫持功能）
【2018年02月09日 14:58:35】: 重启dnsmasq服务...
【2018年02月09日 14:58:36】: ------------------------- shadowsocks 启动完毕 -------------------------
【2018年02月09日 14:58:37】:
【2018年02月09日 14:58:37】: Across the Great Wall we can reach every corner in the world!
【2018年02月09日 14:58:37】:
【2018年02月09日 14:58:37】: =============== 梅林固件 - shadowsocks by sadoneli&Xiaobao ===============

**Comment by lavender1026** [comment]
我也遇到这种情况了
