### ISSUE TITLE
3.84  koolgame  ps4经常上游戏链接时候路由器重启 

### ISSUE THREAD

**Issue by dearrika** [koolshare/koolshare.github.io#777]
3.84  koolgame  ps4经常上游戏链接时候路由器重启

**Comment by skyhsiao** [comment]
我也有这种情况,点解?

**Comment by zorroforever** [comment]
我也是 这个怎么办呀？

**Comment by skyhsiao** [comment]
后来我就没有用koolgame模式了，而是自己搭了一个AnyConnect用玩游戏就用电脑直接连

2018-03-09 7:22 GMT+08:00 zorroforever <notifications@github.com>:

**Comment by zorroforever** [comment]
AnyConnect是什么啊 我去google一下 先谢谢啦
