### ISSUE TITLE
梅林装了ss设置好之后，手机可以翻，电脑不能，什么原因

### ISSUE THREAD

**Issue by qwe4613** [koolshare/koolshare.github.io#779]
梅林装了ss设置好之后，手机连wifi后可以翻，但是网线连的电脑不行

**Comment by jjandnn** [comment]
1-电脑上网正常否？
2-电脑安装客户端可翻否？
3-换浏览器可翻否？
4-路由器主界面view list界面中，电脑是否与手机是一个网段？
5-电脑清理所有缓存了吗？

**Comment by qwe4613** [comment]
1.电脑正常上网；
2.客户端正常翻
3.换尝试了IE不可（用CHROME也不可以）
4.同一网段
5.没有清理所有缓存（清楚cookies那些？）

**Comment by jjandnn** [comment]
cookie不清除，只清缓存。

**Comment by qwe4613** [comment]
清楚缓存后试了，还是不可以

**Comment by qwe4613** [comment]
现固件版本：380.66_4-X7.5  路由器：R7000
刷机官方固件刷R7000_380.66_2过渡
ss3.8.4

**Comment by jjandnn** [comment]
好，路由器，你开了onetime authentication没？

**Comment by jjandnn** [comment]
你是3.8.4？你的服务端装的ss是ss，还是ssr？

**Comment by jjandnn** [comment]
路由ss配置-国内dns：自动获取；国外：dns2socks：8.8.8.8:53；pc 终端：ipconfig 确保网段一致，指向网关是默认192.128.2.1，本地以太ipv4 dns强制：114.114.114.114 备用8888. host中删除所有非默认信息，改回原版。关闭路由kcp，udp。jeff只开第二个。不设置重启清盘。
这么做其实是你的客户端解析正常，路由不稳定，让路由放弃解析，开客户端可以自己udp全局真转。
上述方式如果继续有问题，PC端disable pathMTU discovery。不了解，直接百度一下。一堆。然后重启。在我眼里3.8.4是最好的版本，固件380.68 4-x77和7000，6400，6300之间的配合完美。实测。

**Comment by qwe4613** [comment]
谢谢你耐心的解释。
目前清空host之后，可以使用了。
当时担心稳定性问题，没有刷梅林7.7，看你这么说，后面可以考虑刷上去了。

**Comment by jjandnn** [comment]
兄弟，千万别对7000不放心，我是电话机子生产厂谈过心的。卖国内，隐藏部分功能，是没办法，机子的所有硬件和海外主力销售区域的，完全一样，没水分。所以，神器级别，最稳定的机子。梅林再升3年，这台机子还能适配。

**Comment by jjandnn** [comment]
补充一下，要是你后面升77，一定要先回原厂，确保清除所有数据沉冗。因为4个9小宝改固件，本质上是基于华硕自主研发的微型linux系统编译，改写了web服务器前端。
ps：借你的提问科普了，别介意，防止其他兄弟遇上一样问题，没头绪。

**Comment by xx791117** [comment]
我的正好相反，手机上app youtube、推特、脸书用不了，网页可以打开

**Comment by linwei870116** [comment]
3.8.4的SSR。。为什么打开了科学上网开关，然后一点反应都没了？？我刷新页面，然后开关又是关着的。。谁知道这是什么问题？

**Comment by jjandnn** [comment]
楼上的兄弟，
1，你开关开了以后，两行字：国外链接，本地链接字样出现没？
2，其他应用打开后，可以开启或保存吗？
3，如果显示链接上，你确定自己按了下面的保存按钮没？
@linwei870116
