### ISSUE TITLE
捐赠

### ISSUE THREAD

**Issue by davy7** [koolshare/koolshare.github.io#78]
刚刚捐赠了20元，聊表一下心意 
                           来自koolshare  ID:quasimodo  交易时间：2016-05-09 11:04

**Comment by Garry1171111** [comment]
刚捐赠了10元，支持开发组！

**Comment by Garry1171111** [comment]
刚捐赠10元，支持开发组！  

来自koolshare ID:xueyao123  交易时间：2016-05-09 15:33

**Comment by jannson** [comment]
谢谢，我会尽快加上你们俩的ID。感谢支持！！！

**Comment by zdxssl** [comment]
刚捐赠了8.88元，虽然金额不多，算是对开发组长期以来的感谢吧，聊表心意。

来自koolshare ID:zdx0780 交易时间：2016-05-10 10:19

**Comment by jannson** [comment]
@zdxssl 谢谢。

**Comment by jannson** [comment]
仅仅记录下，未来更新：youxiben 68 元

**Comment by jannson** [comment]
捐献已经可以自动生成名单： http://c.koolshare.io
如果想修改名字情告知。
