### ISSUE TITLE
AC68U 刷的美林7.7 SS 手机app 无法翻墙，网页可以？

### ISSUE THREAD

**Issue by xx791117** [koolshare/koolshare.github.io#780]
AC68U 刷的梅林7.7&koolshare  SS 3.8.4 后 手机app 无法翻墙，网页可以？之前用长宽虽然很慢，但一切正常，换了联通网速提升明显，但是手机上却无法用app youtube了，怀疑是解析的问题，可是换了很多解析服务器依旧如此，好奇怪的问题啊？求解答！！

**Comment by jjandnn** [comment]
1，手机用软件如小火箭、土豆丝之类全局、udp可上否？
2，什么手机？安卓、苹果？
3，网页可翻，是用客户端翻，还是直接接路由？是pac，还是全局，或udp？电脑端是网线，还是wifi？
4，路由是原猫未动？还是搞过桥接？
5，你说的换dns是换了路由ss里的那个dns设置，还是你手机端换了？

假设电脑直连网线，pac可翻，那你的路由的dns设置就没问题。

**Comment by jjandnn** [comment]
不好意思，没看清。你的意思是就手机，手机的浏览器可以，app不可以是吗？

**Comment by xx791117** [comment]
@jjandnn  是的手机的浏览器、pc的浏览器都可以翻墙，但是app不行永远是网络未连接，手机上单独挂ss的话app就没问题，不知道app用的地址和普通web有啥区别，很奇怪公司里R1D用的TT装的SS同一app也是联通的就没问题，家里的AC68U换回长宽虽然慢app也没问题，由此可见应该是联通线路的问题，家里的联通有外网ip，我就想不明白了到底是什么问题！是联通线路的dns问题？可是换了好多dns，效果一样！虽然也不影响啥，就是强迫症想搞明白到底怎么回事！

**Comment by xx791117** [comment]
美人鱼岛吗？

**Comment by xx791117** [comment]
没人遇到吗？？

**Comment by jjandnn** [comment]
你的手机是安卓还是苹果？
你root了手机没？

**Comment by jjandnn** [comment]
由于电脑端，无论用客户端、不用客户端，你都正常。你的路由和电脑的dns解析就正常。所以，不用折腾手机的dns，什么东西比dns还优先，就是你手机的hosts、浏览器的缓存。手机被root过，越狱过，就存在host修改的问题。手机既然用ss客户端能上，就说明默认全局（因为ss软件客户端基本都先设置默认全局，除非你自己设置了配置）情况下，手机dns有能力，端口也没问题。只剩下hosts。很多兄弟为了上网方便改hosts，还有部分固件刷机，直接帮你改好了hosts，这就给gfw配合的运营商留了后门。改回来。

**Comment by jjandnn** [comment]
如果手机你的ss客户端是设置过pac的，那你多两个步骤，在连着wifi的情况下，1，用clean手机客户端或电脑iu4之类的软件，连着清理缓存。2，在手机浏览器里打开浏览器：ipip.net。查看是不是和电脑里输入ipip.net的结果一样。不一样，你的dns或host已经被劫持。一样，就只剩host。修改host，方法1，网上下一个干净的，然后http://www.mobile-dad.com/news/253.html。方法2，从新安装固件或之前的备份。

**Comment by xx791117** [comment]
@jjandnn 我的2个手机都是苹果6s  7 没有越狱  家里的各种设备 华为的平板(只安装了Google的服务框架没有root） ipad 安卓手机 root的和没root的都试了一遍一样的手机就是不行，但是这些设备在单位的R1D所的TT下就正常访问，真的见了鬼了。另外还发现一个有趣的现象，pc上用谷歌浏览器打开youtube 视频封面大部分时间打不开偶尔能看到一部分内容，用火狐就没问题。手机上如果挂上SS把app youtube打开读到列表后关掉SS用路由的翻墙就可以点进去看视频看回复 但是就是刷新不了主页列表。换成长宽的线路就一切ok了（就是tm的太慢720p都费劲），这么看来总觉得还是线路的问题，现在我严重怀疑是光猫做了什么手脚，但是想不通这事儿的逻辑关系

**Comment by xx791117** [comment]
@jjandnn  再补充一点 手机的浏览器访问也正常  就是app不行！所以基本也应该排除hosts的问题，哎呀！今年一开年就各种不顺利，换个网页不行！

**Comment by xx791117** [comment]
@jjandnn 强力要求换了个华为的光猫（原来是贝尔的R200O）一切问题解决，研究和试验了好久，原来真的是硬件问题！唉……无语了……

**Comment by jjandnn** [comment]
@xx791117 客气，没能帮你诊断出光猫这个茬，罕见啊。呵呵。ac68u是好设备，光猫的问题其实我也疏忽了，该早想到的。因为，其实你换长城就可以，说明hosts也没出问题，真是……这下又多了一种情况供以后兄弟参考，你关闭掉帖子吧。

**Comment by sky1339m** [comment]
解决了吗？ 我也是网页可以翻墙  app不行，手机里开ss   youtube  app就能用

**Comment by jiamusmith** [comment]
我也碰到这个问题

**Comment by mroooone** [comment]
我也碰到了这个问题， 和ss啊。DNS 都没啥关系； 当然不排除 其他兄弟有因为SS和DNS 的关系； 我的也是路由挂的SS, pc上一切正常； 手机web浏览器也正常，APP 就打不开； 然后铜鼓了一阵发现，google服务被禁止联网了！！！！！  把google服务联网打开就可以啦（华为手机为毛默认给google禁止联网呢）

**Comment by fzsimlu** [comment]
把谷歌IP段，全部强行代理就可以了。

172.217.0.0/16

**Comment by EnochYng** [comment]
我也遇到一模一样的情况，公司的网什么问题没有，家里的网app不能用，光猫是烽火HG2821T-U。难道真的要还光猫？

**Comment by ttylikl** [comment]
2020年2月，AC86U刷了官改，同样问题。只用路由ssr，YouTube APP和Play商店App打不开。但是从手机浏览器可以打开YouTube！
如果我从手机开ssr，那么YouTube APP和网页都能打开。

还没搞明白。。。

**Comment by ttylikl** [comment]
猜测是不是因为路由器上没有全局代理闹的，开启全局代理后发现没什么卵用

**Comment by thomaswade2000** [comment]
> 2020年2月，AC86U刷了官改，同样问题。只用路由ssr，YouTube APP和Play商店App打不开。但是从手机浏览器可以打开YouTube！
> 如果我从手机开ssr，那么YouTube APP和网页都能打开。
> 
> 还没搞明白。。。

兄弟，你搞明白了跟我们说一声，我也遇到了这个问题

**Comment by blackdackm** [comment]
可以这样试试看，先在手机上使用翻墙工具，打开youtube正常使用，然后断开翻墙工具，不要清理缓存，连上科学上网的路由器，直接使用。这样路由器就会自动缓存DNS，YouTube可以正常使用。

**Comment by EnochYng** [comment]
> 可以这样试试看，先在手机上使用翻墙工具，打开youtube正常使用，然后关掉翻墙工具，不要清理缓存，连上科学上网的路由器，打开YouTube使用。这样路由器就会自动缓存DNS，这样以后YouTube可以正常使用。

现在是只能这样用，但是过一会（大概一个小时），YouTube就又变成无法连接网络了。烦死了，不知道怎么能彻底解决。（其他的设备 包括iPhone ，iPad，安卓手机全都是正常的，唯一不正常的就是mi8手机）

**Comment by z7356995** [comment]
刚刚解决了这个问题，这是因为youtube手机app 会到下面这两个网址认证你的google帐号，网页版的没有。但gfwlist并没有把这两个网址加入墙的列表里。所以只要手动到下面网址加入域名黑名单就可以

www.googleapis.com
play.googleapis.com

**Comment by WinjayYu** [comment]
> > 可以这样试试看，先在手机上使用翻墙工具，打开youtube正常使用，然后关掉翻墙工具，不要清理缓存，连上科学上网的路由器，打开YouTube使用。这样路由器就会自动缓存DNS，这样以后YouTube可以正常使用。
> 
> 现在是只能这样用，但是过一会（大概一个小时），YouTube就又变成无法连接网络了。烦死了，不知道怎么能彻底解决。（其他的设备 包括iPhone ，iPad，安卓手机全都是正常的，唯一不正常的就是mi8手机）

我的米6最近升级系统后也出现了这个问题

**Comment by WinjayYu** [comment]
我清除YouTube所有数据后它就好了🤣

**Comment by empersoprano** [comment]
- 添加`googleapis.com`到clash rule中 还是无法登陆
- 手机切换至流量登录后再切回WiFi可以使用

**Comment by z7356995** [comment]
不是clash rule  是路由器上科学上网程序  黑白名单 下的 域名黑名单，， 我抓过包，，在手机上亲测可用

**Comment by z7356995** [comment]
gfw的名单总有漏掉的，，有两个办法，，一个是在路由器上把漏掉的域名补上，，，还有一个办法是路由器上的v2ray开了23456 端口，让漏掉的走这个端口也可以

**Comment by sonicwxr** [comment]
同样的情况，不知道如何解决

**Comment by fzsimlu** [comment]
强制代理谷歌IP段，可以解决：172.217.0.0/16
