### ISSUE TITLE
3.8.4的SSR。。为什么打开了科学上网开关，然后一点反应都没了？？我刷新页面，然后开关又是关着的。。谁知道这是什么问题？

### ISSUE THREAD

**Issue by linwei870116** [koolshare/koolshare.github.io#784]
3.8.4的SSR。。为什么打开了科学上网开关，然后一点反应都没了？？我刷新页面，然后开关又是关着的。。谁知道这是什么问题？固件是380.62_X7.1的。最新的7.7在我这不稳定，有时会断流。R7000路由。

**Comment by xdkaka** [comment]
打开开关按钮，然后点击下面保存提交才行
