### ISSUE TITLE
SS开启之后，国外DNS无法解析 版本3.8.4

### ISSUE THREAD

**Issue by zxzx74147** [koolshare/koolshare.github.io#786]
![image](https://user-images.githubusercontent.com/514530/36606328-5412c5a0-18fe-11e8-91ab-5edb66e481a1.png)
配置如上

开启ss之后：
![image](https://user-images.githubusercontent.com/514530/36606363-700198a4-18fe-11e8-82c5-75ff3552b530.png)
关掉即可：
![image](https://user-images.githubusercontent.com/514530/36606383-84077666-18fe-11e8-8f07-d8005cfec3a4.png)

运行状态如下：
![image](https://user-images.githubusercontent.com/514530/36606458-bd55d6ba-18fe-11e8-860c-838b1f70c6b2.png)

**Comment by cairenbin** [comment]
我今天将VPS的SS改成了chacha20之后遇到了一样的问题。。。以前用aes-256-cfb的时候一切正常

VPS工作状态正常，使用各种终端设备客户端都是OK的
