### ISSUE TITLE
项目捐赠

### ISSUE THREAD

**Issue by zhucezuifan** [koolshare/koolshare.github.io#79]
多谢你们提供的固件，捐赠了123元表示感谢
来自koolshare ID:youhao交易时间：2016-05-09 18:44

**Comment by jannson** [comment]
谢谢，我会尽快加上你的ID。感谢支持！！！

**Comment by jannson** [comment]
捐献已经可以自动生成名单： http://c.koolshare.io
如果想修改名字情告知。
