### ISSUE TITLE
3.8.4总是过段时间就没法翻长城了，已经按#769修改过了

### ISSUE THREAD

**Issue by donny861221** [koolshare/koolshare.github.io#793]
我发现不管用哪个版本，都是过一天或者过两天就不能用了，最新的3.8.4，按照#769这个方法已经修改过了，结果还是一样，出现这种问题后重新保存应用后就好了，请问到底怎么才能彻底解决这个问题，
不行的话下个版本就加上自动重启把

**Comment by trackycn** [comment]
我也是这样, 最后没办法, 降级3.8.1, 用了一周了, 比较稳定, 没有PD

**Comment by donny861221** [comment]
好的吧，晚上回去我试试3.8.1的版本去

**Comment by zhaoqz** [comment]
我也是这样，要经常进去保存应用一下
