### ISSUE TITLE
科学上网插件设置域名白名单就出现错误

### ISSUE THREAD

**Issue by HappyQuQu** [koolshare/koolshare.github.io#794]
我在域名白名单里面设置类两个域名就无法上网 国内国外都是X
![](http://ww4.sinaimg.cn/large/0060lm7Tly1fp1r3os2yqj30l00k1gnh.jpg)
我把白名单去掉就正常了
![](http://ww1.sinaimg.cn/large/0060lm7Tly1fp1r5n7wovj30lf0iggne.jpg)
这是什么原因啊

**Comment by devil126126** [comment]
同问，我也有这个问题
