### ISSUE TITLE
梅林改版固件升级到7.8后路由器上版本3.8.4，但国外一直连不成功！

### ISSUE THREAD

**Issue by magic-monkey** [koolshare/koolshare.github.io#798]
梅林的koolshare改版固件升级到了7.8版本后就出现国外连接无法连接了……重装了也不行，用手机和桌面客户端就没问题，只有路由器上的版本不能连接……到底是新固件的原因还是插件需要更新才能用？

**Comment by Sak4ever** [comment]
两会期间，的确误杀情况严重的多了；梅林固件上的SS已经停摆多天
调试参数无效 VPS是好的 用windows客户端可以正常翻墙

**Comment by monkeyrobo** [comment]
我的ac68u也是7.8版本的，3.8.4连上国外的也是时断时续的，不知道什么bug还是其它问题
