### ISSUE TITLE
定时脚本的”脚本配置“无法直接用命令

### ISSUE THREAD

**Issue by cjameslynn** [koolshare/koolshare.github.io#8]
定时脚本的”脚本配置“无法直接用命令，是不是需要在jffs里先建一个脚本，再把脚本地址填写到上面？
在”脚本配置“文本框里直接输入reboot无效。

**Comment by sadoneli** [comment]
定时脚本目前支持shell脚本，如果你需要调用命令，你可以将命令写进脚本然后去调用，比如自动重启脚本内容
<pre>#!/bin/sh
/sbin/reboot</pre>
