### ISSUE TITLE
项目捐赠

### ISSUE THREAD

**Issue by mumuou** [koolshare/koolshare.github.io#80]
多谢你们的这个项目，开发者辛苦了，88元聊表心意。
![img_0499](https://cloud.githubusercontent.com/assets/19269084/15118612/8e1d0d82-163f-11e6-95ce-fc5f73f09039.PNG)

来自koolshare  ID:mumuou  交易时间：2016-05-09 16:44

**Comment by jannson** [comment]
谢谢，我会尽快加上你的ID。感谢支持！！！

**Comment by jannson** [comment]
捐献已经可以自动生成名单： http://c.koolshare.io
如果想修改名字情告知。
