### ISSUE TITLE
koolgame 模式下一段时间会出错然后整个路由重启造成断网

### ISSUE THREAD

**Issue by zorroforever** [koolshare/koolshare.github.io#800]
如题 麻烦大大啦
电信光猫桥接 路由器AC68U自己拨号 ss版本3.8.4，阿里云启动的gameserver
     Aug  1 08:00:17 kernel: <4>CPU: 0    Tainted: P             (2.6.36.4brcmarm #26)
Aug  1 08:00:17 kernel: <4>PC is at memcpy+0x114/0x368
Aug  1 08:00:17 kernel: <4>LR is at ip_conntrack_ipct_add+0x1ec/0xb50
Aug  1 08:00:17 kernel: <4>pc : [<c0389bac>]    lr : [<c02299b4>]    psr: 60000013
Aug  1 08:00:17 kernel: <4>sp : cc5dba64  ip : 00000002  fp : cc5dba90
Aug  1 08:00:17 kernel: <4>r10: 0000009e  r9 : 00000000  r8 : cb07d810
Aug  1 08:00:17 kernel: <4>r7 : 00000004  r6 : ce09b8c0  r5 : 00000004  r4 : cc714960
Aug  1 08:00:17 kernel: <4>r3 : 00000000  r2 : 00000002  r1 : 00000004  r0 : cc5dbae8
Aug  1 08:00:17 kernel: <4>Flags: nZCv  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment user
Aug  1 08:00:17 kernel: <4>Control: 10c53c7d  Table: 9c4dc04a  DAC: 00000015
Aug  1 08:00:17 kernel: <0>Process koolgame (pid: 8162, stack limit = 0xcc5da270)
Aug  1 08:00:17 kernel: <0>Stack: (0xcc5dba64 to 0xcc5dc000)
Aug  1 08:00:18 kernel: <0>ba60:          cc5dbae8 cc714960 c02299b4 cc714960 00000003 cb007100 cdcb3800
Aug  1 08:00:18 kernel: <0>ba80: 00000001 cb07d824 00000000 00000001 00000000 00000000 00000000 00000000
Aug  1 08:00:18 kernel: <0>baa0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
Aug  1 08:00:18 kernel: <0>bac0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
Aug  1 08:00:18 kernel: <0>bae0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
Aug  1 08:00:18 kernel: <0>bb00: 00000000 00000000 00000000 00000000 00000000 00000000 00000001 c0237c48
Aug  1 08:00:18 kernel: <0>bb20: 00000000 00000000 00000000 00000000 00000001 cc5dbc14 00000000 0000000a
Aug  1 08:00:18 kernel: <0>bb40: 00000001 00000000 b7d0c00e c9929eb4 00000000 00000000 00000000 00000000
Aug  1 08:00:18 kernel: <0>bb60: 00000000 00000000 00000000 00000000 00000000 00000000 00010000 cc4f3f00
Aug  1 08:00:18 kernel: <0>bb80: cde45980 cc41e300 00000000 cc5dbbd8 cc5dbc14 c02288b8 c03e04dc cc5da000
Aug  1 08:00:18 kernel: <0>bba0: cb007400 113e3288 cc5dbbd8 00000000 ce09b8c0 cc5dbbd8 00000000 00000004
Aug  1 08:00:18 kernel: <0>bbc0: cf80e000 cc714960 c023eb0c c02741d4 cc5dbbd8 cb159da0 b7d0c00e 00000000
Aug  1 08:00:18 kernel: <0>bbe0: 00000000 00000000 00020104 2e04a8c0 00000000 00000000 00000000 00115924
Aug  1 08:00:18 kernel: <0>bc00: c04225a8 cc5dbc7c c04225a8 80000000 ce09b8c0 00000004 00000000 c037e96c
Aug  1 08:00:18 kernel: <0>bc20:?^B3eb0c cc5dbca4 c04225a0 00000000 00000004 ce09b8c0 00000000 c023eb0c
Aug  1 08:00:18 kernel: <0>bc40: cc5dbc7c cf80e000 c04225a8 c02258e8 cf80e000 cc5dbc7c c023eb0c 80000000
Aug  1 08:00:18 kernel: <0>bc60: 00000000 cc5dbc7c cc5dbca4 00000002 c04225a0 cc5da000 cf80e000 c03e37b4
Aug  1 08:00:18 kernel: <0>bc80: c0256a40 0002afd6 00000000 ce09b8c0 cf80e000 cc5da000 00000000 cb07d810
Aug  1 08:00:18 kernel: <0>bca0: 00000010 c023f584 cf80e000 c023eb0c 80000000 ce09b8c0 00000000 0000007a
Aug  1 08:00:18 kernel: <0>bcc0: ce09b8c0 ce086ee0 cb007e00 c0257b8c cf80e000 c0256a40 80000000 00000000
Aug  1 08:00:18 kernel: <0>bce0: c82150f4 cc5dbcfc 00000400 00000000 cb07d800 cc5dbefc 00000000 00000009
Aug  1 08:00:18 kernel: <0>bd00: 00000000 00000000 c9929eb4 0104a8c0 00000000 00000000 00000000 00000000
Aug  1 08:00:18 kernel: <0>bd20: 00000000 00000000 00000000 000000ff 00000000 00000000 c9929eb4 00000009
Aug  1 08:00:18 kernel: <0>bd40: 00000000 cc5dbf00 ffffffea 00000000 00000000 cc5dbd98 cc5dbf5c c02ea328
Aug  1 08:00:18 kernel: <0>bd60: 00000040 00000000 00000000 0000007a cc5dbefc c0261afc 00000000 00000000
Aug  1 08:00:18 kernel: <0>bd80: cefc581c cefc5630 0000007a cc5dbf5c c02ea328 c01e97a4 00000000 cc5dbf5c
Aug  1 08:00:18 kernel: <0>bda0: 00000000 00000001 ffffffff 00000000 00000000 00000000 00000000 00000000
Aug  1 08:00:18 kernel: <0>bdc0: cb049200 cc5dbdfc 00000000 00000000 cc5da000 00000002 cc5dbe10 0000001c
Aug  1 08:00:18 kernel: <0>bde0: 00000000 00000040 00000a00 cc5dbf5c c02eb424 c01e98d0 00000040 cb049200
Aug  1 08:00:18 kernel: <0>be00: 9e5527df cb049800 00000000 00000001 ffffffff 00000000 00000000 0000007a
Aug  1 08:00:18 kernel: <0>be20: cf5b3a00 cc5dbefc 00000000 cc5dbf5c cc5dbe7c 00000001 cc5dbefc cc5dbefc
Aug  1 08:00:18 kernel: <0>be40: 00000008 cc5dbf5c cf5b3a00 00000000 cc5da000 cc5dbf5c cf5b3a00 cc5dbefc
Aug  1 08:00:18 kernel: <0>be60: 00000018 c01ebf04 00000001 cc5dbf3c cc5dbf3c 00000008 c003bf80 00000002
Aug  1 08:00:18 kernel: <0>be80: c9929eb4 00000000 00000000 cb049800 00000000 cc5dbf5c 00000001 5161d517
Aug  1 08:00:18 kernel: <0>bea0: cc5dbedc 106d8d28 1061d4fc 1061d4fc 0000001c 00000000 00000a00 cf5a96c0
Aug  1 08:00:18 kernel: <0>bec0: cc5dbedc 106d8d28 1061d4fc cc5da000 00000040 c01ebc04 00000000 8622000a
Aug  1 08:00:18 kernel: <0>bee0: 00000000 00000000 00000000 ffff0000 3405342f 00000000 cf8de840 106aa900
Aug  1 08:00:18 kernel: <0>bf00: 0000007a cf8de840 cf8de880 cc5dbf28 cf8de848 c00fc8b0 00000000 cf8de840
Aug  1 08:00:18 kernel: <0>bf20: cf8de880 c00fcee4 cc5dbf28 cc5dbf28 00000080 106bf74c cc5da000 00000018
Aug  1 08:00:18 kernel: <0>bf40: 00000000 00000008 00000009 00000000 00000000 00000000 004502e0 cc5dbe7c
Aug  1 08:00:18 kernel: <0>bf60: 00000010 cc5dbefc 00000001 cc5dbf3c 00000018 00000040 00000001 fffffff2
Aug  1 08:00:18 kernel: <0>bf80: 00000001 00000000 00000000 1099aba0 00000128 c003dc68 cc5da000 00000000
Aug  1 08:00:18 kernel: <0>bfa0: 00450334 c003dac0 00000000 00000000 00000006 10639a94 00000000 00000000
Aug  1 08:00:18 kernel: <0>bfc0: 00000000 00000000 1099aba0 00000128 00000077 00000000 106a4620 00450334
Aug  1 08:00:18 kernel: <0>bfe0: 1099abbf 10639a40 00094b3c 0016e538 60000010 00000006 7463656c 616d695f
Aug  1 08:00:18 kernel: <4>[<c0389bac>] (PC is at memcpy+0x114/0x368)
Aug  1 08:00:18 kernel: <0>Code: e211c003 0affffc4 e3c11003 e35c0002 (e491e004) 
Aug  1 08:00:18 kernel: <4>---[ end trace b4dd5ca823d0b504 ]---
Aug  1 08:00:18 kernel: <0>Kernel panic - not syncing: Fatal exception
Aug  1 08:00:18 kernel: <4>[<c0043ff8>] (unwind_backtrace+0x0/0xf8) from [<c02cd6f0>] (] (panic+0x7c/0x1a8) from [<c00416f0>] (die+0x1a4/0x1dc)
Aug  1 08:00:18 kernel: <4>[<c00416f0>] (die+0x1a4/0x1dc) from _kernel_fault+0x6c/0x8c) from [<c00452cc>] (do_page_fault+0x150/0x1ec)
Aug  1 08:00:18 kernel: <4>[<c00452cc>] (do_page_fault+0x150/0x1ec) from [<c003d3a4>] (do_DataAbort+0x30/0x9c)
Aug  1 08:00:18 kernel: <
Aug  1 08:00:18 kernel: ____________________________________________________________________________

**Comment by zorroforever** [comment]
在PS4联机游戏时候发生的重启

**Comment by serhtt** [comment]
我的网件r7000 7.7用koolgame一段时间路由器就卡死了……

**Comment by zorroforever** [comment]
哎 后来路由器升级了7.8，server升级到0.3.3 还是会重启-。- 求哪位大大看看哈
