### ISSUE TITLE
请问一下，在gfwlist模式下载的时候，很慢，要切换到全局代理模式才行

### ISSUE THREAD

**Issue by xyiqq** [koolshare/koolshare.github.io#801]
任天堂switch的在线商店下载的时候，如果用gfwlist模式，下载非常慢，只能切换到全局代理才能下载快，但是全局代理大家也知道，上国内网站非常慢，这个要怎么设置才能在gfwlist模式的时候下载也很快？

**Comment by syaofox** [comment]
可以试试大陆白名单方式
