### ISSUE TITLE
国内解析可能存在问题

### ISSUE THREAD

**Issue by M1p0** [koolshare/koolshare.github.io#806]
国内解析为运营商dns  国外解析方式为chinadns1  ssr服务器挂掉后 国内的解析速度也变得异常慢甚至无法打开网页

**Comment by gtjoe1988** [comment]
我也是啊 国内一些经常加载不全还很慢 ss国内状态偶尔会红 关了SS就正常

**Comment by donny861221** [comment]
我的也一样出现这个问题

**Comment by Comah** [comment]
我的也是 满就不说了 经常是打不开 然后需要二次刷新才能勉强打开 状态经常国外红了然后国内红 然后需要手动加载一次才能正常  看来是DNS的问题
