### ISSUE TITLE
固件/插件未来走向

### ISSUE THREAD

**Issue by sadoneli** [koolshare/koolshare.github.io#807]
很久没更新了，积压了200多个issue没有打理，一是因为自己搞了太多东西，根本忙不过来，甚至有影响到自己的生活，二是新的软件中心已经在小宝的主导下进展开发中了。所以决定暂时以最低限度的精力维持一段时间，待自己显示生活稳定下来，新的软件中心发布后再决定开发事宜。

以下下是自己主导或参与的一些路由器下的项目：
1. 基于梅林380代码的X系列的改版固件、软件中心内的科学上网插件和其它一些主要插件
	由于上游merlin固件都过度到了384代码，380版本仅仅是一些寥寥的安全补丁更新，所以，X系列基本上就止步于7.8固件了。现在能透露的是小宝正在主导开发新一代的软件中心，这需要一些时间，所以在新软件中心出来之前，我所负责的科学上网插件的更新也会处于基本停滞状态。科学上网插件2年左右的更新下来，各种增加功能，搞得是越来越复杂，也越来越臃肿，如果功能开全的话，对于处理器性能较弱的华硕和网件的路由来说实在有点吃不消；还有个原因就是最近gfw的封锁越来越摸不透，也许辛苦更新都是做无用功呢。大家需要安装的可以去[这里](https://github.com/koolshare/koolshare.github.io/tree/acelan_softcenter_ui/shadowsocks)下载离线版本，也可以加入[telegram群](https://t.me/joinchat/AAAAAEC7pgV9vPdPcJ4dJw)交流讨论
2. 基于梅林384的RT-AC86U改版固件和软件中心内所有插件
	这个固件目前会维持更新，软件中心插件的话，对应的[科学上网插件](https://github.com/koolshare/rogsoft/tree/master/shadowsocks)现在又不是不能用，所以暂时也不会更新；不过我如果有多的时间的时候，会想法办增加一些插件，比如aliddns等插件等
3. 基于华硕官方384的GT-AC5300的官改固件和rog皮肤的软件中心内所有插件
	同上第2点
4. 参与到fw867的LEDE(OPENWRT)_X64软件中心的[科学上网插件](https://github.com/koolshare/ledesoft/tree/master/koolss)和其它插件
	已经停了几个月没更新lede的科学上网插件了，之前答应过的一些功能暂时也不想添加了，怕走了merlin的老路，搞得越来越臃肿，不过重要的一些二进制文件F大在帮忙弄，所以再停一段时间吧。
5. 之前挖过坑的tomato软件中心固件和对应的科学上网插件。
	[这个](https://github.com/koolshare/ttsoft)我几乎确定我不会去摸了，弃坑之~
6. 基于380代码的mips机型的改版固件和软件中心
	这里说的就是N66U和AC66U两个机器了，性能低下就不说了，2.6的内核，想搞个基于udp转发的游戏模式都没法弄，加上merlin方面也放弃了这两款机型，所以他们也就停留在X7.6了，384的更新也不会有他们，软件中心也放弃更新。

总之，同时搞多个平台的固件和软件中心着实费神，加上380系列的机器老旧的内核 (2.6.36) ，更别提更老内核的mips机型，很多插件需要的二进制编译能把脑壳抓烂。而小宝主导的新的软件中心平台上线之前（在未来merlin 384内），X系列的固件和科学上网插件都会停下来了了。之于86U和GT-AC5300，这两个机器的插件开发相对来说较为轻松，所以固件和插件应该会继续更新，直到新软件中心上线。

新软件中心的科学上网应该还是在目前的科学上网插件的设计框架内，但是会尽力避免现在的臃肿，稳定方面，毕竟涉及到的因素实在是太多了，现在还不好说，目前shadowsocks方案确实出现了太多诸如被封锁等问题，未来会看情况决定是否使用其它方案，或者是自己开发方案？

大家有任何未来开发方面的问题和建议，可以在本issue下提，合理的提问我会尽力回答的~

**Comment by sportfit** [comment]
Although my device updates are stuck with the X7.5 and 3.6.0 plug-ins, the AC68U can still be used normally. I look forward to follow-up simple and stable features or plug-ins. Thank you very much for your selfless efforts and hard work!

**Comment by Lecter0406** [comment]
新的科学上网插件会增加v2ray或者brook这种ssr之外的代理吗？

**Comment by sadoneli** [comment]
@Lecter0406 不会，至少老版本软件中心不会，新版本看情况

**Comment by Comah** [comment]
辛苦了 感谢付出！我的机型是6300-v2  觉得现在384还是有点不太稳定 还有就是希望能加入ssr-server  再次感谢您一直以为的默默付出！

**Comment by myliyifei** [comment]
great work, thank you very much.

**Comment by cyber1984** [comment]
大神，加油，专门注册一个号支持你

**Comment by paldier** [comment]
mips建议继续搞，目前蓝洞 k3c d7000v2等等mips方案在慢慢增多，现有内核是3.10并且已知一年内会更新4.x内核，至少把软件中心依赖的那些二进制更新了吧，其他插件的可以靠大家慢慢更新

**Comment by sadoneli** [comment]
mips架构的asus机型内核不会升级的，一直在2.6，很难弄，所以不会搞

**Comment by paldier** [comment]
我没说ac66u会升级，而是lantiq方案的会升级，而且有sdk用来编译添加插件并不难

**Comment by sadoneli** [comment]
1 需要单独的二进制维护
2 性能较弱
3 开发这边已经没人有mips机器了

**Comment by paldier** [comment]
即使只编译skipd httpd这些也不行？

**Comment by wangsteak** [comment]
真心希望支持v2ray，目前v2ray的可靠性越来越得到体现了，呼声也越来越高，希望作者能认真考虑

**Comment by sadoneli** [comment]
golang程序的在bcm470x上性能真的很着急的，而且v2ray的两个二进制文件加起来就20M大小，压力山大的，所以几乎不会考虑v2ray在merlin路由上的实现

BCM490X估计可能性大些还

**Comment by wangsteak** [comment]
GoFlyway请问这个可以考虑一下么，效果也还不错

**Comment by ioversleep** [comment]
首先感谢一直以来的努力，我觉得以后新的软件中心的科学上网插件可以多兼容一些科学上网方式，比如v2ray或者其他什么的，给大家选择的空间之外也增加了gfw识别的难度，现在用ss的太多了，太容易被针对。怎么说呢，毕竟路由器的主要功能是用来上网，而上网就免不了遇到gfw的问题，所以也可以说是最重要的功能之一了。

**Comment by monkeyrobo** [comment]
V2ray希望能支持吧...作者大大能看见不!

**Comment by koala060528** [comment]
感谢您的无私奉献！！

**Comment by davidadmin** [comment]
大神也要注意休息啊！！

**Comment by snchrome** [comment]
期待新版的插件早日上线。

**Comment by snchrome** [comment]
@sadoneli 大佬，能不能开发一个koolgame的pc客户端啊。在pc上玩WarThunder，用sstap，各种问题，经常莫名其妙和服务器失去链接，还有就是sstap停更。
用koolgame模式非常稳定。不过路由平时还要给给其他设备翻墙，来回在ssr和koolgame切换很麻烦。

**Comment by sadoneli** [comment]
@snchrome 没有的，koolgame这个项目小宝写好到现在也已经很久没更新了。不过我建议换个思路，比如你可以在PC上利用hyper-v虚拟机装一个koolshare论坛的LEDE（现openwrt）固件，把物理网卡给LEDE独占，然后设置内部虚拟交换机作LEDE的lan，在lede软件中心里安装koolgame插件。这样你的PC就单独使用lede下的koolgame，其它机器使和PC忍让用路由的fq软件
相关链接：
http://firmware.koolshare.cn/LEDE_X64_fw867/
http://koolshare.cn/thread-84735-1-1.html
http://koolshare.cn/thread-105764-1-1.html

**Comment by sadoneli** [comment]
![image](https://user-images.githubusercontent.com/10495520/38792780-43f1cc38-4181-11e8-93fb-b7e972366956.png)
HYPER-V交换机网络的配置可以参考这个
绿色虚线框部分：新建一个虚拟网络交换机，名字为wan，选择外部网络，选择你上网的网卡，去掉**允许管理操作系统共享此适配器**（让LEDE独占网卡）
绿色实线框部分：新建一个内部网络，名字为lan，
LEDE虚拟机配置需要依次添加wan和lan两个网络适配器，在lede内会被识别为eth0，eth1
LEDE安装好后配置/etc/config/network，让eth0对应wan，eth1对应wan即可

**Comment by notepad2** [comment]
请问未来ac86u有没有出官改的可能性，就目前体验来说，梅林的更新速度以及漏洞问题跟官方比确实大有不如，而且在目前梅林aimesh功能缺失的情况下，官改的意义在于能用华硕方案解决mesh问题且86u的代价只有gt5300的一半不到。

**Comment by kingofotaku** [comment]
也就是说像6300这些非asus机器是不是就止步380了？

**Comment by jjbb528** [comment]
我的ac66u不想丢掉 有大神升级一下软件中心吧！还有ss安装不上想科学上网呀 急需

**Comment by BurningC4** [comment]
希望能有作者能再次进tomato科学上网的坑

**Comment by DurianFu** [comment]
是不是以后GT-AC5300上没法用科学上网了
