### ISSUE TITLE
用梅林开ssr手机上不了谷歌商店

### ISSUE THREAD

**Issue by exVOICE** [koolshare/koolshare.github.io#808]
谷歌商店一直显示DF-DFERH-01，用LEDE和手机上的SSRR不会出现这种情况

**Comment by Comah** [comment]
谷歌语音也用不了 真的需要更新了

**Comment by Flyju** [comment]
https://github.com/koolshare/koolshare.github.io/issues/714 同样的问题 解决方法在这里 亲测可行
