### ISSUE TITLE
梅林固件  3.8.4

### ISSUE THREAD

**Issue by fzhou223** [koolshare/koolshare.github.io#813]
設置了路由器每日自動重啟，每次重啟完后，科學上網會失效（但開關為開），需要進入保存一下設置后才可。

**Comment by lingaoyi** [comment]
我也是这样，必须要手动打开。

**Comment by hutuxiaogui** [comment]
我的也是这样，设置路由器重启，科学上网的开关为开，需要点保存才可以

**Comment by paceyuan** [comment]
同问，最近折腾的ac88u有这个问题，但之前折腾的68u同7.7版本没有这个问题

**Comment by 2huYa0** [comment]
问题解决了吗？我也碰到这样的问题

**Comment by zyunling** [comment]
同样问题。7.8，SS 3.8.9 正常用几小时后总会失效，需要重新点保存才行。
