### ISSUE TITLE
希望有对某设备"全局ss且屏蔽国内"模式 (或是有自行完成的方式也行)

### ISSUE THREAD

**Issue by RigHakiko** [koolshare/koolshare.github.io#814]
我在虚拟机上看国内网站, 而想在host-os中只看国外网站

因为我为了良好的网络体验, 而给host-os设置成了全局模式, 

然而有时不小心点到了国内网站就可能被追踪 (就算每周点一次, 那几个月下来也能轻易地追踪到, 将来可能在gfw收网时被封ip), 

甚至被利用来发动网络攻击 (比如劫持百度攻击Github, 那么任何国内网站都可能也会) 

请问能否增加这个模式? 把"大陆白名单"中的网站屏蔽掉?

或是有手动设置的方式也可以,

**Comment by sadoneli** [comment]
这种需求需要太少，需要的可以自己实现，但是就算是大陆白名单也不一定能屏蔽掉所有的国内网站
