### ISSUE TITLE
能把反向代理工具Nginx移植上去就好了

### ISSUE THREAD

**Issue by InoriHimea** [koolshare/koolshare.github.io#818]
现在激活IDEA系列用的是10块钱的阿里云搞得反代激活的，5月就好到期啦，到时候搞个本地的还贼麻烦。想着写到路由器里面倒是不错，但是linux又不熟悉，所以也不知道怎么弄。

要是能把xx-net也搞一个就好咯！

**Comment by 772132172** [comment]
不是有别人提供的在线激活网站吗？

**Comment by leochien0102** [comment]
IDEA不是可以做本地激活服务么？

**Comment by liuyang007** [comment]
欢迎使用
[https://icexz.com/idea/](https://icexz.com/idea/)
来激活jetBrains全家桶
了解一下
