### ISSUE TITLE
梅林SS 3.8.4 

### ISSUE THREAD

**Issue by 2olegend** [koolshare/koolshare.github.io#819]
华硕ac68u 380.69_2-X7.8
SS选择什么模式都会全局ss 测试IP也是那个外国节点的ip

**Comment by goIntoAction** [comment]
我也碰到这个问题,最近几天感觉网速好卡,一看ip都是国外的

**Comment by talking28** [comment]
同样情况，象是3月份开始的。首先发现国内爱奇艺不支持本地区。SS一开就是全局

**Comment by bladenick** [comment]
访问权限功能，我这里也是失效的，不管设置是否通过SS, 打开SS后所有链接设备均可访问外网

**Comment by monkeyrobo** [comment]
我的ac68u Firmware:380.69_2-X7.8 科学上网插件-刚开始翻墙都是有效的，过几个小时后就访问不了墙外了...
