### ISSUE TITLE
游戏V2客户端+服务端时常掉线，同服务器普通游戏客户端+服务端无问题；

### ISSUE THREAD

**Issue by sunsan05** [koolshare/koolshare.github.io#82]
如题
同一个服务器，切换游戏客户端V2模式则会经常掉线；「彩虹6这个游戏特别明显，直接就无法登录了；其他游戏偶尔断线；」
但是同服务器，切换普通游戏模式则不会出现这个问题；

路由AC88U 年初的版本；

**Comment by sunsan05** [comment]
另外，我想捐赠，请问怎么搞？

**Comment by jannson** [comment]
微信扫描二维码： https://github.com/koolshare/firmware/blob/master/.resources/img/qr.png

我周末可以与你联调！但是我如何加你QQ ？我不想暴露信息到这里。

**Comment by jannson** [comment]
你到论坛私信我 QQ 吧。后续我在联系你解决问题！感觉不至于有这样的问题~

**Comment by sunsan05** [comment]
已经捐赠100；

我看到更新了最新版的GAMESERVER和路由固件，我晚上回去试一试，如果没此情况了就不麻烦联调了；

**Comment by jannson** [comment]
好的，給力。有问题我都会努力跟进。

**Comment by jannson** [comment]
用这个脚本一键安装很方便：https://raw.githubusercontent.com/clangcn/game-server/master/install-game-server.sh

**Comment by sunsan05** [comment]
好的，我晚上回去试一试。

**Comment by sunsan05** [comment]
我没权限私信，就这里回复QQ吧：84295023
