### ISSUE TITLE
dns地址

### ISSUE THREAD

**Issue by ugist** [koolshare/koolshare.github.io#820]
cf的dns  1.1.1.1
填入国外dns时，无法使用。
看了下规则，被归入chnroute了

**Comment by Comah** [comment]
1.1.1.1还没开始正式投放使用吧？还有几天才能用吧。。

**Comment by proac50** [comment]
在pc端设置cf的1.1.1.1，是可以用的，应该是投入使用了。但ss上，不知道怎么设置端口。
