### ISSUE TITLE
3.8.4 混淆判断有问题 导致开机PD

### ISSUE THREAD

**Issue by Love4Taylor** [koolshare/koolshare.github.io#821]
首先是原版+混淆

开机后插件会莫名以不带混淆的方式自启动, 然后日志疯狂
```
ss-local[1626]: invalid password or cipher
```
必须自己手动 点一次 保存应用 才可以正常

![](https://ws1.sinaimg.cn/large/af997d39gy1fpwmqhuawzj20u01hcgr9.jpg)

![](https://ws1.sinaimg.cn/large/af997d39gy1fpwmtjn4pfj20u01hcgrj.jpg)
 
把原有判断删了 改到 json 里 经测试正常了

![](https://ws1.sinaimg.cn/large/af997d39gy1fpwocbumxkj20u01hcahi.jpg)

**Comment by sadoneli** [comment]
写进配置文件也行的，不过就是如果你用原版SS的话，json里会生成一个空的plugin字段，会导致原版SS出问题？

**Comment by sadoneli** [comment]
我这里无法重现你的问题，所以3.8.5和3.8.6也没有针对的修复计划

**Comment by sadoneli** [comment]
我需要更多的测试

**Comment by sadoneli** [comment]
近日我会详细测试并尝试修复

**Comment by M-os** [comment]
同样问题

**Comment by sadoneli** [comment]
请测试3.8.7

**Comment by Love4Taylor** [comment]
3.8.7 之后正常了
