### ISSUE TITLE
强烈要求添加 pcap_dnsproxy

### ISSUE THREAD

**Issue by yangchuansheng** [koolshare/koolshare.github.io#825]
希望添加 pcap_dnsproxy，或者 指点一下 交叉编译 pcap_dnsproxy 的方法 😄

**Comment by sadoneli** [comment]
此方案在3.7.8中被移除了
https://github.com/koolshare/koolshare.github.io/blob/acelan_softcenter_ui/shadowsocks/Changelog.txt#L46
需要的话可以用3.7.8之前的版本
