### ISSUE TITLE
SS和WebDav、Samba共享冲突

### ISSUE THREAD

**Issue by leepoi** [koolshare/koolshare.github.io#826]
至少2年前就有的老问题了，以前在koolshare发过帖子，也没几个人回复，到现在一直有这个毛病。

开启SS一段时间后（时间不定，因为不是每次用ss后就立马用共享），局域网共享（PC通过Samba、Webdav共享文件给同一局域网内的手机等移动设备），文件下载速度会从正常的 几兆/s  降低到几十KB/s  ，共享功能基本作废。不开SS从来不会出问题（SSR、koolgame都会出问题），只要开了，必定完蛋，且一旦出现这个现象，即使关闭或者重启路由器SS也无济于事，只能重启路由器解决。

路由器主界面内存占用从平时的85MB左右飙升到140MB，如果继续憋着龟速使用共享，则飙升到180MB以上，我打这些字的5分钟内，内存占用从140MB升到了185MB，刚刚路由器彻底死机上不去网了。。。。

这么明显的bug，难道没人遇到过吗？麻烦各位开发人员关注一下吧，这个bug非常恶心。。。

**Comment by sma11black** [comment]
@leepoi 这个问题尝试关闭 NAT加速 功能
具体的设置是 内部网络(LAN) -> Switch Control -> NAT加速：停用
