### ISSUE TITLE
访问控制功能有问题

### ISSUE THREAD

**Issue by MagaFun** [koolshare/koolshare.github.io#827]
如图，即使在删除全部访问控制规则之后，主机仍然走游戏模式。且规则未完全删除

![chrome_2018-04-08_17-18-34.png](https://i.loli.net/2018/04/08/5ac9df858ff56.png)
![chrome_2018-04-08_17-18-43.png](https://i.loli.net/2018/04/08/5ac9df859de87.png)

#822

**Comment by MagaFun** [comment]
#822

**Comment by sadoneli** [comment]
需要卸载一次ss，以清空ss数据才能恢复这个
