### ISSUE TITLE
希望ss在检测到PD时候能自动重启

### ISSUE THREAD

**Issue by christdl** [koolshare/koolshare.github.io#833]
不知道为什么，用一段时间ss会出现pd，然后必须重启才能再次连上，不知道能不能让ss自动在检测到PD后重启。

**Comment by deanwong** [comment]
是公网ip变化就会PD

**Comment by sadoneli** [comment]
1 状态检测只会在进入界面的时候才会进行
2 如果让状态检测常驻，那么有时候网络波动，丢包等问题都会引起pd，然后导致不断重启，这样是不好的

**Comment by christdl** [comment]
那检测外网ip地址变化行不行？比如每隔15分钟检测一次外网ip地址是否变化，变化则检测ss是否pd，是则重启，否则不操作，继续过15分钟检查外望ip地址？

发自我的 iPhone

**Comment by sadoneli** [comment]
这个不需要检测，如果路由器重启拨号的话，会触发防火墙重启的，防火墙重启会触发插件自动重启

**Comment by sadoneli** [comment]
而且不能排除是否是ss本身挂了，如果那样就又需要做备用节点等功能了

**Comment by christdl** [comment]
嗯，确实会比较麻烦。那不知道公网ip变化导致pd本身可以避免吗？

发自我的 iPhone

**Comment by sadoneli** [comment]
这个本来就有这个机制，如果本身挂ss的路由器负责拨号的话，那么公网ip变化是会引起插件重启的
如果是光猫拨号，路由器作为二级的话，即使公网ip变化，也不会引起什么问题的

**Comment by christdl** [comment]
我用的是r7000，7.4版本的小宝系统，ss最新版本，用一段时间还是会pd。特别是ss server插件一起开的时候，感觉pd概率更高。确认过ss的服务器没问题的

发自我的 iPhone

**Comment by sadoneli** [comment]
那会不会可能是你被gfw盯上了，日志里有没有很多reset by peers之类的？
