### ISSUE TITLE
DNS设定中，可否加入Cloudflare的1.1.1.1和1.0.0.1？

### ISSUE THREAD

**Issue by proac50** [koolshare/koolshare.github.io#835]
Cloudflare的DNS比google的快，也稳定很多，希望将这个添加到海外DNS解析中。谢谢！

**Comment by xlighting2017** [comment]
在 DNS设定--国外DNS 里面自己配

**Comment by proac50** [comment]
不知道端口如何选择。保留原有默认的53，则内外都不通。不选择端口也是一样。

**Comment by sadoneli** [comment]
1.1.1.1被很多机构如学校等作为认证或者管理地址，所以不建议加入选项
可以根据实际需要自己定义
