### ISSUE TITLE
使用这个服务，当ss服务挂掉了，整个网都不能上了，需要重启服务后，才能恢复访问外网

### ISSUE THREAD

**Issue by qinfeng8848** [koolshare/koolshare.github.io#837]
1.环境
rt-ac88u    firmware 380.69_2-x7.8
ss服务  使用rixcloud
2.故障现象
ss挂掉的时候，所有网不能上了，需要关一下ss服务再开

**Comment by Comah** [comment]
rixcloud 以前用过 太贵太差劲了 各种变相收费还经常各种断。后来没用了
