### ISSUE TITLE
如果能开发一个v2ray客户端就完美了

### ISSUE THREAD

**Issue by kennysoul** [koolshare/koolshare.github.io#839]
SSR估计很快就会被攻陷，也是时候增加一条路子了....

**Comment by maketa521** [comment]
v2r值得期待~

**Comment by wd** [comment]
我做了一个，希望对你们有帮助。 https://tinyurl.com/koosharev2ray

**Comment by sadoneli** [comment]
有做好但是没放出来，但是感觉对路由负担太大，有时候启动v2ray程序都是个问题，没虚拟内存简直没法玩

**Comment by wd** [comment]
是，基本上虚拟内存是必须的。要不会经常奔溃。

**Comment by kennysoul** [comment]
@wd 我拿台非主力设备试一下，谢谢！
