### ISSUE TITLE
请教一下如何在游戏模式下steam游戏更新不会走SS流量

### ISSUE THREAD

**Issue by luffy0224** [koolshare/koolshare.github.io#840]
上次没注意切换，吃鸡更新就走了SS的几个G流量，请教一下有什么办法能在不切换模式的前提下避免steam更新的时候走SS流量呢~？

**Comment by sadoneli** [comment]
steam下载设置里选中国的一些服务器就行

**Comment by Comah** [comment]
感觉游戏模式不怎样好用了 没有kP-GAME那个模式好
