### ISSUE TITLE
负载均衡启动之后需要重启SSR开关

### ISSUE THREAD

**Issue by Comah** [koolshare/koolshare.github.io#841]
不知道是我的个案问题还是都这样 负债均衡一直有点小问题 之前用不太稳定就没用了 直到今天看到更新了3.89修复负债均衡就测试了一下  启动负载均衡之后  进不去负载管理页面 重启路由之后 重启SSR才能正常  但断电关机再开之后又不行了。。

**Comment by sadoneli** [comment]
一直是这样设计的
提交设置后会开启haproxy，并在ss节点配置中增加一个服务器IP为127.0.0.1，端口为负载均衡服务器端口的帐号；
然后你需要手动选择并提交一次
