### ISSUE TITLE
如何自己开发插件

### ISSUE THREAD

**Issue by TonyYule** [koolshare/koolshare.github.io#842]

**Comment by sadoneli** [comment]
你可以参考本项目里的其它插件，或者本项目收录的插件：https://github.com/koolshare/koolshare.github.io/blob/acelan_softcenter_ui/softcenter/modules.json

**Comment by TonyYule** [comment]
那用什么编程语言开发的 有什么资料学习呢  我是Java程序猿

**Comment by sadoneli** [comment]
主要是shell和html

**Comment by TonyYule** [comment]
比如 我要开发一个插件 实现配置pac 文件 自动代理 该怎么做

**Comment by sadoneli** [comment]
是要实现pac的读取和生成还是pac的分流？
前者的话需要用C或者golang写好程序编译成路由器下能运行的程序来实现
后者据我了解是不能实现的

**Comment by TonyYule** [comment]
pac  我找到了这个 那我怎么编译 打包成插件呢
https://github.com/manugarg/pacparser

**Comment by sadoneli** [comment]
merlin固件的话使用这个工具链 https://github.com/RMerl/am-toolchains

新内核机器的话使用BCM-HND那个，老内核的机器使用BCM-SDK的工具链
编译根据你要编译项目的指南进行
因为merlin固件内很多库没有
所以建议你用全静态编译

具体到你这个项目的话，他是一个库，并不是可以直接用的，所以你还需要自己写你要的程序来调用这个库，然后用对应的工具链来编译

编译好得到二进制文件后，你需要写插件中心的web页面和对应的shell来操纵这个程序到达你要的目的

**Comment by sadoneli** [comment]
是否可以你可以自己编译后在路由器上测试，如果可以达到你的目的，再考虑写插件相关的web界面和shell脚本等

**Comment by blademainer** [comment]
@sadoneli 请问使用go如何编译？我使用 env GOOS=linux GOARCH=arm go build 编译的报：
```shell
Illegal instruction
```
