### ISSUE TITLE
命令行下无法ping通google

### ISSUE THREAD

**Issue by numbqq** [koolshare/koolshare.github.io#843]
380.69_2-X7.8版本固件，网件R6400路由器，配置ss插件后，连上路由器，浏览器可以访问google，但是在命令行下却ping不通google，是不是还有什么需要配置呢？

**Comment by xlighting2017** [comment]
Ping 走的是 ICMP 协议，  ss不能处理ICMP的报文
为什么一定要可以 ping 才行呢?

**Comment by sadoneli** [comment]
要想ping通请用vpn方案
