### ISSUE TITLE
3.8.9大陆白名单无法youtube视频

### ISSUE THREAD

**Issue by Iamsoso** [koolshare/koolshare.github.io#847]
升到3.8.9，大陆白名单下可打开youtube页面，但视频无法打开，换成gfwlist却可以，求教

**Comment by Iamsoso** [comment]
回滚3.8.6后问题解决

**Comment by Comah** [comment]
没这个问题 但是这几个版本都用不了谷歌语音 其他都可以  白名单有漏域名
