### ISSUE TITLE
路由器间歇性无法访问国内网站

### ISSUE THREAD

**Issue by SakutaYo** [koolshare/koolshare.github.io#848]
3.8.6-3.8.9一路过来，以前的版本没用过不清楚
gfwlist和大陆白名单下，每隔一段时间（几小时不定），国内网络无法访问，国外网络一切正常。
参考过faq（4：国内Problem detected!，国外working：4.1：尝试更换国内DNS。）
无论怎么更换都不行，114，阿里，tx，open，都换过了   都不行。

对了，全局模式下没有问题！  求助

**Comment by Comah** [comment]
估计作者还在修改  DNS和白名单还有负债均衡都有问题

**Comment by SakutaYo** [comment]
吓死了，还以为就我这样，问了好多人都没搞定，差点刷回lede。

感谢大佬解答！

**Comment by kxjhcmc** [comment]
由于cdx.txt巨大，导致占用很多CPU资源，所以3.7.7以后的版本都有问题，因为取消了国内优先

**Comment by sadoneli** [comment]
目前除了chinadns1、2不加载cdn.txt外，为了保证较好的国内cdn，其它dns模式都要加载cdn.txt
