### ISSUE TITLE
AC66U-B1 380.69_2-X7.8固件下SS3.8.6以上版本无法运行

### ISSUE THREAD

**Issue by lockonzhao** [koolshare/koolshare.github.io#849]
如题，
AC66U-B1 380.69_2-X7.8固件下SS3.8.6以上版本无法运行，显示双working，但是无法翻墙，3.8.6版本只能使用大陆白名单模式

**Comment by xxpasser** [comment]
怎样停止订阅该邮件？？？？

在 2018-04-29 12:49:07，"sadoneli" <notifications@github.com> 写道：


Closed #849.
