### ISSUE TITLE
R7000上3.8.9有问题啊！

### ISSUE THREAD

**Issue by andyzeng0410** [koolshare/koolshare.github.io#851]
网件R7000，固件版本7.8，插件更新到3.8.9之后，gfwlist模式国内外连接均无法连接，电脑无法浏览网页，但是QQ正常使用。手机上网正常，但是无法科学上网。全局模式国内正常，国外无法连接。经手机VPN和电脑端SSR软件验证服务器没有问题。

**Comment by Nidhoggur1993** [comment]
+1
固件7.4，插件3.8.9，国外不管怎么切都是无法访问，但是用正常的ss客户端，一样的配置是可以的
@sadoneli
