### ISSUE TITLE
RT-AC66U-B1最新版 科学上网 插件 重启后不会自动翻 需要保存dns设置才行

### ISSUE THREAD

**Issue by xz127** [koolshare/koolshare.github.io#852]

**Comment by xz127** [comment]
Enable JFFS custom scripts and configs 开着的

**Comment by xz127** [comment]
哪个版本的科学上网插件比较稳定啊？？

**Comment by sadoneli** [comment]
一般路由重启完毕，连上网后，ss插件还要等一会儿才会启动
有时候在路由器界面点击重启后，重启完毕网页会自动加载进路由界面管理，这个时候可能插件还没起来的
建议重启完毕等2min后再进插件看看
