### ISSUE TITLE
安装插件的时候清理旧版本的时候太暴力了

### ISSUE THREAD

**Issue by wd** [koolshare/koolshare.github.io#853]
https://github.com/koolshare/koolshare.github.io/blob/acelan_softcenter_ui/shadowsocks/shadowsocks/install.sh#L112

这样 `/koolshare/ss/postscripts/` 下面的脚本也会被清理掉。

**Comment by sadoneli** [comment]
确实是，其实这里可以用覆盖的，下个版本我改下这里
建议/koolshare/ss/postscripts/下放你自己脚本的软连接
