### ISSUE TITLE
请问SSServer为何开启了使用SS网络依然不能FQ?

### ISSUE THREAD

**Issue by GreatMichaelFu** [koolshare/koolshare.github.io#854]
top是这样的，R8500 梅林x7.8, 自己离线装了3.8.9 SS, GFW模式一切正常，然后软件中心装了SSServer, 因为我的目的想从公网通过一个vpn既能连到路由器上能实现访问家庭内网和直接FQ的目的（我同时还装了SoftEther,连上L2VPN倒路由器内网后，访问局域网和FQ都没问题，但三星卓手机很变态，上不能一直保持在线，经常掉，要一直在线得用数字服务器地址和DNS很不爽（电信48小时换IP，你懂得，所以只能用ddns域名）, 还是想用安卓客户端的SS,可以有选项一直保持在线），SS安卓客户端连上后（客户端勾选全局模式和DNS选择转发），访问内网和国内公网都没问题，就是不能FQ,哪怕我开启了“使用SS网络”，（这一项我看了脚本就是添加了iptables的 match gfwlist那个redirect chain），好像也不行不work啊？谁能指导一下应该怎么搞吗？我感觉是转发表的问题，请大侠指导一下啊。论坛不让讨论，只能这里求助了，坛子里那些帖子直接加转发表的，加了后勉勉强强可以FQ但是访问内网又不行了，不好使啊。

**Comment by GreatMichaelFu** [comment]
ssserver.sh里启用ss网络对应的函数如下：

write_output(){                                                                                                                                   
        ss_enable=`dbus get ss_basic_enable`                                                                                                      
        if [ "$ssserver_use_ss" == "1" ] && [ "$ss_enable" == "1" ];then                                                                          
                if [ ! -L "/jffs/configs/dnsmasq.d/gfwlist.conf" ];then                                                                           
                        echo link gfwlist.conf                                                                                                    
                        ln -sf /koolshare/ss/rules/gfwlist.conf /jffs/configs/dnsmasq.d/gfwlist.conf                                              
                fi                                                                                                                                
                service restart_dnsmasq                                                                                                           
                **iptables -t nat -A OUTPUT -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-ports 3333**                                       
        fi                                                                                                 
}     

加粗的这个就是插iptable转发的，但好像不work啊

**Comment by Comah** [comment]
ss-server已经被Q得无法使用了  希望能添加ssrr-server吧

**Comment by sadoneli** [comment]
ssrr的话不太好弄，因为依赖python，而路由固件系统是没有这个组件的，一个办法就是静态编译python，但是静态编译的python在arm下问题多多，且占用空间巨大

建议你自己安装entware，使用entware环境安装python，然后部署ssrr-server

**Comment by GreatMichaelFu** [comment]
是墙的原因么？怎么我感觉是iptables的原因呢，因为我稍微加下REDIRECT的规则，就能FQ啊，但是加了之后访问内网就不行了，感觉是那个match-set不work.

**Comment by mbinge** [comment]
有结论么？
