### ISSUE TITLE
1900P 国内外是成功就是。就是无法FQ.求助啊

### ISSUE THREAD

**Issue by neverxuan** [koolshare/koolshare.github.io#855]
之气那1900P一直用68U的7.5固件的。突然一天翻不了就更新3.8.9还是不行。现在用7.8的还是不行。
状态是国内外都成功，谷歌网站那一栏没有IP。
求大大解决啊。

**Comment by gwq031** [comment]
应该是版本的问题，之前一直用3.8.4，但是每隔一段时间就断开了。然后更新版本时也更新，最后到3.8.9翻不了了，卸载重装3.8.4好了
