### ISSUE TITLE
version 文件里面的校验码是什么算法？

### ISSUE THREAD

**Issue by vobasf** [koolshare/koolshare.github.io#856]
version 文件里面的校验码是什么算法？

**Comment by sadoneli** [comment]
MD5

**Comment by vobasf** [comment]
有一些MD5不匹配，比如shadowsocks_3.8.0.tar.gz，MD5算出来是6631BDAEF201334A2FF58743F6501FA6，version文件里对应的MD5是7983772139ebf858d1a8f4e549beb196，请问能否检查一下？

**Comment by sadoneli** [comment]
包是没问题的，可能是当时打包后没有写入md5的原因
