### ISSUE TITLE
报错 /koolshare/ss/ssconfig.sh: line 551: syntax error: unexpected end of file (expecting "fi")

### ISSUE THREAD

**Issue by JiawenXiong** [koolshare/koolshare.github.io#858]
启动报错
/koolshare/ss/ssconfig.sh: line 551: syntax error: unexpected end of file (expecting "fi")

**Comment by JiawenXiong** [comment]
修改 /koolshare/ss/ssconfig.sh 文件，最后加上 fi }

**Comment by sadoneli** [comment]
什么版本啊，没发现这个地方有问题啊？
