### ISSUE TITLE
捐赠

### ISSUE THREAD

**Issue by pk2006** [koolshare/koolshare.github.io#86]
各位大大辛苦了，固件很好用，谢谢！
![qq 20160512155343](https://cloud.githubusercontent.com/assets/19322175/15207582/b51606a2-1859-11e6-8dd9-af0af33f0d2c.png)

**Comment by sadoneli** [comment]
多谢支持，我们会努力做得更好

**Comment by jannson** [comment]
捐献已经可以自动生成名单： http://c.koolshare.io
如果想修改名字情告知。
