### ISSUE TITLE
能否在SS默认模式里增加一个不使用SS的选项？

### ISSUE THREAD

**Issue by huaxianyan** [koolshare/koolshare.github.io#861]
原意是让设备默认不走SS，通过设备控制让指定设备走

**Comment by sadoneli** [comment]
请使用访问控制功能实现
![image](https://user-images.githubusercontent.com/10495520/39140611-ae559e70-4757-11e8-8363-bee369610e0b.png)

**Comment by huaxianyan** [comment]
原来添加了一个就可以修改默认的，感谢

可以close了
