### ISSUE TITLE
梅林SS开始游戏模式后，PS4 NAT类型检测失败，但PC上访问ip正常

### ISSUE THREAD

**Issue by 1095225882** [koolshare/koolshare.github.io#864]
梅林SS开始游戏模式后，PS4 NAT类型检测失败，但PC上访问ip正常。如果使用其他模式，PS4网络NAT2，但是检测ip是在国内本地。是不是udp设置问题？或者vps没有开启udp？求解决方法

**Comment by Se7enMuting** [comment]
NAT失败基本上就是udp被block了，可能你服务器问题，可能你当地运营商的封锁~~

**Comment by 1095225882** [comment]
升级3.9.1后恢复正常
