### ISSUE TITLE
DNS设定中，可否加入对Cloudflare的1.1.1.1和1.0.0.1的支持？

### ISSUE THREAD

**Issue by Mashiromelody** [koolshare/koolshare.github.io#865]
关闭插件，可以正常使用1.1.1.1 1.0.0.1 。  
打开插件，在国外  chinadns1/chinadns2 中填入1.1.1.1 或 1.0.0.1，国外连接就GG。过一段时间国内也会GG。
所以能否添加对cloudflare public dns的支持，或让chromecast的开关回归？

**Comment by sadoneli** [comment]
1.1.1.1被很多学校机构等用作内网认证管理地址，很多环境下不能使用
chromecast（dns劫持功能）默认是开启的
