### ISSUE TITLE
shadowsocks 3.9.1 gfwlist模式下，youtube客户端不能使用

### ISSUE THREAD

**Issue by zacario-li** [koolshare/koolshare.github.io#868]
shadowsocks 3.9.1 gfwlist模式下，youtube客户端不能使用，设置成全局后，就可以使用了，请问能否加入youtube客户端的地址？

**Comment by cjj7227** [comment]
我这没问题

**Comment by Iamsoso** [comment]
我也是，华硕AU68固件7.5，3.9.0后youtube就不正常了，目前回滚停滞在3.8.7

**Comment by zacario-li** [comment]
我昨天更碰到奇怪的问题，我的 华硕AC88U，固件7.7，更新了 ss 3.9.1 后，断电重启后，路由器的Wi-Fi就再也连不上了，只能reset，重新设置一遍。今天我装了ss 3.8.0，就不会这样，然后我刚升级了3.9.2，好像还没碰到问题，youtube的客户端什么的，都可以用了。我待会儿再折腾试试。

**Comment by zacario-li** [comment]
更新了3.9.2的ss，发现重启AC88U，我的wifi又连不上了，又要reset了，天呐。
