### ISSUE TITLE
各位朋友看看是什么情况  无法更新 3.9.1

### ISSUE THREAD

**Issue by zixinpengzong666** [koolshare/koolshare.github.io#869]
![20180428085045](https://user-images.githubusercontent.com/38799931/39390014-3fe1160a-4ac1-11e8-98a7-a923ba26bb45.jpg)

**Comment by sadoneli** [comment]
https://github.com/koolshare/koolshare.github.io/blob/acelan_softcenter_ui/shadowsocks/shadowsocks/install.sh#L14-L19
