### ISSUE TITLE
捐赠

### ISSUE THREAD

**Issue by qqzpjpp** [koolshare/koolshare.github.io#87]
聊表心意，加油~~qqzpjpp，66.66
E20160512163139063381470

**Comment by sadoneli** [comment]
http://c.koolshare.io/
已添加

**Comment by qqzpjpp** [comment]
重复，我就是下面那个面子，而且是66.66，保留这个吧，不保留面子啦，谢谢


发自 网易邮箱大师
在2016年05月12日 19:02，sadoneli 写道:

http://c.koolshare.io/
已添加

**Comment by sadoneli** [comment]
不好意思弄错了，这就改过来先，保留论坛ID这个名字是吧

**Comment by qqzpjpp** [comment]
yes，谢啦


发自 网易邮箱大师
在2016年05月12日 19:06，sadoneli 写道:

不好意思弄错了，这就改过来先，保留论坛ID这个名字是吧

**Comment by sadoneli** [comment]
好了你看看
