### ISSUE TITLE
flock: Bad file descriptor

### ISSUE THREAD

**Issue by whspider** [koolshare/koolshare.github.io#871]
【2018年04月28日 10:19:29】: 更新过程中请不要做奇怪的事，不然可能导致问题！
【2018年04月28日 10:19:29】: 开启SS检查更新：使用主服务器：https://raw.githubusercontent.com/koolshare/koolshare.github.io/acelan_softcenter_ui/shadowsocks...
【2018年04月28日 10:19:29】: 检测主服务器在线版本号...
【2018年04月28日 10:19:31】: 检测到主服务器在线版本号：3.9.1
【2018年04月28日 10:19:31】: 主服务器在线版本号：3.9.1 和本地版本号：3.9.1 相同！
【2018年04月28日 10:19:31】: 那还更新个毛啊，关闭更新进程!
flock: Bad file descriptor

**Comment by sadoneli** [comment]
暂时不影响使用，这个报错后窗口不会自动关闭，请手动关闭
待修

**Comment by sadoneli** [comment]
fixed
