### ISSUE TITLE
3.9.1版本都是working，清除并刷新了dns，清除了hosts依旧上不了google等网站

### ISSUE THREAD

**Issue by destroy3919** [koolshare/koolshare.github.io#872]
![image](https://user-images.githubusercontent.com/16571646/39391712-91225ef2-4ada-11e8-891b-7010278c8920.png)

自从3.8.7之后的版本就这样了，一直不敢升级，也不知道问题出在什么地方。

**Comment by sadoneli** [comment]
不能上是怎么提示的，是dns无法解析还是其它？

**Comment by destroy3919** [comment]
![image](https://user-images.githubusercontent.com/16571646/39391764-3ed14388-4adb-11e8-9fdb-994391f9cf8c.png)
有时候是无法访问，有时候是隐私错误，也不知道要怎么出来，旧版本不会这样的

**Comment by sadoneli** [comment]
这个应该是dns污染，你是不是在路由器的Advanced_DHCP_Content.asp页面定义了什么dns之类的？

**Comment by destroy3919** [comment]
那个页面的DNS也清除过了，还是会出现隐私错误。

**Comment by sadoneli** [comment]
尝试更换国外dns，看是否能解决污染

**Comment by destroy3919** [comment]
谢谢！国外dns更换到tunnel解决了，看来这污染挺严重的。
