### ISSUE TITLE
梅林固件，最近科学上网插件3.9.1，国外连接一直会断，一会儿又连上。。。

### ISSUE THREAD

**Issue by fancygg802** [koolshare/koolshare.github.io#873]
大概最近一个月所有版本都是这个样子，一会儿断，一会儿又连接上。。但是windows客户端上，一切正常。。路由器是R8500和AC68u，都一样。宽带是移动和电信宽带，都试过。。。有一样的问题的么？

**Comment by sadoneli** [comment]
你可以windows客户端每隔5秒检测一次，看是否一会儿断一会好

**Comment by fancygg802** [comment]
win客户端就是5秒检测一次啊~~一直很稳定~~

**Comment by cngzsunny** [comment]
我也是这样，升到3.9.1之后，就看到国外连接就是不断的从叉到勾，又从勾到叉的状态
