### ISSUE TITLE
R6300V2，梅林KS X7.8，SS版本3.9.1，xchacha20-ietf-poly1305加密，双working，无法访问被墙网站

### ISSUE THREAD

**Issue by DesperadoJ** [koolshare/koolshare.github.io#874]
已排查DNS和HOSTS的问题，更换其他加密方式均可成功翻墙；xchacha20-ietf-poly1305加密下显示双working，但是无法访问被墙网站。使用手机或者PC代理，可访问访问被墙网站

**Comment by sadoneli** [comment]
不能上是怎么提示的，是dns无法解析还是超时，还是出现隐私错误？

**Comment by DesperadoJ** [comment]
超时。路由重启后问题没有复现，谢谢
