### ISSUE TITLE
本插件适用于koolshare merlin armv7l固件平台，你的平台不能安装！！！

### ISSUE THREAD

**Issue by ccinoo** [koolshare/koolshare.github.io#875]
杯具~~请问shadowsocks后续会支持7.2和7.8的吗？
我升级插件报错如下：
本插件适用于koolshare merlin armv7l固件平台，你的平台不能安装！！！

**Comment by baronv5** [comment]
出现同样错误，目前3.8.9版本。旧版本升级到3.8.9后，shadowsocks无法翻墙。

**Comment by ccinoo** [comment]
admin@R7000:/tmp/home/root# uname -m
armv7l

查到是 armv7l固件平台啊，怎么报错说不是那？大家遇到这个问题了吗？

**Comment by Monago** [comment]
R7000 梅林7.2 遇到同样问题 杯具了 请大神们看看这个问题吧

**Comment by sadoneli** [comment]
https://github.com/koolshare/koolshare.github.io/blob/acelan_softcenter_ui/shadowsocks/shadowsocks/install.sh#L14-L19

请检查下

**Comment by sadoneli** [comment]
路由器下运行`uname -o` 看看打印的结果内是否包含Merlin
另外运行`ls /koolsahre`，看看是否路由器下有koolshare目录
目前是基于这两个来判断koolshare merlin改版固件的

**Comment by Aisuko** [comment]
那目前不符合这个条件的固件就只能保持原版插件了吗？

**Comment by sadoneli** [comment]
@Aisuko 你是什么机器什么固件？另外你运行上面两个命令的打印信息是什么

**Comment by Aisuko** [comment]
Hi, @sadoneli ,感谢回复，我已经升级到[最新的固件](http://koolshare.cn/forum.php?mod=viewthread&tid=133874&extra=page%3D1%26filter%3Dtypeid%26typeid%3D68)了，之前`不符合版本`这个没有问题了，更新最新版ss，也解决了内网不工作的问题，非常感谢。

**Comment by mydaley** [comment]
@Aisuko 请问您是如何解决的啊，我也同样的问题~

**Comment by Aisuko** [comment]
@mydaley 把固件版本刷到最高，最新版固件地址看我回复Sadoneli的内容，或者去论坛找最新版
