### ISSUE TITLE
版本号无法更新

### ISSUE THREAD

**Issue by eroneko** [koolshare/koolshare.github.io#876]
从 3.8.4 更新到 3.9.2 时不管怎么重复版本号都停在 3.8.4 没有变化，日志输出的都是安装成功。后卸载了 ss，重新离线安装后版本号变成了 3.3.6，同样怎么更新都停在 3.3.6 不变，日志输出的是更改版本号为 3.9.2 成功

**Comment by sadoneli** [comment]
请打开插件更新才能写入版本后
或者关闭插件更新后重新提交，也能写入版本号
