### ISSUE TITLE
梅林RT-AC3100 380.69_2-X7.8

### ISSUE THREAD

**Issue by 474364707** [koolshare/koolshare.github.io#878]
请问下列日志 该怎么处理
Apr 29 00:10:52 rss-redir[18609]: server recv: Connection reset by peer
Apr 29 00:10:52 rss-redir[18609]: server recv: Connection reset by peer
Apr 29 00:11:21 rss-redir[18609]: server recv: Connection reset by peer
Apr 29 00:41:17 rss-redir[18609]: server recv: Connection reset by peer
Apr 29 00:41:17 rss-redir[18609]: server recv: Connection reset by peer
Apr 29 00:41:17 rss-redir[18609]: server recv: Connection reset by peer
Apr 29 01:11:00 rss-redir[18609]: server recv: Connection reset by peer
Apr 29 01:11:00 rss-redir[18609]: server recv: Connection reset by peer
Apr 29 01:11:00 rss-redir[18609]: server recv: Connection reset by peer
Apr 29 01:41:17 rss-redir[18609]: server recv: Connection reset by peer
Apr 29 01:41:17 rss-redir[18609]: server recv: Connection reset by peer
Apr 29 01:41:17 rss-redir[18609]: server recv: Connection reset by peer
Apr 29 02:11:00 rss-redir[18609]: server recv: Connection reset by peer
Apr 29 02:11:00 rss-redir[18609]: server recv: Connection reset by peer
Apr 29 02:11:00 rss-redir[18609]: server recv: Connection reset by peer
Apr 29 02:41:17 rss-redir[18609]: server recv: Connection reset by peer
Apr 29 02:41:17 rss-redir[18609]: server recv: Connection reset by peer
Apr 29 02:41:17 rss-redir[18609]: server recv: Connection reset by peer

**Comment by sadoneli** [comment]
更换更好的线路，或者弄国内中转，
另外此日志应该向shadowsocks-libev作者反馈
