### ISSUE TITLE
3.8.9版及更新版google系网站都有问题

### ISSUE THREAD

**Issue by Roger0822** [koolshare/koolshare.github.io#879]
路由型号：R7000
固件版本：x7.8
插件名称：SS
插件版本：3.89及最新版（现在是3.9.3）

问题描述：更新后双working。但google系网站都无法打开。chrome报不安全的网站。退回3.8.3后正常。

**Comment by ghkghkghk** [comment]
3.9.1-3.9.3使用一切正常，双勾，所有访问一切正常。如果你的不正常，尝试：
1. 清除PC系统DNS后再次访问；
2. 更换插件中的国内外DNS设置后再次尝试。

**Comment by LinusDropTips** [comment]
路由型号：R7000
固件版本：x7.8
插件名称：SS
插件版本：3.89及最新版（现在是3.9.3）
问题描述：出现和楼上差不多的状况，清除DNS无效，更改DNS设置无效，电脑可以访问google台湾但是Google和youtube就会显示超时。手机端的YouTube可以加载评论图片，但无法播放视频，Google商店可以正常使用。

**Comment by sadoneli** [comment]
出现报证书问题和超时一般是dns污染造成的，建议更换插件内国外dns，然后清空浏览器和电脑dns缓存再尝试以下

另外，可以运行命令，```cat /etc/dnsmasq.con```，然后把内容贴上来看看

**Comment by sadoneli** [comment]
现在gfw的污染，有时偶会吧谷歌解析到facebook上，把twitter解析到谷歌上之类的，遇到这种情况就会出现chrome报证书安全问题，之前也看过很多例子，所以确定这就是dns污染。

**Comment by sadoneli** [comment]
确实有个别朋友有这个问题，我只能想到的地方
1 局域网是否有机器自定义了dns服务器？（按理说插件开了dns劫持应该问题不在这里）
2 是否在电脑上设置过一些翻墙等host？
3 是否启用了koolproxy插件的ipset模式？
4 是否在路由器的局域网设置 - dhcp设置中自定义了dns服务器？

**Comment by smileawei** [comment]
从3.8.9后就有这个问题，目前退到3.8.7 没问题

**Comment by ghkghkghk** [comment]
路由器：WS880、斐讯K3
系统：梅林 7.8
插件名称：SS
版本：3.9.3-3.9.5
问题：出现了新问题，不定期不能上网，检查后发现，梅林的DHCP功能失效，检验后，若未装SS，运行正常，安装后，不知何原因可能导致问题。

**Comment by LinusDropTips** [comment]
r7000貌似找到解决方法了，本人在3.9.6版本通过双开路由器和手机客户端使用一段时间后关闭手机端，路由器端居然恢复正常了。
