### ISSUE TITLE
可否让v2忽略虚拟内存？比如提示一下，无虚拟内存也可运行？

### ISSUE THREAD

**Issue by fengyeblade** [koolshare/koolshare.github.io#880]
提交issue请先回答以下问题，以便我们更快的找到问题，多谢配合（本行和以下括号内的内容可以删除）~
  R6300V2 最新固件7.8  SS 3.93

现在是强制必须有虚拟内存才可使用。
但是很多人的v2服务端和客户端都已经进行了优化，内存开销应该很小。 
路由器不安装很多插件的情况下，256内存应该是很足够的。 
可否让v2Ray 不强制检测虚拟内存？ 仅仅提示一下，对于轻量使用的用户，没必要非要使用虚拟内存吧。

谢谢

**Comment by sadoneli** [comment]
v2ray开销很大的，512以下都是强制需要的，你可以在ssh里运行top或者htop，能看到v2ray申请的虚拟内存大小，我这里是780M，虽然实际上用不到这么多，但是这里经常会导致进程起不来或者崩掉。
另外就是速度跑起来的时候，也是很大开销

不需要的话建议个人注释掉 https://github.com/koolshare/koolshare.github.io/blob/acelan_softcenter_ui/shadowsocks/shadowsocks/ss/ssconfig.sh#L1335 这一行使用，但是并不建议

**Comment by fengyeblade** [comment]
好吧，谢谢解答。看来是启动新线程瞬时需要大内存？
