### ISSUE TITLE
dns解析出错

### ISSUE THREAD

**Issue by icetea0822** [koolshare/koolshare.github.io#881]
提交issue请先回答以下问题，以便我们更快的找到问题，多谢配合（本行和以下括号内的内容可以删除）~

##### 问题描述：个别国内网站打不开，或需要打开两次才能打开，有些app如微博中的图片加载不出来，需要再次点击才可以，大部分错误都是在访问国内网站时出现。昨天晚上微博app直接无法刷新，家里所有移动设备的微博app都是这个情况，但pc端网页访问没有问题。
  请问是否是dns出现问题，尝试过更换国内国外dns，还是不行。

插件设置：白名单模式，国内dns使用运营商dns，国外使用chinadns1。

**Comment by sadoneli** [comment]
是否开启了koolproxy之类的广告过滤插件啊

**Comment by icetea0822** [comment]
没有啊 只开启了科学上网和ddnsto 而且ddnsto经常也连接不到后台 后来就给关了 也不行

**Comment by sadoneli** [comment]
ddnsto可能 是因为服务器迁移到国外的原因导致不稳吧

dns问题的话是否关闭科学上网插件后就没了？

**Comment by sadoneli** [comment]
请测试3.9.6是否有该问题

**Comment by icetea0822** [comment]
关掉插件后就没有问题了。
正在测试3.9.6版本。
另，最近打开服务时日志总会写着：
尝试解析ss服务器的ip地址失败，将由ss-redir自己解析。这个提示之前是没有的 ，用自己电脑的nslookup命令也是能够解析的。

**Comment by sadoneli** [comment]
如果那样建议你填ip吧

**Comment by sadoneli** [comment]
https://github.com/koolshare/koolshare.github.io/issues/886
