### ISSUE TITLE
3.9.1开始，华硕AC87R无法升级、安装ss插件

### ISSUE THREAD

**Issue by zhaoxg1980** [koolshare/koolshare.github.io#883]
##### 问题描述：无论是自动升级、web页离线安装、ssh安装都无法安装，提示：
2018-04-30 18:14:07 (665 KB/s) - 'shadowsocks.tar.gz' saved [11244124/11244124]

【2018年04月30日 18:14:07】: 更新包md5校验一致！ 开始安装！...
【2018年04月30日 18:14:07】: 开始解压压缩包...
【2018年04月30日 18:14:09】: 开始安装更新文件...
【2018年04月30日 18:14:09】: 本插件适用于koolshare merlin armv7l固件平台，你的平台不能安装！！！

##### 插件运行日志：
【2018年04月30日 18:13:47】: 更新过程中请不要做奇怪的事，不然可能导致问题！
【2018年04月30日 18:13:47】: 开启SS检查更新：使用主服务器：https://raw.githubusercontent.com/koolshare/koolshare.github.io/acelan_softcenter_ui/shadowsocks...
【2018年04月30日 18:13:47】: 检测主服务器在线版本号...
【2018年04月30日 18:13:49】: 检测到主服务器在线版本号：3.9.4
【2018年04月30日 18:13:49】: 主服务器在线版本号：3.9.4 和本地版本号：3.8.8 不同！
【2018年04月30日 18:13:50】: 开启下载进程，从主服务器上下载更新包...
--2018-04-30 18:13:50--  https://raw.githubusercontent.com/koolshare/koolshare.github.io/acelan_softcenter_ui/shadowsocks/shadowsocks.tar.gz
Resolving raw.githubusercontent.com... 151.101.76.133
Connecting to raw.githubusercontent.com|151.101.76.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11244124 (11M) [application/octet-stream]
Saving to: 'shadowsocks.tar.gz'

     0K .......... .......... .......... .......... ..........  0%  265K 41s
    50K .......... .......... .......... .......... ..........  0% 1.03M 26s
   100K .......... .......... .......... .......... ..........  1%  519K 24s
   150K .......... .......... .......... .......... ..........  1%  805K 21s
   200K .......... .......... .......... .......... ..........  2%  562K 21s
   250K .......... .......... .......... .......... ..........  2%  932K 19s
   300K .......... .......... .......... .......... ..........  3%  609K 19s
   350K .......... .......... .......... .......... ..........  3%  515K 19s
   400K .......... .......... .......... .......... ..........  4%  515K 19s
   450K .......... .......... .......... .......... ..........  4% 1.00M 18s
   500K .......... .......... .......... .......... ..........  5%  495K 18s
   550K .......... .......... .......... .......... ..........  5% 1.20M 17s
   600K .......... .......... .......... .......... ..........  5%  528K 17s
   650K .......... .......... .......... .......... ..........  6% 1.01M 17s
   700K .......... .......... .......... .......... ..........  6%  548K 17s
   750K .......... .......... .......... .......... ..........  7% 1.02M 16s
   800K .......... .......... .......... .......... ..........  7%  548K 16s
   850K .......... .......... .......... .......... ..........  8%  552K 16s
   900K .......... .......... .......... .......... ..........  8% 1018K 16s
   950K .......... .......... .......... .......... ..........  9%  549K 16s
  1000K .......... .......... .......... .......... ..........  9% 1.00M 16s
  1050K .......... .......... .......... .......... .......... 10%  554K 16s
  1100K .......... .......... .......... .......... .......... 10%  993K 15s
  1150K .......... .......... .......... .......... .......... 10%  549K 15s
  1200K .......... .......... .......... .......... .......... 11%  520K 15s
  1250K .......... .......... .......... .......... .......... 11% 1018K 15s
  1300K .......... .......... .......... .......... .......... 12%  542K 15s
  1350K .......... .......... .......... .......... .......... 12% 1012K 15s
  1400K .......... .......... .......... .......... .......... 13%  551K 15s
  1450K .......... .......... .......... .......... .......... 13%  973K 15s
  1500K .......... .......... .......... .......... .......... 14%  528K 15s
  1550K .......... .......... .......... .......... .......... 14% 1.04M 14s
  1600K .......... .......... .......... .......... .......... 15%  526K 14s
  1650K .......... .......... .......... .......... .......... 15%  552K 14s
  1700K .......... .......... .......... .......... .......... 15%  946K 14s
  1750K .......... .......... .......... .......... .......... 16%  562K 14s
  1800K .......... .......... .......... .......... .......... 16% 1001K 14s
  1850K .......... .......... .......... .......... .......... 17%  535K 14s
  1900K .......... .......... .......... .......... .......... 17%  996K 14s
  1950K .......... .......... .......... .......... .......... 18%  540K 14s
  2000K .......... .......... .......... .......... .......... 18%  541K 14s
  2050K .......... .......... .......... .......... .......... 19% 1011K 14s
  2100K .......... .......... .......... .......... .......... 19%  547K 14s
  2150K .......... .......... .......... .......... .......... 20% 1.01M 13s
  2200K .......... .......... .......... .......... .......... 20%  542K 13s
  2250K .......... .......... .......... .......... .......... 20% 1.04M 13s
  2300K .......... .......... .......... .......... .......... 21%  524K 13s
  2350K .......... .......... .......... .......... .......... 21% 1.03M 13s
  2400K .......... .......... .......... .......... .......... 22%  541K 13s
  2450K .......... .......... .......... .......... .......... 22%  534K 13s
  2500K .......... .......... .......... .......... .......... 23%  538K 13s
  2550K .......... .......... .......... .......... .......... 23% 1.01M 13s
  2600K .......... .......... .......... .......... .......... 24%  539K 13s
  2650K .......... .......... .......... .......... .......... 24% 1.03M 13s
  2700K .......... .......... .......... .......... .......... 25%  559K 13s
  2750K .......... .......... .......... .......... .......... 25%  996K 12s
  2800K .......... .......... .......... .......... .......... 25%  539K 12s
  2850K .......... .......... .......... .......... .......... 26%  542K 12s
  2900K .......... .......... .......... .......... .......... 26% 1.04M 12s
  2950K .......... .......... .......... .......... .......... 27%  537K 12s
  3000K .......... .......... .......... .......... .......... 27%  937K 12s
  3050K .......... .......... .......... .......... .......... 28%  538K 12s
  3100K .......... .......... .......... .......... .......... 28%  991K 12s
  3150K .......... .......... .......... .......... .......... 29%  536K 12s
  3200K .......... .......... .......... .......... .......... 29%  535K 12s
  3250K .......... .......... .......... .......... .......... 30%  965K 12s
  3300K .......... .......... .......... .......... .......... 30%  567K 12s
  3350K .......... .......... .......... .......... .......... 30%  855K 11s
  3400K .......... .......... .......... .......... .......... 31%  551K 11s
  3450K .......... .......... .......... .......... .......... 31% 1.07M 11s
  3500K .......... .......... .......... .......... .......... 32%  530K 11s
  3550K .......... .......... .......... .......... .......... 32% 1001K 11s
  3600K .......... .......... .......... .......... .......... 33%  494K 11s
  3650K .......... .......... .......... .......... .......... 33%  539K 11s
  3700K .......... .......... .......... .......... .......... 34%  985K 11s
  3750K .......... .......... .......... .......... .......... 34%  533K 11s
  3800K .......... .......... .......... .......... .......... 35%  959K 11s
  3850K .......... .......... .......... .......... .......... 35%  542K 11s
  3900K .......... .......... .......... .......... .......... 35% 1017K 11s
  3950K .......... .......... .......... .......... .......... 36%  542K 11s
  4000K .......... .......... .......... .......... .......... 36%  486K 11s
  4050K .......... .......... .......... .......... .......... 37%  960K 10s
  4100K .......... .......... .......... .......... .......... 37%  528K 10s
  4150K .......... .......... .......... .......... .......... 38% 1.05M 10s
  4200K .......... .......... .......... .......... .......... 38%  554K 10s
  4250K .......... .......... .......... .......... .......... 39% 1.01M 10s
  4300K .......... .......... .......... .......... .......... 39%  539K 10s
  4350K .......... .......... .......... .......... .......... 40% 1020K 10s
  4400K .......... .......... .......... .......... .......... 40%  545K 10s
  4450K .......... .......... .......... .......... .......... 40%  544K 10s
  4500K .......... .......... .......... .......... .......... 41%  542K 10s
  4550K .......... .......... .......... .......... .......... 41%  993K 10s
  4600K .......... .......... .......... .......... .......... 42%  547K 10s
  4650K .......... .......... .......... .......... .......... 42%  976K 9s
  4700K .......... .......... .......... .......... .......... 43%  536K 9s
  4750K .......... .......... .......... .......... .......... 43% 1.07M 9s
  4800K .......... .......... .......... .......... .......... 44%  519K 9s
  4850K .......... .......... .......... .......... .......... 44%  552K 9s
  4900K .......... .......... .......... .......... .......... 45%  994K 9s
  4950K .......... .......... .......... .......... .......... 45%  537K 9s
  5000K .......... .......... .......... .......... .......... 45%  962K 9s
  5050K .......... .......... .......... .......... .......... 46%  530K 9s
  5100K .......... .......... .......... .......... .......... 46%  866K 9s
  5150K .......... .......... .......... .......... .......... 47%  507K 9s
  5200K .......... .......... .......... .......... .......... 47%  519K 9s
  5250K .......... .......... .......... .......... .......... 48%  996K 9s
  5300K .......... .......... .......... .......... .......... 48%  551K 9s
  5350K .......... .......... .......... .......... .......... 49%  971K 8s
  5400K .......... .......... .......... .......... .......... 49%  530K 8s
  5450K .......... .......... .......... .......... .......... 50% 1.02M 8s
  5500K .......... .......... .......... .......... .......... 50%  549K 8s
  5550K .......... .......... .......... .......... .......... 50%  984K 8s
  5600K .......... .......... .......... .......... .......... 51%  528K 8s
  5650K .......... .......... .......... .......... .......... 51%  547K 8s
  5700K .......... .......... .......... .......... .......... 52% 1.02M 8s
  5750K .......... .......... .......... .......... .......... 52%  555K 8s
  5800K .......... .......... .......... .......... .......... 53%  988K 8s
  5850K .......... .......... .......... .......... .......... 53%  554K 8s
  5900K .......... .......... .......... .......... .......... 54%  935K 8s
  5950K .......... .......... .......... .......... .......... 54%  547K 8s
  6000K .......... .......... .......... .......... .......... 55%  509K 7s
  6050K .......... .......... .......... .......... .......... 55% 1.06M 7s
  6100K .......... .......... .......... .......... .......... 56%  531K 7s
  6150K .......... .......... .......... .......... .......... 56% 1000K 7s
  6200K .......... .......... .......... .......... .......... 56%  559K 7s
  6250K .......... .......... .......... .......... .......... 57%  975K 7s
  6300K .......... .......... .......... .......... .......... 57%  554K 7s
  6350K .......... .......... .......... .......... .......... 58% 1.01M 7s
  6400K .......... .......... .......... .......... .......... 58%  513K 7s
  6450K .......... .......... .......... .......... .......... 59%  536K 7s
  6500K .......... .......... .......... .......... .......... 59% 1.00M 7s
  6550K .......... .......... .......... .......... .......... 60%  530K 7s
  6600K .......... .......... .......... .......... .......... 60% 1.03M 7s
  6650K .......... .......... .......... .......... .......... 61%  547K 6s
  6700K .......... .......... .......... .......... .......... 61%  863K 6s
  6750K .......... .......... .......... .......... .......... 61%  571K 6s
  6800K .......... .......... .......... .......... .......... 62%  541K 6s
  6850K .......... .......... .......... .......... .......... 62%  944K 6s
  6900K .......... .......... .......... .......... .......... 63%  546K 6s
  6950K .......... .......... .......... .......... .......... 63% 1.00M 6s
  7000K .......... .......... .......... .......... .......... 64%  509K 6s
  7050K .......... .......... .......... .......... .......... 64%  826K 6s
  7100K .......... .......... .......... .......... .......... 65%  584K 6s
  7150K .......... .......... .......... .......... .......... 65%  911K 6s
  7200K .......... .......... .......... .......... .......... 66%  507K 6s
  7250K .......... .......... .......... .......... .......... 66%  563K 6s
  7300K .......... .......... .......... .......... .......... 66%  773K 5s
  7350K .......... .......... .......... .......... .......... 67%  567K 5s
  7400K .......... .......... .......... .......... .......... 67% 1.02M 5s
  7450K .......... .......... .......... .......... .......... 68%  532K 5s
  7500K .......... .......... .......... .......... .......... 68% 1.02M 5s
  7550K .......... .......... .......... .......... .......... 69%  536K 5s
  7600K .......... .......... .......... .......... .......... 69%  528K 5s
  7650K .......... .......... .......... .......... .......... 70%  530K 5s
  7700K .......... .......... .......... .......... .......... 70% 1.03M 5s
  7750K .......... .......... .......... .......... .......... 71%  525K 5s
  7800K .......... .......... .......... .......... .......... 71%  954K 5s
  7850K .......... .......... .......... .......... .......... 71%  538K 5s
  7900K .......... .......... .......... .......... .......... 72% 1.03M 5s
  7950K .......... .......... .......... .......... .......... 72%  559K 4s
  8000K .......... .......... .......... .......... .......... 73%  533K 4s
  8050K .......... .......... .......... .......... .......... 73% 1011K 4s
  8100K .......... .......... .......... .......... .......... 74%  545K 4s
  8150K .......... .......... .......... .......... .......... 74% 1015K 4s
  8200K .......... .......... .......... .......... .......... 75%  527K 4s
  8250K .......... .......... .......... .......... .......... 75% 1.04M 4s
  8300K .......... .......... .......... .......... .......... 76%  553K 4s
  8350K .......... .......... .......... .......... .......... 76%  995K 4s
  8400K .......... .......... .......... .......... .......... 76%  523K 4s
  8450K .......... .......... .......... .......... .......... 77%  538K 4s
  8500K .......... .......... .......... .......... .......... 77%  985K 4s
  8550K .......... .......... .......... .......... .......... 78%  553K 4s
  8600K .......... .......... .......... .......... .......... 78%  997K 4s
  8650K .......... .......... .......... .......... .......... 79%  545K 3s
  8700K .......... .......... .......... .......... .......... 79% 1.01M 3s
  8750K .......... .......... .......... .......... .......... 80%  533K 3s
  8800K .......... .......... .......... .......... .......... 80%  550K 3s
  8850K .......... .......... .......... .......... .......... 81%  999K 3s
  8900K .......... .......... .......... .......... .......... 81%  553K 3s
  8950K .......... .......... .......... .......... .......... 81% 1.01M 3s
  9000K .......... .......... .......... .......... .......... 82%  551K 3s
  9050K .......... .......... .......... .......... .......... 82% 1020K 3s
  9100K .......... .......... .......... .......... .......... 83%  544K 3s
  9150K .......... .......... .......... .......... .......... 83% 1.00M 3s
  9200K .......... .......... .......... .......... .......... 84%  538K 3s
  9250K .......... .......... .......... .......... .......... 84%  556K 3s
  9300K .......... .......... .......... .......... .......... 85% 1017K 2s
  9350K .......... .......... .......... .......... .......... 85%  559K 2s
  9400K .......... .......... .......... .......... .......... 86% 1015K 2s
  9450K .......... .......... .......... .......... .......... 86%  557K 2s
  9500K .......... .......... .......... .......... .......... 86% 1017K 2s
  9550K .......... .......... .......... .......... .......... 87%  561K 2s
  9600K .......... .......... .......... .......... .......... 87%  518K 2s
  9650K .......... .......... .......... .......... .......... 88% 1010K 2s
  9700K .......... .......... .......... .......... .......... 88%  560K 2s
  9750K .......... .......... .......... .......... .......... 89% 1.03M 2s
  9800K .......... .......... .......... .......... .......... 89%  548K 2s
  9850K .......... .......... .......... .......... .......... 90%  537K 2s
  9900K .......... .......... .......... .......... .......... 90% 1010K 2s
  9950K .......... .......... .......... .......... .......... 91%  462K 1s
 10000K .......... .......... .......... .......... .......... 91%  583K 1s
 10050K .......... .......... .......... .......... .......... 91%  807K 1s
 10100K .......... .......... .......... .......... .......... 92%  575K 1s
 10150K .......... .......... .......... .......... .......... 92%  787K 1s
 10200K .......... .......... .......... .......... .......... 93%  603K 1s
 10250K .......... .......... .......... .......... .......... 93% 1.01M 1s
 10300K .......... .......... .......... .......... .......... 94%  521K 1s
 10350K .......... .......... .......... .......... .......... 94%  966K 1s
 10400K .......... .......... .......... .......... .......... 95%  548K 1s
 10450K .......... .......... .......... .......... .......... 95%  549K 1s
 10500K .......... .......... .......... .......... .......... 96% 1.03M 1s
 10550K .......... .......... .......... .......... .......... 96%  533K 1s
 10600K .......... .......... .......... .......... .......... 96%  993K 0s
 10650K .......... .......... .......... .......... .......... 97%  526K 0s
 10700K .......... .......... .......... .......... .......... 97%  884K 0s
 10750K .......... .......... .......... .......... .......... 98%  553K 0s
 10800K .......... .......... .......... .......... .......... 98%  497K 0s
 10850K .......... .......... .......... .......... .......... 99%  875K 0s
 10900K .......... .......... .......... .......... .......... 99%  558K 0s
 10950K .......... .......... ..........                      100%  717K=17s

2018-04-30 18:14:07 (665 KB/s) - 'shadowsocks.tar.gz' saved [11244124/11244124]

【2018年04月30日 18:14:07】: 更新包md5校验一致！ 开始安装！...
【2018年04月30日 18:14:07】: 开始解压压缩包...
【2018年04月30日 18:14:09】: 开始安装更新文件...
【2018年04月30日 18:14:09】: 本插件适用于koolshare merlin armv7l固件平台，你的平台不能安装！！！

**Comment by xmoonxia** [comment]
华硕AC1900 更新从3.9.1-3.9.5开始同样出现这样的问题
提示本插件适用于koolshare merlin armv7l固件平台，你的平台不能安装！！！

**Comment by sadoneli** [comment]
@xmoonxia 固件什么版本

**Comment by sadoneli** [comment]
去除了安装限制 https://github.com/koolshare/koolshare.github.io/commit/17643f93801566d430500b5a4205aa8a38f7d90c
请更新到最新3.9.5试试
