### ISSUE TITLE
ss 出现这个错误提示：/koolshare/ss/ssconfig.sh: line 1940: can't create /var/lock/koolss.lock: nonexistent directory

### ISSUE THREAD

**Issue by master-walker** [koolshare/koolshare.github.io#884]
提交issue请先回答以下问题，以便我们更快的找到问题，多谢配合（本行和以下括号内的内容可以删除）~

**Comment by sadoneli** [comment]
1 重启试试，/var/lock 这个文件夹一般开机后就会有的，也许是你不小心给删掉了？因为他是挂在./tmp目录的，等同于/tmp/var/lock
2 试试 ```mkdir -p /tmp/var/lock```命令，然后重新运行插件试试

**Comment by master-walker** [comment]
升级到7.8版本，解决了。我没删过文件夹
