### ISSUE TITLE
3.9.5ss插件重启路由之后路由无法连接

### ISSUE THREAD

**Issue by RekiDunois** [koolshare/koolshare.github.io#885]
提交issue请先回答以下问题，以便我们更快的找到问题，多谢配合（本行和以下括号内的内容可以删除）~

**Comment by quin47** [comment]
r7000 同样的问题，ss更新后，重启后WiFi，有线皆无法连接，分配IP失败，只能重置系统，重启后正常，安装最新ss后问题复现。

**Comment by sadoneli** [comment]
能进入后先输入命令
```
cd /jffs/scripts
sh dnsmasq.postconf /etc/dnsmasq.conf
```
看看是否有任何报错

输入以下命令可以关闭ss：
```
cd /koolshare/ss/
dbus set ss_basic_enable=0
sh ssconfig.stop
```

**Comment by quin47** [comment]
启用 Enable JFFS custom scripts and configs后, 正常工作

**Comment by ghkghkghk** [comment]
同样的问题我也出现。
路由器：WS880、斐讯K3
系统：梅林 7.8
插件名称：SS
版本：3.9.5
问题：不能上网，DHCP失效。
