### ISSUE TITLE
回国模式下设置任何访问控制,其他设备都会变成全局模式

### ISSUE THREAD

**Issue by wsyccc** [koolshare/koolshare.github.io#887]
##### 插件设置截图：
![capture](https://user-images.githubusercontent.com/15988828/39481876-c832c1ae-4d21-11e8-96f4-5618101e2aca.PNG)

**Comment by sadoneli** [comment]
请提供下你【帐号设置】和【访问控制】里的设置截图

**Comment by wsyccc** [comment]
shadowsocks server 和 v2ray 都存在同样的问题的。
v2ray【帐号设置】
![default](https://user-images.githubusercontent.com/15988828/39507607-90a49c9a-4d93-11e8-92dd-b985df02f662.PNG)
shadowsocks 【帐号设置】
![2](https://user-images.githubusercontent.com/15988828/39507617-9a2ced08-4d93-11e8-8e81-24baff6fa34f.PNG)
【访问控制】设置
![1](https://user-images.githubusercontent.com/15988828/39507624-a330296a-4d93-11e8-8e2a-2aea8818fc7b.PNG)

**Comment by sadoneli** [comment]
https://github.com/koolshare/koolshare.github.io/commit/344b9bfb271fba3d3be182ab12a1cd89dba084d7

**Comment by sadoneli** [comment]
已经修了，等下次打包再看

**Comment by wsyccc** [comment]
好的 多谢！

**Comment by sadoneli** [comment]
更新3.9.8
