### ISSUE TITLE
油管上不去，其他都正常

### ISSUE THREAD

**Issue by ShawnCN77** [koolshare/koolshare.github.io#888]
你使用的路由器型号、固件版本?
 路由型号：ac68u
固件版本：x7.8

 插件名称：科学上网
插件版本：3.9.6

任何模式都不能上youtube，其他像ins，推特都能上的，就是youtube不行，清理了cookies，dns都不行，局域网其他电脑可以上，手机也能上youtube

**Comment by ShawnCN77** [comment]
确实是迅游pac的原因，大神！
是不是只要把那个打勾去掉就可以不用管他了？还是每次启动迅游以后他还会自动开启这个pc

**Comment by sadoneli** [comment]
去掉吧，会不会重新打勾我没确认过，但是不打勾迅游也是可以加速的
我就是因为这事儿放弃了迅游转了UU

**Comment by ShawnCN77** [comment]
应该是我昨天没有关掉加速直接关机的原因- -！
我用UU吃鸡太卡了，是不是通过SSR吃鸡没法解决延迟？我还特地自己搞了个VPS，延迟还是好严重

**Comment by sadoneli** [comment]
ssr不能用chiain_?协议，有延迟的
另外vps建议最好韩国的之类

**Comment by ShawnCN77** [comment]
韩国的VPS太贵了，核算下来还是加速器性价比高了，我架了个日本的，一点没改善，唉。。。
万分感谢了，兄弟
