### ISSUE TITLE
v2ray 问题

### ISSUE THREAD

**Issue by suntiny** [koolshare/koolshare.github.io#889]
提交issue请先回答以下问题，以便我们更快的找到问题，多谢配合（本行和以下括号内的内容可以删除）~

netgear 6400 380.69_2-X7.8
用s大的v2ray，设置好swap，再重新启动，但由于swap启动的慢，ss的v2ray总是不能自动启动，并且启动后，大概2分钟google各类服务才能使用。

**Comment by sadoneli** [comment]
1 确实性能有原因
2 为了节省jffs空间，我用了压缩后的v2ray程序，运行的时候程序有一个解压过程，可能会比telegram koolshare v2ray plugin群里的简易插件更加耗时这是肯定的，不过我测试R7000在1g虚拟内存下运行还是很好的，启动还是不慢得

你可以试试用非压缩的v2ray和v2ctl主程序

**Comment by suntiny** [comment]
大神，关于swap挂载，重启后没有，用usb3.0口和usb2.0口都不行，是虚拟内存插件有问题？

**Comment by suntiny** [comment]
swap问题拆腾了一早上，结果热插拔了一下U盘，路由器没有无线，只有重置了一回，不拆腾了，用ssr了，但是心里还是担心，被和谐了，之前一天换三个IP。

**Comment by sadoneli** [comment]
v2ray的话，因为swap加载在后面的，所以启动不起来了，另外BCM4708还是不建议v2ray了，太消耗性能
