### ISSUE TITLE
老版本SS不支持Shadowskcs Relay

### ISSUE THREAD

**Issue by malash** [koolshare/koolshare.github.io#89]
`Shadowsocks Relay`是利用`HA Proxy`中转`Shadowsocks`链接实现加速的，详见：
https://github.com/shadowsocks/shadowsocks/wiki/Setup-a-Shadowsocks-relay#better-version

使用1.4.7版的时候支持Relay，但1.4.8就不支持了，看了下Changelog应该和`shadowsocks-libev`版本有关：
https://github.com/koolshare/koolshare.github.io/blob/master/shadowsocks/Changelog.txt#L29-L32

所以还是希望能使用较新版本的`shadowsocks-libev`

谢谢！

**Comment by sadoneli** [comment]
观察2.4.6一阵子再说

**Comment by sadoneli** [comment]
最新ss已经用2.4.8
