### ISSUE TITLE
koolgame模式会崩溃，引起路由器重启

### ISSUE THREAD

**Issue by mulky5858** [koolshare/koolshare.github.io#890]
提交issue请先回答以下问题，以便我们更快的找到问题，多谢配合（本行和以下括号内的内容可以删除）~

##### 关键系统日志：
Aug  1 08:00:18 kernel: <1>Unable to handle kernel NULL pointer derefere?U?at virtual address 00000004
Aug  1 08:00:18 kernel: <1>pgd = 9e2e4000
Aug  1 08:00:18 kernel: <1>[00000004] *pgd=57f85031, *pte=00000000, *ppte=00000000
Aug  1 08:00:18 kernel: <0>Internal error: Oops: 17 [#1] PREEMPT SMP
Aug  1 08:00:18 kernel: <0>last sysfs file: /sys/class/net/ppp0/speed
Aug  1 08:00:18 kernel: <4>module:  xt_comment	 7f678000	 527
Aug  1 08:00:18 kernel: <4>module:  xt_socket	 7f672000	 1514
Aug  1 08:00:18 kernel: <4>module:  xt_TPROXY	 7f66c000	 958
Aug  1 08:00:18 kernel: <4>module:  nf_tproxy_core	 7f666000	 1262
Aug  1 08:00:18 kernel: <4>module:  ipt_REDIRECT	 7f660000	 846
Aug  1 08:00:18 kernel: <4>module:  ip_set_hash_net	 7f655000	 22930
Aug  1 08:00:18 kernel: <4>module:  xt_set	 7f64e000	 7395
Aug  1 08:00:18 kernel: <4>module:  ip_set	 7f642000	 23793
Aug  1 08:00:18 kernel: <4>module:  nf_nat_sip	 7f63b000	 5031
Aug  1 08:00:18 kernel: <4>module:  nf_conntrack_sip	 7f632000	 15713
Aug  1 08:00:18 kernel: <4>module:  nf_nat_h323	 7f62b000	 4761
Aug  1 08:00:18 kernel: <4>module:  nf_conntrack_h323	 7f61d000	 33807
Aug  1 08:00:18 kernel: <4>module:  nf_nat_rtsp	 7f617000	 3202
Aug  1 08:00:18 kernel: <4>module:  nf_conntrack_rtsp	 7f611000	 4067
Aug  1 08:00:18 kernel: <4>module:  nf_nat_ftp	 7f60b000	 1144
Aug  1 08:00:18 kernel: <4>module:  nf_conntrack_ftp	 7f604000	 4909
Aug  1 08:00:18 kernel: <4>module:  ip6table_mangle	 7f5fe000	 934
Aug  1 08:00:18 kernel: <4>module:  cdc_mbim	 7f5f8000	 3129
Aug  1 08:00:18 kernel: <4>module:  qmi_wwan	 7f5f1000	 5780
Aug  1 08:00:18 kernel: <4>module:  cdc_wdm	 7f5ea000	 7252
Aug  1 08:00:18 kernel: <4>module:  cdc_ncm	 7f5e2000	 8750
Aug  1 08:00:18 kernel: <4>module:  rndis_host	 7f5db000	 4936
Aug  1 08:00:18 kernel: <4>module:  cdc_ether	 7f5d5000	 3187
Aug  1 08:00:18 kernel: <4>module:  asix	 7f5cd000	 10832
Aug  1 08:00:18 kernel: <4>module:  usbnet	 7f5c4000	 11165
Aug  1 08:00:18 kernel: <4>module:  mii	 7f5be000	 3367
Aug  1 08:00:18 kernel: <4>module:  usblp	 7f5b6000	 10321
Aug  1 08:00:18 kernel: <4>module:  ohci_hcd	 7f5ac000	 17918
Aug  1 08:00:18 kernel: <4>module:  ehci_hcd	 7f59f000	 31941
Aug  1 08:00:18 kernel: <4>module:  thfsplus	 7f582000	 85433
Aug  1 08:00:18 kernel: <4>module:  tntfs	 7f502000	 467362
Aug  1 08:00:18 kernel: <4>module:  tfat	 7f4c9000	 191383
Aug  1 08:00:18 kernel: <4>module:  ext2	 7f4b4000	 53816
Aug  1 08:00:18 kernel: <4>module:  ext4	 7f473000	 222314
Aug  1 08:00:18 kernel: <4>module:  jbd2	 7f45f000	 49581
Aug  1 08:00:18 kernel: <4>module:  crc16	 7f459000	 1007
Aug  1 08:00:18 kernel: <4>module:  ext3	 7f436000	 106581
Aug  1 08:00:18 kernel: <4>module:  jbd	 7f425000	 42863
Aug  1 08:00:18 kernel: <4>module:  mbcache	 7f41e000	 4599
Aug  1 08:00:18 kernel: <4>module:  usb_storage	 7f40f000	 34402
Aug  1 08:00:18 kernel: <4>module:  sg	 7f404000	 20031
Aug  1 08:00:18 kernel: <4>module:  sd_mod	 7f3f8000	 22199
Aug  1 08:00:18 kernel: <4>module:  scsi_wait_scan	 7f3f2000	 416
Aug  1 08:00:18 kernel: <4>module:  scsi_mod	 7f3cd000	 108826
Aug  1 08:00:18 kernel: <4>module:  usbcore	 7f3a9000	 102962
Aug  1 08:00:18 kernel: <4>module:  ip6t_LOG	 7f3a2000	 4494
Aug  1 08:00:18 kernel: <4>module:  ip6table_filter	 7f39c000	 750
Aug  1 08:00:18 kernel: <4>module:  jffs2	 7f37e000	 91550
Aug  1 08:00:18 kernel: <4>module:  zlib_deflate	 7f374000	 19489
Aug  1 08:00:18 kernel: <4>module:  nf_nat_pptp	 7f36e000	 1602
Aug  1 08:00:18 kernel: <4>module:  nf_conntrack_pptp	 7f368000	 3355
Aug  1 08:00:18 kernel: <4>module:  nf_nat_proto_gre	 7f362000	 887
Aug  1 08:00:18 kernel: <4>module:  nf_conntrack_proto_gre	 7f35c000	 3296
Aug  1 08:00:18 kernel: <4>module:  dhd	 7f079000	 2275898
Aug  1 08:00:18 kernel: <4>module:  dpsta	 7f073000	 2744
Aug  1 08:00:18 kernel: <4>module:  igs	 7f06a000	 12371
Aug  1 08:00:18 kernel: <4>module:  emf	 7f05f000	 21593
Aug  1 08:00:18 kernel: <4>module:  et	 7f04b000	 52543
Aug  1 08:00:18 kernel: <4>module:  ctf	 7f041000	 19647
Aug  1 08:00:18 kernel: <4>module:  rtl8365mb	 7f000000	 192718
Aug  1 08:00:18 kernel: <4>Modules linked in: xt_comment xt_socket xt_TPROXY nf_tproxy_core ipt_REDIRECT ip_set_hash_net xt_set ip_set nf_nat_sip nf_conntrack_sip nf_nat_h323 nf_conntrack_h323 nf_nat_rtsp nf_conntrack_rtsp nf_nat_ftp nf_conntrack_ftp ip6table_mangle cdc_mbim qmi_wwan cdc_wdm cdc_ncm rndis_host cdc_ether asix usbnet mii usblp ohci_hcd ehci_hcd thfsplus tntfs(P) tfat(P) ext2 ext4 jbd2 crc16 ext3 jbd mbcache usb_storage sg sd_mod scsi_wait_scan scsi_mod usbcore ip6t_LOG ip6table_filter jff
Aug  1 08:00:18 kernel: <4>CPU: 0    Tainted: P             (2.6.36.4brcmarm #3)
Aug  1 08:00:18 kernel: <4>PC is at memcpy+0x114/0x330
Aug  1 08:00:18 kernel: <4>LR is at ip_conntrack_ipct_add+0x1ec/0xb30
Aug  1 08:00:18 kernel: <4>pc : [<803d3814>]    lr : [<8025a4c8>]    psr: 60000013
Aug  1 08:00:18 kernel: <4>sp : 97b27a54  ip : 00000002  fp : 9e243e24
Aug  1 08:00:18 kernel: <4>r10: 0000009e  r9 : 97b27a84  r8 : 9e243e10
Aug  1 08:00:18 kernel: <4>r7 : 00000004  r6 : 97eaad20  r5 : 00000004  r4 : 9de9c690
Aug  1 08:00:18 kernel: <4>r3 : 00000000  r2 : 00000002  r1 : 00000004  r0 : 97b27adc
Aug  1 08:00:18 kernel: <4>Flags: nZCv  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment user
Aug  1 08:00:18 kernel: <4>Control: 10c53c7d  Table: 5e2e404a  DAC: 00000015
Aug  1 08:00:18 kernel: <0>Process koolgame (pid: 540, stack limit = 0x97b26270)
Aug  1 08:00:18 kernel: <0>Stack: (0x97b27a54 to 0x97b28000)
Aug  1 08:00:18 kernel: <0>7a40:                                              97b27adc 9de9c690 8025a4c8
Aug  1 08:00:18 kernel: <0>7a60: 9e24c800 9dc5b000 97b26000 803110dc 00000001 00000000 00000000 00000001
Aug  1 08:00:18 kernel: <0>7a80: 9dc5b000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
Aug  1 08:00:18 kernel: <0>7aa0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
Aug  1 08:00:18 kernel: <0>7ac0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
Aug  1 08:00:18 kernel: <0>7ae0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
Aug  1 08:00:18 kernel: <0>7b00: 00000001 8026b964 00000000 9cc34a00 9cc34a5c 00000000 00000001 97b27c14
Aug  1 08:00:18 kernel: <0>7b20: 9cc34a5c 00000019 00000001 00000000 f9689a76 9f28c373 00000000 00000000
Aug  1 08:00:18 kernel: <0>7b40: 00000000 00000000 00000000 00000000 00000000 00000000 97b27b80 97b27bd4
Aug  1 08:00:18 kernel: <0>7b60: 00000000 9e24c000 00000002 97b27c10 00000000 97eaad20 97b27c14 802593cc
Aug  1 08:00:18 kernel: <0>7b80: 8042c9f4 97b26000 9e24c000 1142f688 97b27bc0 97eaad20 00000000 97b27bc0
Aug  1 08:00:18 kernel: <0>7ba0: 00000000 00000004 99eb2000 9de9c690 80272aec 802a8aa8 97b27bc0 00000001
Aug  1 08:00:18 kernel: <0>7bc0: f9689a76 00000000 00000000 00000000 00020b04 9732a8c0 00000000 00000000
Aug  1 08:00:18 kernel: <0>7be0: 00000000 001153f6 00000000 97eaad20 80490b20 80000000 97eaad20 00000004
Aug  1 08:00:18 kernel: <0>7c00: 00000000 802ac430 80272aec 00000004 99eb2000 97b27c7c 80490b20 803c82a8
Aug  1 08:00:18 kernel: <0>7c20: 80272aec 97b27ca4 80490b18 00000000 0000 ^C 97eaad20 00000000 80272aec
Aug  1 08:00:18 kernel: <0>7c40: 97b27c7c 99eb2000 80490b20 802553ec 99eb2000 97b27c7c 80272aec 80000000
Aug  1 08:00:18 kernel: <0>7c60: 00000000 97b27c7c 97b27ca4 00000002 80490b18 97b26000 99eb2000 8042fbb4
Aug  1 08:00:18 kernel: <0>7c80: 8028ab94 01b97f51 00000000 97eaad20 99eb2000 97b26000 00000000 9e243e10
Aug  1 08:00:18 kernel: <0>7ca0: 00000010 80273590 99eb2000 80272aec 80000000 97eaad20 00000000 0000007a
Aug  1 08:00:18 kernel: <0>7cc0: 97eaad20 9fb9a220 9e25a100 8028bce0 99eb2000 8028ab94 80000000 00000000
Aug  1 08:00:18 kernel: <0>7ce0: 97b26000 97b27cfc 00000000 00000000 9e243e00 97b27efc 00000070 0000000d
Aug  1 08:00:18 kernel: <0>7d00: 00000000 00000000 9f28c373 0132a8c0 00000000 00000000 00000000 00000000
Aug  1 08:00:18 kernel: <0>7d20: 00000000 00000000 00000000 000000ff 00000000 00000000 9f28c373 0000000d
Aug  1 08:00:18 kernel: <0>7d40: 00000000 97b27f00 ffffffea 00000000 00000000 97b27d98 97b27f5c 8032bea8
Aug  1 08:00:18 kernel: <0>7d60: 00000040 00000000 00000000 0000007a 97b27efc 80296000 00000000 00000000
Aug  1 08:00:18 kernel: <0>7d80: 9fbd52a4 9fbd50b0 0000007a 97b27f5c 8032bea8 802182cc 00000000 97b27f5c
Aug  1 08:00:18 kernel: <0>7da0: 00000000 00000001 ffffffff 00000000 00000000 00000000 00000000 00000000
Aug  1 08:00:18 kernel: <0>7dc0: 9fa4b600 97b26000 00000000 00000000 97b26000 00000002 97b27e10 0000001c
Aug  1 08:00:18 kernel: <0>7de0: 00000000 00000040 00000a00 97b27f5c 8032d088 802183f8 00000040 8004f020
Aug  1 08:00:18 kernel: <0>7e00: 58bbb7df 9fa49e00 00000000 00000001 ffffffff 00000000 00000000 0000007a
Aug  1 08:00:18 kernel: <0>7e20: 9f52eb60 97b27efc 00000000 97b27f5c 97b27e7c 00000001 97b27efc 97b27efc
Aug  1 08:00:18 kernel: <0>7e40: 00000008 97b27f5c 9f52eb60 00000000 97b26000 97b27f5c 9f52eb60 97b27efc
Aug  1 08:00:18 kernel: <0>7e60: 00000018 8021aa2c 00000001 97b27f3c 97b27f3c 00000008 8004f020 00000002
Aug  1 08:00:18 kernel: <0>7e80: 9f28c373 00000000 00000000 9fa49e00 00000000 97b27f5c 00000001 80486dd4
Aug  1 08:00:18 kernel: <0>7ea0: 80486dd0 80486de0 004502e0 8009f3d4 97b27ec4 ffffffff 00000a00 9f6c8820
Aug  1 08:00:18 kernel: <0>7ec0: 97b27edc 108ba028 107744fc 97b26000 00000040 8021a72c 00000000 00000000
Aug  1 08:00:18 kernel: <0>7ee0: 00000000 00000000 00000000 800a16fc 0304342f 00000000 9d9cb8a0 106acc80
Aug  1 08:00:18 kernel: <0>7f00: 0000007a 9d9cb8a0 9d9cb8e0 97b27f28 9d9cb8a8 80112060 00000000 9d9cb8a0
Aug  1 08:00:18 kernel: <0>7f20: 9d9cb8e0 80112694 97b27f28 97b27f28 00000080 106d774c 97b26000 00000018
Aug  1 08:00:18 kernel: <0>7f40: 00000000 00000008 0000000d 00000000 00000000 00000000 004502e0 97b27e7c
Aug  1 08:00:18 kernel: <0>7f60: 00000010 97b27efc 00000001 97b27f3c 00000018 00000040 00000001 fffffff2
Aug  1 08:00:18 kernel: <0>7f80: 00000001 00000000 00000000 108882a0 00000128 80050c68 97b26000 00000000
Aug  1 08:00:18 kernel: <0>7fa0: 00450334 80050ac0 00000000 00000000 00000006 1063da94 00000000 00000000
Aug  1 08:00:18 kernel: <0>7fc0: 00000000 00000000 108882a0 00000128 00000077 00000000 106a2540 00450334
Aug  1 08:00:18 kernel: <0>7fe0: 108882bf 1063da40 00094b3c 0016e538 60000010 00000006 00000000 00000000
Aug  1 08:00:18 kernel: <4>[<803d3814>] (PC is at memcpy+0x114/0x330)
Aug  1 08:00:18 kernel: <0>Code: e211c003 0affffc4 e3c11003 e35c0002 (e491e004) 
Aug  1 08:00:18 kernel: <4>---[ end trace 77d926ff167b3c7c ]---
Aug  1 08:00:18 kernel: <0>Kernel panic - not syncing: Fatal exception
Aug  1 08:00:18 kernel: <4>[<8005701c>] (unwind_backtrace+0x0/0xf8) from [<8030e144>] (panic+0x7c/0x1a8)
Aug  1 08:00:18 kernel: <4>[<8030e144>] (panic+0x7c/0x1a8) from [<800546f0>] (die+0x1a4/0x1dc)
Aug  1 08:00:18 kernel: <4>[<800546f0>] (die+0x1a4/0x1dc) from [<800584b4>] (__do_kernel_fault+0x6c/0x8c)
Aug  1 08:00:18 kernel: <4>[<800584b4>] (__do_kernel_fault+0x6c/0x8c) from [<80058624>] (do_page_fault+0x150/0x1ec)
Aug  1 08:00:18 kernel: <4>[<80058624>] (do_page_fault+0x150/0x1ec) from [<800503a4>] (do_DataAbort+0x30/0x9c)
Aug  1 08:00:18 kernel: <4>[<800503a4>] (do_DataAbort+0x30/0x9c) from [<803d294c>] (__dabt_svc+0x4c/0x60)
Aug  1 08:00:18 kernel: <4>Exception stack(0x97b27a08 to 0x97b27a50)
Aug  1 08:00:18 kernel: <4>7a00:                   97b27adc 00000004 00000002 00000000 9de9c690 00000004
Aug  1 08:00:19 kernel: <4>7a20: 97eaad20 00000004 9e243e10 97b27a84 0000009e 9e243e24 00000002 97b27a54
Aug  1 08:00:19 kernel: <4>7a40: 8025a4c8 803d3814 60000013 ffffffff
Aug  1 08:00:19 kernel: <4>[<803d294c>] (__dabt_svc+0x4c/0x60) from [<803d3814>] (memcpy+0x114/0x330)
Aug  1 08:00:19 kernel: ng
Aug  1 08:00:19 kernel: 38)
Aug  1 08:00:19 kernel: <4>Exception stack(0x96c21f0call+0x0/0x30)
Aug  1 08:00:19 kernel: <0>Rebooting in 3 seconds..

**Comment by sadoneli** [comment]
对于golang的程序，都是建议使用虚拟内存的,koolgame也不例外

**Comment by mulky5858** [comment]
AC88U的1G内存还是不够么

**Comment by sadoneli** [comment]
够的，在有虚拟内存的情况下崩溃的？

**Comment by mulky5858** [comment]
没有虚拟内存，AC88U自带的1G内存崩溃。

**Comment by sadoneli** [comment]
ac88U是128M flash 512M ram。不是1G内存

需要虚拟内存的

**Comment by mulky5858** [comment]
哦，看错了，那我弄个虚拟内存再试试
