### ISSUE TITLE
科学上网卸载不干净

### ISSUE THREAD

**Issue by liuyang007** [koolshare/koolshare.github.io#891]
提交issue请先回答以下问题，以便我们更快的找到问题，多谢配合（本行和以下括号内的内容可以删除）~

##### 问题描述：
卸载插件没有卸载干净，强迫症无法接受
- /jffs/.koolshare/ss 目录
- /jffs/scripts/ 各种启动钩子中还是有ssconfig.sh

**Comment by sadoneli** [comment]
1. /jffs/.koolshare/ss https://github.com/koolshare/koolshare.github.io/issues/853
2. 待修

**Comment by sadoneli** [comment]
https://github.com/koolshare/koolshare.github.io/blob/acelan_softcenter_ui/shadowsocks/shadowsocks/uninstall.sh#L47-L49
