### ISSUE TITLE
KCP加速不可用

### ISSUE THREAD

**Issue by 2shou** [koolshare/koolshare.github.io#893]
##### 插件设置截图：
![kcp](https://user-images.githubusercontent.com/2646161/39567883-f7ee519c-4ef2-11e8-9a30-1f695a09e5f7.jpg)

科学上网可用，但开启KCP加速失败，配置如图，本地的ss用相同的KCP加速配置正常使用。

**Comment by sadoneli** [comment]
请检查你的kcp配置，kcp加速这个功能确定是可用的
0 检查帐号设置，保持ss帐号设置，不需要更改监听地址和端口
1 检查是否开启数据压缩，注意勾选是不压缩，不勾选是压缩
2 检查kcptun进程是否启动，如果没有，建议使用虚拟内存后尝试

**Comment by 2shou** [comment]
ssh到路由器调试了下，确认是密码中带有空格的缘故，可以考虑修复一下。

**Comment by calledT** [comment]
同样的问题，MAC和Android上的KCPTUN都正常，科学上网插件里的KCP加速开启就无法连接需要科学上网的网址
