### ISSUE TITLE
gfwlist模式无法科学上网，开启全局模式路由器访问不了

### ISSUE THREAD

**Issue by KimiChen** [koolshare/koolshare.github.io#894]
提交issue请先回答以下问题，以便我们更快的找到问题，多谢配合（本行和以下括号内的内容可以删除）~

##### 插件设置截图：
![ss2](https://user-images.githubusercontent.com/618941/39574048-48405ffe-4f08-11e8-9141-b09c683a25bf.png)

##### 插件运行日志：
![ss1](https://user-images.githubusercontent.com/618941/39574073-5d59b8b8-4f08-11e8-90d8-bc0785719773.png)

##### 其它信息（如果有）：
【2018年05月03日 19:30:12】: ======================= 梅林固件 - 【科学上网】 ========================
【2018年05月03日 19:30:12】:
【2018年05月03日 19:30:12】: ------------------------- 启动【科学上网】 -----------------------------
【2018年05月03日 19:30:12】: 关闭ss-redir进程...
【2018年05月03日 19:30:13】: 关闭ss-local进程:23456端口...
【2018年05月03日 19:30:14】: 关闭dns2socks进程...
【2018年05月03日 19:30:14】: 删除ss相关的名单配置文件.
【2018年05月03日 19:30:14】: 重启dnsmasq服务...
【2018年05月03日 19:30:16】: 清除iptables规则和ipset...
【2018年05月03日 19:30:18】: 检测到你的SS服务器已经是IP格式：119.9.75.160,跳过解析...
【2018年05月03日 19:30:18】: 创建ipset名单
ipset v4.5: Unknown arg `-!'
Try `ipset -H' or 'ipset --help' for more information.
ipset v4.5: Unknown arg `-!'
Try `ipset -H' or 'ipset --help' for more information.
ipset v4.5: Unknown arg `-!'
Try `ipset -H' or 'ipset --help' for more information.
ipset v4.5: Unknown arg `-!'
Try `ipset -H' or 'ipset --help' for more information.
ipset v4.5: Unknown arg `-!'
Try `ipset -H' or 'ipset --help' for more information.
ipset v4.5: Line 1 does not start as a valid restore command

Restore failed at line 1:
Try `ipset -H' or 'ipset --help' for more information.
【2018年05月03日 19:30:18】: 自动判断使用国内优先模式，不加载cdn.txt
【2018年05月03日 19:30:18】: 创建gfwlist的软连接到/jffs/etc/dnsmasq.d/文件夹.
【2018年05月03日 19:30:18】: 创建SS配置文件到/koolshare/ss/ss.json
【2018年05月03日 19:30:18】: 开启ss-redir进程，用于透明代理.
【2018年05月03日 19:30:18】: ss-redir的 tcp 走ss-redir.
【2018年05月03日 19:30:18】: ss-redir的 udp 未开启.
【2018年05月03日 19:30:19】: ss-redir 启动完毕！.
【2018年05月03日 19:30:19】: 开启ss-local，提供socks5代理端口：23456
【2018年05月03日 19:30:19】: 开启dns2socks，用于dns解析...
【2018年05月03日 19:30:19】: 加载nat规则!
【2018年05月03日 19:30:19】: 写入iptables规则到nat表中...
iptables v1.4.14: Set white_list doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.14: Set white_list doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.14: Set black_list doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.14: Set gfwlist doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.14: Set black_list doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.14: Set chnroute doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.14: Set black_list doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.14: Set chnroute doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.14: Set black_list doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.14: Set chnroute doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
【2018年05月03日 19:30:20】: 加载ACL规则：【全部主机】【全部端口】模式为：gfwlist模式
iptables v1.4.14: Set router doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
【2018年05月03日 19:30:20】: DNS劫持规则已经添加，跳过~
【2018年05月03日 19:30:20】: 重启dnsmasq服务...
【2018年05月03日 19:30:21】: ss规则定时更新任务未启用！
【2018年05月03日 19:30:21】: ------------------------ 【科学上网】 启动完毕 ------------------------
【2018年05月03日 19:30:22】:
【2018年05月03日 19:30:22】: Across the Great Wall we can reach every corner in the world!
【2018年05月03日 19:30:22】:
【2018年05月03日 19:30:22】: ======================= 梅林固件 - 【科学上网】 ========================

**Comment by sadoneli** [comment]
https://github.com/koolshare/koolshare.github.io/blob/acelan_softcenter_ui/shadowsocks/Changelog.txt#L613

从3.1.6版本开始就不支持X7.2以前的固件，请升级最新固件
