### ISSUE TITLE
3.8.4版本以上双working无法工作

### ISSUE THREAD

**Issue by lockonzhao** [koolshare/koolshare.github.io#895]
提交issue请先回答以下问题，以便我们更快的找到问题，多谢配合（本行和以下括号内的内容可以删除）~

##### 问题描述：3.8.4以上GFW和大陆白名单模式都显示双working，但是无法工作，3.8.4以下版本只能大陆白名单模式可以工作
公司同样的固件但是路由器是RT-5300AC，SS也是同样设置就一切正常

##### 插件运行日志：
![1](https://user-images.githubusercontent.com/38553172/39579733-0fc93ad0-4f1a-11e8-8c59-e70ec8598972.png)
![2](https://user-images.githubusercontent.com/38553172/39579735-10184eb8-4f1a-11e8-996b-da5fd0de78d1.png)
![3](https://user-images.githubusercontent.com/38553172/39579736-10631cc2-4f1a-11e8-81b4-24dab49ab5d6.png)
![4](https://user-images.githubusercontent.com/38553172/39579738-10b25bf2-4f1a-11e8-97da-33043d0a0d05.png)
![5](https://user-images.githubusercontent.com/38553172/39579739-111aede8-4f1a-11e8-83a1-58aef88102e5.png)
![6](https://user-images.githubusercontent.com/38553172/39579740-120e9dee-4f1a-11e8-807b-b759fe6c8ff1.png)

**Comment by sadoneli** [comment]
1 提供系统日志和插件提交日志
2 是否所有局域网设备都是这样？

**Comment by sadoneli** [comment]
能看到你的流量从PREROUTING链到了SHADOWSOCKS链，并且有流量正确的到达SHADOWSOCKS_GFW链，但是SHADOWSOCKS_GFW链里没有匹配到gfwlist的流量

根据你的iptables信息，认为你开了梅林固件的【智能网络卫士】-【DNSFilter】导致8.8.8.8等dns请求被过滤掉了，请关闭改功能！

**Comment by lockonzhao** [comment]
已解决。。。感谢

**Comment by lockonzhao** [comment]
已解决。。。感谢
