### ISSUE TITLE
gfwlist模式无法科学上网，全局模式能科学上网

### ISSUE THREAD

**Issue by qcsunny** [koolshare/koolshare.github.io#896]
提交issue请先回答以下问题，以便我们更快的找到问题，多谢配合（本行和以下括号内的内容可以删除）~

##### 插件设置截图：
gfwlist模式：
![gfwlist模式](http://ww1.sinaimg.cn/large/a9f643dagy1fqymjjgkqnj210c0xtti4.jpg)
分流检测![](http://ww1.sinaimg.cn/large/a9f643dagy1fqymt7d64zj20uh0m9gp2.jpg)
全局模式：
![全局模式](http://ww1.sinaimg.cn/large/a9f643dagy1fqymjjdi8yj20qs0vln12.jpg)
分流检测![](http://ww1.sinaimg.cn/large/a9f643dagy1fqymt7dc78j20sz0logp3.jpg)

##### 插件配置文件：
[ss_conf_backup.txt](https://github.com/koolshare/koolshare.github.io/files/1971854/ss_conf_backup.txt)
##### 插件运行日志：
```
【2018年05月04日 00:27:37】: ======================= 梅林固件 - 【科学上网】 ========================
【2018年05月04日 00:27:37】:
【2018年05月04日 00:27:37】: ------------------------- 启动【科学上网】 -----------------------------
【2018年05月04日 00:27:37】: 关闭ssr-redir进程...
【2018年05月04日 00:27:38】: 关闭ssr-local进程:23456端口...
【2018年05月04日 00:27:38】: 关闭dns2socks进程...
【2018年05月04日 00:27:39】: 删除ss相关的名单配置文件.
【2018年05月04日 00:27:39】: 重启dnsmasq服务...
【2018年05月04日 00:27:40】: 清除iptables规则和ipset...
【2018年05月04日 00:27:42】: 删除ss规则定时更新任务...
【2018年05月04日 00:27:42】: 检测到你的SS服务器已经是IP格式：167.99.xx.xx,跳过解析...
【2018年05月04日 00:27:42】: 创建ipset名单
【2018年05月04日 00:27:43】: 自动判断dns解析使用国外优先模式...
【2018年05月04日 00:27:43】: 你选择的解析方案【dns2socks】无国内cdn，需要加载cdn.txt，路由器开销较大...
【2018年05月04日 00:27:43】: 生成cdn加速列表到/tmp/sscdn.conf，加速用的dns：119.29.29.29
【2018年05月04日 00:27:45】: 应用域名黑名单
【2018年05月04日 00:27:45】: 创建SSR配置文件到/koolshare/ss/ss.json
【2018年05月04日 00:27:45】: 开启ssr-redir进程，用于透明代理.
【2018年05月04日 00:27:45】: rss-redir的 tcp 走rss-redir.
【2018年05月04日 00:27:45】: rss-redir的 udp 未开启.
【2018年05月04日 00:27:45】: rss-redir 启动完毕！.
【2018年05月04日 00:27:45】: 开启ssr-local，提供socks5代理端口：23456
【2018年05月04日 00:27:45】: 开启dns2socks，用于dns解析...
【2018年05月04日 00:27:45】: 加载nat规则!
【2018年05月04日 00:27:46】: 写入iptables规则到nat表中...
【2018年05月04日 00:27:46】: 加载ACL规则：【全部主机】【全部端口】模式为：全局模式
【2018年05月04日 00:27:46】: DNS劫持规则已经添加，跳过~
【2018年05月04日 00:27:46】: 重启dnsmasq服务...
【2018年05月04日 00:27:47】: 添加ss规则定时更新任务，每天0自动检测更新规则.
【2018年05月04日 00:27:47】: ------------------------ 【科学上网】 启动完毕 ------------------------
【2018年05月04日 00:27:48】:
【2018年05月04日 00:27:48】: Across the Great Wall we can reach every corner in the world!
【2018年05月04日 00:27:48】:
【2018年05月04日 00:27:48】: ======================= 梅林固件 - 【科学上网】 ========================
```
##### 其它信息（如果有）：
```
【2018年05月04日 00:51:09】:
① 程序版本（插件版本：3.9.6）：
-----------------------------------------------------------
程序			版本		备注
ss-redir		3.1.3		2018年04月15日编译
ss-tunnel		3.1.3 		2018年04月15日编译
ss-local		3.1.3		2018年04月15日编译
obfs-local		0.0.5		2018年04月15日编译
ssrr-redir		3.5.2 		2017年11月13日编译
ssrr-tunnel		3.5.2 		2017年11月13日编译
ssrr-local		3.5.2 		2017年11月13日编译
haproxy			1.8.1 		2017年11月13日编译
dns2socks		V2.0 	
cdns			1.0 		2017年12月09日编译
chinadns1		1.3.2 		2017年12月09日编译
chinadns2		2.0.0 		2017年12月09日编译
client_linux_arm5	20180316	kcptun
v2ray			v3.21		20180423
-----------------------------------------------------------

② 检测当前相关进程工作状态：（你正在使用SSR-libev,选择的模式是【gfwlist模式】,国外DNS解析方案是：dns2socks）
-----------------------------------------------------------
程序		状态	PID
ssr-redir	工作中	pid：11191
ssr-local	工作中	pid：11209
dns2socks	工作中	pid：11223 11222 11217
-----------------------------------------------------------


③ 检测iptbales工作状态：
----------------------------------------------------- nat表 PREROUTING 链 --------------------------------------------------------
Chain PREROUTING (policy ACCEPT 2841 packets, 294K bytes)
 pkts bytes target     prot opt in     out     source               destination         
  441 23548 SHADOWSOCKS  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0           
24442 2699K VSERVER    all  --  *      *       0.0.0.0/0            14.117.188.132      
    0     0 VSERVER    all  --  *      *       0.0.0.0/0            169.254.213.10      
 3060  261K VSERVER    all  --  *      *       0.0.0.0/0            14.117.191.83       
    0     0 VSERVER    all  --  *      *       0.0.0.0/0            169.254.167.52      
 2185  140K DNSFILTER  udp  --  *      *       192.168.2.0/24       0.0.0.0/0            udp dpt:53
    0     0 DNSFILTER  tcp  --  *      *       192.168.2.0/24       0.0.0.0/0            tcp dpt:53
    0     0 PCREDIRECT  all  --  br0    *       0.0.0.0/0            0.0.0.0/0            MAC 54:04:A6:D4:B7:D0
    0     0 PCREDIRECT  all  --  br0    *       0.0.0.0/0            0.0.0.0/0            MAC 90:C3:5F:1E:FC:55

----------------------------------------------------- nat表 OUTPUT 链 ------------------------------------------------------------
Chain OUTPUT (policy ACCEPT 361 packets, 23969 bytes)
 pkts bytes target     prot opt in     out     source               destination         
   18  1080 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set router dst redir ports 3333
    0     0 SHADOWSOCKS_EXT  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0xc0a80200/0xffffff00

----------------------------------------------------- nat表 SHADOWSOCKS 链 --------------------------------------------------------
Chain SHADOWSOCKS (1 references)
 pkts bytes target     prot opt in     out     source               destination         
  161  8328 RETURN     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set white_list dst
  280 15220 SHADOWSOCKS_GFW  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0           

----------------------------------------------------- nat表 SHADOWSOCKS_EXT 链 --------------------------------------------------------
Chain SHADOWSOCKS_EXT (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 RETURN     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set white_list dst
    0     0 SHADOWSOCKS_GFW  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0           

----------------------------------------------------- nat表 SHADOWSOCKS_GFW 链 ----------------------------------------------------
Chain SHADOWSOCKS_GFW (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set black_list dst redir ports 3333
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set gfwlist dst redir ports 3333

----------------------------------------------------- nat表 SHADOWSOCKS_CHN 链 -----------------------------------------------------
Chain SHADOWSOCKS_CHN (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set black_list dst redir ports 3333
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            ! match-set chnroute dst redir ports 3333

----------------------------------------------------- nat表 SHADOWSOCKS_GAM 链 -----------------------------------------------------
Chain SHADOWSOCKS_GAM (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set black_list dst redir ports 3333
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            ! match-set chnroute dst redir ports 3333

----------------------------------------------------- nat表 SHADOWSOCKS_GLO 链 -----------------------------------------------------
Chain SHADOWSOCKS_GLO (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            redir ports 3333

----------------------------------------------------- nat表 SHADOWSOCKS_HOM 链 -----------------------------------------------------
Chain SHADOWSOCKS_HOM (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set black_list dst redir ports 3333
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set chnroute dst redir ports 3333
-----------------------------------------------------------------------------------------------------------------------------------

-----------------------------------------------------------------------------------------------------------------------------------

 ```

**Comment by sadoneli** [comment]
你开了梅林固件的【智能网络卫士】-【DNSFilter】导致8.8.8.8等dns请求被过滤掉了，请关闭改功能！

**Comment by sadoneli** [comment]
https://github.com/koolshare/koolshare.github.io/issues/895 一样的问题

**Comment by qcsunny** [comment]
确实，关闭【智能网络卫士】-【DNSFilter】功能之后使用无问题了
谢谢

**Comment by mobiusding** [comment]
Mar 18 23:49:46 【ss_tproxy】: 更新 [全部] 规则
Mar 18 23:49:46 【sh_ss_tproxy.sh】: update_gfwlist
Mar 18 23:49:46 【update_gfwlist】: 开始下载更新 gfwlist 文件....
Mar 18 23:49:46 【update_gfwlist】: 正在获取官方 gfwlist....
Mar 18 23:49:53 【下载】: 下载失败:【/tmp/checkmd5/30930】 URL:【https://cdn.jsdelivr.net/gh/gfwlist/gfwlist/gfwlist.txt】
Mar 18 23:49:53 【下载】: 重新下载:【/tmp/checkmd5/30930】 URL:【https://cdn.jsdelivr.net/gh/gfwlist/gfwlist/gfwlist.txt】
Mar 18 23:49:56 【下载】: 下载失败:【/tmp/checkmd5/30930】 URL:【https://cdn.jsdelivr.net/gh/gfwlist/gfwlist/gfwlist.txt】
Mar 18 23:49:56 【下载】: wget_err ：404错误！
Mar 18 23:49:56 【下载】: 下载【/opt/app/ss_tproxy/rule/tmp_base64_gfwlist.txt】错误，2次下载md5不匹配！【https://cdn.jsdelivr.net/gh/gfwlist/gfwlist/gfwlist.txt】
Mar 18 23:49:56 【下载】: 删除【/opt/app/ss_tproxy/rule/tmp_base64_gfwlist.txt】文件，麻烦看看哪里问题！
Mar 18 23:49:56 【update_gfwlist】: 错误！！！获取官方 gfwlist 下载失败
Mar 18 23:49:56 【update_gfwlist】: 加入 固件内置list规则 列表....
Mar 18 23:49:56 【update_gfwlist】: 处理订阅列表1....海外加速
Mar 18 23:50:03 【下载】: 下载失败:【/tmp/checkmd5/30930】 URL:【https://opt.cn2qq.com/opt-file/list.txt】
Mar 18 23:50:03 【下载】: 重新下载:【/tmp/checkmd5/30930】 URL:【https://raw.githubusercontent.com/hiboyhiboy/opt-file/master/list.txt】
Mar 18 23:50:06 【下载】: 下载失败:【/tmp/checkmd5/30930】 URL:【https://raw.githubusercontent.com/hiboyhiboy/opt-file/master/list.txt】
Mar 18 23:50:06 【下载】: wget_err ：404错误！
Mar 18 23:50:06 【下载】: 下载【/opt/app/ss_tproxy/rule/tmp_gfwlist_tmp.txt】错误，2次下载md5不匹配！【https://opt.cn2qq.com/opt-file/list.txt】
Mar 18 23:50:06 【下载】: 删除【/opt/app/ss_tproxy/rule/tmp_gfwlist_tmp.txt】文件，麻烦看看哪里问题！
Mar 18 23:50:06 【update_gfwlist】: 处理订阅列表2....处理只做dns解释的域名
Mar 18 23:50:13 【下载】: 下载失败:【/tmp/checkmd5/30930】 URL:【https://opt.cn2qq.com/opt-file/dnsonly.txt】
Mar 18 23:50:13 【下载】: 重新下载:【/tmp/checkmd5/30930】 URL:【https://raw.githubusercontent.com/hiboyhiboy/opt-file/master/dnsonly.txt】
Mar 18 23:50:16 【下载】: 下载失败:【/tmp/checkmd5/30930】 URL:【https://raw.githubusercontent.com/hiboyhiboy/opt-file/master/dnsonly.txt】
Mar 18 23:50:16 【下载】: wget_err ：404错误！
Mar 18 23:50:16 【下载】: 下载【/opt/app/ss_tproxy/rule/tmp_gfwlist_tmp.txt】错误，2次下载md5不匹配！【https://opt.cn2qq.com/opt-file/dnsonly.txt】
Mar 18 23:50:16 【下载】: 删除【/opt/app/ss_tproxy/rule/tmp_gfwlist_tmp.txt】文件，麻烦看看哪里问题！
Mar 18 23:50:16 【update_gfwlist】: 处理订阅列表3....处理需要排除的域名解释
Mar 18 23:50:23 【下载】: 下载失败:【/tmp/checkmd5/30930】 URL:【https://opt.cn2qq.com/opt-file/passby.txt】
Mar 18 23:50:23 【下载】: 重新下载:【/tmp/checkmd5/30930】 URL:【https://raw.githubusercontent.com/hiboyhiboy/opt-file/master/passby.txt】
Mar 18 23:50:26 【下载】: 下载失败:【/tmp/checkmd5/30930】 URL:【https://raw.githubusercontent.com/hiboyhiboy/opt-file/master/passby.txt】
Mar 18 23:50:26 【下载】: wget_err ：404错误！
Mar 18 23:50:26 【下载】: 下载【/opt/app/ss_tproxy/rule/tmp_gfwlist_tmp.txt】错误，2次下载md5不匹配！【https://opt.cn2qq.com/opt-file/passby.txt】
Mar 18 23:50:26 【下载】: 删除【/opt/app/ss_tproxy/rule/tmp_gfwlist_tmp.txt】文件，麻烦看看哪里问题！
Mar 18 23:50:27 【update_gfwlist】: 完成下载 gfwlist 文件
Mar 18 23:50:27 【update_gfwlist】: 开始加载 gfwlist 规则....
Mar 18 23:50:28 【update_gfwlist】: 配置更新，完成加载 gfwlist 规则....
Mar 18 23:50:28 【sh_ss_tproxy.sh】: update_chnroute
Mar 18 23:50:28 【update_chnroute】: 开始下载更新 chnroute 文件....
Mar 18 23:50:31 【下载】: 下载失败:【/tmp/checkmd5/31794】 URL:【https://cdn.jsdelivr.net/gh/17mon/china_ip_list/china_ip_list.txt】
Mar 18 23:50:31 【下载】: 重新下载:【/tmp/checkmd5/31794】 URL:【https://cdn.jsdelivr.net/gh/17mon/china_ip_list/china_ip_list.txt】
Mar 18 23:50:38 【下载】: 下载失败:【/tmp/checkmd5/31794】 URL:【https://cdn.jsdelivr.net/gh/17mon/china_ip_list/china_ip_list.txt】
Mar 18 23:50:38 【下载】: wget_err ：404错误！
Mar 18 23:50:38 【下载】: 下载【/opt/app/ss_tproxy/rule/tmp_chnroute_tmp.txt】错误，2次下载md5不匹配！【https://cdn.jsdelivr.net/gh/17mon/china_ip_list/china_ip_list.txt】
Mar 18 23:50:38 【下载】: 删除【/opt/app/ss_tproxy/rule/tmp_chnroute_tmp.txt】文件，麻烦看看哪里问题！
Mar 18 23:50:54 【下载】: 下载失败:【/tmp/checkmd5/31794】 URL:【https://opt.cn2qq.com/opt-file/chnroute.txt】
Mar 18 23:50:54 【下载】: 重新下载:【/tmp/checkmd5/31794】 URL:【https://raw.githubusercontent.com/hiboyhiboy/opt-file/master/chnroute.txt】
Mar 18 23:50:56 【下载】: 下载失败:【/tmp/checkmd5/31794】 URL:【https://raw.githubusercontent.com/hiboyhiboy/opt-file/master/chnroute.txt】
Mar 18 23:50:56 【下载】: wget_err ：404错误！
Mar 18 23:50:56 【下载】: 下载【/opt/app/ss_tproxy/rule/tmp_chnroute_tmp.txt】错误，2次下载md5不匹配！【https://opt.cn2qq.com/opt-file/chnroute.txt】
Mar 18 23:50:56 【下载】: 删除【/opt/app/ss_tproxy/rule/tmp_chnroute_tmp.txt】文件，麻烦看看哪里问题！
Mar 18 23:50:57 【update_chnroute】: 错误！！！下载文件为空，使用 固件内置 /etc/storage/china_ip_list.txt 规则....
Mar 18 23:50:57 【update_chnroute】: 完成下载 chnroute 文件
Mar 18 23:50:57 【update_chnroute】: 开始加载 chnroute 规则....
Mar 18 23:50:59 【update_chnroute】: 配置更新，完成加载 chnroute 规则....
Mar 18 23:50:59 【sh_ss_tproxy.sh】: update_chnlist
Mar 18 23:50:59 【update_chnlist】: 开始下载更新 chnlist 文件....
Mar 18 23:51:15 【下载】: 下载失败:【/tmp/checkmd5/32276】 URL:【https://raw.github.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf】
Mar 18 23:51:15 【下载】: 重新下载:【/tmp/checkmd5/32276】 URL:【https://raw.github.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf】
Mar 18 23:51:21 【下载】: 下载失败:【/tmp/checkmd5/32276】 URL:【https://raw.github.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf】
Mar 18 23:51:21 【下载】: wget_err ：404错误！
Mar 18 23:51:21 【下载】: 下载【/opt/app/ss_tproxy/rule/tmp_chnlist_tmp.txt】错误，2次下载md5不匹配！【https://raw.github.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf】
Mar 18 23:51:21 【下载】: 删除【/opt/app/ss_tproxy/rule/tmp_chnlist_tmp.txt】文件，麻烦看看哪里问题！
Mar 18 23:51:21 【update_chnlist】: 完成下载 chnlist 文件
Mar 18 23:51:21 【sh_ss_tproxy.sh】: update_wanlanlist_ipset
