### ISSUE TITLE
手机无法登陆Google账号 

### ISSUE THREAD

**Issue by cccdeccc** [koolshare/koolshare.github.io#897]
提交issue请先回答以下问题，以便我们更快的找到问题，多谢配合（本行和以下括号内的内容可以删除）~

##### 问题描述：手机无法登陆Google账号 YouTube客户端连不上
使用手机ssr客户端后 可以登陆Google账号 YouTube视频也能打开了

**Comment by sadoneli** [comment]
请尝试清除dns缓存后试试
1 开关飞行模式，测试是否能打开
2 重启手机清除dns缓存，测试是否可以

**Comment by sadoneli** [comment]
no further info
