### ISSUE TITLE
/koolshare/ss/ssconfig.sh: line 1175: syntax error: unexpected end of file (expecting "fi")

### ISSUE THREAD

**Issue by xblvesting** [koolshare/koolshare.github.io#901]
提交issue请先回答以下问题，以便我们更快的找到问题，多谢配合（本行和以下括号内的内容可以删除）~

**Comment by xlighting2017** [comment]
友情配图
![image](https://user-images.githubusercontent.com/25970065/39673285-e74e42d6-516b-11e8-8aab-dbb32ad582a0.png)

**Comment by sadoneli** [comment]
![image](https://user-images.githubusercontent.com/10495520/39694428-d958d48a-5219-11e8-9644-5c9b60c3eacb.png)
最后那个}是必须的，为了保证最后生成的json文件能正确闭合
