### ISSUE TITLE
不管GFWList模式还是大陆白名单模式，国内网站都会走SSR

### ISSUE THREAD

**Issue by Hzh873851987** [koolshare/koolshare.github.io#902]
提交issue请先回答以下问题，以便我们更快的找到问题，多谢配合（本行和以下括号内的内容可以删除）~

##### 插件设置截图：
![h 7i4ncwgbei c vzy1r](https://user-images.githubusercontent.com/27913556/39670876-90641192-5140-11e8-988e-f9754e2e9910.png)

##### 插件运行日志：
![u03 83 z 0tpelgg1op_d](https://user-images.githubusercontent.com/27913556/39670892-bc6bb664-5140-11e8-9fee-6eadeeda3965.png)

##### 其它信息（如果有）：
![uu_zmo ow 2zg ia af_a](https://user-images.githubusercontent.com/27913556/39670904-19940224-5141-11e8-8148-2a95a4a0f06d.png)

**Comment by Jetranger** [comment]
是否在访问控制那里添加了针对该主机的访问控制？

**Comment by Hzh873851987** [comment]
我今天换了端口80 正常了

**Comment by Hzh873851987** [comment]
没有
今天把端口换到80 ip111分流显示的正常（但是我没有在换之前检查）
不过 国外连接断problem的时候国内网站依然会无法访问
而且 依旧会时断时续（这是被盯上了嘛？？）
@Jetranger

**Comment by Hzh873851987** [comment]
现在就比较好玩了
国内显示的是我的SSR IP
国外和Google显示的是我的IP
= =？

**Comment by Hzh873851987** [comment]
现在就比较好玩了
国内和google显示的是我的SSR IP
国外显示的是我的IP
= =？

**Comment by Jetranger** [comment]
没有遇到过你说的这种问题，建议把JFFS格式化后重新安装试试，路由器也可以重置，如果所有重置手段都试过了还是不行再来咨询。

**Comment by leoleozhu** [comment]
我也发现了类似问题，无论是GFWLIST还是国内IP白名单都如此

**Comment by Hzh873851987** [comment]
有解决吗？？@leoleozhu

**Comment by leoleozhu** [comment]
没有，我没关注，暂时停用了路由器上，单独开了socks5 proxy供有翻墙需求的设备使用。

回退老版是否可以？

**Comment by ronniealorenzo** [comment]
我也是一样的问题，今天才发现国内和Google都走ss，国外不走。
按 @Jetranger 说的把JFFS格式化，现在看起来已经正常了

**Comment by Hzh873851987** [comment]
emmm... 格式化了JFFS我发现插件列表里没有科学上网= =
so 有谁能提供我一个离线插件吗 thx

**Comment by ronniealorenzo** [comment]
@Hzh873851987 这里不就有吗？https://github.com/koolshare/koolshare.github.io/tree/acelan_softcenter_ui/shadowsocks

**Comment by Hzh873851987** [comment]
这不是SS吗？@ronniealorenzo

**Comment by ronniealorenzo** [comment]
@Hzh873851987 没明白什么意思。
我用的就是这个，难道你用的不是这个吗？

**Comment by Hzh873851987** [comment]
恩 是这个了 我以为这是插件中心里的那个SS@ronniealorenzo
不过 我的问题还是没有解决。。

**Comment by Hzh873851987** [comment]
解决了！
清理JFFS后 重新安装SSR 但是不要恢复之前的SSR配置 全部手动重新填就可以了
此贴终结！
