### ISSUE TITLE
kp开启启动无效

### ISSUE THREAD

**Issue by sunnoy** [koolshare/koolshare.github.io#903]
提交issue请先回答以下问题，以便我们更快的找到问题，多谢配合（本行和以下括号内的内容可以删除）~

#### 插件具体设置（请尽量提供以下信息，如果截图或者关键信息，请打码或者更改）?

路由器重启后，kp开机启动无效，必须要手动启动一次才可以过滤广告

**Comment by sadoneli** [comment]
是否有开机后的系统日志？

**Comment by sunnoy** [comment]
经过这几天的观察，已经正常，日志无法重现了，我设定的每天3点重启。
