### ISSUE TITLE
科学上网插件导致的域名解析问题

### ISSUE THREAD

**Issue by zesming** [koolshare/koolshare.github.io#904]
路由器型号：AC88U & AC68U
固件版本：380.69_2-X7.8

插件名称：科学上网
插件版本：3.9.6

问题：
在【账号设置】的【服务器】中如果填写域名（例如 zesming.xx 这样的一级域名），保存应用后该路由器子网内的所有对上述域名下的二级域名的解析都会定向到一级域名对应的 IP，dig 命令查询了下发现是路由器中的 DNS 解析服务返回了这个错误的 IP，我怀疑在保存插件设置的时候，是不是有什么通配设置影响到了二级域名的解析。

**Comment by xlighting2017** [comment]
echo "address=/$ss_basic_server/$server_ip" > /jffs/configs/dnsmasq.d/ss_host.conf

默认会将 服务器域名 解析结果保存下来，如果写顶级域名，确实会影响二级域名解析，而且没办法改进了

最好的解决方案，是把你的服务器 也部署到二级域名上

**Comment by zesming** [comment]
这样啊，那我还是先用 IP 来设置服务器地址吧

**Comment by sadoneli** [comment]
确实是妥协之举，不然有时候设置域名的话因为没法解析而导致连不上ss服务器
但是有时候设置的dns走了服务器转发，又需要连上ss服务器才能解析

更形象点来说就是下面中情况：
ss说：dnsmasq，快把老子要解析域名的ip地址给我，我要连上ss服务器！
dnsmasq说：老子解析的这个域名要走ss服务器转发，你丫赶快连上服务器，我好解析给你。

结果就死循环了，谁也别想工作了
最近加这个就是想的在ss开启前，解析一次，拿到地址后存到hosts里，这样在ss没连上服务器的时候，dnsmasq也能告诉ss要连域名的ip地址

**Comment by zesming** [comment]
用域名的应该是会有更换 IP 的需求吧，如果写到 hosts 里面的话，会不会在未来更换 IP 后这边又要重新连接导致连接不上的情况？

有没有可能单独把设置为 SS 服务器的域名单独列出来，用 WAN 口的 DNS 服务器来解析？或者别的解析策略？

没有研究过这方面，瞎猜的 ; P
