### ISSUE TITLE
希望可以自动切换v2ray节点，最近被封的很频繁

### ISSUE THREAD

**Issue by leafiy** [koolshare/koolshare.github.io#905]
路由型号：6300v2
固件版本：380.69_2-X7.8

插件名称：梅林固件 - 科学上网插件
插件版本：3.9.8

问题描述：联通网5月开始使用v2ray试过ws、tcp、h2均会在15-30分钟以后断流，域名无法ping通，但ip和正常网站访问正常，之后一小时左后会解封，需要频繁更换节点使用，所以希望能增加定时切换节点功能或者故障转移功能

**Comment by sadoneli** [comment]
https://github.com/koolshare/koolshare.github.io/issues/833#issuecomment-385225536

**Comment by sadoneli** [comment]
除非有非常成熟的方案，不然不会去做这个
