### ISSUE TITLE
能否添加自定义acl模式？

### ISSUE THREAD

**Issue by freefrank** [koolshare/koolshare.github.io#906]
回国模式又挂了，貌似不是插件的问题因为安卓版ssr的回国模式也出问题了，但是安卓sar可以用自定义的acl文件分流。
请问可不可以添加自定义acl模式方便大家自定义分流？

非常感谢。

**Comment by sadoneli** [comment]
路由上和手机/电脑上情况不一样的

路由上分流默认靠iptables，这样效率最好，如果用acl会出奇的慢，而且提供透明代理的ss-redir并不支持acl，也没法支持acl

ss-local是支持acl的，但是并不能透明代理

**Comment by freefrank** [comment]
好吧谢谢大佬
