### ISSUE TITLE
shadowsocks如果使用域名作为服务器地址之后该域名解析会异常

### ISSUE THREAD

**Issue by cjahv** [koolshare/koolshare.github.io#912]
##### 问题描述：
RT：**shadowsocks如果使用域名作为服务器地址之后该域名解析会异常**
### 具体表现：

1. 我使用域名（是我的主域名）作为ss服务器地址

2. 连接成功后我尝试使用dig解析我域名下的其他子域名，这时所有子域名的解析结果将和主域名一直

### 尝试操作：

1. 使用ip作为服务器地址

2. 子域名解析正常

**Comment by xlighting2017** [comment]
#904
