### ISSUE TITLE
ss  分为开发版和稳定版

### ISSUE THREAD

**Issue by zuohuadong** [koolshare/koolshare.github.io#914]
提交issue请先回答以下问题，以便我们更快的找到问题，多谢配合（本行和以下括号内的内容可以删除）~

##### 问题描述：
3.8以上版本，ss 经常出问题～～ 能不能基于 3.7.0 维护一个新分支，目前换成3.7 已经稳定运行两周了。

ss-开发版
（3.8+ 真是太不稳定了）
ss-稳定版

**Comment by sadoneli** [comment]
这个插件其实就是shell和html的组合，目的就是调用翻墙相关的程序运行，配置相关iptables等
3.7.0和后来的任何版本在核心上和其它版本并没有本质的区别，翻墙的稳定性首要还是在线路上
另外根本没那么多精力去维护多个分支，只是想在软件中心2,0出来前把这个插件画一个我个人比较满意的句号。

**Comment by sadoneli** [comment]
另外如果你使用插件有问题，可以指出来具体一点的，仅仅说不稳定，就比较暧昧了，我完全无法根据这三个字推到出你那里问题的原因

就插件进化到目前来看，只有很少数情况下，确实是插件的问题导致了问题，但是问题应该都是比较分明的，比如直接不工作等。如果是勾和叉反复跳的话，这个我就没法帮你，在两年前写在插件内的问题排查说明就已经指出了

**Comment by zuohuadong** [comment]
@sadoneli  
有时候切换 dns解析方式会好，但是过不了1天，又变叉。
有时候切换也没用～
但是同时，手机上的ss客户端 可以连上，网也正常。

目前换成3.7.0是好了～暂时不敢升了～

**Comment by sadoneli** [comment]
可以提供详细的设置，插件日志，系统日志，dnsmasq配置文件内容等信息
