### ISSUE TITLE
大陆白名单模式的bug

### ISSUE THREAD

**Issue by fhq** [koolshare/koolshare.github.io#918]
梅林固件 - 科学上网插件 - 3.9.6

我把模式设置成大陆白名单后，发现找不开路由器管理页面了。

因为我路由器地址设置成11.1.1.1之类的了
我猜可能是因为这个ip规则认为是国外的，所以走了代理。

能否在使用大陆白名单模式的同时把路由器的地址过滤开不走代理呢？

**Comment by sadoneli** [comment]
你好，这不是bug，请使用规定的保留地址作为路由器的lan ip
相关文档：https://en.wikipedia.org/wiki/IPv4

**Comment by fhq** [comment]
好的，我原来就是想着内网弄个简单好记的地址，没想到还有和公网IP冲突的时候~~

**Comment by sadoneli** [comment]
10.0.0.1作为lan ip也比较好记吧，哈哈
