### ISSUE TITLE
使用SS连接后国外连接部分不通

### ISSUE THREAD

**Issue by Rick7Xu** [koolshare/koolshare.github.io#919]
##### 插件设置截图：
<img width="758" alt="default" src="https://user-images.githubusercontent.com/16173930/39964682-6dff6ed6-56bc-11e8-8b86-0743d23485d8.png">

##### 插件运行日志：
<img width="756" alt="default" src="https://user-images.githubusercontent.com/16173930/39964685-79073a2a-56bc-11e8-994e-b87619740031.png">

##### 其它信息（如果有）：
[插件状态.txt](https://github.com/koolshare/koolshare.github.io/files/1998190/default.txt)

**Comment by sadoneli** [comment]
看信息是你的dnsmasq工作问题，ipset没工作
贴上你的系统日志看看，另外尝试切换下国内dns试试

**Comment by Rick7Xu** [comment]
另外用朋友的一个是可以的用，而失败的配置在手机端相同网络用Potatso相同配置可通。
<img width="581" alt="pass_case" src="https://user-images.githubusercontent.com/16173930/39964945-0fef715a-56c2-11e8-9feb-e3831a625720.png">

**Comment by yj19777** [comment]
我也出现这样的状况，昨晚还是正常的，今天就国外连接失败了

**Comment by sadoneli** [comment]
This system doesn't provide enough entropy to quickly generate high-quality random numbers. Installing the rng-utils/rng-tools, jitterentropy or haveged packages may help. On virtualized Linux environments, also consider using virtio-rng. The service will not start until enough entropy has been collected.

问题貌似都是处在使用ss-libev
熵不够，这个貌似不知道怎么搞

**Comment by sadoneli** [comment]
[shadowsocks-libev_3.13_static_binary.zip](https://github.com/koolshare/koolshare.github.io/files/1998281/shadowsocks-libev_3.13_static_binary.zip)
1. 先关闭科学上网插件
2. 下载这里的shadowsocks-libev二进制文件，然后用winscp拷贝到路由器的/koolshare/bin目录，替换同名文件
3. 运行chmod +x /koolshare/bin/*
4. 重新开启科学上网插件，看是否正常使用，系统日志是否出现：This system doesn't provide enough entropy to quickly generate high-quality random numbers. Installing the rng-utils/rng-tools, jitterentropy or haveged packages may help. On virtualized Linux environments, also consider using virtio-rng. The service will not start until enough entropy has been collected.
5. 如果问题解决或者没有解决都请反馈下

**Comment by sadoneli** [comment]
另外运行 `cat /proc/sys/kernel/random/entropy_avail`查看系统的熵值是否低于160，因为ss-libev服务只有在收集到足够的熵后才会启动

**Comment by sadoneli** [comment]
3.9.9是否正常？

**Comment by chuanyueqianye** [comment]
ac66u b1, 7.8固件，插件3.9.9版本，国外连接不可用，使用ssr客户端没有问题。使用上述方法无效，熵值有时低于160有时高于160，均无法连接。升级7.9固件也无改善...

**Comment by Rick7Xu** [comment]
1. 升级到3.9.9依然失败，此时熵为180，如下图
<img width="467" alt="entropy" src="https://user-images.githubusercontent.com/16173930/39993475-94bc49f8-57a8-11e8-8f6f-4487bb40d6eb.PNG">
2. 用压缩包文件替换后依然失败，此时熵为923，如下图
<img width="456" alt="entropy_2" src="https://user-images.githubusercontent.com/16173930/39993527-bc70a156-57a8-11e8-82ec-9b5b9c6bea22.PNG">
3. 此时系统日志依然有“This system doesn't provide enough entropy to quickly generate high-quality random numbers...”，附上日志。
[System_Log.txt](https://github.com/koolshare/koolshare.github.io/files/2000378/System_Log.txt)

**Comment by Rick7Xu** [comment]
附上日志
[System_Log.txt](https://github.com/koolshare/koolshare.github.io/files/2000381/System_Log.txt)

**Comment by yj19777** [comment]
更新了shadowsocks-libev还是没有解决，日志如下：

2018年05月17日 00:44:18】: 创建SSR配置文件到/koolshare/ss/ss.json
【2018年05月17日 00:44:18】: 开启ssr-redir进程，用于透明代理.
【2018年05月17日 00:44:18】: rss-redir的 tcp 走rss-redir.
【2018年05月17日 00:44:18】: rss-redir的 udp 未开启.
【2018年05月17日 00:44:19】: rss-redir 启动完毕！.
【2018年05月17日 00:44:19】: 开启ssr-local，提供socks5代理端口：23456
【2018年05月17日 00:44:19】: 开启dns2socks，用于dns解析...
【2018年05月17日 00:44:19】: 加载nat规则!
【2018年05月17日 00:44:19】: 写入iptables规则到nat表中...

系统的熵值是175

**Comment by sadoneli** [comment]
@yj19777 你这个是ssr来着，就我所知，需要足够熵才会启动的是ss来着

**Comment by yj19777** [comment]
@sadoneli 那SSR出现楼主的这种情况，要怎么排查

**Comment by sportfit** [comment]
新购入68P刷上最新7.9固件/3.9.9插件，使用二周不到，无论SSorSSRR国外开始频繁X，试用了所有的DNS，国外就是X，无奈换回68W固件停留7.5/插件3.6.0，国外稳定working，不知道要怎么排查

**Comment by kurosaki65** [comment]
SS 替换了对应的文件, 还是国外连接 不通, 这个什么原因?

**Comment by sportfit** [comment]
回滚到3.9.1方才正常，看提示原来这版是修复3.9.0.DNS污染的，暂且停留。

**Comment by plalzhang** [comment]
想下载ss3.5.2版本，貌似搬瓦工配合这个最稳定

**Comment by Rick7Xu** [comment]
试了试离线安装3.6.5/3.7.8/3.8.1/3.9.1版本，都还是不通

**Comment by Rick7Xu** [comment]
刚刚升级到4.0.1后问题解决了，目前连接正常
