### ISSUE TITLE
Asus AC88U的6.6版仍然无法读取json、或对json容错能力不足

### ISSUE THREAD

**Issue by gdillainepub** [koolshare/koolshare.github.io#94]
Asus AC88U的6.6

1. 似乎仍然只能接受MIME: text/plain的文件，而且格式不是1.4.9 change log里说的那种json格式。我做了很多的尝试让AC88U的6.6固件 $$去恢复，结果要么失败、要么只能回复1个节点的配置。

2.上述尝试失败后，我手工输入结点信息，再用导出，发觉dump出来仍然是6.5固件里的那种text/plain文件，区别在于现在可以导出所有节点了。最后，用这个dump出来的conf_backup.txt，再尝试让ss回复，这次成功了。似乎这是唯一他能接受的格式。

3. 固件1.4.9的change log里说测试过几个json文件通过，我不知道那些和我的有什么区别。我现在附上2个json文件供前辈debug：

   **demo1.json**，是我从服务商得到的原始json文件的格式：我只做了如下改动：把原先总共12个节点删掉7个，剩下5个保留；编辑掉了节点的地址端口等不允许公开的信息。

**demo2.json**: 由于demo1一开头包含了配置ShadowsocksX客户端的一些Key，而6.6固件不能ignore这些东西，所以demo2就是删除了所有和$$ node信息无关的Key之后保存的json。但任然不行

4. 我的json似乎和Mac OSX上的plist是相同的格式都是XML，因为都可以用PlistEdit Pro编辑。但是目前1.4.9，只能读取XML/json直接写在“最根部”（就是直接在root下面）。但问题如果多个节点json没法都写在根部，最起码要有1层，然后用1个Dictionary 表示一个节点。这我也试过了，6.6固件只能读取第1个Dictionary的配置，后面的全部抛弃了。

=========>
测试: Mac OSX 10.6.8
浏览器: Safari, Chrome, Opera 都用过了。

[json.zip](https://github.com/koolshare/koolshare.github.io/files/265174/json.zip)

**Comment by sadoneli** [comment]
@gdillainepub 这种格式的目前确实不能读取，目前只支持分行定义参数的json

**Comment by sadoneli** [comment]
shell脚本对读取json天生不好使，此问题可能搁置
