### ISSUE TITLE
feature request：可在$$配置中edit节点列表。

### ISSUE THREAD

**Issue by gdillainepub** [koolshare/koolshare.github.io#95]
我是ASUS RT-AC88U。之前看见某大发的新版$$ changelog，说是可以支持json格式了。于是我从6.5升级到6.1.1，发觉怎么弄都不行（见之前的一个issue），只能手输，输的有点急，每个节点信息，空格的都填了，等我差不多填完了才发现，我忘记改加密方式了！

这下惨，只能删了重输，我有14个节点那。。。

因为希望：除了增加（+）和（-），还能多一个Edit选项；这样就不用删掉重来，只许改一下加密算法就可以了。

====================================
除此之外，如果有多个节点，自然依据ping的结果选择，但是ping又很慢，比如我14个节点要ping好久。是否可以提供某种排序、或者改变节点在配置表中的前后位置的方法（比如把第8条拉到第2条之类），我不太懂，但貌似现在的HTML做到这点不难。

**Comment by sadoneli** [comment]
https://github.com/koolshare/koolshare.github.io/blob/acelan_softcenter_ui/shadowsocks/Changelog.txt#L33
