### ISSUE TITLE
Asus AC88U的6.6.1 /$$ 1.4.9 持续报错

### ISSUE THREAD

**Issue by gdillainepub** [koolshare/koolshare.github.io#96]
完全相同的$$节点和配置，在6.5版国内国外都能工作。

然而，升级6.6.1之后，无论是GFW还是大陆白模式，这样已经持续好几天：
![screenshot 2016-05-16 at 03 55 56](https://cloud.githubusercontent.com/assets/18560453/15276418/2a39b682-1b1a-11e6-9fda-70746addc67c.png)

奇怪的是，按理这样国外不能用，但实际却能用。反复检查，发现：只要在自定义黑名单里加入过东西，国外连接就会显示不正常（实际可用——至少我测试的几个网站可用）

**Comment by yulhun** [comment]
能不能这个也加 https://github.com/felixonmars/dnsmasq-china-list
更新了，还有https://github.com/hijackfilter/hijackfilter

**Comment by houzi-** [comment]
@yulhun
dnsmasq-china-list这个是可以有的！
还有dnsfilter我相信不久就会出来了吧！

**Comment by houzi-** [comment]
@yulhun
还有建议你重新开一个issues来提这个建议！

**Comment by sadoneli** [comment]
@yulhun 这个list本来就是有的，https://github.com/koolshare/koolshare.github.io/blob/master/shadowsocks/shadowsocks/ss/redchn/cdn.txt

**Comment by sadoneli** [comment]
@gdillainepub 翻墙以实际效果为准，这里仅提供参考

**Comment by gdillainepub** [comment]
$$实际效果正常的时候当然没关系，就怕实际工作也不正常的时候，这个提示相当于虚设了，起不到帮助排查问题作用。

因此还是希望有时间时可以解决下。。因为毕竟在更新6.6.1 (AC88U）和$$ 1.4.8之前，同样的这些$$节点，完全相同的设置，从未出现过这个情况。




On May 18, 2016, at 10:20 , sadoneli wrote:


@gdillainepub<https://github.com/gdillainepub> 翻墙以实际效果为准，这里仅提供参考
