### ISSUE TITLE
Bug: AC88U_6.6.1遗传了merlin 380.59的bug——wl命令不工作

### ISSUE THREAD

**Issue by gdillainepub** [koolshare/koolshare.github.io#97]
AC88U的6.6.1, 发现wl指令不工作，表现为:

- 如果"正确的" wl argument，如 `# wl txpwr_target_max` , wl不会返回任何值
- 如果"错误"的wl argument，如 `wl xyz`  , wl能正常的返回一个 `wl: Unsupported`

由于之前的6.5 不存在这个问题，我刷了原版梅林RT-AC88U_380.59_0.trx测试，发现同样的wl不工作。估计小宝的AC88U_6.6.1是遗传了梅林380.59的问题。

我试图想提取6.5版的/usr/sbin/wl 替换6.6.1的wl，然而Read only 没法改。

只能拜托开发组下次编译固件的时候能把wl的这个问题也顺便解决了……感谢！

**Comment by houzi-** [comment]
先用mount 来挂载覆盖就可以了

**Comment by gdillainepub** [comment]
> 先用mount 来挂载覆盖就可以了

谢谢回复，不过能具体说说mount 什么吗？单个文件wl？我就是不知道如何覆盖READ ONLY的/usr/bin/wl

麻烦LS具体说说，怎么操作

**Comment by sadoneli** [comment]
把能用的wl的二进制文件备份下来，然后上传到新固件里，比如上传到/jffs分区，然后
chmod +x /jffs/wl
mount --bind /jffs/wl /usr/sbin/wl

2016-05-23 10:29 GMT+08:00 gdillainepub <notifications@github.com>:
