### ISSUE TITLE
Bug: kcptun 连接不成功

### ISSUE THREAD

**Issue by nykma** [koolshare/koolshare.github.io#98]
服务端是 20160518 的版本，加了 `--tuncrypt --mode "fast2"`，使用配套client连接正常。
我试着手动修改 `kcptun_config.json` 把 `tuncrypt` 置 1 后启动 `kcp_router`，建立连接时一直输出这种log：
```
2016/05/19 13:15:38 closed addr 127.0.0.1:12546
2016/05/19 13:15:38 copy2 302 read tcp 10.0.0.1:23456->10.0.0.57:53423: use of closed network connection
2016/05/19 13:15:38 new socks5 conn by 127.0.0.1:12546
```
> 10.0.0.57是我电脑，我直接把浏览器的SOCKS5代理指到它expose的23456上了

是因为新服务端改过`tuncrypt`实现了？我看客户端还是0514版的

感谢解答。另外希望下个版本能修改更多 `kcptun_config.json` 里可自定的项。至少需要 `tuncrypt` 开关和 `mode` 的选项。

**Comment by nykma** [comment]
看了一下部署脚本，好像服务端的背后不是socks5的转发服务？我是配的dante来转发

**Comment by sadoneli** [comment]
已经更新独立插件
